import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const root=path.resolve('design/labrador-puppy/motion-anatomy');
const dom=new JSDOM(fs.readFileSync(path.join(root,'review.html'),'utf8'),{runScripts:'outside-only',url:'https://motion.invalid/'});
const w=dom.window;let time=0,next=1;const raf=new Map();
w.requestAnimationFrame=f=>{const id=next++;raf.set(id,f);return id};w.cancelAnimationFrame=id=>raf.delete(id);
Object.defineProperty(w.performance,'now',{value:()=>time});
w.Image=class{set src(value){this._src=value;queueMicrotask(()=>this.onload?.())}get src(){return this._src}decode(){return Promise.resolve()}};
w.matchMedia=()=>({matches:false,addEventListener(){}});let observer;
w.IntersectionObserver=class{constructor(fn){observer=fn}observe(){}};
w.eval(fs.readFileSync(path.join(root,'manifest.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'previous-manifest.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'player.js'),'utf8'));
const settle=()=>new Promise(r=>setImmediate(r));await settle();await settle();
const $=id=>w.document.getElementById(id),click=id=>$(id).click(),frame=()=>Number($('scrub').value);
function advance(t){time=t;const work=[...raf.values()];raf.clear();for(const f of work)f(time)}
assert.equal($('play').disabled,false);assert.equal($('speed').value,'0.25');assert.equal(frame(),1);assert.equal(raf.size,0);
click('next');assert.equal(frame(),2);click('prev');click('prev');assert.equal(frame(),48);click('next');assert.equal(frame(),1);
click('play');advance(200);assert.equal(frame(),6);
$('speed').value='1';$('speed').dispatchEvent(new w.Event('change'));advance(250);assert.equal(frame(),11);
click('play');advance(1000);assert.equal(frame(),11);
$('scrub').value='22';$('scrub').dispatchEvent(new w.Event('input'));assert.equal(frame(),22);assert.match($('physics-readout').textContent,/배 체중/);
$('view').value='three-quarter';$('view').dispatchEvent(new w.Event('change'));await settle();await settle();assert.equal(frame(),22);assert.match($('frame').src,/three-quarter\/022.png$/);
w.document.querySelector('[data-frame="35"]').click();assert.equal(frame(),35);
$('variant').value='old';$('variant').dispatchEvent(new w.Event('change'));await settle();await settle();assert.equal(frame(),35);assert.match($('frame').src,/motion-physics\/frames\/three-quarter\/035.png$/);assert.match($('physics-readout').textContent,/배 체중/);
click('play');advance(1100);assert.equal(frame(),45);click('play');w.document.querySelector('[data-frame="35"]').click();
$('variant').value='new';$('variant').dispatchEvent(new w.Event('change'));await settle();await settle();assert.equal(frame(),35);assert.doesNotMatch($('frame').src,/motion-physics/);
w.document.body.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(frame(),36);
click('play');observer([{isIntersecting:false}]);assert.equal($('play').textContent,'재생');assert.equal(raf.size,0);
for(const version of ['.','../motion-physics'])for(const v of w.MOTION.views)for(let f=1;f<=w.MOTION.frames;f++)assert.ok(fs.existsSync(path.join(root,version,`frames/${v}/${String(f).padStart(3,'0')}.png`)));
console.log('Anatomy player: step/wrap, matching 100fps timing, 1/4 speed, force readout, comparison, keyboard and offscreen stop passed; 192 frame paths exist. DOM logic test, not browser rendering.');
w.close();
