import { sizeConflictReviewSchema, type SizeConflictReview } from "./schema";

const reviews = [
  { slug: "shetland-sheepdog", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "35~37cm는 이상적 중심값이고 33~41cm는 내부 출처가 지지하는 전체 범위입니다." },
  { slug: "puli", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "간략 대표값 대신 성별 공식 범위를 합친 36~45cm·10~15kg를 사용합니다." },
  { slug: "shar-pei", kind: "minor", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "최솟값 2cm 차이이며 내부 공식 범위 44~51cm가 더 구체적이고 등급은 같습니다." },
  { slug: "white-swiss-shepherd-dog", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "성별 범위를 합친 53~66cm가 간략 원고의 55~66cm보다 완전합니다." },
  { slug: "dogo-argentino", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "상세의 성별 범위가 61~67cm·40~45kg로 더 구체적이며 최종 등급은 같습니다." },
  { slug: "continental-bulldog", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "20~30kg 일반 참고 대신 성별 표준값 25~30kg를 사용하며 의미를 혼합하지 않습니다." },
  { slug: "wire-fox-terrier", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "체고는 수컷 상한이고 암컷은 더 작다는 설명뿐이라 전체 완전 범위를 만들 수 없습니다." },
  { slug: "kerry-blue-terrier", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "체중 15~18kg는 수컷 기준이고 암컷 하한이 없어 전체 성견 범위로 확정할 수 없습니다." },
  { slug: "norfolk-terrier", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "identity.size", note: "25cm는 이상적 값이고 23~25cm·5~6kg는 내부 일반 성견 범위로 별도 의미가 확인됩니다." },
  { slug: "norwich-terrier", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "identity.size", note: "25cm는 이상적 값이고 23~25cm·5~6kg는 내부 일반 성견 범위로 별도 의미가 확인됩니다." },
  { slug: "miniature-bull-terrier", kind: "rounding", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "25~35cm와 25.4~35.6cm는 인치 환산 차이지만 체중 고정값이 없어 잠정 상태입니다." },
  { slug: "australian-silky-terrier", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "공식 체중 범위는 없지만 내부 참고 대표값 4.5kg가 명시되어 대표값 방식으로 계산할 수 있습니다." },
  { slug: "swedish-vallhund", kind: "true-conflict", outcome: "conflict", selectedLocation: "breedFactOverrides", note: "같은 참고 체중 범위가 9~14kg와 9~16kg로 달라 내부 자료만으로 선택할 수 없습니다." },
  { slug: "italian-volpino", kind: "true-conflict", outcome: "conflict", selectedLocation: "breedFactOverrides", note: "같은 참고 체중 범위가 4~5kg와 3.6~7.3kg로 크게 달라 내부 자료만으로 선택할 수 없습니다." },
  { slug: "eurasier", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "상세 성별 범위를 합친 18~30kg를 사용하며 간략값 18~32kg와 최종 등급 차이가 없습니다." },
  { slug: "hokkaido", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "45~52cm는 45.5~51.5cm 성별 기준을 반올림한 값으로 상세 원값을 유지합니다." },
  { slug: "kai", kind: "true-conflict", outcome: "conflict", selectedLocation: "heroSizeDetails", note: "체고와 체중 범위가 45~56cm·14~27kg와 42~53cm·11.3~18.1kg로 실질적으로 다릅니다." },
  { slug: "kishu", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "성별 기준과 환산값을 합친 범위가 더 구체적이며 Dog Atlas 등급은 바뀌지 않습니다." },
  { slug: "shikoku", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "성별 기준과 소수 환산값을 합친 범위가 더 구체적이며 Dog Atlas 등급은 바뀌지 않습니다." },
  { slug: "harrier", kind: "minor", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "48~53cm와 48~55cm의 작은 범위 차이는 등급에 영향이 없고 보정표가 더 완전합니다." },
  { slug: "english-foxhound", kind: "minor", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "체중 최솟값 2kg 차이는 등급에 영향이 없고 내부 보정 근거 27~34kg를 사용합니다." },
  { slug: "petit-basset-griffon-vendeen", kind: "minor", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "34~38cm와 33~39cm는 양 끝 1cm 차이이며 내부 보정 범위를 사용합니다." },
  { slug: "german-wire-haired-pointing-dog", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "체중 최솟값 2kg 차이는 등급에 영향이 없고 상세 참고 범위 23~32kg를 사용합니다." },
  { slug: "wire-haired-pointing-griffon-korthals", kind: "true-conflict", outcome: "conflict", selectedLocation: "heroSizeDetails", note: "같은 참고 체중 범위가 20~27kg와 16~32kg로 실질적으로 달라 재확인이 필요합니다." },
  { slug: "english-pointer", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "체중 상한 30kg와 34kg 차이는 등급에 영향이 없고 상세 참고 범위를 사용합니다." },
  { slug: "irish-water-spaniel", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "20~30kg와 20~31kg는 파운드 환산 반올림 차이로 상세 환산값을 유지합니다." },
  { slug: "tibetan-terrier", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "36~41cm는 수컷 범위이고 암컷은 더 작다고만 되어 있어 전체 하한을 확정할 수 없습니다." },
  { slug: "japanese-chin", kind: "true-conflict", outcome: "conflict", selectedLocation: "heroSizeDetails", note: "일반 범위 20~27cm·1.5~6kg와 성별·참고값 25cm 전후·3.2~5kg가 실질적으로 다릅니다." },
  { slug: "prague-ratter", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "breedFactOverrides", note: "21~23cm·2~3kg는 중심 범위이고 20~24cm·2.6kg는 허용 범위와 대표값으로 의미가 구분됩니다." },
  { slug: "sloughi", kind: "minor", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "체중 범위 18~28kg와 20~29kg 차이는 등급에 영향이 없고 상세 참고값을 사용합니다." },
  { slug: "bergamasco-shepherd", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "56~60cm는 이상적 중심값이고 54~62cm는 성별 허용 범위라 상세 범위를 사용합니다." },
  { slug: "slovakian-cuvac", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "30~45kg와 31~44kg는 반올림된 외곽값 차이로 상세 성별 범위를 유지합니다." },
  { slug: "entlebucher-mountain-dog", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "기본 체고와 허용 체고, 일반 체중과 환산 참고값의 의미를 분리해 상세값을 사용합니다." },
  { slug: "greater-swiss-mountain-dog", kind: "true-conflict", outcome: "conflict", selectedLocation: "heroSizeDetails", note: "같은 체중 범위가 50~65kg와 39~64kg로 실질적으로 달라 내부 자료만으로 선택할 수 없습니다." },
  { slug: "parson-russell-terrier", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "31~36cm는 중심 범위이고 31~38cm는 성별 허용 범위라 상세값을 사용합니다." },
  { slug: "sealyham-terrier", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "체고는 31cm 이하 상한뿐이며 완전 범위가 아니므로 체중이 있어도 잠정 상태입니다." },
  { slug: "thai-ridgeback", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "이상적 체고와 허용 체고는 구분되지만 내부에 고정 체중 수치가 없습니다." },
  { slug: "cirneco-dell-etna", kind: "meaning-difference", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "44~50cm는 기본 성별 범위이고 42~52cm는 허용 오차를 포함한 범위라 상세 의미를 채택합니다." },
  { slug: "grand-basset-griffon-vendeen", kind: "meaning-difference", outcome: "provisional", selectedLocation: "heroSizeDetails", note: "기본 체고와 ±1cm 허용 범위는 구분되지만 내부에 고정 체중 수치가 없습니다." },
  { slug: "german-long-haired-pointer", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "평균 30kg의 중복 표기가 대표값과 30~30kg로 달리 파싱된 기술적 차이입니다." },
  { slug: "irish-terrier", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "같은 45.5cm가 성별로 반복되어 대표값과 45.5~45.5cm로 달리 파싱된 기술적 차이입니다." },
  { slug: "large-munsterlander", kind: "rounding", outcome: "confirmed", selectedLocation: "heroSizeDetails", note: "평균 30kg의 반복 표기가 대표값과 30~30kg로 달리 파싱된 기술적 차이입니다." },
  { slug: "boerboel", kind: "meaning-difference", outcome: "conflict", selectedLocation: "breedFactOverrides", note: "KUSA의 최소·이상 체고와 다른 등록기관의 일반 성견 범위가 섞여 있어 기준 선택 검수가 필요합니다." },
] satisfies SizeConflictReview[];

export const sizeConflictReviews = sizeConflictReviewSchema.array().length(43).parse(reviews);
export const sizeConflictReviewBySlug = new Map(sizeConflictReviews.map((review) => [review.slug, review]));
