import { breedFeatureCollectionSchema } from "./schema";

export const breedFeatureSets = breedFeatureCollectionSchema.parse([
  {
    slug: "japanese-spitz",
    intro: "사람과의 관계, 주변 변화에 대한 반응, 매일 체감할 털 관리 부담을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "사람 곁에서 함께 움직이길 좋아해요.",
        description: "사람을 좋아하고 보호자와 산책하거나 놀이하는 시간을 즐기는 영리하고 쾌활한 반려견이에요. 다만 사람과 가까워지는 속도와 애정을 표현하는 방식은 강아지마다 달라요.",
        image: "/illustrations/v4/japanese-spitz-feature-companionship.webp",
        alt: "사람 곁을 따라 걸으며 얼굴을 바라보는 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/"],
      },
      {
        eyebrow: "짖음과 알림",
        title: "작은 변화에도 먼저 반응할 수 있어요.",
        description: "현관 소리나 창밖 움직임에 반응해 짖을 수 있어요. 짖음이 길어지지 않도록 소리가 들린 뒤 조용히 기다리는 연습을 어릴 때부터 해두면 좋아요.",
        image: "/illustrations/v4/japanese-spitz-feature-calm-alert.webp",
        alt: "닫힌 문밖의 작은 소리를 조용히 알아차린 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/", "https://www.ukcdogs.com/breed-groups/japanese-spitz"],
      },
      {
        eyebrow: "털 관리 부담",
        title: "풍성한 이중모는 꾸준한 빗질이 필요해요.",
        description: "짧고 촘촘한 속털과 풍성한 겉털을 함께 가진 견종이에요. 특히 털갈이 시기에는 빠진 속털이 엉키지 않도록 규칙적인 빗질을 생활에 포함해야 해요.",
        image: "/illustrations/v4/japanese-spitz-feature-double-coat.webp",
        alt: "빠진 속털을 브러시로 빗어 관리하는 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/", "https://www.ukcdogs.com/breed-groups/japanese-spitz"],
      },
    ],
  },
  {
    slug: "maltese",
    intro: "사람과 가까이 지내는 방식, 작은 체구의 생활 안전, 긴 피모 관리 부담을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "사람 가까이에서 시간을 보내길 좋아해요.",
        description: "가족과 가까이 머물며 함께 시간을 보내는 것을 좋아하는 모습을 보일 수 있어요. 함께하는 시간뿐 아니라 짧고 편안한 혼자 쉬기도 천천히 익혀주세요.",
        image: "/illustrations/v4/maltese-feature-companionship.webp",
        alt: "앉아 있는 사람 가까이에서 얼굴을 바라보는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/maltese/", "https://www.akc.org/expert-advice/dog-breeds/maltese-right-for-you/"],
      },
      {
        eyebrow: "작은 체구와 안전",
        title: "작은 몸에 맞는 생활 동선이 필요해요.",
        description: "높은 가구에서 뛰어내리거나 거친 상호작용은 작은 몸에 부담이 될 수 있어요. 발이 닿는 바닥과 오르내리는 높이, 아이와 만나는 방식을 차분히 살펴주세요.",
        image: "/illustrations/v4/maltese-feature-small-body-safety.webp",
        alt: "낮은 반려견 계단 옆에서 사람의 안내를 받는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/expert-advice/dog-breeds/maltese-right-for-you/"],
      },
      {
        eyebrow: "피모 관리 부담",
        title: "긴 실키 코트는 매일 엉킴을 살펴야 해요.",
        description: "길고 곧은 흰 피모를 유지하려면 피부 가까이까지 부드럽게 빗고 엉킨 곳을 확인하는 시간이 필요해요. 빗질과 목욕, 피모 관리를 편안한 일상으로 익혀주세요.",
        image: "/illustrations/v4/maltese-feature-coat-care.webp",
        alt: "긴 흰 피모를 금속 빗으로 차분히 관리받는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/maltese/"],
      },
    ],
  },
  {
    slug: "border-collie",
    intro: "움직임을 읽는 몰이 행동, 빠른 학습에 맞는 과제, 활동 뒤 차분히 쉬는 리듬을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "몰이와 움직임",
        title: "움직이는 대상을 먼저 읽고 따라갈 수 있어요.",
        description: "양 떼의 방향을 읽고 모으도록 발달한 목양견이에요. 달리는 사람이나 놀이하는 아이처럼 빠르게 움직이는 대상에 시선이 고정되거나 따라가려는 모습이 보이면 거리를 두고 보호자에게 돌아오는 신호를 연습해주세요.",
        image: "/illustrations/v4/border-collie-feature-herding-focus.webp",
        alt: "공원에서 멀리 지나가는 사람과 자전거를 알아차린 뒤 보호자를 바라보는 성견 보더콜리 삽화",
        sourceUrls: ["https://images.akc.org/pdf/breeds/standards/Border_Collie.pdf", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
      {
        eyebrow: "배움과 과제",
        title: "빠르게 배우는 만큼 생각할 일이 필요해요.",
        description: "신호를 익히고 문제를 해결하는 활동에 적극적으로 참여할 수 있어요. 같은 공 던지기만 오래 반복하기보다 냄새 찾기, 짧은 협력 훈련, 규칙이 있는 놀이를 번갈아 제공해주세요.",
        image: "/illustrations/v4/border-collie-feature-thinking-tasks.webp",
        alt: "사람의 손 신호를 바라보며 냄새 상자와 훈련 도구 사이에서 과제를 기다리는 성견 보더콜리 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/border-collie/", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
      {
        eyebrow: "활동과 휴식",
        title: "많이 움직인 뒤 쉬는 법도 함께 배워야 해요.",
        description: "활동량이 높은 편이지만 자극을 계속 늘리는 것만으로 생활이 편안해지지는 않아요. 산책과 과제 뒤에는 소리와 움직임이 적은 자리에서 흥분을 낮추고 쉬는 시간을 일상에 넣어주세요.",
        image: "/illustrations/v4/border-collie-feature-calm-rest.webp",
        alt: "산책 도구와 장난감이 정리된 방에서 매트 위에 편안히 쉬는 성견 보더콜리 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/border-collie/", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
    ],
  },
  {
    slug: "greyhound",
    intro: "움직임을 보는 시선, 짧게 속도를 내고 쉬는 리듬, 얇은 피모에 맞는 보온 준비를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "시각과 추적",
        title: "멀리 움직이는 대상을 먼저 발견할 수 있어요.",
        description: "눈으로 움직임을 찾고 빠르게 쫓도록 발달한 시각 하운드예요. 산책 중 작은 동물이나 빠르게 지나가는 대상에 주의가 쏠릴 수 있으니, 안전한 리드를 사용하고 실제 반응을 살펴주세요.",
        image: "/illustrations/v4/greyhound-feature-visual-tracking.webp",
        alt: "현대 공원에서 멀리 지나가는 자전거를 알아차리고 보호자 곁에 서 있는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/assets/000/004/111/training_tips_original.pdf?1581612710="],
      },
      {
        eyebrow: "질주와 휴식",
        title: "빠르게 달리는 능력과 하루 종일 바쁜 생활은 달라요.",
        description: "짧게 속도를 내는 순간과 편안히 쉬는 시간이 함께 필요한 견종이에요. 안전하게 달릴 수 있는 통제된 기회와 냄새 맡는 산책을 마련하고, 활동 뒤에는 조용히 회복할 자리를 준비해주세요.",
        image: "/illustrations/v4/greyhound-feature-sprint-rest.webp",
        alt: "안전하게 울타리가 설치된 공원 운동장에서 짧게 달리는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/home-a-greyhound/all-about-greyhounds"],
      },
      {
        eyebrow: "얇은 피모와 온도",
        title: "짧은 털은 추운 날 더 세심한 준비가 필요해요.",
        description: "피모가 짧고 몸에 지방이 적은 편이라 추운 날씨와 차가운 바닥을 불편해할 수 있어요. 기온과 개별 반응에 맞춰 보온 의류를 사용하고, 몸을 받쳐주는 따뜻한 휴식 자리를 마련해주세요.",
        image: "/illustrations/v4/greyhound-feature-cold-weather.webp",
        alt: "쌀쌀한 늦가을 공원에서 몸에 맞는 보온 코트를 입고 산책하는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/about-us/news/3908-quick-tips-to-keep-your-greyhound-healthy-in-winter"],
      },
    ],
  },
  {
    slug: "yakutian-laika",
    intro: "사람과 함께 움직이는 방식, 몸과 판단을 쓰는 활동, 풍성한 이중모의 계절 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 협력",
        title: "사람 가까이에서 함께 움직이려 해요.",
        description: "사람과 가까이 지내고 함께 역할을 수행하는 데 적극적으로 참여할 수 있어요. 산책과 짧은 신호 놀이를 함께하며 보호자에게 시선을 돌리고 차분히 기다리는 경험도 만들어주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-cooperation.webp",
        alt: "현대 공원에서 벤치에 앉은 보호자의 손 신호를 바라보는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/365g05-en.pdf", "https://www.akc.org/dog-breeds/yakutian-laika/"],
      },
      {
        eyebrow: "활동과 과제",
        title: "움직임과 생각할 일을 함께 채워야 해요.",
        description: "활동량과 에너지가 높은 편이라 걷기만 길게 반복하기보다 냄새 찾기, 방향 신호, 안전한 하네스 운동처럼 몸과 판단을 함께 쓰는 과제를 번갈아 제공해주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-purposeful-activity.webp",
        alt: "숲길에서 몸에 맞는 하네스를 착용하고 보호자와 함께 달리는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/yakutian-laika/", "https://www.akc.org/expert-advice/dog-breeds/yakutian-laika-breed-history/"],
      },
      {
        eyebrow: "이중모와 계절",
        title: "풍성한 이중모는 털갈이와 더위 준비가 필요해요.",
        description: "굵은 겉털과 촘촘한 속털이 추운 환경을 견디도록 발달한 견종이에요. 피부 가까이까지 규칙적으로 빗고, 더운 계절에는 선선한 시간대의 활동과 편안한 실내 온도를 마련해주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-double-coat.webp",
        alt: "선선한 실내에서 풍성한 이중모를 브러시로 관리받는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/365g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/yakutian-laika-breed-history/"],
      },
    ],
  },
  {
    slug: "samoyed",
    intro: "사람과 일상을 나누는 방식, 힘과 지구력을 쓰는 활동, 두꺼운 이중모의 계절 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 동행",
        title: "일상에 함께 참여하는 것을 좋아할 수 있어요.",
        description: "사람 가까이 머물며 가족의 활동에 참여하려는 모습을 보일 수 있어요. 함께 걷고 놀아주는 시간뿐 아니라, 가까운 자리에서 편안히 쉬고 짧게 혼자 머무는 경험도 천천히 알려주세요.",
        image: "/illustrations/v4/samoyed-feature-companionship.webp",
        alt: "현대 가정에서 외출을 준비하는 가족 가까이에 편안히 누워 있는 성견 사모예드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/212g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/samoyed-right-for-you/"],
      },
      {
        eyebrow: "활동과 과제",
        title: "힘과 지구력을 쓸 목적 있는 활동이 필요해요.",
        description: "힘과 활동성이 높은 작업견이라 걷기만 길게 반복하기보다 냄새 찾기, 방향 신호, 안전한 하네스 운동처럼 몸과 판단을 함께 쓰는 과제를 번갈아 제공해주세요.",
        image: "/illustrations/v4/samoyed-feature-purposeful-activity.webp",
        alt: "선선한 숲길에서 몸에 맞는 당김 하네스를 착용하고 보호자와 함께 달리는 성견 사모예드 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/samoyed/", "https://www.akc.org/expert-advice/dog-breeds/samoyed-history/"],
      },
      {
        eyebrow: "이중모와 계절",
        title: "두꺼운 이중모는 자주 빗고 계절을 조절해야 해요.",
        description: "부드럽고 촘촘한 속털 위에 더 길고 거친 겉털이 자라는 견종이에요. 평소에도 피부 가까이까지 빗고, 털갈이 시기에는 관리 횟수를 늘리며 더운 날에는 선선한 생활 환경을 마련해주세요.",
        image: "/illustrations/v4/samoyed-feature-double-coat.webp",
        alt: "선선한 실내의 미끄럽지 않은 매트에서 풍성한 이중모를 빗질받는 성견 사모예드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/212g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/samoyed-right-for-you/"],
      },
    ],
  },
  {
    slug: "chihuahua",
    intro: "아주 작은 몸에 맞는 생활 안전, 소리에 반응하는 방식, 피모와 기온에 따른 보온 준비를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "작은 몸과 안전",
        title: "낮은 높이와 보이는 동선부터 준비해요.",
        description: "아주 작은 성견은 소파에서 뛰어내리거나 사람 발과 스치는 일도 큰 부담이 될 수 있어요. 미끄럽지 않은 바닥과 낮은 발판을 마련하고, 문을 오갈 때 발밑을 확인해주세요.",
        image: "/illustrations/v4/chihuahua-feature-small-body-safety.webp",
        alt: "미끄럽지 않은 러그와 낮은 발판이 놓인 거실에서 보호자가 발밑을 살피는 동안 걷는 성견 치와와 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/chihuahua/"],
      },
      {
        eyebrow: "소리와 알림",
        title: "작은 소리에도 빠르게 주의를 돌릴 수 있어요.",
        description: "현관이나 복도의 낯선 소리를 먼저 알아차리고 알리려는 모습이 나타날 수 있어요. 소리를 확인한 뒤 보호자에게 돌아와 매트에서 기다리는 짧은 순서를 차분히 알려주세요.",
        image: "/illustrations/v4/chihuahua-feature-alert-response.webp",
        alt: "닫힌 현관문 소리를 알아차린 뒤 보호자의 손짓을 따라 매트로 돌아오는 성견 치와와 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/chihuahua/"],
      },
      {
        eyebrow: "피모와 보온",
        title: "단모와 장모에 맞춰 추운 날을 준비해요.",
        description: "치와와에는 매끄러운 단모와 부드러운 장모가 있어 관리 방식이 달라요. 피모 길이만 믿기보다 기온과 떨림, 움직임을 살피고 따뜻한 휴식 자리나 몸에 맞는 가벼운 옷을 준비해주세요.",
        image: "/illustrations/v4/chihuahua-feature-coat-warmth.webp",
        alt: "서늘한 날 창가의 담요와 가벼운 옷 가까이에서 쉬는 단모와 장모 성견 치와와 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/218g09-en.pdf", "https://www.akc.org/dog-breeds/chihuahua/"],
      },
    ],
  },
  {
    slug: "shih-tzu",
    intro: "사람 가까이에서 쉬는 방식, 짧은 얼굴에 맞는 더운 날의 리듬, 긴 피모와 얼굴 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "가까운 자리에서 일상을 나누길 좋아할 수 있어요.",
        description: "가족이 머무는 공간을 따라가거나 같은 방의 편안한 자리를 고르는 모습이 보일 수 있어요. 늘 안고 있기보다 스스로 가까이 오고 물러날 수 있는 자리도 함께 마련해주세요.",
        image: "/illustrations/v4/shih-tzu-feature-companionship.webp",
        alt: "책을 읽는 보호자 곁의 별도 매트에 편안히 엎드린 흰색과 금색의 성견 시추 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/shih-tzu/", "https://www.akc.org/expert-advice/dog-breeds/shih-tzu-history/"],
      },
      {
        eyebrow: "짧은 얼굴과 더위",
        title: "더운 날에는 짧고 선선한 움직임이 필요해요.",
        description: "짧고 넓은 주둥이를 가진 시추는 더운 시간의 긴 활동보다 선선한 시간대와 그늘진 길이 편안할 수 있어요. 물과 휴식을 준비하고 걷는 속도는 그날의 반응에 맞춰주세요.",
        image: "/illustrations/v4/shih-tzu-feature-heat-care.webp",
        alt: "여름 아침 그늘진 산책길에서 보호자가 건넨 물그릇 앞에 편안히 서 있는 성견 시추 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/208g09-en.pdf", "https://www.akc.org/dog-breeds/shih-tzu/"],
      },
      {
        eyebrow: "피모와 얼굴 관리",
        title: "눈을 가리지 않도록 매일 짧게 살펴요.",
        description: "길고 촘촘한 피모는 엉킴을 풀어주는 빗질이 필요하고, 얼굴 털은 눈과 코 주변을 가리지 않게 관리해야 해요. 빗과 부드러운 천을 한 번에 오래 쓰기보다 짧게 익혀주세요.",
        image: "/illustrations/v4/shih-tzu-feature-coat-face-care.webp",
        alt: "미끄럽지 않은 매트에서 보호자가 성견 시추의 털을 빗고 눈가를 부드러운 천으로 닦는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/208g09-en.pdf", "https://www.akc.org/dog-breeds/shih-tzu/"],
      },
    ],
  },
  {
    slug: "poodle",
    intro: "네 가지 크기의 생활 차이, 물건을 찾고 가져오는 과제, 계속 자라는 곱슬 피모의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "네 가지 크기",
        title: "같은 푸들이어도 생활의 규모는 크게 달라요.",
        description: "푸들은 스탠더드·미디엄·미니어처·토이 네 크기로 나뉘어요. 어린 강아지의 현재 크기만 보지 말고 부모견과 예상 성견 크기를 확인해 이동 공간과 활동 계획을 세워주세요.",
        image: "/illustrations/v4/poodle-feature-four-sizes.webp",
        alt: "같은 바닥에 성견 스탠더드·미디엄·미니어처·토이 푸들이 큰 순서대로 서 있는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/172g09-en.pdf"],
      },
      {
        eyebrow: "회수와 배움",
        title: "찾고 가져오는 짧은 과제에 집중할 수 있어요.",
        description: "물에서 대상을 회수하던 배경이 있는 만큼 물건을 찾아 가져오거나 새로운 신호를 배우는 활동에 적극적으로 참여할 수 있어요. 성공하기 쉬운 짧은 과제와 조용한 휴식을 번갈아 주세요.",
        image: "/illustrations/v4/poodle-feature-learning-retrieval.webp",
        alt: "공원에서 회수용 더미를 물고 보호자의 손으로 돌아오는 살구색 성견 미니어처 푸들 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/poodle-standard/", "https://www.akc.org/expert-advice/dog-breeds/poodle-history/"],
      },
      {
        eyebrow: "곱슬 피모 관리",
        title: "빗질과 미용을 정기 일정으로 잡아야 해요.",
        description: "촘촘한 곱슬 피모는 계속 자라며 빠진 털이 안쪽에 머물러 엉킬 수 있어요. 피부 가까이까지 나누어 빗고, 원하는 길이에 맞춰 전문 미용과 도구 적응 시간을 계획해주세요.",
        image: "/illustrations/v4/poodle-feature-coat-care.webp",
        alt: "낮은 미끄럼 방지 미용대에서 보호자가 살구색 성견 미니어처 푸들의 곱슬 피모를 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/172g09-en.pdf", "https://www.akc.org/dog-breeds/poodle-standard/"],
      },
    ],
  },
  {
    slug: "dachshund",
    intro: "땅굴의 냄새를 좇던 집중력, 낮고 긴 몸에 맞는 생활 동선, 아홉 가지 바라이어티의 차이를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "땅굴과 후각",
        title: "좁은 곳의 냄새를 끝까지 확인하려 할 수 있어요.",
        description: "지상과 지하에서 사냥감을 추적하도록 발전한 견종이에요. 산책에서는 코로 살필 시간을 충분히 주고, 집에서는 담요나 상자에 숨긴 물건을 안전하게 찾는 과제를 마련해주세요.",
        image: "/illustrations/v4/dachshund-feature-underground-scent.webp",
        alt: "흙굴 모양의 안전한 후각 놀이 상자에서 냄새를 찾는 성견 닥스훈트 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/148g04-en.pdf", "https://www.akc.org/dog-breeds/dachshund/"],
      },
      {
        eyebrow: "낮은 몸과 동선",
        title: "높이보다 미끄럽지 않은 길을 먼저 준비해요.",
        description: "짧은 다리와 긴 몸으로 반복해서 뛰어내리거나 미끄러지는 동선은 부담이 될 수 있어요. 소파에는 안정적인 경사로를 두고 자주 다니는 바닥은 미끄럽지 않게 정리해주세요.",
        image: "/illustrations/v4/dachshund-feature-safe-routes.webp",
        alt: "낮은 소파 옆의 완만한 경사로와 미끄럼 방지 러그를 이용하는 성견 닥스훈트 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/dachshund/"],
      },
      {
        eyebrow: "아홉 바라이어티",
        title: "세 크기와 세 피모를 함께 구분해요.",
        description: "닥스훈트는 스탠더드·미니어처·래빗의 세 크기와 단모·장모·와이어헤어의 세 피모 조합으로 나뉘어요. 이름만 보지 말고 성견 크기와 피모에 맞는 공간과 손질을 확인해주세요.",
        image: "/illustrations/v4/dachshund-feature-nine-varieties.webp",
        alt: "세 가지 크기와 단모·장모·와이어헤어의 차이를 아홉 마리 성견으로 보여주는 닥스훈트 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/148g04-en.pdf"],
      },
    ],
  },
  {
    slug: "beagle",
    intro: "냄새 길을 오래 읽는 산책, 풍부한 목소리의 상황, 먹을거리와 생활 환경의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "냄새와 산책",
        title: "앞으로 가는 거리보다 냄새를 읽는 시간이 중요해요.",
        description: "지면의 냄새를 따라 무리로 사냥하던 후각 하운드예요. 산책에서는 안전한 장비를 사용하고, 정해진 범위 안에서 코로 경로를 확인할 시간을 충분히 마련해주세요.",
        image: "/illustrations/v4/beagle-feature-scent-tracking.webp",
        alt: "공원의 긴 리드줄 안에서 풀밭 냄새를 차분히 추적하는 성견 비글 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/161g06-en.pdf", "https://www.akc.org/dog-breeds/beagle/"],
      },
      {
        eyebrow: "목소리와 알림",
        title: "짖음과 하울링이 나타나는 상황을 먼저 살펴요.",
        description: "냄새를 좇는 동안 무리와 정보를 나누던 배경처럼 다양한 목소리를 낼 수 있어요. 소리를 억누르기보다 무엇을 보거나 들었는지 기록하고, 보호자에게 돌아와 쉬는 순서를 알려주세요.",
        image: "/illustrations/v4/beagle-feature-voice.webp",
        alt: "창밖 소리에 목소리를 낸 뒤 보호자의 손짓을 따라 매트로 돌아오는 성견 비글 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/161g06-en.pdf", "https://www.akc.org/dog-breeds/beagle/"],
      },
      {
        eyebrow: "먹을거리 관리",
        title: "찾는 능력을 막기보다 안전한 환경으로 바꿔요.",
        description: "냄새로 먹을거리를 빠르게 발견할 수 있어요. 사료와 쓰레기는 닫힌 수납공간에 보관하고, 하루 급여량 안에서 노즈워크 상자나 찾기 놀이로 탐색 욕구를 채워주세요.",
        image: "/illustrations/v4/beagle-feature-food-management.webp",
        alt: "닫힌 수납장과 밀폐 쓰레기통이 있는 주방에서 급여를 기다리는 성견 비글 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/beagle/"],
      },
    ],
  },
  {
    slug: "english-cocker-spaniel",
    intro: "사람 가까이에서 찾고 가져오는 활동, 계통에 따른 생활 차이, 긴 귀와 장식털의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "탐색과 회수",
        title: "가까운 거리에서 찾고 가져오는 과제를 즐길 수 있어요.",
        description: "덤불에서 새를 찾아 날아오르게 하던 조렵견이에요. 냄새 상자나 캔버스 더미처럼 안전한 대상을 찾고 보호자에게 돌아오는 짧은 활동을 휴식과 번갈아 주세요.",
        image: "/illustrations/v4/english-cocker-spaniel-feature-search-retrieve.webp",
        alt: "풀밭에서 초록색 캔버스 회수용 더미를 물고 보호자에게 돌아오는 성견 잉글리시 코커 스패니얼 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/005g08-en.pdf", "https://www.akc.org/dog-breeds/english-cocker-spaniel/"],
      },
      {
        eyebrow: "작업형과 쇼형",
        title: "같은 견종 안에서도 체형과 활동 리듬이 달라요.",
        description: "작업 계통과 전시 계통은 체격, 피모량, 활동 성향에서 차이가 나타날 수 있어요. 견종 이름만으로 판단하지 말고 부모견과 성장 환경, 실제 성견의 모습을 확인해주세요.",
        image: "/illustrations/v4/english-cocker-spaniel-feature-working-show.webp",
        alt: "늘씬한 블루 론 작업형과 풍성한 금색 쇼형 성견 잉글리시 코커 스패니얼을 나란히 보여주는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/005g08-en.pdf"],
      },
      {
        eyebrow: "귀와 장식털",
        title: "산책 뒤 귀와 피모를 짧게 확인해요.",
        description: "늘어진 귀와 다리·배의 장식털에는 습기와 풀씨, 작은 이물질이 머물 수 있어요. 산책 뒤 귀 안쪽과 발, 엉킨 털을 살피고 손질 접촉은 짧게 나누어 익혀주세요.",
        image: "/illustrations/v4/english-cocker-spaniel-feature-ear-coat-care.webp",
        alt: "산책 뒤 보호자가 성견 잉글리시 코커 스패니얼의 늘어진 귀와 장식털을 살피는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/005g08-en.pdf", "https://www.akc.org/dog-breeds/english-cocker-spaniel/"],
      },
    ],
  },
  {
    slug: "labrador-retriever",
    intro: "물에서 찾아 가져오는 활동, 큰 몸으로 인사하는 순간, 촘촘한 이중모의 물기와 털갈이 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "물과 회수",
        title: "찾아 물고 돌아오는 협력 활동에 참여할 수 있어요.",
        description: "어부 곁의 물가 작업과 사냥감 회수로 발전한 리트리버예요. 물놀이는 안전한 수질과 완만한 진입로를 확인하고, 회수 활동은 멈춤과 반환 신호까지 짧게 구성해주세요.",
        image: "/illustrations/v4/labrador-retriever-feature-water-retrieval.webp",
        alt: "잔잔하고 얕은 물에서 회수용 더미를 물고 보호자에게 돌아오는 검은색 성견 래브라도 리트리버 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/122g08-en.pdf", "https://www.akc.org/dog-breeds/labrador-retriever/"],
      },
      {
        eyebrow: "큰 몸과 인사",
        title: "반가움도 네 발을 바닥에 둔 채 표현하도록 도와요.",
        description: "사람에게 힘차게 다가가는 개체는 친근한 의도와 별개로 상대를 밀 수 있어요. 방문객과 거리를 확보하고, 보호자에게 돌아와 네 발로 서거나 앉는 짧은 인사 순서를 연습해주세요.",
        image: "/illustrations/v4/labrador-retriever-feature-calm-greeting.webp",
        alt: "현관에서 보호자 곁에 네 발을 바닥에 둔 채 방문객을 맞는 검은색 성견 래브라도 리트리버 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/labrador-retriever/"],
      },
      {
        eyebrow: "이중모와 물기",
        title: "젖은 뒤 속털까지 말리고 털갈이를 준비해요.",
        description: "짧지만 촘촘하고 날씨에 강한 이중모를 지닌 견종이에요. 물놀이 뒤 피부 가까이의 물기와 귀를 확인하고, 털갈이 시기에는 규칙적인 빗질로 빠진 속털을 정리해주세요.",
        image: "/illustrations/v4/labrador-retriever-feature-double-coat-care.webp",
        alt: "물놀이 뒤 보호자가 수건과 브러시로 검은색 성견 래브라도 리트리버의 피모를 관리하는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/122g08-en.pdf"],
      },
    ],
  },
  {
    slug: "golden-retriever",
    intro: "사람과 맞춰 찾아오는 회수 활동, 큰 몸의 차분한 인사, 긴 장식털의 물기와 엉킴 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "협력과 회수",
        title: "대상을 찾아 부드럽게 가져오는 과제를 함께해요.",
        description: "물과 육지에서 사냥한 새를 찾아 회수하도록 발전한 견종이에요. 부드러운 회수용 더미를 찾아 보호자에게 돌아오는 활동을 짧게 구성하고, 성공 뒤에는 조용히 쉬게 해주세요.",
        image: "/illustrations/v4/golden-retriever-feature-cooperative-retrieval.webp",
        alt: "풀밭에서 회수용 더미를 물고 보호자의 손으로 돌아오는 금색 성견 골든 리트리버 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/111g08-en.pdf", "https://www.akc.org/dog-breeds/golden-retriever/"],
      },
      {
        eyebrow: "큰 몸과 인사",
        title: "사람을 좋아해도 차분한 거리는 따로 배워야 해요.",
        description: "반갑게 다가가는 큰 몸은 어린이나 낯선 사람에게 부담이 될 수 있어요. 상대가 인사를 원하는지 확인하고, 보호자 곁에서 기다린 뒤 천천히 다가가는 순서를 알려주세요.",
        image: "/illustrations/v4/golden-retriever-feature-calm-greeting.webp",
        alt: "공원에서 보호자 곁에 차분히 앉아 아이와 거리를 두고 인사를 기다리는 금색 성견 골든 리트리버 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/golden-retriever/"],
      },
      {
        eyebrow: "장식털과 물기",
        title: "귀 뒤와 다리의 긴 털까지 나누어 살펴요.",
        description: "촘촘한 속털과 목·다리·꼬리의 장식털은 젖은 뒤 마르는 데 시간이 걸리고 엉킬 수 있어요. 물놀이와 산책 뒤 물기와 이물질을 확인하고 피부 가까이부터 나누어 빗어주세요.",
        image: "/illustrations/v4/golden-retriever-feature-feathered-coat-care.webp",
        alt: "산책 뒤 보호자가 수건과 브러시로 금색 성견 골든 리트리버의 귀 뒤와 다리 장식털을 관리하는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/111g08-en.pdf"],
      },
    ],
  },
  {
    slug: "german-shepherd-dog",
    intro: "사람과 과제를 맞추는 집중력, 낯선 접근을 다루는 거리, 두 가지 이중모의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "협업과 과제",
        title: "움직이기만큼 사람과 함께 판단할 일이 필요해요.",
        description: "목양과 여러 서비스 작업을 수행해 온 견종이에요. 냄새 상자 구분, 방향 전환, 기다리기처럼 보호자의 신호를 읽고 해결하는 짧은 과제를 휴식과 번갈아 주세요.",
        image: "/illustrations/v4/german-shepherd-dog-feature-cooperative-tasks.webp",
        alt: "공원에서 보호자의 손 신호를 보며 두 냄새 상자 중 하나를 확인하는 성견 저먼 셰퍼드 독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/166g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/german-shepherd-dog/"],
      },
      {
        eyebrow: "낯선 접근과 거리",
        title: "먼저 살필 수 있는 거리가 차분한 반응을 도와요.",
        description: "주변 변화에 빠르게 주의를 돌리는 개체는 방문객을 가까이서 바로 만나면 부담이 커질 수 있어요. 안전문으로 거리를 확보하고 보호자에게 시선을 돌리는 순간을 차분히 알려주세요.",
        image: "/illustrations/v4/german-shepherd-dog-feature-visitor-distance.webp",
        alt: "현관 안전문 안에서 보호자 곁에 머물며 방문객과 거리를 둔 성견 저먼 셰퍼드 독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/166g01-en.pdf"],
      },
      {
        eyebrow: "두 가지 이중모",
        title: "일반모와 장모 모두 속털까지 관리해요.",
        description: "저먼 셰퍼드 독에는 일반 이중모와 장모 이중모가 있어요. 겉털 길이만 보지 말고 피부 가까이의 속털을 나누어 빗고, 털갈이 시기에는 관리 횟수를 늘려주세요.",
        image: "/illustrations/v4/german-shepherd-dog-feature-coat-varieties.webp",
        alt: "일반 이중모와 장모 이중모 성견 저먼 셰퍼드 독이 나란히 있고 한 마리가 빗질받는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/166g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/german-shepherd-dog/"],
      },
    ],
  },
  {
    slug: "korea-jindo-dog",
    intro: "스스로 거리를 선택하는 관계, 움직임에 집중할 때의 출입 안전, 촘촘한 이중모의 계절 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "선택과 신뢰",
        title: "다가오고 물러날 선택권으로 관계를 쌓아요.",
        description: "낯선 사람이나 접촉을 받아들이는 속도는 개체마다 달라요. 억지로 안거나 인사시키기보다 편안한 거리를 두고, 개가 스스로 다가왔을 때 짧고 차분하게 반응해주세요.",
        image: "/illustrations/v4/korea-jindo-dog-feature-choice-and-trust.webp",
        alt: "조용한 공원에서 앉은 보호자의 열린 손으로 스스로 다가가는 백색 성견 진돗개 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/334g05-en.pdf", "https://www.thekkf.or.kr/new_home/03_kkf_service/03_approval_3.php?gid=5&idx=70"],
      },
      {
        eyebrow: "출입과 산책 안전",
        title: "문을 열기 전에 장비와 안쪽 안전문을 확인해요.",
        description: "사냥견의 배경처럼 움직이는 대상에 시선이 오래 머물 수 있어요. 현관과 마당에는 한 번 더 닫히는 구간을 만들고, 문을 열기 전에 몸에 맞는 하네스와 리드를 연결해주세요.",
        image: "/illustrations/v4/korea-jindo-dog-feature-entry-safety.webp",
        alt: "현관 안쪽 안전문 뒤에서 보호자가 하네스와 리드를 연결하는 동안 기다리는 백색 성견 진돗개 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/334g05-en.pdf"],
      },
      {
        eyebrow: "이중모와 털갈이",
        title: "뻣뻣한 겉털 아래 빠진 속털을 나누어 빗어요.",
        description: "부드럽고 조밀한 속털이 빳빳한 겉털을 받치는 이중모예요. 평소에는 피부 상태를 살피며 빗고, 계절성 털갈이에는 빠진 속털이 머물지 않도록 짧게 자주 관리해주세요.",
        image: "/illustrations/v4/korea-jindo-dog-feature-seasonal-coat.webp",
        alt: "밝고 선선한 실내에서 보호자가 백색 성견 진돗개의 빠진 속털을 빗으로 정리하는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/334g05-en.pdf", "https://www.thekkf.or.kr/new_home/03_kkf_service/03_approval_3.php?gid=5&idx=70"],
      },
    ],
  },
  {
    slug: "siberian-husky",
    intro: "먼 거리를 움직이는 지구력, 여러 겹의 출입 안전, 두꺼운 이중모에 맞는 더운 날의 리듬을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "지구력과 보행",
        title: "짧은 전력 질주보다 꾸준히 움직이는 리듬이 어울려요.",
        description: "가벼운 짐을 싣고 적당한 속도로 먼 거리를 이동하던 썰매견이에요. 선선한 날에는 냄새 탐색과 일정한 보행을 섞고, 하네스 활동은 장비와 몸 상태에 맞게 시작해주세요.",
        image: "/illustrations/v4/siberian-husky-feature-endurance.webp",
        alt: "선선한 숲길에서 당김용 하네스를 착용하고 보호자와 일정한 속도로 달리는 성견 시베리안 허스키 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/270g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/siberian-husky/"],
      },
      {
        eyebrow: "출입과 이탈 방지",
        title: "한 개의 문보다 겹쳐 닫히는 동선을 만들어요.",
        description: "이동 욕구가 큰 개체는 열린 출입구를 빠르게 통과할 수 있어요. 현관 안쪽 안전문과 바깥문을 한 번에 열지 않고, 리드와 하네스 연결을 확인한 뒤 이동해주세요.",
        image: "/illustrations/v4/siberian-husky-feature-exit-safety.webp",
        alt: "닫힌 현관 안전문과 바깥 대문 사이에서 보호자가 산책 장비를 확인하는 성견 시베리안 허스키 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/270g05-en.pdf"],
      },
      {
        eyebrow: "이중모와 더위",
        title: "더운 낮에는 활동보다 시원한 회복을 우선해요.",
        description: "북방 환경에 맞는 촘촘한 이중모를 지녔어요. 더운 계절에는 선선한 시간대로 산책을 옮기고, 실내 온도와 물·휴식 자리를 준비하며 피모를 짧게 밀지 말고 상태에 맞게 관리해주세요.",
        image: "/illustrations/v4/siberian-husky-feature-heat-care.webp",
        alt: "더운 낮 커튼과 선풍기가 있는 실내의 쿨매트에서 물그릇 곁에 쉬는 성견 시베리안 허스키 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/270g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/siberian-husky/"],
      },
    ],
  },
  {
    slug: "whippet",
    intro: "빠른 움직임을 보는 시선, 짧게 달리고 회복하는 리듬, 얇은 피모와 몸을 받쳐주는 휴식을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "시각과 안전",
        title: "빠르게 지나가는 대상을 먼저 발견할 수 있어요.",
        description: "눈으로 움직임을 찾고 쫓던 시각 하운드예요. 자전거나 작은 동물에 시선이 고정될 수 있으니 산책에서는 리드를 유지하고, 충분한 거리에서 보호자에게 돌아보는 연습을 해주세요.",
        image: "/illustrations/v4/whippet-feature-visual-tracking.webp",
        alt: "공원에서 멀리 지나가는 자전거를 본 뒤 보호자의 손으로 시선을 돌리는 성견 휘핏 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/162g10-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/whippet/"],
      },
      {
        eyebrow: "질주와 회복",
        title: "짧게 속도를 낸 뒤 천천히 가라앉혀요.",
        description: "속도를 내는 능력과 하루 종일 뛰는 생활은 달라요. 완전히 닫힌 안전한 공간에서 짧게 달릴 기회를 마련하고, 끝난 뒤에는 물을 마시며 호흡과 움직임이 편안해지는지 살펴주세요.",
        image: "/illustrations/v4/whippet-feature-sprint-recovery.webp",
        alt: "울타리가 닫힌 운동장에서 짧게 달린 뒤 보호자 곁에서 물을 마시며 쉬는 성견 휘핏의 두 장면 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/162g10-en.pdf"],
      },
      {
        eyebrow: "보온과 휴식",
        title: "얇은 피모와 몸을 받쳐줄 따뜻한 자리가 필요해요.",
        description: "가늘고 짧은 피모는 추운 날의 바람과 찬 바닥을 그대로 느끼기 쉬워요. 기온과 개별 반응에 맞는 가벼운 옷을 사용하고, 몸 전체를 받쳐주는 푹신한 침구를 마련해주세요.",
        image: "/illustrations/v4/whippet-feature-warm-rest.webp",
        alt: "추운 날 가벼운 옷을 입고 두꺼운 원형 침구에 몸을 말아 쉬는 성견 휘핏 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/162g10-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/whippet/"],
      },
    ],
  },
  {
    slug: "pyrenean-mountain-dog",
    intro: "주변을 스스로 살피는 방식, 밤의 알림을 줄이는 환경, 초대형 성견에 맞는 이동 동선을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "독립적인 관찰",
        title: "지시를 기다리기보다 주변을 오래 살필 수 있어요.",
        description: "산지에서 가축 곁을 지키며 위험을 판단하던 보호견이에요. 안전하게 닫힌 공간에서 주변을 관찰할 시간을 주고, 억지로 시선을 끊기보다 보호자에게 돌아오는 선택을 알려주세요.",
        image: "/illustrations/v4/pyrenean-mountain-dog-feature-independent-watch.webp",
        alt: "안전하게 울타리가 설치된 넓은 정원의 그늘진 자리에서 주변을 살피는 성견 그레이트 피레니즈 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/137g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/pyrenean-mountain-dog/"],
      },
      {
        eyebrow: "밤의 알림",
        title: "소리를 막기 전에 반응할 이유부터 줄여요.",
        description: "밤에도 창밖 움직임이나 먼 소리를 확인하려는 개체가 있어요. 암막 커튼으로 시야를 줄이고 휴식 자리를 창에서 옮긴 뒤, 일정한 생활 소리와 매트에서 쉬는 순서를 마련해주세요.",
        image: "/illustrations/v4/pyrenean-mountain-dog-feature-night-alert.webp",
        alt: "밤에 보호자가 암막 커튼을 닫고 백색소음 기기를 켜는 동안 큰 매트에서 쉬는 성견 그레이트 피레니즈 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/137g02-en.pdf"],
      },
      {
        eyebrow: "초대형 생활 동선",
        title: "성견의 크기로 차량과 문, 이동 방법을 계산해요.",
        description: "성견은 체고가 80cm에 이를 수 있어 안아 옮기기 어렵고 작은 차량이나 좁은 문이 부담이 될 수 있어요. 넓은 출입구와 미끄럽지 않은 경사로, 몸을 받칠 휴식 공간을 미리 준비해주세요.",
        image: "/illustrations/v4/pyrenean-mountain-dog-feature-giant-scale.webp",
        alt: "넓고 낮은 미끄럼 방지 경사로를 이용해 큰 차량에 오르는 성견 그레이트 피레니즈 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/137g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/pyrenean-mountain-dog/"],
      },
    ],
  },
  {
    slug: "french-bulldog",
    intro: "짧은 얼굴에 맞춘 회복 관찰, 더위를 피하는 활동 시간, 얼굴 주름과 귀의 일상 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "호흡과 회복",
        title: "운동량보다 편안하게 회복하는지 먼저 봐요.",
        description: "짧은 얼굴 구조 때문에 같은 활동 뒤에도 호흡 부담이 다르게 나타날 수 있어요. 짧게 움직인 뒤 그늘에서 쉬게 하고, 평소보다 거친 숨이나 늦은 회복을 귀여운 특징으로 넘기지 마세요.",
        image: "/illustrations/v4/french-bulldog-feature-breathing-recovery.webp",
        alt: "짧은 실내 놀이 뒤 보호자가 시간을 확인하는 동안 물그릇 곁에서 차분히 회복하는 황갈색 성견 프렌치 불도그 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/101g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/french-bulldog/"],
      },
      {
        eyebrow: "더위와 활동 시간",
        title: "더운 낮을 피하고 선선한 시간에 짧게 걸어요.",
        description: "기온과 습도가 높으면 체온을 낮추기 어려울 수 있어요. 산책은 아침이나 저녁으로 옮기고, 그늘과 물을 준비한 뒤 호흡 상태에 따라 바로 멈출 수 있는 짧은 동선을 고르세요.",
        image: "/illustrations/v4/french-bulldog-feature-heat-aware-walk.webp",
        alt: "햇빛이 약한 나무 그늘 산책로에서 보호자 곁에 서 있고 물그릇이 준비된 황갈색 성견 프렌치 불도그 삽화",
        sourceUrls: ["https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/french-bulldog/"],
      },
      {
        eyebrow: "얼굴과 귀 관리",
        title: "주름 사이의 습기와 큰 귀 안쪽을 나누어 살펴요.",
        description: "얼굴 주름과 귀는 겉에서 보기 어려운 자극이나 습기가 남을 수 있어요. 부드럽게 닦은 뒤 완전히 말리고, 냄새·붉어짐·불편함이 반복되면 가정 관리만 이어가지 말고 진료를 받아주세요.",
        image: "/illustrations/v4/french-bulldog-feature-face-care.webp",
        alt: "미끄럼 방지 매트 위에서 보호자가 황갈색 성견 프렌치 불도그의 얼굴 주름과 큰 귀를 부드럽게 살피는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/101g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/french-bulldog/"],
      },
    ],
  },
  {
    slug: "basenji",
    intro: "시각과 후각을 함께 쓰는 탐색, 짖음과 다른 소리 표현, 짧은 피모에 맞는 추운 날의 보호를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "시각·후각 탐색",
        title: "냄새를 맡는 동안에도 먼 움직임을 함께 살필 수 있어요.",
        description: "사냥에서 시각과 후각을 함께 사용한 견종이에요. 산책에서는 몸에 맞는 하네스와 리드를 유지하고, 빠른 대상에 시선이 고정되기 전 충분한 거리에서 보호자에게 돌아보는 선택을 알려주세요.",
        image: "/illustrations/v4/basenji-feature-tracking-safety.webp",
        alt: "공원에서 냄새를 맡다가 멀리 지나가는 자전거를 바라보며 보호자의 리드 안에 머무는 적백색 성견 바센지 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/043g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/basenji/"],
      },
      {
        eyebrow: "독특한 소리 표현",
        title: "짖음이 적다는 말이 조용하다는 뜻은 아니에요.",
        description: "바센지는 일반적인 짖음 외에도 요들처럼 들리는 독특한 소리로 감정과 요구를 표현할 수 있어요. 소리 자체를 억누르기보다 언제 무엇에 반응하는지 살피고 차분한 휴식으로 전환해주세요.",
        image: "/illustrations/v4/basenji-feature-vocal-expression.webp",
        alt: "거실에서 입을 열어 독특한 소리를 내고 보호자가 차분히 관찰하는 적백색 성견 바센지 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/043g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/basenji/"],
      },
      {
        eyebrow: "짧은 피모와 추위",
        title: "선선함과 추위를 같은 조건으로 보지 않아요.",
        description: "짧고 고운 피모는 관리가 간단해 보여도 찬 바람을 막아주는 층이 두껍지 않아요. 기온과 개별 반응에 맞는 옷을 사용하고, 산책 뒤에는 따뜻하고 외풍 없는 자리에서 쉬게 해주세요.",
        image: "/illustrations/v4/basenji-feature-cold-weather.webp",
        alt: "추운 날 얇은 보온복을 입고 현관 안쪽 따뜻한 침구로 들어오는 적백색 성견 바센지 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/043g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/basenji/"],
      },
    ],
  },
  {
    slug: "welsh-corgi-pembroke",
    intro: "움직이는 대상을 읽는 몰이 집중, 낮고 긴 몸에 맞는 안전한 동선, 촘촘한 이중모의 털갈이를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "움직임과 몰이 집중",
        title: "빠르게 움직이는 발과 방향 변화에 주의가 모일 수 있어요.",
        description: "소의 움직임을 읽으며 몰던 목축견이에요. 달리는 사람이나 자전거에 집중할 때는 거리를 확보하고, 뒤쫓기 전에 보호자의 손 신호를 보고 방향을 바꾸는 짧은 연습을 해주세요.",
        image: "/illustrations/v4/welsh-corgi-pembroke-feature-moving-focus.webp",
        alt: "공원에서 멀리 달리는 아이들을 본 뒤 무릎을 낮춘 보호자의 손 신호로 시선을 돌리는 적백색 성견 웰시 코기 펨브로크 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/039g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/pembroke-welsh-corgi/"],
      },
      {
        eyebrow: "낮은 몸과 동선",
        title: "높은 점프보다 낮고 미끄럽지 않은 길을 만들어요.",
        description: "짧은 다리와 긴 몸은 활동을 막아야 한다는 뜻이 아니에요. 소파 주변에 낮은 경사로와 미끄럼 방지 매트를 두고, 반복해서 뛰어내리는 대신 네 발로 천천히 오르내리는 습관을 알려주세요.",
        image: "/illustrations/v4/welsh-corgi-pembroke-feature-safe-routes.webp",
        alt: "소파 옆 낮은 경사로와 미끄럼 방지 매트를 네 발로 이용하는 적백색 성견 웰시 코기 펨브로크 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/039g01-en.pdf"],
      },
      {
        eyebrow: "이중모와 털갈이",
        title: "짧은 겉털 아래의 촘촘한 속털까지 나누어 빗어요.",
        description: "짧거나 중간 길이의 겉털 아래에는 날씨를 견디는 촘촘한 속털이 있어요. 평소에는 피부 가까이 엉킴과 상태를 살피고, 계절성 털갈이에는 빠진 속털이 머물지 않도록 짧게 자주 빗어주세요.",
        image: "/illustrations/v4/welsh-corgi-pembroke-feature-double-coat.webp",
        alt: "미끄럼 방지 미용대에서 보호자가 적백색 성견 웰시 코기 펨브로크의 빠진 속털을 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/039g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/pembroke-welsh-corgi/"],
      },
    ],
  },
  {
    slug: "miniature-schnauzer",
    intro: "주변을 알린 뒤 돌아오는 연습, 작은 대상을 찾는 탐색 과제, 수염과 거친 피모의 반복 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "알림과 돌아오기",
        title: "알아차린 뒤 보호자 곁으로 돌아오는 순서를 만들어요.",
        description: "현관 소리나 방문객을 빠르게 알아차리는 개체가 있어요. 반응을 혼내기보다 문과 거리를 둔 매트를 마련하고, 한 번 확인한 뒤 보호자의 손 신호를 따라 돌아와 쉬는 순서를 짧게 연습해주세요.",
        image: "/illustrations/v4/miniature-schnauzer-feature-alert-return.webp",
        alt: "닫힌 현관문을 확인한 뒤 보호자의 열린 손과 작은 매트 쪽으로 돌아오는 솔트앤페퍼 성견 미니어처 슈나우저 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/183g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/miniature-schnauzer/"],
      },
      {
        eyebrow: "찾기와 문제 해결",
        title: "작은 움직임을 찾던 집중력을 안전한 과제로 바꿔요.",
        description: "농장 주변의 작은 해수를 살피던 배경이 있어요. 살아 있는 동물을 쫓게 하기보다 냄새 상자나 천 장난감 중 목표를 찾는 과제로 탐색 욕구를 쓰고, 성공 뒤에는 흥분을 낮춰 쉬게 해주세요.",
        image: "/illustrations/v4/miniature-schnauzer-feature-search-tasks.webp",
        alt: "정원에서 낮은 냄새 상자 안의 천 장난감을 찾는 솔트앤페퍼 성견 미니어처 슈나우저 삽화",
        sourceUrls: ["https://www.akc.org/expert-advice/dog-breeds/miniature-schnauzer-history/"],
      },
      {
        eyebrow: "수염과 거친 피모",
        title: "수염의 물기와 몸의 빗질을 따로 챙겨요.",
        description: "거친 겉털과 부드러운 속털, 긴 수염은 관리 지점이 달라요. 몸은 피부 가까이 나누어 빗고 음식이나 물이 묻은 수염은 닦아 완전히 말리며, 원하는 피모 길이에 맞춰 정기 미용을 계획하세요.",
        image: "/illustrations/v4/miniature-schnauzer-feature-beard-coat-care.webp",
        alt: "미끄럼 방지 미용대에서 보호자가 솔트앤페퍼 성견 미니어처 슈나우저의 수염을 닦고 몸의 거친 털을 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/183g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/miniature-schnauzer/"],
      },
    ],
  },
  {
    slug: "yorkshire-terrier",
    intro: "아주 작은 몸에 맞는 생활 안전, 테리어의 탐색 욕구, 길고 곧은 실키 코트의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "작은 몸과 안전",
        title: "안아 옮기기만 하기보다 스스로 걷는 안전한 길을 만들어요.",
        description: "작은 체격은 소파에서의 낙상이나 큰 발에 부딪히는 일도 큰 부담이 될 수 있어요. 낮은 경사로와 미끄럼 방지 매트를 두고, 가족이 이동할 때 개의 위치를 먼저 확인하는 습관을 함께 들이세요.",
        image: "/illustrations/v4/yorkshire-terrier-feature-small-body-safety.webp",
        alt: "거실에서 보호자가 지켜보는 가운데 소파 옆 낮은 경사로를 이용하는 청색과 황갈색 성견 요크셔 테리어 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/086g03-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/yorkshire-terrier/"],
      },
      {
        eyebrow: "테리어의 탐색",
        title: "작은 크기 안의 집중력을 찾기 놀이로 써요.",
        description: "소형 테리어의 배경처럼 좁은 공간과 작은 움직임을 세심하게 살필 수 있어요. 낮은 냄새 상자나 천 장난감을 찾아보는 짧은 과제를 주고, 살아 있는 작은 동물을 쫓는 놀이는 피해주세요.",
        image: "/illustrations/v4/yorkshire-terrier-feature-terrier-search.webp",
        alt: "거실 러그 위의 낮은 냄새 상자를 살피는 청색과 황갈색 성견 요크셔 테리어 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/086g03-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/yorkshire-terrier/"],
      },
      {
        eyebrow: "실키 코트 관리",
        title: "긴 털은 피부 가까이부터 나누어 빗어요.",
        description: "몸 양옆으로 곧게 내려오는 가늘고 긴 피모는 엉킴과 바닥의 이물질을 자주 확인해야 해요. 미끄럽지 않은 자리에서 털을 층별로 나누어 빗고, 눈을 가리는 얼굴 털과 생활에 맞는 길이도 함께 관리하세요.",
        image: "/illustrations/v4/yorkshire-terrier-feature-silky-coat-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 청색과 황갈색 성견 요크셔 테리어의 길고 곧은 피모를 나누어 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/086g03-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/yorkshire-terrier/"],
      },
    ],
  },
  {
    slug: "shiba",
    intro: "스스로 거리를 선택하는 관계, 사냥 배경에 맞춘 출입 안전, 계절마다 크게 바뀌는 이중모 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "선택과 신뢰",
        title: "다가오고 물러날 선택권을 남겨두어요.",
        description: "접촉을 받아들이는 속도와 방식은 개체마다 달라요. 먼저 손을 뻗어 붙잡기보다 편안한 거리를 두고, 개가 스스로 다가왔을 때 짧게 반응한 뒤 물러날 수 있게 해주세요.",
        image: "/illustrations/v4/shiba-feature-choice-and-trust.webp",
        alt: "조용한 거실에서 앉은 보호자의 열린 손으로 스스로 다가가는 적색 성견 시바 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/257g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/japanese-shiba-inu/"],
      },
      {
        eyebrow: "출입과 추적 안전",
        title: "문을 열기 전에 안쪽 안전문과 산책 장비를 확인해요.",
        description: "산지에서 냄새와 움직임을 좇던 사냥견의 배경이 있어요. 현관에는 한 번 더 닫히는 구간을 만들고, 바깥문을 열기 전에 몸에 맞는 하네스와 리드가 연결됐는지 확인해주세요.",
        image: "/illustrations/v4/shiba-feature-entry-safety.webp",
        alt: "닫힌 현관 안전문 안쪽에서 보호자가 적색 성견 시바의 하네스와 리드를 확인하는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/257g05-en.pdf"],
      },
      {
        eyebrow: "계절성 이중모",
        title: "짧은 겉털 아래 빠진 속털을 나누어 빗어요.",
        description: "곧고 단단한 겉털 아래에는 부드럽고 촘촘한 속털이 있어요. 평소에는 피부 상태를 살피며 빗고, 계절성 털갈이에는 빠진 속털이 머물지 않도록 관리 횟수를 늘려주세요.",
        image: "/illustrations/v4/shiba-feature-seasonal-coat.webp",
        alt: "미끄럼 방지 매트에서 보호자가 적색 성견 시바의 빠진 속털을 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/257g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/japanese-shiba-inu/"],
      },
    ],
  },
  {
    slug: "akita",
    intro: "관계를 서두르지 않는 거리, 큰 힘을 차분히 다루는 보행, 들어 올릴 수 없는 성견의 이동 동선을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "관계와 거리",
        title: "낯선 대상과 꼭 가까이 인사하지 않아도 괜찮아요.",
        description: "낯선 사람이나 개를 받아들이는 범위는 개체와 경험에 따라 달라요. 충분한 거리에서 관찰할 수 있게 하고, 피하거나 보호자 곁으로 돌아오는 선택을 막지 마세요.",
        image: "/illustrations/v4/akita-feature-respectful-distance.webp",
        alt: "공원에서 보호자 곁에 서서 멀리 지나가는 낯선 사람을 차분히 관찰하는 적색 성견 아키타 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/255g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/japanese-akita-inu/"],
      },
      {
        eyebrow: "큰 힘과 보행",
        title: "당기기 시작한 뒤보다 멈추고 방향을 바꾸는 연습을 먼저 해요.",
        description: "성견의 큰 체격과 힘은 일상 산책에서도 충분한 준비를 요구해요. 넓고 조용한 길에서 보호자의 신호에 맞춰 멈추고 돌아서는 동작을 짧게 연습하고, 몸에 맞는 장비를 사용해주세요.",
        image: "/illustrations/v4/akita-feature-calm-walking.webp",
        alt: "넓은 산책로에서 보호자의 손 신호에 맞춰 멈추고 방향을 바꾸는 적색 성견 아키타 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/255g05-en.pdf"],
      },
      {
        eyebrow: "대형견 이동 동선",
        title: "들어 올릴 수 없을 때의 이동 방법을 미리 연습해요.",
        description: "성견의 큰 체격은 차량 탑승이나 병원 이동에서도 별도의 준비를 요구해요. 넓고 미끄럽지 않은 발판이나 낮은 경사로를 마련하고, 아프기 전부터 천천히 오르고 머무는 과정을 짧게 연습해주세요.",
        image: "/illustrations/v4/akita-feature-large-dog-route.webp",
        alt: "보호자가 적색 성견 아키타와 함께 넓은 미끄럼 방지 경사로를 이용해 차량 탑승을 연습하는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/255g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/japanese-akita-inu/"],
      },
    ],
  },
  {
    slug: "bichon-frise",
    intro: "여러 생활 공간에 적응해 온 반려견의 배경, 구름 같은 외모 안의 활기찬 움직임, 촘촘한 곱슬 피모의 구조를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람 곁의 반려견",
        title: "여러 생활 공간에 적응하며 사람 가까이 머물러 온 소형견이에요.",
        description: "비숑 프리제는 특정 작업보다 사람과 함께 이동하고 생활하는 반려견으로 자리 잡았습니다. 사람의 관심을 적극적으로 찾는 개체라면 교감 시간과 더불어 가까운 자기 자리에서 편히 쉬는 경험도 마련해주세요.",
        image: "/illustrations/v4/bichon-frise-feature-independent-rest.webp",
        alt: "보호자가 책상에서 일하는 동안 조금 떨어진 자기 매트에서 편안히 쉬는 백색 성견 비숑 프리제 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/215g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/bichon-frise/"],
      },
      {
        eyebrow: "활기찬 움직임",
        title: "둥글고 풍성한 외모 안에는 빠르고 가벼운 움직임이 있어요.",
        description: "비숑 프리제의 움직임은 빠르고 자유로우며 작은 몸으로도 제법 넓게 나아가는 것이 특징입니다. 산책과 짧은 이동 과제로 몸을 쓰게 하되, 흥분이 커지기 전에 자기 자리에서 쉬는 순서까지 함께 알려주세요.",
        image: "/illustrations/v4/bichon-frise-feature-cooperative-learning.webp",
        alt: "실내의 두 낮은 표식 사이를 보호자의 손 신호에 맞춰 이동한 뒤 매트에서 쉬는 백색 성견 비숑 프리제의 연속 장면 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/215g09-en.pdf"],
      },
      {
        eyebrow: "곱슬 피모와 건조",
        title: "겉모양보다 피부 가까이의 엉킴과 습기를 확인해요.",
        description: "부드러운 나선형 털은 빠진 털이 피모 안에 머물며 엉킬 수 있어요. 작은 구역으로 나누어 피부 가까이부터 빗고, 목욕 뒤에는 속까지 완전히 말리는 시간과 정기 미용을 계획하세요.",
        image: "/illustrations/v4/bichon-frise-feature-curly-coat-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 백색 성견 비숑 프리제의 곱슬 피모를 나누어 빗고 수건과 드라이어를 준비한 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/215g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/bichon-frise/"],
      },
    ],
  },
  {
    slug: "cavalier-king-charles-spaniel",
    intro: "사람 곁의 토이 스패니얼이라는 배경, 작은 몸에 남은 탐색 욕구, 긴 귀와 장식털의 특징을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "교감과 혼자 쉬기",
        title: "붙어 있는 시간과 자기 자리의 휴식을 함께 알려줘요.",
        description: "가족 가까이 머무는 것을 선호하는 개체가 많지만, 늘 접촉해야만 편안해지면 혼자 있는 순간이 어려워질 수 있어요. 같은 방의 매트에서 시작해 짧고 편안한 독립 휴식을 익혀주세요.",
        image: "/illustrations/v4/cavalier-king-charles-spaniel-feature-independent-rest.webp",
        alt: "보호자가 소파에서 책을 읽는 동안 조금 떨어진 자기 매트에서 편안히 쉬는 블렌하임 성견 캐벌리어 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/136g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/cavalier-king-charles-spaniel/"],
      },
      {
        eyebrow: "스패니얼의 탐색",
        title: "느린 산책에서도 코를 쓰는 시간을 충분히 줘요.",
        description: "작은 반려견이지만 스패니얼다운 움직임과 탐색 욕구를 함께 지녔어요. 조용한 길에서 냄새를 선택해 맡게 하고, 보호자에게 돌아보는 순간과 느슨한 리드를 차분히 보상해주세요.",
        image: "/illustrations/v4/cavalier-king-charles-spaniel-feature-scent-walk.webp",
        alt: "조용한 숲길에서 하네스와 느슨한 리드를 착용하고 낙엽 냄새를 맡는 블렌하임 성견 캐벌리어 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/136g09-en.pdf"],
      },
      {
        eyebrow: "긴 귀와 장식털",
        title: "실키한 긴 귀와 가슴·다리의 장식털이 외형을 이뤄요.",
        description: "높게 자리한 긴 귀와 가슴·다리·발의 풍성한 장식털은 캐벌리어를 알아보는 중요한 특징입니다. 산책 뒤 귀와 긴 털에 붙은 이물질과 물기를 확인하고, 잡아당기지 않도록 작은 구역으로 나누어 빗어주세요.",
        image: "/illustrations/v4/cavalier-king-charles-spaniel-feature-feathered-coat-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 블렌하임 성견 캐벌리어의 귀 뒤와 가슴 장식털을 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/136g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/cavalier-king-charles-spaniel/"],
      },
    ],
  },
  {
    slug: "pug",
    intro: "활동 뒤 호흡 회복, 더위를 피하는 짧은 동선, 얼굴 주름과 눈의 일상 점검을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "호흡과 회복",
        title: "짧게 움직인 뒤 편안한 숨으로 돌아오는지 봐요.",
        description: "짧은 얼굴 구조에서는 활동의 길이보다 호흡 상태와 회복 시간이 더 중요한 기준이 될 수 있어요. 조금이라도 거친 숨이 길어지면 즉시 멈추고 서늘한 자리에서 쉬게 해주세요.",
        image: "/illustrations/v4/pug-feature-breathing-recovery.webp",
        alt: "짧은 실내 활동 뒤 보호자가 시간을 확인하는 동안 물그릇 곁의 쿨매트에서 쉬는 황갈색 성견 퍼그 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/253g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/pug/"],
      },
      {
        eyebrow: "더위와 짧은 동선",
        title: "선선한 시간과 그늘을 먼저 고르고 멀리 가지 않아요.",
        description: "기온과 습도가 높으면 체온을 낮추기 어려울 수 있어요. 산책은 이른 아침이나 저녁의 그늘진 짧은 길로 옮기고, 물과 바로 돌아올 수 있는 동선을 준비해주세요.",
        image: "/illustrations/v4/pug-feature-cool-walk.webp",
        alt: "이른 아침 그늘진 산책로에서 보호자와 짧게 걷고 근처 벤치에 물그릇이 준비된 황갈색 성견 퍼그 삽화",
        sourceUrls: ["https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/pug/"],
      },
      {
        eyebrow: "얼굴 주름과 눈",
        title: "주름 속 습기와 돌출된 눈의 변화를 매일 확인해요.",
        description: "얼굴 주름에는 습기와 이물질이 남기 쉽고 큰 눈은 주변 자극에 노출될 수 있어요. 부드럽게 닦고 완전히 말린 뒤, 붉어짐·눈물·불편함이 반복되면 진료를 받아주세요.",
        image: "/illustrations/v4/pug-feature-face-eye-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 황갈색 성견 퍼그의 얼굴 주름을 닦고 눈 상태를 살피는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/253g09-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/pug/"],
      },
    ],
  },
  {
    slug: "bernese-mountain-dog",
    intro: "사람 가까이에서 보조를 맞추는 성향, 큰 몸의 힘을 조절하는 방식, 장모 삼색 이중모의 특징을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과 보조 맞추기",
        title: "가족 가까이에서 함께 움직이고 맡은 일에 참여하려 할 수 있어요.",
        description: "사람 곁에서 여러 일을 보조하던 배경은 오늘의 생활에서 가족의 움직임을 따라다니거나 함께하는 과제에 차분히 참여하는 모습으로 나타날 수 있어요. 가벼운 물건 찾기나 옮기기처럼 속도보다 협업에 집중하는 활동을 마련해보세요.",
        image: "/illustrations/v4/bernese-mountain-dog-feature-shared-task.webp",
        alt: "현대의 정원에서 보호자 곁을 걸으며 가벼운 천 바구니를 옮기는 성견 버니즈 마운틴 독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/045g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/bernese-mountain-dog/"],
      },
      {
        eyebrow: "차분한 힘",
        title: "큰 몸과 힘을 천천히 멈추고 방향을 바꾸는 연습이 중요해요.",
        description: "차분해 보이는 개체도 성견이 되면 몸의 무게와 힘만으로 좁은 동선이나 인사 상황에 부담을 줄 수 있어요. 넓은 회전 공간과 느슨한 리드, 천천히 멈추는 경험을 일찍 익히면 사람과 안전하게 보조를 맞추는 데 도움이 됩니다.",
        image: "/illustrations/v4/bernese-mountain-dog-feature-controlled-strength.webp",
        alt: "넓은 농장 마당의 두 표식 사이를 지난 뒤 보호자 곁에서 차분히 멈춘 성견 버니즈 마운틴 독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/045g02-en.pdf"],
      },
      {
        eyebrow: "장모 삼색 이중모",
        title: "검정·황갈색·흰색 피모 안쪽의 엉킴과 습기까지 살펴요.",
        description: "길고 풍성한 검은 바탕 털과 황갈색 포인트, 제한된 흰 무늬는 버니즈를 알아보는 중요한 특징입니다. 큰 몸의 이중모는 빗질과 건조에 시간이 많이 들고 더위에도 부담이 될 수 있어, 서늘한 환경과 피부 가까이까지 확인하는 관리가 필요해요.",
        image: "/illustrations/v4/bernese-mountain-dog-feature-tricolor-coat-care.webp",
        alt: "서늘한 현관의 미끄럼 방지 매트에서 보호자가 성견 버니즈 마운틴 독의 장모 삼색 피모를 수건으로 말리는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/045g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/bernese-mountain-dog/"],
      },
    ],
  },
  {
    slug: "dobermann",
    intro: "보호자 중심의 주의, 빠른 판단과 협업, 짧은 피모가 만드는 추위 부담을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "보호자 중심의 주의",
        title: "주변을 살피면서도 보호자의 위치와 반응을 함께 확인할 수 있어요.",
        description: "사람 가까이에서 주변을 살피던 역할은 생활에서도 낯선 접근을 빠르게 알아차리고 보호자의 반응을 확인하는 모습으로 나타날 수 있어요. 경계를 키우기보다 충분한 거리를 두고 본 뒤 보호자에게 시선을 돌리는 흐름을 반복해주세요.",
        image: "/illustrations/v4/dobermann-feature-handler-focused-attention.webp",
        alt: "현대 공원에서 멀리 있는 방문자를 확인한 뒤 보호자의 손 신호를 바라보는 자연 귀와 긴 꼬리의 성견 도베르만 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/143g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/dobermann/"],
      },
      {
        eyebrow: "빠른 판단과 협업",
        title: "주변을 살핀 뒤 보호자의 작은 신호로 빠르게 돌아올 수 있어요.",
        description: "빠른 주의 전환과 높은 협업 욕구가 함께 나타나는 개체는 짧고 분명한 신호 과제에 깊이 집중할 수 있어요. 자극을 본 뒤 보호자에게 돌아오고 함께 이동하는 과제로 민첩함을 안전한 협업 방향으로 연결해주세요.",
        image: "/illustrations/v4/dobermann-feature-handler-cooperation.webp",
        alt: "공원의 낮은 표식을 확인한 뒤 느슨한 리드로 보호자의 손 신호를 바라보는 자연 귀와 긴 꼬리의 성견 도베르만 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/143g02-en.pdf"],
      },
      {
        eyebrow: "짧은 피모와 추위",
        title: "몸에 밀착된 짧은 털은 추운 날 보온을 대신해주지 못해요.",
        description: "도베르만의 피모는 짧고 단단하며 몸에 가깝게 붙어 있어 날렵한 윤곽이 그대로 드러납니다. 기온이 낮거나 바람이 센 날에는 활동 시간과 몸 상태를 살피고, 필요한 개체에게 움직임을 방해하지 않는 보온 의류를 준비하세요.",
        image: "/illustrations/v4/dobermann-feature-short-coat-cold.webp",
        alt: "눈이 쌓인 길로 나가기 전 현관에서 보호자가 자연 귀와 긴 꼬리의 성견 도베르만에게 보온 외투를 입히는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/143g02-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/dobermann/"],
      },
    ],
  },
  {
    slug: "german-spitz",
    intro: "한 품종 안의 다섯 크기 바라이어티, 집과 농가의 변화를 알리던 빠른 반응, 풍성하게 선 이중모를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "다섯 바라이어티",
        title: "울프스피츠부터 포메라이언까지 한 품종 안에서 크기가 크게 달라요.",
        description: "저먼 스피츠에는 울프스피츠, 자이언트, 미디엄, 미니어처, 포메라이언의 다섯 바라이어티가 있습니다. 같은 스피츠형 외모를 공유해도 성견의 크기와 필요한 공간·이동 장비가 크게 달라, 이름 뒤의 바라이어티를 반드시 함께 확인해야 해요.",
        image: "/illustrations/v4/german-spitz-feature-five-varieties.webp",
        alt: "울프스피츠부터 주황색 포메라이언까지 서로 다른 크기의 저먼 스피츠 다섯 바라이어티를 나란히 보여주는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/097g05-en.pdf"],
      },
      {
        eyebrow: "빠른 알림 반응",
        title: "작은 소리와 방문을 먼저 알아차려 목소리로 알릴 수 있어요.",
        description: "현관 소리나 창밖 움직임을 빠르게 알아차리고 목소리로 알리는 개체가 있어요. 소리를 막는 것만으로 끝내지 말고, 확인 뒤 보호자를 바라보고 쉬는 자리로 이동하는 흐름을 알려주세요.",
        image: "/illustrations/v4/german-spitz-feature-alert-reorientation.webp",
        alt: "현관 밖의 택배 소리를 확인한 뒤 보호자의 손 신호 쪽으로 고개를 돌리는 주황색 성견 포메라이언 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/097g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/pomeranian/"],
      },
      {
        eyebrow: "서 있는 이중모",
        title: "풍성한 겉털 아래의 두꺼운 속털까지 나누어 확인해요.",
        description: "곧게 서는 긴 겉털과 짧고 두꺼운 속털, 목 둘레의 풍성한 갈기는 저먼 스피츠의 공통된 외형을 만듭니다. 겉면만 빗으면 빠진 속털과 엉킴을 놓칠 수 있으므로 작은 구역씩 털을 들어 올려 피부 가까이까지 살펴주세요.",
        image: "/illustrations/v4/german-spitz-feature-double-coat-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 주황색 성견 포메라이언의 풍성한 이중모를 작은 구역으로 나누어 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/097g05-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/toy/pomeranian/"],
      },
    ],
  },
  {
    slug: "shetland-sheepdog",
    intro: "달리는 대상의 경로를 읽는 모습, 소리와 작은 신호에 대한 빠른 반응, 길고 풍성한 이중모를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "몰이와 움직임",
        title: "달리는 대상의 경로를 읽고 따라가거나 앞을 막으려 할 수 있어요.",
        description: "가축의 방향을 세밀하게 살피던 역할은 생활에서 자전거·달리는 사람·다른 동물의 움직임에 빠르게 집중하는 모습으로 나타날 수 있어요. 충분한 거리를 확보하고 움직임을 본 뒤 보호자에게 돌아오는 선택을 차분히 알려주세요.",
        image: "/illustrations/v4/shetland-sheepdog-feature-alert-reorientation.webp",
        alt: "멀리 지나가는 자전거를 본 뒤 넓은 거리를 둔 채 보호자의 손 신호로 고개를 돌리는 성견 셔틀랜드 시프독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/088g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/shetland-sheepdog/"],
      },
      {
        eyebrow: "소리와 작은 신호",
        title: "작은 소리와 사람의 표정 변화를 빠르게 알아차릴 수 있어요.",
        description: "주변 소리와 사람의 작은 몸짓을 함께 읽는 개체는 현관음이나 가족의 움직임에도 빠르게 반응할 수 있어요. 예측 가능한 휴식 자리를 마련하고, 소리를 확인한 뒤 짧은 손 신호에 집중하고 다시 쉬는 흐름을 만들어주세요.",
        image: "/illustrations/v4/shetland-sheepdog-feature-sound-cue.webp",
        alt: "현대의 조용한 현관 매트에서 복도 소리를 확인한 뒤 보호자의 손 신호를 바라보는 성견 셔틀랜드 시프독 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/088g01-en.pdf"],
      },
      {
        eyebrow: "긴 이중모",
        title: "목둘레 갈기와 장식털 아래의 엉키기 쉬운 구역을 따로 살펴요.",
        description: "길고 곧은 겉털과 부드럽고 촘촘한 속털, 풍성한 목둘레와 다리 장식털이 셔틀랜드 시프독의 윤곽을 만듭니다. 특히 귀 뒤와 겨드랑이는 마찰로 엉키기 쉬워 겉털을 잡아당기지 않도록 작은 구역씩 나누어 빗어야 해요.",
        image: "/illustrations/v4/shetland-sheepdog-feature-long-coat-care.webp",
        alt: "미끄럼 방지 매트에서 보호자가 세이블 앤 화이트 성견 셔틀랜드 시프독의 귀 뒤와 긴 장식털을 나누어 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/088g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/shetland-sheepdog/"],
      },
    ],
  },
  {
    slug: "australian-shepherd",
    intro: "움직이는 대상에 대한 몰이 집중, 사람과 계속 주고받는 과제, 높은 활동 뒤 휴식으로 전환하는 능력을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "움직임을 읽는 몰이",
        title: "달리는 대상의 방향을 읽고 따라가거나 앞을 막으려 할 수 있어요.",
        description: "가축의 흐름을 읽던 작업 특성은 생활에서 아이·자전거·다른 동물의 움직임에 강하게 집중하는 모습으로 나타날 수 있어요. 쫓기 시작한 뒤 제지하기보다 넉넉한 거리를 두고 보호자를 확인하거나 다른 경로로 전환하는 경험을 먼저 쌓아주세요.",
        image: "/illustrations/v4/australian-shepherd-feature-movement-focus.webp",
        alt: "현대 공원에서 멀리 지나가는 자전거를 확인한 뒤 보호자의 손 신호를 바라보는 긴 꼬리의 블루멀 성견 오스트레일리안 셰퍼드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/342g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/australian-shepherd/"],
      },
      {
        eyebrow: "지속적인 협업",
        title: "한 번의 운동보다 사람과 계속 주고받는 과제에 깊이 몰입할 수 있어요.",
        description: "사람의 방향 신호를 읽으며 위치를 바꾸는 데 집중하는 개체는 목적 없는 달리기보다 찾기·구분하기·멈추기를 이어가는 과제에서 만족을 얻을 수 있어요. 과제의 난도와 시간을 조절해 흥분만 높아지지 않도록 살펴주세요.",
        image: "/illustrations/v4/australian-shepherd-feature-cooperative-task.webp",
        alt: "현대 공원의 낮은 표식 사이에서 보호자의 손 신호를 확인하는 긴 꼬리의 블루멀 성견 오스트레일리안 셰퍼드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/342g01-en.pdf"],
      },
      {
        eyebrow: "과제와 회복 전환",
        title: "많이 달리는 것만큼 일을 마친 뒤 스스로 쉬는 전환도 중요해요.",
        description: "몸과 머리를 함께 쓰는 과제에 깊이 몰입한 뒤에도 다음 일을 기다리며 쉽게 긴장을 풀지 못하는 개체가 있어요. 냄새 찾기와 방향 구분처럼 목적 있는 활동을 제공하되, 끝 신호 뒤 매트에서 호흡을 낮추는 시간까지 한 흐름으로 구성해주세요.",
        image: "/illustrations/v4/australian-shepherd-feature-work-to-rest.webp",
        alt: "방향 과제를 마친 뒤 현대 가정의 현관 매트에서 쉬고 보호자가 낮은 표식을 정리하는 긴 꼬리의 블루멀 성견 오스트레일리안 셰퍼드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/342g01-en.pdf", "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/australian-shepherd/"],
      },
    ],
  },
]);

const breedFeaturesBySlug = new Map(breedFeatureSets.map((featureSet) => [featureSet.slug, featureSet]));

export function getBreedFeatures(slug: string) {
  return breedFeaturesBySlug.get(slug);
}
