import { breedFeatureCollectionSchema } from "./schema";

export const breedFeatureSets = breedFeatureCollectionSchema.parse([
  {
    slug: "japanese-spitz",
    intro: "사람과의 관계, 주변 변화에 대한 반응, 매일 체감할 털 관리 부담을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "사람 곁에서 함께 움직이길 좋아해요.",
        description: "사람을 좋아하고 보호자와 산책하거나 놀이하는 시간을 즐기는 영리하고 쾌활한 반려견이에요. 다만 사람과 가까워지는 속도와 애정을 표현하는 방식은 강아지마다 달라요.",
        image: "/illustrations/v4/japanese-spitz-feature-companionship.webp",
        alt: "사람 곁을 따라 걸으며 얼굴을 바라보는 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/"],
      },
      {
        eyebrow: "짖음과 알림",
        title: "작은 변화에도 먼저 반응할 수 있어요.",
        description: "현관 소리나 창밖 움직임에 반응해 짖을 수 있어요. 짖음이 길어지지 않도록 소리가 들린 뒤 조용히 기다리는 연습을 어릴 때부터 해두면 좋아요.",
        image: "/illustrations/v4/japanese-spitz-feature-calm-alert.webp",
        alt: "닫힌 문밖의 작은 소리를 조용히 알아차린 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/", "https://www.ukcdogs.com/breed-groups/japanese-spitz"],
      },
      {
        eyebrow: "털 관리 부담",
        title: "풍성한 이중모는 꾸준한 빗질이 필요해요.",
        description: "짧고 촘촘한 속털과 풍성한 겉털을 함께 가진 견종이에요. 특히 털갈이 시기에는 빠진 속털이 엉키지 않도록 규칙적인 빗질을 생활에 포함해야 해요.",
        image: "/illustrations/v4/japanese-spitz-feature-double-coat.webp",
        alt: "빠진 속털을 브러시로 빗어 관리하는 재패니즈 스피츠 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/japanese-spitz/", "https://www.ukcdogs.com/breed-groups/japanese-spitz"],
      },
    ],
  },
  {
    slug: "maltese",
    intro: "사람과 가까이 지내는 방식, 작은 체구의 생활 안전, 긴 피모 관리 부담을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "사람 가까이에서 시간을 보내길 좋아해요.",
        description: "가족과 가까이 머물며 함께 시간을 보내는 것을 좋아하는 모습을 보일 수 있어요. 함께하는 시간뿐 아니라 짧고 편안한 혼자 쉬기도 천천히 익혀주세요.",
        image: "/illustrations/v4/maltese-feature-companionship.webp",
        alt: "앉아 있는 사람 가까이에서 얼굴을 바라보는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/maltese/", "https://www.akc.org/expert-advice/dog-breeds/maltese-right-for-you/"],
      },
      {
        eyebrow: "작은 체구와 안전",
        title: "작은 몸에 맞는 생활 동선이 필요해요.",
        description: "높은 가구에서 뛰어내리거나 거친 상호작용은 작은 몸에 부담이 될 수 있어요. 발이 닿는 바닥과 오르내리는 높이, 아이와 만나는 방식을 차분히 살펴주세요.",
        image: "/illustrations/v4/maltese-feature-small-body-safety.webp",
        alt: "낮은 반려견 계단 옆에서 사람의 안내를 받는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/expert-advice/dog-breeds/maltese-right-for-you/"],
      },
      {
        eyebrow: "피모 관리 부담",
        title: "긴 실키 코트는 매일 엉킴을 살펴야 해요.",
        description: "길고 곧은 흰 피모를 유지하려면 피부 가까이까지 부드럽게 빗고 엉킨 곳을 확인하는 시간이 필요해요. 빗질과 목욕, 피모 관리를 편안한 일상으로 익혀주세요.",
        image: "/illustrations/v4/maltese-feature-coat-care.webp",
        alt: "긴 흰 피모를 금속 빗으로 차분히 관리받는 성견 말티즈 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/maltese/"],
      },
    ],
  },
  {
    slug: "border-collie",
    intro: "움직임을 읽는 몰이 행동, 빠른 학습에 맞는 과제, 활동 뒤 차분히 쉬는 리듬을 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "몰이와 움직임",
        title: "움직이는 대상을 먼저 읽고 따라갈 수 있어요.",
        description: "양 떼의 방향을 읽고 모으도록 발달한 목양견이에요. 달리는 사람이나 놀이하는 아이처럼 빠르게 움직이는 대상에 시선이 고정되거나 따라가려는 모습이 보이면 거리를 두고 보호자에게 돌아오는 신호를 연습해주세요.",
        image: "/illustrations/v4/border-collie-feature-herding-focus.webp",
        alt: "공원에서 멀리 지나가는 사람과 자전거를 알아차린 뒤 보호자를 바라보는 성견 보더콜리 삽화",
        sourceUrls: ["https://images.akc.org/pdf/breeds/standards/Border_Collie.pdf", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
      {
        eyebrow: "배움과 과제",
        title: "빠르게 배우는 만큼 생각할 일이 필요해요.",
        description: "신호를 익히고 문제를 해결하는 활동에 적극적으로 참여할 수 있어요. 같은 공 던지기만 오래 반복하기보다 냄새 찾기, 짧은 협력 훈련, 규칙이 있는 놀이를 번갈아 제공해주세요.",
        image: "/illustrations/v4/border-collie-feature-thinking-tasks.webp",
        alt: "사람의 손 신호를 바라보며 냄새 상자와 훈련 도구 사이에서 과제를 기다리는 성견 보더콜리 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/border-collie/", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
      {
        eyebrow: "활동과 휴식",
        title: "많이 움직인 뒤 쉬는 법도 함께 배워야 해요.",
        description: "활동량이 높은 편이지만 자극을 계속 늘리는 것만으로 생활이 편안해지지는 않아요. 산책과 과제 뒤에는 소리와 움직임이 적은 자리에서 흥분을 낮추고 쉬는 시간을 일상에 넣어주세요.",
        image: "/illustrations/v4/border-collie-feature-calm-rest.webp",
        alt: "산책 도구와 장난감이 정리된 방에서 매트 위에 편안히 쉬는 성견 보더콜리 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/border-collie/", "https://www.akc.org/expert-advice/dog-breeds/border-collie-right-for-you/"],
      },
    ],
  },
  {
    slug: "greyhound",
    intro: "움직임을 보는 시선, 짧게 속도를 내고 쉬는 리듬, 얇은 피모에 맞는 보온 준비를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "시각과 추적",
        title: "멀리 움직이는 대상을 먼저 발견할 수 있어요.",
        description: "눈으로 움직임을 찾고 빠르게 쫓도록 발달한 시각 하운드예요. 산책 중 작은 동물이나 빠르게 지나가는 대상에 주의가 쏠릴 수 있으니, 안전한 리드를 사용하고 실제 반응을 살펴주세요.",
        image: "/illustrations/v4/greyhound-feature-visual-tracking.webp",
        alt: "현대 공원에서 멀리 지나가는 자전거를 알아차리고 보호자 곁에 서 있는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/assets/000/004/111/training_tips_original.pdf?1581612710="],
      },
      {
        eyebrow: "질주와 휴식",
        title: "빠르게 달리는 능력과 하루 종일 바쁜 생활은 달라요.",
        description: "짧게 속도를 내는 순간과 편안히 쉬는 시간이 함께 필요한 견종이에요. 안전하게 달릴 수 있는 통제된 기회와 냄새 맡는 산책을 마련하고, 활동 뒤에는 조용히 회복할 자리를 준비해주세요.",
        image: "/illustrations/v4/greyhound-feature-sprint-rest.webp",
        alt: "안전하게 울타리가 설치된 공원 운동장에서 짧게 달리는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/home-a-greyhound/all-about-greyhounds"],
      },
      {
        eyebrow: "얇은 피모와 온도",
        title: "짧은 털은 추운 날 더 세심한 준비가 필요해요.",
        description: "피모가 짧고 몸에 지방이 적은 편이라 추운 날씨와 차가운 바닥을 불편해할 수 있어요. 기온과 개별 반응에 맞춰 보온 의류를 사용하고, 몸을 받쳐주는 따뜻한 휴식 자리를 마련해주세요.",
        image: "/illustrations/v4/greyhound-feature-cold-weather.webp",
        alt: "쌀쌀한 늦가을 공원에서 몸에 맞는 보온 코트를 입고 산책하는 성견 그레이하운드 삽화",
        sourceUrls: ["https://www.greyhoundtrust.org.uk/about-us/news/3908-quick-tips-to-keep-your-greyhound-healthy-in-winter"],
      },
    ],
  },
  {
    slug: "yakutian-laika",
    intro: "사람과 함께 움직이는 방식, 몸과 판단을 쓰는 활동, 풍성한 이중모의 계절 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 협력",
        title: "사람 가까이에서 함께 움직이려 해요.",
        description: "사람과 가까이 지내고 함께 역할을 수행하는 데 적극적으로 참여할 수 있어요. 산책과 짧은 신호 놀이를 함께하며 보호자에게 시선을 돌리고 차분히 기다리는 경험도 만들어주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-cooperation.webp",
        alt: "현대 공원에서 벤치에 앉은 보호자의 손 신호를 바라보는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/365g05-en.pdf", "https://www.akc.org/dog-breeds/yakutian-laika/"],
      },
      {
        eyebrow: "활동과 과제",
        title: "움직임과 생각할 일을 함께 채워야 해요.",
        description: "활동량과 에너지가 높은 편이라 걷기만 길게 반복하기보다 냄새 찾기, 방향 신호, 안전한 하네스 운동처럼 몸과 판단을 함께 쓰는 과제를 번갈아 제공해주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-purposeful-activity.webp",
        alt: "숲길에서 몸에 맞는 하네스를 착용하고 보호자와 함께 달리는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/yakutian-laika/", "https://www.akc.org/expert-advice/dog-breeds/yakutian-laika-breed-history/"],
      },
      {
        eyebrow: "이중모와 계절",
        title: "풍성한 이중모는 털갈이와 더위 준비가 필요해요.",
        description: "굵은 겉털과 촘촘한 속털이 추운 환경을 견디도록 발달한 견종이에요. 피부 가까이까지 규칙적으로 빗고, 더운 계절에는 선선한 시간대의 활동과 편안한 실내 온도를 마련해주세요.",
        image: "/illustrations/v4/yakutian-laika-feature-double-coat.webp",
        alt: "선선한 실내에서 풍성한 이중모를 브러시로 관리받는 성견 야쿠티안 라이카 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/365g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/yakutian-laika-breed-history/"],
      },
    ],
  },
  {
    slug: "samoyed",
    intro: "사람과 일상을 나누는 방식, 힘과 지구력을 쓰는 활동, 두꺼운 이중모의 계절 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 동행",
        title: "일상에 함께 참여하는 것을 좋아할 수 있어요.",
        description: "사람 가까이 머물며 가족의 활동에 참여하려는 모습을 보일 수 있어요. 함께 걷고 놀아주는 시간뿐 아니라, 가까운 자리에서 편안히 쉬고 짧게 혼자 머무는 경험도 천천히 알려주세요.",
        image: "/illustrations/v4/samoyed-feature-companionship.webp",
        alt: "현대 가정에서 외출을 준비하는 가족 가까이에 편안히 누워 있는 성견 사모예드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/212g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/samoyed-right-for-you/"],
      },
      {
        eyebrow: "활동과 과제",
        title: "힘과 지구력을 쓸 목적 있는 활동이 필요해요.",
        description: "힘과 활동성이 높은 작업견이라 걷기만 길게 반복하기보다 냄새 찾기, 방향 신호, 안전한 하네스 운동처럼 몸과 판단을 함께 쓰는 과제를 번갈아 제공해주세요.",
        image: "/illustrations/v4/samoyed-feature-purposeful-activity.webp",
        alt: "선선한 숲길에서 몸에 맞는 당김 하네스를 착용하고 보호자와 함께 달리는 성견 사모예드 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/samoyed/", "https://www.akc.org/expert-advice/dog-breeds/samoyed-history/"],
      },
      {
        eyebrow: "이중모와 계절",
        title: "두꺼운 이중모는 자주 빗고 계절을 조절해야 해요.",
        description: "부드럽고 촘촘한 속털 위에 더 길고 거친 겉털이 자라는 견종이에요. 평소에도 피부 가까이까지 빗고, 털갈이 시기에는 관리 횟수를 늘리며 더운 날에는 선선한 생활 환경을 마련해주세요.",
        image: "/illustrations/v4/samoyed-feature-double-coat.webp",
        alt: "선선한 실내의 미끄럽지 않은 매트에서 풍성한 이중모를 빗질받는 성견 사모예드 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/212g05-en.pdf", "https://www.akc.org/expert-advice/dog-breeds/samoyed-right-for-you/"],
      },
    ],
  },
  {
    slug: "chihuahua",
    intro: "아주 작은 몸에 맞는 생활 안전, 소리에 반응하는 방식, 피모와 기온에 따른 보온 준비를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "작은 몸과 안전",
        title: "낮은 높이와 보이는 동선부터 준비해요.",
        description: "아주 작은 성견은 소파에서 뛰어내리거나 사람 발과 스치는 일도 큰 부담이 될 수 있어요. 미끄럽지 않은 바닥과 낮은 발판을 마련하고, 문을 오갈 때 발밑을 확인해주세요.",
        image: "/illustrations/v4/chihuahua-feature-small-body-safety.webp",
        alt: "미끄럽지 않은 러그와 낮은 발판이 놓인 거실에서 보호자가 발밑을 살피는 동안 걷는 성견 치와와 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/chihuahua/"],
      },
      {
        eyebrow: "소리와 알림",
        title: "작은 소리에도 빠르게 주의를 돌릴 수 있어요.",
        description: "현관이나 복도의 낯선 소리를 먼저 알아차리고 알리려는 모습이 나타날 수 있어요. 소리를 확인한 뒤 보호자에게 돌아와 매트에서 기다리는 짧은 순서를 차분히 알려주세요.",
        image: "/illustrations/v4/chihuahua-feature-alert-response.webp",
        alt: "닫힌 현관문 소리를 알아차린 뒤 보호자의 손짓을 따라 매트로 돌아오는 성견 치와와 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/chihuahua/"],
      },
      {
        eyebrow: "피모와 보온",
        title: "단모와 장모에 맞춰 추운 날을 준비해요.",
        description: "치와와에는 매끄러운 단모와 부드러운 장모가 있어 관리 방식이 달라요. 피모 길이만 믿기보다 기온과 떨림, 움직임을 살피고 따뜻한 휴식 자리나 몸에 맞는 가벼운 옷을 준비해주세요.",
        image: "/illustrations/v4/chihuahua-feature-coat-warmth.webp",
        alt: "서늘한 날 창가의 담요와 가벼운 옷 가까이에서 쉬는 단모와 장모 성견 치와와 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/218g09-en.pdf", "https://www.akc.org/dog-breeds/chihuahua/"],
      },
    ],
  },
  {
    slug: "shih-tzu",
    intro: "사람 가까이에서 쉬는 방식, 짧은 얼굴에 맞는 더운 날의 리듬, 긴 피모와 얼굴 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "사람과의 관계",
        title: "가까운 자리에서 일상을 나누길 좋아할 수 있어요.",
        description: "가족이 머무는 공간을 따라가거나 같은 방의 편안한 자리를 고르는 모습이 보일 수 있어요. 늘 안고 있기보다 스스로 가까이 오고 물러날 수 있는 자리도 함께 마련해주세요.",
        image: "/illustrations/v4/shih-tzu-feature-companionship.webp",
        alt: "책을 읽는 보호자 곁의 별도 매트에 편안히 엎드린 흰색과 금색의 성견 시추 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/shih-tzu/", "https://www.akc.org/expert-advice/dog-breeds/shih-tzu-history/"],
      },
      {
        eyebrow: "짧은 얼굴과 더위",
        title: "더운 날에는 짧고 선선한 움직임이 필요해요.",
        description: "짧고 넓은 주둥이를 가진 시추는 더운 시간의 긴 활동보다 선선한 시간대와 그늘진 길이 편안할 수 있어요. 물과 휴식을 준비하고 걷는 속도는 그날의 반응에 맞춰주세요.",
        image: "/illustrations/v4/shih-tzu-feature-heat-care.webp",
        alt: "여름 아침 그늘진 산책길에서 보호자가 건넨 물그릇 앞에 편안히 서 있는 성견 시추 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/208g09-en.pdf", "https://www.akc.org/dog-breeds/shih-tzu/"],
      },
      {
        eyebrow: "피모와 얼굴 관리",
        title: "눈을 가리지 않도록 매일 짧게 살펴요.",
        description: "길고 촘촘한 피모는 엉킴을 풀어주는 빗질이 필요하고, 얼굴 털은 눈과 코 주변을 가리지 않게 관리해야 해요. 빗과 부드러운 천을 한 번에 오래 쓰기보다 짧게 익혀주세요.",
        image: "/illustrations/v4/shih-tzu-feature-coat-face-care.webp",
        alt: "미끄럽지 않은 매트에서 보호자가 성견 시추의 털을 빗고 눈가를 부드러운 천으로 닦는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/208g09-en.pdf", "https://www.akc.org/dog-breeds/shih-tzu/"],
      },
    ],
  },
  {
    slug: "poodle",
    intro: "네 가지 크기의 생활 차이, 물건을 찾고 가져오는 과제, 계속 자라는 곱슬 피모의 관리를 먼저 살펴보세요.",
    cards: [
      {
        eyebrow: "네 가지 크기",
        title: "같은 푸들이어도 생활의 규모는 크게 달라요.",
        description: "푸들은 스탠더드·미디엄·미니어처·토이 네 크기로 나뉘어요. 어린 강아지의 현재 크기만 보지 말고 부모견과 예상 성견 크기를 확인해 이동 공간과 활동 계획을 세워주세요.",
        image: "/illustrations/v4/poodle-feature-four-sizes.webp",
        alt: "같은 바닥에 성견 스탠더드·미디엄·미니어처·토이 푸들이 큰 순서대로 서 있는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/172g09-en.pdf"],
      },
      {
        eyebrow: "회수와 배움",
        title: "찾고 가져오는 짧은 과제에 집중할 수 있어요.",
        description: "물에서 대상을 회수하던 배경이 있는 만큼 물건을 찾아 가져오거나 새로운 신호를 배우는 활동에 적극적으로 참여할 수 있어요. 성공하기 쉬운 짧은 과제와 조용한 휴식을 번갈아 주세요.",
        image: "/illustrations/v4/poodle-feature-learning-retrieval.webp",
        alt: "공원에서 회수용 더미를 물고 보호자의 손으로 돌아오는 살구색 성견 미니어처 푸들 삽화",
        sourceUrls: ["https://www.akc.org/dog-breeds/poodle-standard/", "https://www.akc.org/expert-advice/dog-breeds/poodle-history/"],
      },
      {
        eyebrow: "곱슬 피모 관리",
        title: "빗질과 미용을 정기 일정으로 잡아야 해요.",
        description: "촘촘한 곱슬 피모는 계속 자라며 빠진 털이 안쪽에 머물러 엉킬 수 있어요. 피부 가까이까지 나누어 빗고, 원하는 길이에 맞춰 전문 미용과 도구 적응 시간을 계획해주세요.",
        image: "/illustrations/v4/poodle-feature-coat-care.webp",
        alt: "낮은 미끄럼 방지 미용대에서 보호자가 살구색 성견 미니어처 푸들의 곱슬 피모를 빗는 삽화",
        sourceUrls: ["https://www.fci.be/Nomenclature/Standards/172g09-en.pdf", "https://www.akc.org/dog-breeds/poodle-standard/"],
      },
    ],
  },
]);

const breedFeaturesBySlug = new Map(breedFeatureSets.map((featureSet) => [featureSet.slug, featureSet]));

export function getBreedFeatures(slug: string) {
  return breedFeaturesBySlug.get(slug);
}
