import { standardBreedDetailSchema } from "./schema";

type Step = [string, string, string, string, string];
type Reality = [string, string, string, string];
type SizeDetails = { summaryRows: { label: string; value: string }[]; detailsLabel: string; items: { id: string; label: string; value: string }[] };
type Seed = { slug: string; nameKo: string; metadataDescription: string; heroStatement: string; size: SizeDetails; storyTitle: string; storyDescription: string; steps: [Step, Step, Step]; caution: string; realitiesTitle: string; realities: [Reality, Reality]; readiness: [string, string, string]; relatedTitle: string; relatedDescription: string; related: Record<string, string> };

const seeds: Seed[] = [
  {
    slug: "polish-tatra-sheepdog", nameKo: "폴리시 타트라 셰퍼드",
    metadataDescription: "타트라 산맥 포드할레의 양 떼를 지킨 폴리시 타트라 셰퍼드의 흰 이중모, 경계 역할과 생활 동선을 살펴봅니다.",
    heroStatement: "15세기 포드할레에 정착한 목축민의 개에서 이어져 양을 모는 일보다 곰과 늑대로부터 무리를 지키는 일을 주로 맡은, 크고 흰 폴란드 산악견이에요.",
    size: { summaryRows: [{ label: "체고", value: "성별로 다름" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 65~70cm" }, { id: "female", label: "암컷", value: "체고 60~65cm" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] },
    storyTitle: "흰 산악견은 왜 양을 모는 일보다 무리 곁을 지키는 일에 더 오래 쓰였을까요?", storyDescription: "가축 보호 역할을 넓은 경계 확인과 실내에서 관찰을 멈추는 순서로 바꿔봐요.",
    steps: [["과거의 역할", "타트라 산맥의 양과 가축 곁에서 곰과 늑대를 구분하며 무리를 지켰어요.", "포드할레 목축민이 흰 개를 이어온 이유 중 하나는 어두운 포식자와 쉽게 구분하기 위해서였어요. 20세기 전쟁 뒤에는 자코파네의 작업견을 중심으로 다시 정리됐어요.", "history", "타트라 산지의 양 떼 바깥을 살피는 폴리시 타트라 셰퍼드 역사 삽화"], ["오늘의 활동", "울타리 안 세 경계 표식을 보호자와 천천히 확인하고 마지막에서 돌아와요.", "표식마다 오래 머물지 않고 한 번 냄새를 맡으면 다음으로 이동하세요. 마지막 뒤에는 같은 문으로 실내에 들어가요.", "tatra-boundary-three", "울타리 안 세 경계 표식을 걷는 폴리시 타트라 셰퍼드 삽화"], ["함께 살 때", "바깥문이 닫히면 창문에서 떨어진 큰 침대에 옆으로 누워요.", "계속 밖을 살피지 않도록 낮은 가림막을 두고 방문객 통로와 휴식 자리를 나누세요.", "boundary-to-white-bed", "창문에서 떨어진 큰 침대에 쉬는 폴리시 타트라 셰퍼드 삽화"]],
    caution: "가축 보호 역사가 모든 개체의 판단이나 낯선 대상 반응을 같게 만들지 않아요. 실제 반응을 보고 울타리와 소개 거리를 정해야 해요.", realitiesTitle: "큰 흰 몸과 풍성한 이중모는 출입구·여름 그늘·털갈이에서 무엇을 바꿀까요?",
    realities: [["white-guardian-gate", "큰 몸이 문 앞으로 바로 나가지 않도록 넓은 이중 출입 구역을 둬요.", "첫 문을 닫고 위치를 확인한 뒤 다음 문을 여세요. 여름에는 대기 구역에도 그늘과 물을 준비해요.", "넓은 이중 출입 구역에서 기다리는 폴리시 타트라 셰퍼드 삽화"], ["tatra-white-doublecoat", "목 갈기와 허벅지·꼬리의 긴 흰 털은 속털부터 구역을 나눠 말려요.", "겉의 얼룩보다 피부 가까운 뭉침과 발가락 사이 털을 먼저 확인하세요.", "흰 이중모를 구역별로 관리받는 폴리시 타트라 셰퍼드 삽화"]],
    readiness: ["높고 넓은 울타리와 이중 출입 구역을 준비할 수 있나요?", "바깥 관찰을 끝내고 실내에서 쉬는 순서를 만들 수 있나요?", "풍성한 흰 이중모를 피부부터 관리할 수 있나요?"], relatedTitle: "흰 산악 보호견도 형성 지역과 체형 기준이 달라요.", relatedDescription: "털색보다 지역, 무리 보호 방식과 생활 공간을 비교해보세요.", related: { "slovakian-cuvac": "슬로바키안 쿠바츠는 인접한 산악권에서 가축을 지킨 흰 보호견이에요.", "maremma-sheepdog": "마렘마 앤 아브루초 셰퍼드는 이탈리아의 계절 이동 목축을 따른 흰 보호견이에요." },
  },
  {
    slug: "romanian-mioritic-shepherd-dog", nameKo: "루마니안 미오리틱 셰퍼드", metadataDescription: "카르파티아의 자연 집단에서 작업 능력으로 선발된 루마니안 미오리틱 셰퍼드의 큰 체구, 긴 거친 털과 경계 생활을 살펴봅니다.", heroStatement: "카르파티아 산맥의 자연 집단에서 곰·늑대·스라소니로부터 가축을 지키는 쓰임을 중심으로 선발된, 머리와 다리까지 긴 거친 털이 덮는 큰 루마니아 셰퍼드예요.",
    size: { summaryRows: [{ label: "체고", value: "최소·이상 기준" }, { label: "몸무게", value: "체격에 비례" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "최소 70cm · 이상적 75cm" }, { id: "female", label: "암컷", value: "최소 65cm · 이상적 70cm" }, { id: "weight", label: "몸무게", value: "체격에 비례 · 고정 수치 없음" }] },
    storyTitle: "온몸의 긴 털을 지닌 큰 셰퍼드는 왜 카르파티아 무리 곁에서 포식자를 막았을까요?", storyDescription: "무리 보호 역할을 먼 자극 확인과 넓은 실내 휴식으로 풀어봐요.", steps: [["과거의 역할", "카르파티아 목초지에서 가축 곁을 지키며 큰 포식자에 맞섰어요.", "외형보다 실제 쓰임을 중심으로 자연 집단에서 선발됐고 1981년에 루마니아 표준이 처음 작성됐어요.", "history", "카르파티아 목초지의 무리 바깥을 지키는 미오리틱 셰퍼드 역사 삽화"], ["오늘의 활동", "넓은 울타리 안 먼 세 지점을 천천히 보고 보호자 곁으로 돌아와요.", "달려가 확인하게 하지 말고 긴 줄을 느슨하게 유지하세요. 마지막 지점 뒤에는 물을 마시고 실내로 이동해요.", "carpathian-distant-check", "먼 세 지점을 차례로 확인하는 루마니안 미오리틱 셰퍼드 삽화"], ["함께 살 때", "관찰이 끝나면 몸 전체를 받치는 큰 매트에서 출입구를 등지고 쉬어요.", "현관과 창문이 동시에 보이지 않는 자리를 고르고 다음 소리에 바로 일어나지 않게 기다려요.", "distant-check-to-mat", "출입구를 등진 큰 매트에서 쉬는 루마니안 미오리틱 셰퍼드 삽화"]], caution: "포식자와 맞선 역사가 모든 개체의 용기나 낯선 동물 반응을 보장하지 않아요. 실제 회복 속도에 맞춰 거리를 관리해야 해요.", realitiesTitle: "큰 몸과 10cm 이상 긴 거친 털은 문·바닥·젖은 날 관리에서 무엇을 요구할까요?", realities: [["mioritic-wide-turn", "현관과 차량에는 큰 몸이 제자리에서 꺾이지 않을 넓은 회전 공간을 둬요.", "좁은 문 앞 물건을 치우고 미끄럼 방지 러그를 길게 이어주세요.", "넓은 현관 회전 구역을 걷는 루마니안 미오리틱 셰퍼드 삽화"], ["mioritic-long-coat-dry", "머리·몸·다리의 긴 거친 털과 부드러운 속털은 젖은 뒤 층을 나눠 말려요.", "귀 아래·겨드랑이·배와 발을 먼저 나누고 피부 가까운 습기를 확인하세요.", "긴 거친 털을 구역별로 말리는 루마니안 미오리틱 셰퍼드 삽화"]], readiness: ["큰 몸이 도는 넓은 통로와 높은 울타리를 마련할 수 있나요?", "먼 자극 확인 뒤 실내 휴식으로 이어갈 수 있나요?", "온몸의 긴 털과 속털을 젖은 날 말릴 수 있나요?"], relatedTitle: "루마니아 산악 보호견도 털 길이와 체형이 달라요.", relatedDescription: "미오리틱의 긴 털과 카르파티안의 중간 길이 늑대회색 털을 비교해보세요.", related: { "romanian-carpathian-shepherd-dog": "루마니안 카르파티안 셰퍼드는 더 짧은 늑대회색 이중모와 민첩한 체형을 지녀요.", "maremma-sheepdog": "마렘마 앤 아브루초 셰퍼드는 이탈리아 목축 이동을 따른 흰 장모 보호견이에요." },
  },
  {
    slug: "romanian-carpathian-shepherd-dog", nameKo: "루마니안 카르파티안 셰퍼드", metadataDescription: "카르파티아·다뉴브 지역에서 가축을 지킨 루마니안 카르파티안 셰퍼드의 늑대회색 이중모, 민첩한 체형과 경계 동선을 살펴봅니다.", heroStatement: "카르파티아·다뉴브 지역의 토착 집단에서 수백 년 동안 가축과 목자를 지키는 쓰임을 중심으로 유지된, 늑대회색의 민첩하고 큰 루마니아 보호견이에요.",
    size: { summaryRows: [{ label: "체고", value: "성별 이상 범위" }, { label: "몸무게", value: "체격에 비례" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "이상적 65~73cm · ±2cm" }, { id: "female", label: "암컷", value: "이상적 59~67cm · ±2cm" }, { id: "weight", label: "몸무게", value: "체격에 비례 · 고정 수치 없음" }] },
    storyTitle: "늑대회색 산악견은 어떻게 큰 몸을 유지하면서도 무리 둘레를 민첩하게 살폈을까요?", storyDescription: "자연스러운 경계 역할을 넓은 곡선 이동과 실내 종료로 바꿔봐요.", steps: [["과거의 역할", "카르파티아 산지에서 양 떼와 목자를 지키며 무리 둘레를 움직였어요.", "1934년 첫 표준이 작성되기 전부터 실제 쓰임이 선발의 중심이었고 큰 몸이지만 무겁지 않은 형태가 유지됐어요.", "history", "카르파티아 산길의 양 떼 둘레를 살피는 카르파티안 셰퍼드 역사 삽화"], ["오늘의 활동", "울타리 안 넓은 반원을 따라 세 표식을 확인하고 출발점으로 돌아와요.", "좁은 회전과 급정지를 피하고 같은 속도의 트로트로 움직이세요.", "wolfgrey-semicircle", "넓은 반원 표식을 걷는 루마니안 카르파티안 셰퍼드 삽화"], ["함께 살 때", "표식이 수납되면 낮은 가림막 뒤 긴 침대에서 옆으로 누워요.", "바깥 시야와 방문객 통로를 동시에 보지 않는 자리에 침대를 고정하세요.", "semicircle-to-screened-bed", "낮은 가림막 뒤 침대에서 쉬는 루마니안 카르파티안 셰퍼드 삽화"]], caution: "자연 보호견이라는 설명이 모든 개체의 판단이나 가족 애착을 보장하지 않아요. 울타리와 소개 거리는 실제 반응으로 정해야 해요.", realitiesTitle: "민첩한 큰 몸과 늑대회색 이중모는 울타리·바닥·계절 털갈이에서 무엇을 바꿀까요?", realities: [["carpathian-corner-clearance", "문과 울타리 모서리에는 큰 몸이 곡선으로 도는 빈 공간을 남겨요.", "문 앞 수납물을 치우고 긴 미끄럼 방지 러그를 이어주세요.", "넓은 모서리 통로를 도는 루마니안 카르파티안 셰퍼드 삽화"], ["wolfgrey-doublecoat", "거친 중간 길이 겉털과 부드러운 속털은 목·다리 뒤·꼬리를 나눠 관리해요.", "늑대회색의 농담보다 속털 뭉침과 젖은 피부를 먼저 확인하세요.", "늑대회색 이중모를 구역별로 관리받는 루마니안 카르파티안 셰퍼드 삽화"]], readiness: ["높은 울타리와 넓은 회전 동선을 준비할 수 있나요?", "바깥 확인 뒤 가림막 뒤에서 쉬게 할 수 있나요?", "계절마다 늑대회색 이중모를 관리할 수 있나요?"], relatedTitle: "카르파티아 보호견도 털 길이와 몸의 무게감이 달라요.", relatedDescription: "지역 이름보다 체형과 피모, 실제 생활 공간을 비교해보세요.", related: { "romanian-mioritic-shepherd-dog": "미오리틱은 머리와 다리까지 훨씬 긴 거친 털이 덮는 더 풍성한 보호견이에요.", sarplaninac: "샤르플라니나츠는 샤르 산맥에서 가축을 지킨 더 짧고 단단해 보이는 장모 보호견이에요." },
  },
  {
    slug: "broholmer", nameKo: "브로홀머", metadataDescription: "중세 사슴 사냥에서 덴마크 대농장과 영지 경비로 역할이 바뀐 브로홀머의 큰 체구, 짧은 털과 실내 동선을 살펴봅니다.", heroStatement: "중세에는 사슴 사냥에 쓰이고 이후 덴마크의 큰 농장과 영지를 지키다가 거의 사라진 뒤 1970년대에 복원된, 묵직한 머리와 짧은 털의 대형 마스티프예요.", size: { summaryRows: [{ label: "체고", value: "성별 약 기준" }, { label: "몸무게", value: "성별 범위" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "약 75cm · 50~70kg" }, { id: "female", label: "암컷", value: "약 70cm · 40~60kg" }] }, storyTitle: "사슴 사냥견은 어떻게 덴마크 영지의 차분한 경비견이 됐을까요?", storyDescription: "역할의 변화를 낮은 냄새 선택과 큰 몸의 조용한 휴식으로 연결해봐요.", steps: [["과거의 역할", "중세 사슴 사냥 뒤 큰 농장과 영지의 경비를 맡았어요.", "18세기 브로홀름 영지의 세헤스테드가 타입을 정리했고 전후 거의 사라진 개체군은 1975년부터 덴마크 켄넬 클럽과 함께 복원됐어요.", "history", "덴마크 영지 입구를 지키는 브로홀머 역사 삽화"], ["오늘의 활동", "낮은 세 상자 중 영지 냄새 천이 든 하나를 찾고 매트로 돌아와요.", "상자는 뒤집히지 않게 고정하고 한 번 찾은 뒤 더 밀지 않도록 바로 수납하세요.", "estate-scent-crates", "낮은 세 냄새 상자 중 하나를 찾는 브로홀머 삽화"], ["함께 살 때", "상자가 치워지면 넓은 통로 밖의 단단한 큰 침대에서 쉬어요.", "머리와 몸 전체를 받치고 사람이 지나갈 공간을 남기는 자리를 고르세요.", "crates-to-heavy-bed", "큰 침대에서 쉬는 브로홀머 삽화"]], caution: "차분한 경비견이라는 표준 설명이 모든 개체의 방문객 반응을 보장하지 않아요. 큰 힘과 실제 회복 속도를 함께 봐야 해요.", realitiesTitle: "70cm 안팎의 큰 몸과 짧은 속털은 현관·차량·계절 관리에서 무엇을 요구할까요?", realities: [["broholmer-wide-ramp", "차량과 높은 턱에는 큰 몸이 곧게 걷는 넓고 완만한 발판을 고정해요.", "발판 옆 틈을 막고 차 안에서 몸을 돌릴 높이와 폭을 확보하세요.", "넓은 차량 발판을 걷는 브로홀머 삽화"], ["short-coat-loose-skin", "짧은 털과 목의 느슨한 피부는 접히는 부분을 눌러 말리고 계절 속털을 빗어요.", "턱 아래와 목이 젖으면 부드러운 천으로 닦고 완전히 마른 뒤 고무 브러시를 사용하세요.", "짧은 털과 목 피부를 관리받는 브로홀머 삽화"]], readiness: ["큰 몸이 도는 현관과 차량 공간을 준비할 수 있나요?", "방문객이 올 때 별도 대기 자리를 운영할 수 있나요?", "짧은 털과 느슨한 목 피부를 관리할 수 있나요?"], relatedTitle: "대형 마스티프도 역할과 몸의 비율이 달라요.", relatedDescription: "키보다 역사적 역할, 머리와 피부, 이동 공간을 비교해보세요.", related: { mastiff: "마스티프는 영국의 더 무겁고 넓은 대형 마스티프 계통이에요.", "great-dane": "그레이트 데인은 더 높고 길게 뻗은 체형의 독일계 대형견이에요." },
  },
  {
    slug: "fila-brasileiro", nameKo: "필라 브라질레이로", metadataDescription: "브라질 영지 경비와 가축 관리에 쓰인 필라 브라질레이로의 큰 힘, 느슨한 피부와 독특한 보행을 살펴봅니다.", heroStatement: "브라질의 넓은 영지를 지키고 가축을 다루며 큰 사냥감도 추적한, 온몸의 느슨한 피부와 낙타처럼 같은 쪽 다리를 함께 옮기는 보행이 특징인 대형 경비견이에요.", size: { summaryRows: [{ label: "체고", value: "성별로 다름" }, { label: "몸무게", value: "성별 최소 기준" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "65~75cm · 50kg 이상" }, { id: "female", label: "암컷", value: "60~70cm · 40kg 이상" }] }, storyTitle: "느슨한 피부의 큰 개는 왜 브라질 영지에서 경비와 가축 관리를 함께 맡았을까요?", storyDescription: "강한 경계 역할을 넓은 통로와 확실한 이중 출입 관리로 바꿔봐요.", steps: [["과거의 역할", "브라질 영지를 지키고 가축을 몰며 큰 사냥감도 추적했어요.", "표준은 오늘의 주된 쓰임을 경비로 적고 있으며 큰 체구와 방향 전환 능력, 느슨한 피부가 고유 외형으로 남았어요.", "history", "브라질 농장 영지의 가축 통로를 지키는 필라 브라질레이로 역사 삽화"], ["오늘의 활동", "넓은 직선 통로의 두 표식을 천천히 걷고 보호자 옆에서 멈춰요.", "좁은 회전이나 흥분하는 추적 대신 같은 속도로 걷는 짧은 순서를 사용하세요.", "brazil-wide-pace", "넓은 직선 표식을 걷는 필라 브라질레이로 삽화"], ["함께 살 때", "통로 확인 뒤 출입문 두 개가 닫힌 안쪽 침대에서 쉬어요.", "방문객과 마주치는 길을 분리하고 문 하나를 닫기 전에는 다음 문을 열지 마세요.", "pace-to-inner-bed", "닫힌 이중문 안쪽 침대에서 쉬는 필라 브라질레이로 삽화"]], caution: "영지 경비 역사가 낯선 사람에 대한 반응을 정당화하거나 예측해주지 않아요. 안전한 관리와 실제 반응 확인이 먼저예요.", realitiesTitle: "큰 힘과 느슨한 피부는 이중문·하네스·건조 관리에서 무엇을 바꿀까요?", realities: [["fila-locked-vestibule", "두 문이 동시에 열리지 않는 넓고 잠금 가능한 대기 구역을 만들어요.", "하네스를 연결하고 개의 위치를 확인한 뒤 한 문씩 여세요.", "두 문이 닫힌 넓은 대기 구역의 필라 브라질레이로 삽화"], ["fila-skin-fold-dry", "목과 가슴의 느슨한 피부는 젖은 뒤 접히는 부분을 펼쳐 말려요.", "문지르지 말고 부드러운 천으로 눌러 닦으며 피부 상태를 눈으로 확인하세요.", "목과 가슴의 느슨한 피부를 말리는 필라 브라질레이로 삽화"]], readiness: ["잠금 가능한 이중 출입 구역을 일관되게 운영할 수 있나요?", "큰 힘을 감당할 넓은 통로와 장비를 준비할 수 있나요?", "느슨한 피부와 짧은 털을 매일 확인할 수 있나요?"], relatedTitle: "영지 경비에 쓰인 마스티프형도 체형과 관리가 달라요.", relatedDescription: "보호 역할보다 피부, 움직임과 출입 안전을 비교해보세요.", related: { boerboel: "보어보엘은 남아프리카 농장 경비에 쓰인 더 정사각형에 가까운 대형견이에요.", "cane-corso": "카네 코르소는 이탈리아 농장과 재산 경비에 쓰인 더 팽팽한 피부의 몰로서예요." },
  },
  {
    slug: "hovawart", nameKo: "호바바르트", metadataDescription: "이름부터 농장·영지의 수호자를 뜻하는 호바바르트의 복원 역사, 후각 작업과 긴 털 관리를 살펴봅니다.", heroStatement: "중세 고지독일어로 농장과 영지의 수호자를 뜻하는 이름을 지녔고 1922년부터 농가의 유사 타입과 여러 작업견을 바탕으로 복원된, 긴 털의 독일 작업견이에요.", size: { summaryRows: [{ label: "체고", value: "성별로 다름" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 63~70cm" }, { id: "female", label: "암컷", value: "체고 58~65cm" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] }, storyTitle: "‘영지의 수호자’라는 오래된 이름은 어떻게 현대의 다목적 작업견으로 이어졌을까요?", storyDescription: "경비와 좋은 후각을 짧은 흔적 찾기와 조용한 종료로 연결해봐요.", steps: [["형성 배경", "농장과 영지의 수호자를 뜻하는 오래된 이름의 작업견을 20세기에 복원했어요.", "농가에 남은 유사 타입과 저먼 셰퍼드·뉴펀들랜드·레온베르거 등을 활용해 1922년부터 견종을 다시 만들었어요.", "history", "독일 농가 영지 입구를 살피는 호바바르트 역사 삽화"], ["오늘의 활동", "짧은 잔디 길에 놓인 세 냄새 조각을 차례로 찾아 마지막 상자를 알려요.", "코를 쓰되 달리지 않도록 조각 사이를 넓게 두고 정답 뒤에는 상자를 닫아 수납하세요.", "estate-track-cloths", "짧은 잔디 길의 냄새 조각을 찾는 호바바르트 삽화"], ["함께 살 때", "냄새 도구가 치워지면 가족 통로 옆 긴 침대에서 쉬어요.", "현관을 직접 지키지 않으면서 가족과 떨어지지 않는 자리를 고르세요.", "track-to-family-bed", "가족 통로 옆 긴 침대에서 쉬는 호바바르트 삽화"]], caution: "다목적 작업견이라는 설명이 모든 개체의 경비·수색 능력을 보장하지 않아요. 실제 집중 시간과 자극 회복을 봐야 해요.", realitiesTitle: "큰 몸과 긴 털은 차량·바닥·풀씨 관리에서 무엇을 요구할까요?", realities: [["hovawart-vehicle-turn", "차량에는 긴 몸이 곧게 오르고 안에서 방향을 바꿀 공간을 확보해요.", "넓은 발판을 고정하고 적재 공간의 높이와 미끄럼을 먼저 확인하세요.", "넓은 차량 발판을 오르는 호바바르트 삽화"], ["hovawart-feather-check", "가슴·배·다리 뒤·꼬리의 긴 털은 산책 뒤 풀씨와 엉킴을 나눠 확인해요.", "털 끝부터 풀고 젖은 속털이 남지 않게 구역별로 말리세요.", "긴 장식털의 풀씨를 확인받는 호바바르트 삽화"]], readiness: ["냄새 찾기와 휴식을 짧은 순서로 제공할 수 있나요?", "큰 몸의 차량 이동과 미끄럼 없는 바닥을 준비할 수 있나요?", "긴 털의 풀씨와 젖은 속털을 관리할 수 있나요?"], relatedTitle: "독일계 큰 작업견도 피모와 역할 구성이 달라요.", relatedDescription: "경비라는 말보다 후각 활용, 털 길이와 가족 동선을 비교해보세요.", related: { leonberger: "레온베르거는 호바바르트 복원에 쓰인 더 크고 풍성한 독일 대형견이에요.", "german-shepherd-dog": "저먼 셰퍼드 독은 복원에 영향을 준 더 각진 체형의 목양·작업견이에요." },
  },
  {
    slug: "landseer", nameKo: "랜드시어", metadataDescription: "검은 뉴펀들랜드보다 다리가 길고 흰 바탕에 검은 패치가 선명한 랜드시어의 경비·동반 역할, 큰 몸과 장모 관리를 살펴봅니다.", heroStatement: "검은 뉴펀들랜드보다 다리가 길고 흰 바탕에 검은 머리와 몸 패치가 뚜렷한 모습으로 독일·스위스에서 별도 표준이 된, 크고 균형 잡힌 경비·동반견이에요.", size: { summaryRows: [{ label: "체고", value: "성별로 다름" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 72~80cm" }, { id: "female", label: "암컷", value: "체고 67~72cm" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] }, storyTitle: "흰 바탕의 큰 개는 왜 뉴펀들랜드와 닮았어도 유럽 대륙에서 별도 견종이 됐을까요?", storyDescription: "긴 다리와 큰 몸을 낮은 물 찾기와 충분한 건조·휴식으로 연결해봐요.", steps: [["형성 배경", "유럽 대륙에서 검은 뉴펀들랜드보다 다리가 긴 흰색·검은색 타입을 별도로 유지했어요.", "FCI 표준은 독일·스위스 기원의 경비·동반견으로 분류하고 뚜렷한 흰 바탕과 검은 패치를 요구해요.", "history", "유럽 호숫가 영지의 사람 곁에 선 랜드시어 역사 삽화"], ["오늘의 활동", "얕은 물통 두 개 중 냄새 뜨개가 든 쪽을 찾고 마른 매트로 돌아와요.", "물통은 발을 담그지 않을 깊이로 두고 찾은 뒤 더 휘젓지 않게 바로 치우세요.", "landseer-water-bowls", "얕은 두 물통 중 냄새 뜨개를 찾는 랜드시어 삽화"], ["함께 살 때", "물통이 치워지면 몸 전체가 펴지는 마른 큰 침대에서 쉬어요.", "물놀이 구역과 실내 휴식 자리를 분리하고 젖은 발로 미끄러지지 않게 러그를 이어주세요.", "water-to-dry-bed", "마른 큰 침대에서 쉬는 랜드시어 삽화"]], caution: "물가에 잘 어울리는 외형이 모든 개체의 수영 능력이나 물 선호를 보장하지 않아요. 얕은 환경에서 선택을 먼저 봐야 해요.", realitiesTitle: "긴 다리의 큰 몸과 흰 장모는 물기·차량·바닥 관리에서 무엇을 바꿀까요?", realities: [["landseer-wide-ramp", "차량에는 긴 다리와 큰 몸이 비틀지 않을 넓고 완만한 발판을 고정해요.", "차량 안 머리 높이와 몸을 돌릴 폭을 확보하고 젖은 발판은 바로 말리세요.", "넓은 차량 발판을 걷는 랜드시어 삽화"], ["landseer-patch-coat-dry", "흰 장모와 검은 패치의 털은 목·가슴·배·꼬리를 나눠 속까지 말려요.", "흰색의 얼룩보다 피부 가까운 습기와 발가락 사이 털을 먼저 확인하세요.", "흰색과 검은색 장모를 구역별로 말리는 랜드시어 삽화"]], readiness: ["큰 몸과 긴 다리가 움직일 넓은 실내·차량 공간이 있나요?", "물 활동 뒤 미끄럼을 막고 충분히 쉬게 할 수 있나요?", "긴 털을 속까지 말리고 빗을 수 있나요?"], relatedTitle: "뉴펀들랜드 계열처럼 보여도 다리 비율과 표준이 달라요.", relatedDescription: "털색만이 아니라 체형과 생활 공간, 젖은 털 관리를 비교해보세요.", related: { newfoundland: "뉴펀들랜드는 더 낮고 묵직한 체형과 여러 모색을 지닌 별도 견종이에요.", leonberger: "레온베르거는 사자빛 긴 털과 검은 마스크를 지닌 더 육중한 대형견이에요." },
  },
  {
    slug: "pyrenean-mastiff", nameKo: "피레니안 마스티프", metadataDescription: "스페인 피레네에서 늑대와 곰으로부터 가축을 지킨 피레니안 마스티프의 초대형 체구, 흰 바탕 패치 장모와 출입 안전을 살펴봅니다.", heroStatement: "스페인 피레네에서 늑대와 곰으로부터 가축을 지켰고 오늘은 농촌 영지 경비를 맡는, 흰 바탕에 뚜렷한 마스크와 패치를 지닌 매우 큰 산악 마스티프예요.", size: { summaryRows: [{ label: "체고", value: "최소·권장 기준" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "최소 77cm · 권장 81cm 초과" }, { id: "female", label: "암컷", value: "최소 72cm · 권장 75cm 초과" }, { id: "weight", label: "몸무게", value: "상한·고정 수치 없음" }] }, storyTitle: "매우 큰 흰 마스티프는 왜 피레네 가축 무리에서 포식자와 맞섰을까요?", storyDescription: "산악 보호 역할을 느린 경계 걷기와 넓은 대기·휴식 공간으로 바꿔봐요.", steps: [["과거의 역할", "피레네 산지의 가축을 늑대와 곰에게서 지켰어요.", "매우 큰 몸이지만 둔해 보이지 않는 힘과 민첩성을 요구받았고 오늘은 농촌 영지와 사람을 지키는 역할로 설명돼요.", "history", "피레네 산지 가축 무리의 바깥을 지키는 피레니안 마스티프 역사 삽화"], ["오늘의 활동", "넓은 울타리 안 두 경계 지점을 느리게 확인하고 큰 매트로 돌아와요.", "달리기보다 고른 걸음으로 이동하고 지점마다 보호자 쪽으로 몸을 돌리면 다음으로 가세요.", "pyrenean-two-boundaries", "넓은 두 경계 지점을 확인하는 피레니안 마스티프 삽화"], ["함께 살 때", "확인이 끝나면 문과 창문에서 떨어진 초대형 침대에 옆으로 누워요.", "통로를 막지 않으면서 다리와 꼬리까지 받치는 자리를 벽 쪽에 두세요.", "boundaries-to-giant-bed", "초대형 침대에서 쉬는 피레니안 마스티프 삽화"]], caution: "포식자와 맞선 역사가 모든 개체의 대담함이나 다른 동물 반응을 정하지 않아요. 물리적 관리와 실제 반응 확인이 먼저예요.", realitiesTitle: "상한이 없는 큰 체고와 두꺼운 장모는 문·차량·여름 관리에서 무엇을 요구할까요?", realities: [["mastiff-extra-wide-gate", "두 문 사이에 초대형 몸이 완전히 들어가는 넓은 잠금 대기 구역을 둬요.", "몸과 꼬리가 문틈을 벗어난 것을 확인한 뒤 한 문씩 여세요.", "초대형 이중문 대기 구역의 피레니안 마스티프 삽화"], ["mask-patch-longcoat", "흰 바탕의 중간 길이 거친 털은 목·배·다리 뒤·꼬리를 나눠 빗고 말려요.", "패치 색보다 두꺼운 털 아래 피부와 여름의 열·습기를 먼저 확인하세요.", "흰 패치 장모를 구역별로 관리받는 피레니안 마스티프 삽화"]], readiness: ["초대형 몸이 도는 문·차량·실내 공간이 있나요?", "잠금 가능한 넓은 이중 출입 구역을 만들 수 있나요?", "두꺼운 장모와 여름 열 관리를 이어갈 수 있나요?"], relatedTitle: "피레네의 흰 대형견도 마스티프형과 보호견형이 달라요.", relatedDescription: "이름보다 마스크·패치, 체고 기준과 공간 부담을 비교해보세요.", related: { "pyrenean-mountain-dog": "그레이트 피레니즈는 프랑스 피레네의 흰 가축 보호견으로 다른 체형 표준을 지녀요.", "spanish-mastiff": "스패니시 마스티프는 스페인 이동 목축에서 무리를 지킨 별도 초대형 마스티프예요." },
  },
  {
    slug: "sarplaninac", nameKo: "샤르플라니나츠", metadataDescription: "샤르 산맥에서 가축을 포식자로부터 지킨 샤르플라니나츠의 평균 체고, 긴 거친 털과 산악 생활 동선을 살펴봅니다.", heroStatement: "샤르 산맥을 중심으로 오래도록 소와 양을 포식자에게서 지키며 원래 타입을 유지한, 짙은 등에서 다리 쪽으로 옅어지는 단색 장모의 발칸 산악 보호견이에요.", size: { summaryRows: [{ label: "체고", value: "평균·최소 기준" }, { label: "몸무게", value: "성별 범위" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "평균 62cm · 최소 56cm · 35~45kg" }, { id: "female", label: "암컷", value: "평균 58cm · 최소 54cm · 30~40kg" }] }, storyTitle: "샤르 산맥의 보호견은 어떻게 가축 무리 곁에서 오래된 타입을 유지했을까요?", storyDescription: "산악 경계를 넓은 경사 걷기와 실내 휴식, 긴 털 관리로 바꿔봐요.", steps: [["과거의 역할", "샤르 산맥의 가축 무리를 포식자로부터 지켰어요.", "강한 목축이 이어진 산악 지역에서 원래 역할과 타입이 유지됐고 1939년 FCI에 등록됐어요.", "history", "샤르 산맥 목초지의 가축 무리를 지키는 샤르플라니나츠 역사 삽화"], ["오늘의 활동", "낮은 완경사 길의 세 표식을 천천히 오르고 같은 길로 내려와요.", "가파른 계단과 급한 회전을 피하고 발이 미끄러지지 않는 넓은 길을 사용하세요.", "shar-gentle-slope", "완만한 경사 표식을 걷는 샤르플라니나츠 삽화"], ["함께 살 때", "경사 걷기 뒤 문에서 떨어진 단단한 침대에 몸을 내려놓아요.", "바깥 소리를 계속 확인하지 않도록 가림막과 일정한 실내 종료 시간을 사용하세요.", "slope-to-solid-bed", "문에서 떨어진 침대에서 쉬는 샤르플라니나츠 삽화"]], caution: "오래된 보호 역할이 모든 개체의 신뢰성이나 경계 강도를 보장하지 않아요. 실제 반응과 생활 환경을 함께 봐야 해요.", realitiesTitle: "단단한 몸과 긴 거친 털은 경사·발·계절 관리에서 무엇을 바꿀까요?", realities: [["sarplaninac-slope-traction", "경사와 현관에는 큰 발이 미끄러지지 않는 넓은 러그를 이어주세요.", "회전 지점의 폭을 넓히고 젖은 발로 계단을 오르지 않게 해요.", "넓은 미끄럼 방지 경사로를 걷는 샤르플라니나츠 삽화"], ["shar-long-coarse-coat", "목 갈기와 다리 뒤·꼬리의 긴 거친 털은 속털부터 나눠 관리해요.", "색의 농담보다 피부 가까운 뭉침과 젖은 발 사이 털을 먼저 확인하세요.", "긴 거친 산악 털을 관리받는 샤르플라니나츠 삽화"]], readiness: ["높은 울타리와 넓은 경사 동선을 준비할 수 있나요?", "바깥 경계 뒤 정해진 실내 자리에서 쉬게 할 수 있나요?", "긴 거친 털과 속털을 계절마다 관리할 수 있나요?"], relatedTitle: "발칸과 동유럽 보호견도 체형과 피모가 달라요.", relatedDescription: "지역, 평균 체고와 긴 털의 생활 부담을 비교해보세요.", related: { "caucasian-shepherd-dog": "코카시안 셰퍼드는 더 크고 무거운 체형 범위의 코카서스 보호견이에요.", kuvasz: "쿠바스는 흰 물결 이중모를 지닌 헝가리 가축 보호견이에요." },
  },
  {
    slug: "tosa", nameKo: "도사", metadataDescription: "시코쿠견과 서양 대형견을 교배해 일본 도사 지역에서 형성된 도사의 역사, 큰 힘과 짧은 털의 생활 관리를 살펴봅니다.", heroStatement: "14세기부터 이어진 일본 투견 문화 속에서 시코쿠견에 불독·마스티프·포인터·그레이트 데인 등을 차례로 더해 도사 지역에서 형성된, 짧은 털의 크고 단단한 일본 마스티프예요.", size: { summaryRows: [{ label: "체고", value: "성별 최소 기준" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 60cm 이상" }, { id: "female", label: "암컷", value: "체고 55cm 이상" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] }, storyTitle: "도사 지역의 큰 개는 어떻게 일본견과 여러 서양 대형견의 특징을 함께 갖게 됐을까요?", storyDescription: "형성 역사를 오늘의 짧은 힘 조절 과제와 분명한 휴식·출입 관리로 바꿔봐요.", steps: [["형성 배경", "시코쿠견에 여러 서양 대형견을 순차적으로 교배해 도사 지역에서 만들었어요.", "불독·마스티프·저먼 포인터·그레이트 데인이 기록돼 있고 오늘의 FCI 표준은 주된 쓰임을 경비로 설명해요.", "history", "일본 도사 지역의 전통 마당에 선 성견 도사 역사 삽화"], ["오늘의 활동", "넓은 러그 위 낮은 무게 상자를 짧게 밀고 보호자 옆 매트로 이동해요.", "상자는 몸보다 훨씬 가볍게 하고 한 번 움직이면 바로 멈춰 보상하세요.", "tosa-light-push", "낮은 가벼운 상자를 한 번 미는 성견 도사 삽화"], ["함께 살 때", "상자가 수납되면 방문객 통로와 분리된 단단한 침대에서 쉬어요.", "문이 열리기 전 잠금 구역으로 이동하고 직접 마주치는 동선을 만들지 마세요.", "push-to-secure-bed", "분리된 단단한 침대에서 쉬는 성견 도사 삽화"]], caution: "역사적 용도는 오늘의 개체 행동을 단정하거나 대립 상황을 허용하는 근거가 아니에요. 예방적인 물리 관리와 실제 반응 확인이 필요해요.", realitiesTitle: "큰 힘과 짧은 털·목 피부는 출입구·장비·건조 관리에서 무엇을 요구할까요?", realities: [["tosa-locked-double-door", "방문객과 마주치지 않도록 잠금 가능한 두 문 사이에 넓은 대기 구역을 둬요.", "하네스를 연결하고 몸과 꼬리가 문에서 벗어난 뒤 한 문씩 여세요.", "두 문이 닫힌 넓은 대기 구역의 성견 도사 삽화"], ["tosa-shortcoat-neck", "짧고 단단한 털과 목의 느슨한 피부는 젖은 뒤 접히는 곳을 눌러 말려요.", "턱 아래와 가슴의 습기를 확인하고 불편해하면 손질을 짧게 나누세요.", "짧은 털과 목 피부를 관리받는 성견 도사 삽화"]], readiness: ["잠금 가능한 이중 출입 구역을 매번 운영할 수 있나요?", "큰 힘을 감당할 장비와 넓은 동선을 준비할 수 있나요?", "짧은 털과 목 피부를 편안하게 관리할 수 있나요?"], relatedTitle: "대형 마스티프형도 형성 역사와 체형이 달라요.", relatedDescription: "과거의 명칭보다 오늘 필요한 출입 안전과 힘 관리를 비교해보세요.", related: { mastiff: "마스티프는 도사 형성에 영향을 준 더 무겁고 넓은 영국계 대형견이에요.", "cane-corso": "카네 코르소는 이탈리아의 농장·경비 역할을 지닌 더 각진 몰로서예요." },
  },
];

const appendAndParticle = (name: string) => { const last = name.charCodeAt(name.length - 1); return `${name}${last >= 0xac00 && last <= 0xd7a3 && (last - 0xac00) % 28 !== 0 ? "과" : "와"}`; };

export const expansionTo300Batch03StandardBreedDetails = seeds.map((seed) => standardBreedDetailSchema.parse({
  slug: seed.slug, reviewStatus: "production-draft", nameKo: seed.nameKo, metadataDescription: seed.metadataDescription, heroStatement: seed.heroStatement, heroSizeDetails: seed.size,
  story: { title: seed.storyTitle, description: seed.storyDescription, steps: seed.steps.map(([navLabel, title, body, imageId, imageAlt], index) => ({ navLabel, eyebrow: `${index + 1}단계 · ${index === 0 ? "무엇을 하던 개였을까?" : index === 1 ? "그 흔적은 지금 어떻게 나타날까?" : "보호자는 무엇을 체감할까?"}`, title, body, image: `/illustrations/${imageId === "history" ? "v3" : "v4"}/${seed.slug}-${imageId === "history" ? "history" : `feature-${imageId}`}.webp`, imageAlt })), caution: seed.caution },
  realitiesTitle: seed.realitiesTitle, realities: seed.realities.map(([id, title, body, imageAlt]) => ({ id, title, body, image: `/illustrations/v4/${seed.slug}-feature-${id}.webp`, imageAlt })), readinessTitle: `${appendAndParticle(seed.nameKo)} 살기 전 확인할 세 가지`, readinessQuestions: seed.readiness, relatedTitle: seed.relatedTitle, relatedDescription: seed.relatedDescription, relatedDifferences: seed.related,
}));
