import { standardBreedDetailSchema } from "./schema";

type Step = [string, string, string, string, string];
type Reality = [string, string, string, string];
type SizeDetails = { summaryRows: { label: string; value: string }[]; detailsLabel: string; items: { id: string; label: string; value: string }[] };
type Seed = { slug: string; nameKo: string; metadataDescription: string; heroStatement: string; size: SizeDetails; storyTitle: string; storyDescription: string; steps: [Step, Step, Step]; caution: string; realitiesTitle: string; realities: [Reality, Reality]; readiness: [string, string, string]; relatedTitle: string; relatedDescription: string; related: Record<string, string> };

const seeds: Seed[] = [
  {
    slug: "tornjak", nameKo: "토르냐크", metadataDescription: "중세 기록에서 현대 복원까지 이어진 토르냐크의 가축 보호 역할, 흰 바탕의 긴 털과 넓은 생활 동선을 살펴봅니다.", heroStatement: "1067년과 1374년 기록에 등장한 보스니아·크로아티아 산악 목양견의 후손을 1970년대부터 되살린, 흰 바탕에 선명한 패치와 풍성한 꼬리를 지닌 큰 보호견이에요.",
    size: { summaryRows: [{ label: "체고", value: "성별·허용 오차 기준" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "65~70cm · 허용 ±2cm" }, { id: "female", label: "암컷", value: "60~65cm · 허용 ±2cm" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] },
    storyTitle: "한때 거의 사라졌던 산악 보호견은 어떻게 오래된 기록을 따라 다시 이어졌을까요?", storyDescription: "가축과 농장을 지키던 역할을 넓은 트로트와 실내 휴식으로 연결해봐요.",
    steps: [["과거의 역할", "산악 목초지의 가축을 지키고 농장 마당을 경계했어요.", "중세 기록에 남은 토착 목양견 후손을 조사해 1972년부터 보존을 시작했고 1978년 순종 번식이 이어졌어요.", "history", "보스니아와 크로아티아 산악 목초지의 가축 곁을 지키는 토르냐크 역사 삽화"], ["오늘의 활동", "넓은 타원 길의 색이 다른 세 표식을 고른 속도로 돌아요.", "긴 보폭의 트로트를 살리되 급회전하지 않고 마지막 표식 뒤 같은 출입구로 돌아오세요.", "mountain-oval-trot", "넓은 타원 표식을 트로트로 걷는 토르냐크 삽화"], ["함께 살 때", "표식이 치워지면 현관에서 떨어진 큰 침대에 몸을 길게 펴요.", "바깥문과 창을 동시에 보지 않는 자리를 고르고 통로에는 꼬리가 놓일 폭을 남겨주세요.", "trot-to-plumed-bed", "현관에서 떨어진 큰 침대에 쉬는 토르냐크 삽화"]],
    caution: "가축 보호 역사가 모든 개체의 경계 강도나 판단을 정하지 않아요. 낯선 대상과의 거리는 실제 반응을 보고 조절해야 해요.", realitiesTitle: "큰 몸과 긴 패치 이중모는 출입구·바닥·젖은 날 관리에서 무엇을 바꿀까요?", realities: [["tornjak-wide-gate", "풍성한 꼬리까지 문 안으로 들어오는 넓은 이중 출입 구역을 둬요.", "첫 문을 닫고 몸과 꼬리의 위치를 확인한 뒤 다음 문을 여세요.", "넓고 닫힌 이중 출입 구역에서 기다리는 토르냐크 삽화"], ["tornjak-parti-coat", "목 갈기·허벅지·꼬리의 긴 털과 겨울 속털은 층을 나눠 말려요.", "패치 색보다 피부 가까운 습기와 털 뭉침을 먼저 확인하세요.", "흰 바탕 패치 장모를 구역별로 관리받는 토르냐크 삽화"]],
    readiness: ["큰 몸과 꼬리가 도는 넓은 실내·출입 공간이 있나요?", "바깥 확인 뒤 정해진 자리에서 쉬게 할 수 있나요?", "긴 이중모를 젖은 날 속까지 말릴 수 있나요?"], relatedTitle: "발칸 산악 보호견도 체형과 털색이 달라요.", relatedDescription: "같은 지역 이름보다 몸의 비율과 피모, 출입 공간을 비교해보세요.", related: { sarplaninac: "샤르플라니나츠는 단색에 가까운 짙은 산악 털을 지닌 보호견이에요.", "croatian-sheepdog": "크로아티안 셰퍼드는 더 작고 검은 곱슬 털로 가축을 모으는 목양견이에요." },
  },
  {
    slug: "central-asian-shepherd-dog", nameKo: "센트럴 아시안 셰퍼드", metadataDescription: "중앙아시아에서 가축·카라반 행렬·거처를 지킨 센트럴 아시안 셰퍼드의 큰 힘, 두 피모 길이와 출입 안전을 살펴봅니다.", heroStatement: "카스피해에서 중국·우랄 남부·아프가니스탄까지 이어지는 넓은 지역에서 자연 선택을 거치며 가축과 카라반 행렬, 거처를 지킨 크고 단단한 산악 보호견이에요.",
    size: { summaryRows: [{ label: "체고", value: "성별 최소 기준" }, { label: "몸무게", value: "성별 최소 기준" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "70cm 이상 · 50kg 이상" }, { id: "female", label: "암컷", value: "65cm 이상 · 40kg 이상" }] },
    storyTitle: "넓은 중앙아시아를 오간 개는 왜 가축뿐 아니라 카라반과 사람의 거처도 함께 지켰을까요?", storyDescription: "오래 이동하며 경계를 지킨 역할을 짧은 둘레 확인과 확실한 출입 관리로 바꿔봐요.",
    steps: [["과거의 역할", "가축 무리와 카라반 행렬, 사람의 거처를 포식자와 침입에서 지켰어요.", "혹독한 기후와 넓은 이동 범위에서 힘을 아끼며 판단하는 개들이 이어졌고 1930년대 소련에서 체계적인 견종 작업이 시작됐어요.", "history", "중앙아시아 카라반 행렬과 가축 무리 곁을 지키는 센트럴 아시안 셰퍼드 역사 삽화"], ["오늘의 활동", "넓은 울타리의 세 모서리를 천천히 확인하고 가운데 물그릇으로 돌아와요.", "모서리마다 오래 서지 않게 한 번 확인하면 다음으로 움직이고 전체 순서를 짧게 끝내세요.", "three-corners-water", "넓은 세 모서리를 확인하고 물그릇으로 돌아오는 센트럴 아시안 셰퍼드 삽화"], ["함께 살 때", "확인이 끝나면 바깥 시야가 가려진 단단한 큰 침대에서 쉬어요.", "방문객 통로와 휴식 공간을 문으로 분리하고 계속 현관을 지키는 배치를 피하세요.", "corners-to-screened-bed", "바깥 시야가 가려진 큰 침대에서 쉬는 센트럴 아시안 셰퍼드 삽화"]],
    caution: "넓은 지역에서 살아남은 역사가 모든 개체의 독립성이나 대담함을 보장하지 않아요. 큰 힘과 실제 회복 속도를 함께 봐야 해요.", realitiesTitle: "최소 65cm가 넘는 몸과 두 피모 길이는 문·장비·털 관리에서 무엇을 요구할까요?", realities: [["central-asian-locked-court", "두 문이 동시에 열리지 않는 넓고 잠금 가능한 대기 구역을 만들어요.", "하네스를 연결하고 개의 위치를 확인한 뒤 한 문씩 여세요.", "두 문이 닫힌 넓은 대기 구역의 센트럴 아시안 셰퍼드 삽화"], ["central-asian-two-coats", "3~5cm형과 7~10cm형 모두 거친 겉털 아래 속털을 나눠 확인해요.", "목 갈기와 귀 뒤·다리 뒤·꼬리의 털 길이에 맞춰 빗질 구역을 조정하세요.", "서로 다른 털 길이의 관리 부위를 보여주는 센트럴 아시안 셰퍼드 삽화"]],
    readiness: ["잠금 가능한 넓은 이중 출입 공간을 운영할 수 있나요?", "큰 힘을 감당할 장비와 미끄럼 없는 바닥이 있나요?", "피모 길이에 맞춘 속털 관리를 이어갈 수 있나요?"], relatedTitle: "중앙아시아 보호견은 이름보다 지역과 몸의 규모를 봐야 해요.", relatedDescription: "생활 공간과 출입 안전, 털 길이의 차이를 비교해보세요.", related: { "caucasian-shepherd-dog": "코카시안 셰퍼드는 코카서스의 더 풍성하고 무거운 산악 보호견이에요.", "mongolian-bankhar": "몽골리안 방카르는 몽골 유목 환경에서 가축을 지켜온 랜드레이스예요." },
  },
  {
    slug: "spanish-mastiff", nameKo: "스패니시 마스티프", metadataDescription: "스페인 이동 목축에서 늑대로부터 양 떼를 지킨 스패니시 마스티프의 초대형 체구, 느슨한 피부와 생활 공간을 살펴봅니다.", heroStatement: "계절마다 먼 길을 이동하던 메리노 양 떼와 함께 걸으며 늑대 같은 포식자로부터 무리를 지킨, 체고 상한이 없고 깊은 목소리와 느슨한 피부를 지닌 초대형 마스티프예요.",
    size: { summaryRows: [{ label: "체고", value: "최소·권장 기준" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "최소 77cm · 권장 80cm 초과" }, { id: "female", label: "암컷", value: "최소 72cm · 권장 75cm 초과" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] },
    storyTitle: "초대형 마스티프는 어떻게 계절마다 이동하는 양 떼의 속도를 따라 포식자를 막았을까요?", storyDescription: "이동 목축의 넓은 보행을 오늘의 긴 직선 걷기와 큰 휴식 공간으로 바꿔봐요.",
    steps: [["과거의 역할", "스페인의 계절 이동 목축에서 양 떼를 늑대와 포식자로부터 지켰어요.", "양과 함께 먼 길을 옮기며 무리 바깥을 살폈고 오늘은 농촌의 재산과 사람을 지키는 역할도 이어져요.", "history", "스페인 이동 목축로의 메리노 양 떼 곁을 걷는 스패니시 마스티프 역사 삽화"], ["오늘의 활동", "넓고 평평한 직선 길의 두 표식을 느린 걸음으로 왕복해요.", "급회전 대신 끝에서 큰 곡선으로 방향을 바꾸고 짧은 왕복 뒤 물을 마시게 하세요.", "transhumance-straight-walk", "넓은 직선 표식 길을 걷는 스패니시 마스티프 삽화"], ["함께 살 때", "걷기가 끝나면 통로 밖 초대형 침대에 몸과 꼬리를 모두 내려놔요.", "사람이 넘지 않아도 되는 벽 쪽 자리를 고르고 일어날 때 미끄러지지 않게 러그를 이어주세요.", "walk-to-giant-wall-bed", "벽 쪽 초대형 침대에서 쉬는 스패니시 마스티프 삽화"]],
    caution: "포식자를 막던 역사가 모든 개체의 보호 행동이나 낯선 동물 반응을 같게 만들지 않아요. 물리적 관리가 먼저예요.", realitiesTitle: "상한이 없는 큰 체고와 두꺼운 피부는 문·바닥·목 주변 관리에서 무엇을 바꿀까요?", realities: [["spanish-mastiff-extra-wide-door", "몸과 꼬리가 모두 들어가는 초대형 이중 출입 구역을 확보해요.", "두 문을 동시에 열지 말고 문턱에는 넓은 미끄럼 방지 면을 붙이세요.", "초대형 이중 출입 구역에서 기다리는 스패니시 마스티프 삽화"], ["spanish-mastiff-neck-dry", "목과 가슴의 느슨한 피부와 중간 길이 털은 젖은 뒤 접힌 곳을 눌러 말려요.", "턱 아래와 목 주름의 습기를 확인하고 부드러운 천으로 나눠 닦으세요.", "목과 가슴 피부를 건조하는 스패니시 마스티프 삽화"]],
    readiness: ["초대형 몸이 도는 문·실내·차량 공간이 있나요?", "넓은 이중 출입 구역을 매번 운영할 수 있나요?", "목 피부와 중간 길이 털을 젖은 날 관리할 수 있나요?"], relatedTitle: "스페인 산악 마스티프도 이동 역할과 모색이 달라요.", relatedDescription: "체고만 보지 말고 과거 이동 방식과 오늘 필요한 공간을 비교해보세요.", related: { "pyrenean-mastiff": "피레니안 마스티프는 흰 바탕의 마스크와 패치가 뚜렷한 스페인 피레네 보호견이에요.", mastiff: "마스티프는 영국에서 형성된 더 넓고 무거운 체형의 마스티프예요." },
  },
  {
    slug: "australian-terrier", nameKo: "오스트레일리안 테리어", metadataDescription: "거친 호주 개척지에서 일과 동반을 함께한 오스트레일리안 테리어의 작은 체구, 목 갈기와 탐색 생활을 살펴봅니다.", heroStatement: "영국계 테리어 여러 종을 바탕으로 태즈메이니아와 호주 남동부의 거친 환경에서 일손·경계·동반을 함께 맡도록 만든, 목 갈기와 부드러운 정수리 털이 선명한 작은 작업 테리어예요.",
    size: { summaryRows: [{ label: "체고", value: "수컷 약 25cm" }, { label: "몸무게", value: "수컷 약 6.5kg" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 약 25cm · 약 6.5kg" }, { id: "female", label: "암컷", value: "수컷 기준보다 조금 작음" }] },
    storyTitle: "작은 테리어는 왜 거친 호주 개척지에서 일손과 경계, 동반을 함께 맡았을까요?", storyDescription: "작지만 단단한 탐색성을 낮은 돌길 냄새 찾기와 실내 정리로 연결해봐요.",
    steps: [["형성 배경", "호주 남동부 개척지에서 작은 작업견이자 경계견, 동반견으로 자리 잡았어요.", "스카이·스코티시·댄디 딘몬트 계통과 요크셔 테리어의 영향이 기록돼 있으며 호주에서 처음 발전한 견종 중 하나예요.", "history", "호주 개척지 농가의 돌담과 창고 주변을 살피는 오스트레일리안 테리어 역사 삽화"], ["오늘의 활동", "낮은 돌 세 개 사이에 숨긴 작은 냄새 통 하나를 찾아요.", "돌은 움직이지 않게 고정하고 정답을 찾으면 더 파고들기 전에 통을 치우세요.", "low-rock-scent-tube", "낮은 돌 사이 냄새 통을 찾는 오스트레일리안 테리어 삽화"], ["함께 살 때", "냄새 통이 서랍에 들어가면 낮은 쿠션에서 앞발을 내려놓고 쉬어요.", "현관을 직접 마주 보지 않는 자리에 쿠션을 두고 활동 도구는 눈앞에서 수납하세요.", "tube-to-low-cushion", "낮은 쿠션에서 쉬는 오스트레일리안 테리어 삽화"]],
    caution: "작은 작업 테리어라는 배경이 모든 개체의 추적 강도나 짖음을 정하지 않아요. 실제 반응과 회복을 확인해야 해요.", realitiesTitle: "낮고 단단한 몸과 6cm 거친 털은 문틈·목 갈기·바닥에서 무엇을 바꿀까요?", realities: [["australian-terrier-gap-screen", "낮은 문틈과 울타리 아래는 머리가 들어가지 않는 촘촘한 가림판으로 막아요.", "가림판의 모서리와 들뜬 부분을 주기적으로 손으로 확인하세요.", "낮은 울타리 틈이 가림판으로 막힌 공간의 오스트레일리안 테리어 삽화"], ["australian-ruff-topknot", "목 갈기와 부드러운 정수리 털은 거친 몸털과 나눠 빗어요.", "얼굴 앞을 가리지 않게 털 방향을 정리하고 속털 뭉침을 먼저 확인하세요.", "목 갈기와 정수리 털을 관리받는 오스트레일리안 테리어 삽화"]],
    readiness: ["낮은 문틈과 울타리 아래를 촘촘히 막을 수 있나요?", "짧은 찾기 뒤 도구를 치우고 쉬게 할 수 있나요?", "거친 몸털과 목 갈기를 나눠 관리할 수 있나요?"], relatedTitle: "호주 소형 테리어도 털의 질감과 역할이 달라요.", relatedDescription: "실키한 털보다 거친 작업 피모와 낮은 생활 경계를 비교해보세요.", related: { "australian-silky-terrier": "오스트레일리안 실키 테리어는 더 가볍고 길게 흐르는 실키 코트를 지닌 토이 테리어예요.", "cairn-terrier": "케언 테리어는 스코틀랜드 돌무더기에서 작은 사냥감을 찾던 거친 털의 소형 테리어예요." },
  },
  {
    slug: "irish-terrier", nameKo: "아이리시 테리어", metadataDescription: "아일랜드 농장 다목적견과 전쟁 전령견으로 쓰인 아이리시 테리어의 붉은 거친 털, 긴 다리와 생활 리듬을 살펴봅니다.", heroStatement: "아일랜드 농장에서 경계·사냥·건독 역할을 두루 맡고 제1차 세계대전에는 포화 속 전령견으로 쓰인, 긴 다리와 붉은 거친 털이 특징인 중형 테리어예요.",
    size: { summaryRows: [{ label: "체고", value: "약 45.5cm" }, { label: "몸무게", value: "성별로 다름" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 약 45.5cm · 12.25kg" }, { id: "female", label: "암컷", value: "체고 약 45.5cm · 11.4kg" }] },
    storyTitle: "농장 다목적견은 어떻게 전쟁의 소음 속에서도 메시지를 옮기는 전령견이 됐을까요?", storyDescription: "빠르게 움직이는 자신감을 짧은 천 전달과 분명한 휴식으로 연결해봐요.",
    steps: [["과거의 역할", "농장에서 경계와 사냥을 맡았고 제1차 세계대전에는 전령견으로 일했어요.", "19세기 말 붉은 단색이 정착됐고 소음과 혼란 속 메시지를 옮긴 기록으로 민첩함과 대담함이 알려졌어요.", "history", "제1차 세계대전 통신소 사이로 메시지 주머니를 옮기는 아이리시 테리어 역사 삽화"], ["오늘의 활동", "넓은 직선 길 끝의 가벼운 천 주머니를 찾아 출발 매트로 가져와요.", "왕복은 한 번으로 끝내고 주머니를 놓으면 바로 물과 휴식으로 이어가세요.", "message-pouch-return", "직선 길의 천 주머니를 가져오는 아이리시 테리어 삽화"], ["함께 살 때", "주머니가 상자에 들어가면 통로 옆 긴 쿠션에서 다리를 펴고 쉬어요.", "다음 물건을 계속 찾지 않도록 상자를 닫고 지나가는 사람과 부딪히지 않는 자리를 고르세요.", "pouch-to-long-cushion", "긴 쿠션에서 다리를 펴고 쉬는 아이리시 테리어 삽화"]],
    caution: "전령견 기록이 모든 개체의 대담함이나 집중력을 보장하지 않아요. 소음에 대한 실제 반응과 회복 시간을 봐야 해요.", realitiesTitle: "긴 다리와 붉은 거친 털은 울타리·활동 거리·수염 관리에서 무엇을 요구할까요?", realities: [["irish-terrier-tall-clear-gate", "긴 다리로 기대도 흔들리지 않는 높고 촘촘한 문을 사용해요.", "문 앞에는 도움닫기할 가구를 두지 말고 잠금 장치를 손 높이보다 위에 두세요.", "높고 촘촘한 문 앞에 선 아이리시 테리어 삽화"], ["irish-wiry-beard", "짧고 빽빽한 거친 몸털과 작은 턱수염은 젖은 뒤 따로 말려요.", "털을 길게 늘이지 말고 피부가 보이지 않는 빽빽함과 턱 아래 습기를 확인하세요.", "붉은 거친 털과 턱수염을 관리받는 아이리시 테리어 삽화"]],
    readiness: ["높고 흔들리지 않는 문과 울타리를 준비할 수 있나요?", "빠른 왕복 활동 뒤 바로 쉬는 순서를 만들 수 있나요?", "거친 붉은 털과 턱수염을 관리할 수 있나요?"], relatedTitle: "아일랜드 테리어도 몸높이와 작업 방식이 달라요.", relatedDescription: "붉은 털보다 다리 길이, 이동 속도와 피모 관리를 비교해보세요.", related: { "kerry-blue-terrier": "케리 블루 테리어는 푸른 곱슬 털과 더 넓은 농장 작업 배경을 지녀요.", "soft-coated-wheaten-terrier": "소프트 코티드 휘튼 테리어는 부드러운 밀색 털의 아일랜드 농장견이에요." },
  },
  {
    slug: "lakeland-terrier", nameKo: "레이클랜드 테리어", metadataDescription: "잉글랜드 레이크 디스트릭트의 바위산에서 여우를 추적한 레이클랜드 테리어의 좁은 체형, 거친 털과 생활 안전을 살펴봅니다.", heroStatement: "잉글랜드 레이크 디스트릭트의 가파른 바위틈에서 양을 노리는 여우를 찾아 들어가도록 길고 좁은 몸과 빠른 움직임을 갖춘, 단단한 거친 털의 소형 테리어예요.",
    size: { summaryRows: [{ label: "체고", value: "37cm 이하" }, { label: "몸무게", value: "성별로 다름" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 37cm 이하 · 7.7kg" }, { id: "female", label: "암컷", value: "체고 37cm 이하 · 6.8kg" }] },
    storyTitle: "좁고 깊은 가슴의 테리어는 왜 레이크 디스트릭트 바위틈을 오르내렸을까요?", storyDescription: "바위산 추적을 안전한 낮은 통로 냄새 찾기와 실내 휴식으로 바꿔봐요.",
    steps: [["과거의 역할", "레이크 디스트릭트의 바위틈에서 양을 노리는 여우를 추적했어요.", "좁은 가슴과 긴 다리는 거친 경사를 빠르게 건너고 틈 안으로 들어가는 작업에 맞춰졌어요.", "history", "레이크 디스트릭트의 바위 경사에서 여우 흔적을 찾는 레이클랜드 테리어 역사 삽화"], ["오늘의 활동", "낮고 열린 세 아치 중 냄새 천이 놓인 통로를 찾아 통과해요.", "몸이 끼지 않는 넓은 아치만 사용하고 정답 통로를 한 번 지나면 천을 치우세요.", "open-arches-scent", "낮고 열린 아치에서 냄새 천을 찾는 레이클랜드 테리어 삽화"], ["함께 살 때", "아치가 접혀 수납되면 벽 쪽 낮은 침대에 몸을 둥글게 말아요.", "바위 모양 장난감과 아치를 보이지 않게 치우고 현관에서 떨어진 자리를 사용하세요.", "arches-to-wall-bed", "벽 쪽 낮은 침대에서 쉬는 레이클랜드 테리어 삽화"]],
    caution: "바위틈 여우 추적 역사가 모든 개체의 추적 강도나 굴 파기를 같게 만들지 않아요. 좁은 공간은 실제 몸 폭을 확인해야 해요.", realitiesTitle: "좁은 몸과 빠른 움직임, 거친 털은 울타리 틈·낮은 통로·손질에서 무엇을 바꿀까요?", realities: [["lakeland-rock-gap-barrier", "돌담과 울타리 아래의 작은 틈은 단단한 촘촘망으로 막아요.", "머리만 들어가는 틈도 남기지 말고 망의 들뜬 모서리를 확인하세요.", "돌담 아래 틈이 촘촘망으로 막힌 공간의 레이클랜드 테리어 삽화"], ["lakeland-harsh-coat", "빽빽한 거친 겉털과 속털은 목·가슴·다리 털을 나눠 정리해요.", "털의 윤기보다 피부를 보호하는 단단한 질감과 겨드랑이 엉킴을 먼저 봐요.", "거친 이중모를 구역별로 관리받는 레이클랜드 테리어 삽화"]],
    readiness: ["울타리와 돌담의 작은 틈까지 막을 수 있나요?", "좁은 통로 활동을 안전한 크기로 제한할 수 있나요?", "거친 겉털과 속털을 정기적으로 관리할 수 있나요?"], relatedTitle: "영국 작업 테리어도 지형과 몸의 폭이 달라요.", relatedDescription: "비슷한 거친 털보다 작업한 지형과 틈 안전을 비교해보세요.", related: { "border-terrier": "보더 테리어는 국경 언덕에서 기마 사냥대를 따라 여우를 추적했어요.", "welsh-terrier": "웰시 테리어는 웨일스 산지에서 여우·오소리·수달을 추적한 더 넓은 체형의 테리어예요." },
  },
  {
    slug: "skye-terrier", nameKo: "스카이 테리어", metadataDescription: "스코틀랜드 서부 섬에서 형성된 스카이 테리어의 몸길이, 바닥에 흐르는 이중모와 낮은 생활 동선을 살펴봅니다.", heroStatement: "스코틀랜드 서부 섬에서 이어진 오래된 테리어로, 몸길이가 체고의 두 배에 이르고 단단한 몸 위로 긴 이중모가 바닥 가까이 흐르는 독특한 소형견이에요.",
    size: { summaryRows: [{ label: "체고", value: "이상적 25~26cm" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "이상적 체고 25~26cm" }, { id: "female", label: "암컷", value: "같은 비율로 수컷보다 조금 작음" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] },
    storyTitle: "몸길이가 키의 두 배인 테리어는 왜 서부 섬의 낮고 거친 지형에 맞춰졌을까요?", storyDescription: "낮은 몸의 탐색을 평평한 냄새 길과 허리 부담을 줄인 휴식으로 풀어봐요.",
    steps: [["형성 배경", "스코틀랜드 서부 섬의 오래된 낮은 테리어 계통에서 형성됐어요.", "케언 테리어 원형을 포함한 여러 계통의 영향이 기록돼 있고 곧게 선 귀와 늘어진 귀 두 형태가 모두 남아 있어요.", "history", "스코틀랜드 스카이섬의 낮은 돌담 곁을 살피는 스카이 테리어 역사 삽화"], ["오늘의 활동", "평평한 긴 러그 위 세 냄새 조각을 천천히 따라가요.", "점프나 급회전 없이 코를 낮춰 걸을 수 있게 조각 사이를 넓게 두세요.", "flat-long-scent-line", "평평한 긴 러그의 냄새 조각을 따라가는 스카이 테리어 삽화"], ["함께 살 때", "냄새 조각이 치워지면 계단 없는 낮고 긴 침대에 몸을 펴요.", "자주 지나는 길과 분리하고 침대 가장자리도 낮게 골라 오르내림을 줄이세요.", "scent-to-long-low-bed", "낮고 긴 침대에서 쉬는 스카이 테리어 삽화"]],
    caution: "오래된 테리어 배경이 모든 개체의 낯선 사람 반응이나 추적 욕구를 정하지 않아요. 긴 몸은 실제 움직임을 보고 환경을 맞춰야 해요.", realitiesTitle: "체고의 두 배인 몸길이와 바닥 가까운 장모는 계단·문턱·젖은 날에 무엇을 요구할까요?", realities: [["skye-low-ramp", "소파와 차량의 높은 턱에는 길고 완만한 낮은 발판을 고정해요.", "발판 앞뒤가 미끄러지지 않게 하고 뛰어내릴 옆 틈을 막아주세요.", "길고 완만한 낮은 발판을 걷는 스카이 테리어 삽화"], ["skye-floor-coat-dry", "바닥 가까이 흐르는 겉털과 부드러운 속털은 배·옆구리·귀 장식털을 나눠 말려요.", "눈을 가리지 않게 이마 털을 정리하고 발 사이의 모래와 습기를 먼저 확인하세요.", "바닥 가까운 긴 이중모를 말리는 스카이 테리어 삽화"]],
    readiness: ["계단과 높은 턱의 반복을 줄일 수 있나요?", "긴 몸이 펴지는 낮고 넓은 자리를 마련할 수 있나요?", "바닥에 닿는 긴 이중모를 매일 확인할 수 있나요?"], relatedTitle: "낮고 긴 테리어도 털과 몸 비율이 달라요.", relatedDescription: "체고만 보지 말고 몸길이, 문턱과 피모 부담을 비교해보세요.", related: { "dandie-dinmont-terrier": "댄디 딘몬트 테리어는 굽은 등선과 부드러운 톱노트가 뚜렷한 낮은 테리어예요.", "scottish-terrier": "스코티시 테리어는 더 짧고 단단한 몸과 거친 털을 지닌 스코틀랜드 테리어예요." },
  },
  {
    slug: "dandie-dinmont-terrier", nameKo: "댄디 딘몬트 테리어", metadataDescription: "스코틀랜드 국경지대의 사냥 테리어에서 문학 작품의 이름을 얻은 댄디 딘몬트 테리어의 낮고 긴 몸, 톱노트 관리를 살펴봅니다.", heroStatement: "스코틀랜드 국경지대에서 오소리와 수달 같은 사냥감을 추적하던 낮고 긴 테리어로, 월터 스콧의 소설 속 인물 이름을 따라 견종명이 굳어진 부드러운 톱노트의 소형견이에요.",
    size: { summaryRows: [{ label: "체고", value: "고정 기준 없음" }, { label: "몸무게", value: "8~11kg" }], detailsLabel: "FCI 기준 보기", items: [{ id: "height", label: "체고", value: "FCI 고정 기준 없음" }, { id: "weight", label: "몸무게", value: "작업 상태 8~11kg · 낮은 쪽 선호" }] },
    storyTitle: "국경지대의 사냥 테리어는 어떻게 소설 속 인물의 이름을 가진 견종이 됐을까요?", storyDescription: "낮고 유연한 추적을 부드러운 냄새 선택과 긴 몸의 휴식으로 연결해봐요.",
    steps: [["형성 배경", "스코틀랜드 국경지대에서 오소리와 수달을 추적하던 낮은 테리어였어요.", "월터 스콧의 소설에 등장한 댄디 딘몬트라는 인물과 그의 테리어들에서 오늘의 이름을 얻었어요.", "history", "스코틀랜드 국경지대 강둑에서 흔적을 찾는 댄디 딘몬트 테리어 역사 삽화"], ["오늘의 활동", "낮은 갈대 모형 사이 두 냄새 주머니 중 하나를 골라요.", "몸을 비틀어 파고들지 않게 모형 간격을 넓히고 선택 뒤 바로 주머니를 치우세요.", "reed-scent-pouches", "낮은 갈대 모형 사이 냄새 주머니를 고르는 댄디 딘몬트 테리어 삽화"], ["함께 살 때", "갈대 모형이 접히면 낮고 긴 쿠션에 배와 다리를 모두 내려놔요.", "쿠션 주변에 오르내릴 물건을 두지 말고 통로에서 떨어진 벽 쪽을 사용하세요.", "pouches-to-long-cushion", "낮고 긴 쿠션에 쉬는 댄디 딘몬트 테리어 삽화"]],
    caution: "과거 사냥 역할이 모든 개체의 집요함이나 작은 동물 반응을 정하지 않아요. 긴 몸의 움직임과 실제 반응을 함께 봐야 해요.", realitiesTitle: "낮고 긴 유연한 몸과 부드러운 톱노트는 문턱·소파·피모 관리에서 무엇을 바꿀까요?", realities: [["dandie-gentle-step", "높은 소파와 문턱에는 길고 완만한 발판을 고정해요.", "옆으로 뛰어내리지 않게 발판 가장자리와 가구 사이 틈을 막아주세요.", "길고 완만한 발판을 걷는 댄디 딘몬트 테리어 삽화"], ["dandie-topknot-pencil-coat", "부드러운 톱노트와 연필처럼 갈라지는 몸털은 서로 다른 빗으로 나눠 관리해요.", "눈 주변의 부드러운 털을 당기지 말고 배와 앞다리 장식털의 엉킴을 확인하세요.", "톱노트와 연필 모양 몸털을 관리받는 댄디 딘몬트 테리어 삽화"]],
    readiness: ["높은 턱과 소파에 완만한 발판을 설치할 수 있나요?", "낮고 긴 몸이 펴지는 휴식 자리가 있나요?", "톱노트와 이중모를 다른 방식으로 관리할 수 있나요?"], relatedTitle: "낮고 긴 테리어도 등선과 피모가 달라요.", relatedDescription: "몸길이만 보지 말고 발판과 털 관리의 차이를 비교해보세요.", related: { "skye-terrier": "스카이 테리어는 더 곧은 등선과 바닥에 흐르는 긴 털을 지녀요.", "glen-of-imaal-terrier": "글렌 오브 이말 테리어는 더 무겁고 앞다리가 굽은 아일랜드 작업 테리어예요." },
  },
  {
    slug: "glen-of-imaal-terrier", nameKo: "글렌 오브 이말 테리어", metadataDescription: "아일랜드 글렌 오브 이말 농가에서 오소리·여우·쥐를 상대하고 회전바퀴를 돌린 글렌 오브 이말 테리어의 생활 조건을 살펴봅니다.", heroStatement: "아일랜드 글렌 오브 이말의 거친 농가에서 오소리·여우·쥐를 상대하고 회전바퀴를 돌리는 일까지 맡았던, 낮은 몸에 큰 힘이 응축된 중소형 작업 테리어예요.",
    size: { summaryRows: [{ label: "체고", value: "수컷 최대 35.5cm" }, { label: "몸무게", value: "수컷 16kg" }], detailsLabel: "FCI 성별 기준 보기", items: [{ id: "male", label: "수컷", value: "체고 최대 35.5cm · 16kg" }, { id: "female", label: "암컷", value: "수컷 기준보다 알맞게 작음" }] },
    storyTitle: "낮지만 묵직한 테리어는 왜 사냥뿐 아니라 농가의 회전바퀴까지 돌렸을까요?", storyDescription: "오래 힘을 쓰던 역할을 짧은 밀기보다 낮은 후각 선택과 충분한 회복으로 바꿔봐요.",
    steps: [["과거의 역할", "글렌의 농가에서 오소리·여우를 사냥하고 쥐를 줄이며 회전바퀴도 돌렸어요.", "오랫동안 지역 안에서 실용견으로만 이어졌고 1934년에 아일랜드 켄넬 클럽의 인정을 받았어요.", "history", "아일랜드 글렌 오브 이말 농가의 회전바퀴와 창고 곁에 선 테리어 역사 삽화"], ["오늘의 활동", "낮은 세 통 중 농가 냄새 천이 든 하나를 조용히 찾아요.", "통은 무겁게 고정하고 앞발로 밀기 전에 정답을 알리면 바로 열어 보상하세요.", "quiet-farm-tins", "낮은 세 통에서 냄새 천을 찾는 글렌 오브 이말 테리어 삽화"], ["함께 살 때", "통이 수납되면 단단하고 낮은 매트에 넓은 가슴을 내려놓아요.", "다음 통을 찾으러 다니지 않게 수납장을 닫고 계단에서 떨어진 자리를 고르세요.", "tins-to-firm-mat", "단단하고 낮은 매트에서 쉬는 글렌 오브 이말 테리어 삽화"]],
    caution: "과거의 강한 작업이 모든 개체의 끈기나 작은 동물 반응을 보장하지 않아요. 짧은 다리와 큰 몸의 실제 움직임을 봐야 해요.", realitiesTitle: "짧고 굽은 앞다리와 16kg 안팎의 몸은 계단·발판·거친 털 관리에서 무엇을 요구할까요?", realities: [["glen-wide-low-ramp", "계단과 차량에는 폭이 넓고 기울기가 낮은 발판을 고정해요.", "짧은 다리가 옆으로 빠지지 않게 가장자리를 만들고 젖은 발판은 바로 말리세요.", "폭이 넓고 낮은 발판을 걷는 글렌 오브 이말 테리어 삽화"], ["glen-harsh-undercoat", "중간 길이 거친 겉털과 부드러운 속털은 가슴·배·다리 뒤를 나눠 빗어요.", "털을 부풀리기보다 피부 가까운 엉킴과 젖은 배 털을 먼저 확인하세요.", "거친 겉털과 속털을 관리받는 글렌 오브 이말 테리어 삽화"]],
    readiness: ["계단과 차량에 넓고 낮은 발판을 둘 수 있나요?", "묵직한 낮은 몸이 편히 도는 실내 공간이 있나요?", "거친 겉털과 부드러운 속털을 나눠 관리할 수 있나요?"], relatedTitle: "아일랜드 테리어도 다리 길이와 몸의 무게감이 달라요.", relatedDescription: "크기 분류보다 계단 부담과 피모, 과거의 일 방식을 비교해보세요.", related: { "dandie-dinmont-terrier": "댄디 딘몬트 테리어는 더 유연한 등선과 부드러운 톱노트가 특징이에요.", "soft-coated-wheaten-terrier": "소프트 코티드 휘튼 테리어는 더 높고 부드러운 밀색 털의 농장견이에요." },
  },
  {
    slug: "japanese-terrier", nameKo: "재패니즈 테리어", metadataDescription: "나가사키에 들어온 스무드 폭스 테리어 계통에서 항구 도시의 무릎개로 자리 잡은 재패니즈 테리어의 얇은 피모와 생활을 살펴봅니다.", heroStatement: "17세기 네덜란드에서 나가사키로 들어온 스무드 폭스 테리어를 작은 포인터·토착견과 교배해 만들고 고베·요코하마에서 무릎개로 사랑받은, 2mm 남짓의 아주 짧은 털을 지닌 작은 테리어예요.",
    size: { summaryRows: [{ label: "체고", value: "약 30~33cm" }, { label: "몸무게", value: "고정 기준 없음" }], detailsLabel: "FCI 기준 보기", items: [{ id: "height", label: "암수 공통", value: "체고 약 30~33cm" }, { id: "weight", label: "몸무게", value: "FCI 고정 기준 없음" }] },
    storyTitle: "유럽에서 건너온 테리어 계통은 어떻게 일본 항구 도시의 작은 무릎개가 됐을까요?", storyDescription: "항구의 빠르고 밝은 움직임을 가벼운 천 찾기와 따뜻한 실내 휴식으로 연결해봐요.",
    steps: [["형성 배경", "나가사키로 들어온 스무드 폭스 테리어 계통이 일본의 작은 개들과 섞였어요.", "고베와 요코하마에서 무릎개로 길러졌고 1920년대 계획 번식을 거쳐 1930년 무렵 타입이 고정됐어요.", "history", "고베 항구의 집 안 창가에서 사람 곁에 머무는 재패니즈 테리어 역사 삽화"], ["오늘의 활동", "평평한 바닥의 가벼운 천 세 장 중 항구 냄새가 든 한 장을 찾아요.", "천이 미끄러지지 않게 고정하고 코로 선택하면 바로 접어 상자에 넣으세요.", "harbor-cloth-choice", "평평한 바닥의 천 세 장 중 하나를 고르는 재패니즈 테리어 삽화"], ["함께 살 때", "천 상자가 닫히면 햇빛이 직접 닿지 않는 따뜻한 낮은 침대에서 쉬어요.", "차가운 바닥과 현관 바람을 피하고 얇은 몸이 완전히 들어가는 자리를 고르세요.", "cloth-to-warm-bed", "따뜻한 낮은 침대에서 쉬는 재패니즈 테리어 삽화"]],
    caution: "항구 도시의 무릎개 역사와 밝은 표준 설명이 모든 개체의 사람 선호나 활동성을 보장하지 않아요. 실제 반응을 봐야 해요.", realitiesTitle: "작은 몸과 약 2mm의 아주 짧은 털은 문틈·바닥 온도·피부 확인에서 무엇을 바꿀까요?", realities: [["japanese-terrier-door-gap", "현관과 발코니의 낮은 틈은 작은 머리가 빠지지 않는 촘촘한 가림판으로 막아요.", "미닫이문이 덜 닫힌 틈과 방충망 아래 들뜬 부분도 함께 확인하세요.", "낮은 문틈이 촘촘히 막힌 공간의 재패니즈 테리어 삽화"], ["japanese-terrier-shortcoat", "약 2mm의 짧은 털은 빗질보다 피부와 발의 마찰·건조를 먼저 살펴요.", "부드러운 천으로 닦고 차가운 날에는 젖은 몸이 식기 전에 완전히 말리세요.", "아주 짧은 삼색 털과 피부를 확인받는 재패니즈 테리어 삽화"]],
    readiness: ["작은 몸이 빠질 문틈과 방충망 아래를 막을 수 있나요?", "차가운 바닥과 현관 바람을 피할 자리가 있나요?", "아주 짧은 털 아래 피부 상태를 자주 확인할 수 있나요?"], relatedTitle: "작은 테리어도 작업견과 항구 반려견의 배경이 달라요.", relatedDescription: "체고보다 털 길이, 온도와 실내 동선을 비교해보세요.", related: { "smooth-fox-terrier": "스무드 폭스 테리어는 재패니즈 테리어 형성에 영향을 준 더 큰 영국 작업 테리어예요.", "prague-ratter": "프라하 라터는 더 작고 궁정·도시의 설치류 통제 배경을 지닌 반려견이에요." },
  },
];

const appendAndParticle = (name: string) => { const last = name.charCodeAt(name.length - 1); return `${name}${last >= 0xac00 && last <= 0xd7a3 && (last - 0xac00) % 28 !== 0 ? "과" : "와"}`; };

export const expansionTo300Batch04StandardBreedDetails = seeds.map((seed) => standardBreedDetailSchema.parse({
  slug: seed.slug, reviewStatus: "production-draft", nameKo: seed.nameKo, metadataDescription: seed.metadataDescription, heroStatement: seed.heroStatement, heroSizeDetails: seed.size,
  story: { title: seed.storyTitle, description: seed.storyDescription, steps: seed.steps.map(([navLabel, title, body, imageId, imageAlt], index) => ({ navLabel, eyebrow: `${index + 1}단계 · ${index === 0 ? "무엇을 하던 개였을까?" : index === 1 ? "그 흔적은 지금 어떻게 나타날까?" : "보호자는 무엇을 체감할까?"}`, title, body, image: `/illustrations/${imageId === "history" ? "v3" : "v4"}/${seed.slug}-${imageId === "history" ? "history" : `feature-${imageId}`}.webp`, imageAlt })), caution: seed.caution },
  realitiesTitle: seed.realitiesTitle, realities: seed.realities.map(([id, title, body, imageAlt]) => ({ id, title, body, image: `/illustrations/v4/${seed.slug}-feature-${id}.webp`, imageAlt })), readinessTitle: `${appendAndParticle(seed.nameKo)} 살기 전 확인할 세 가지`, readinessQuestions: seed.readiness, relatedTitle: seed.relatedTitle, relatedDescription: seed.relatedDescription, relatedDifferences: seed.related,
}));
