import { z } from "zod";
import { cardSchema } from "./giant-cards";

export const extraSmallCards = z.array(cardSchema).parse([
  {
    slug: "chihuahua",
    name: "치와와",
    nameEn: "CHIHUAHUA",
    number: "01",
    edition: "COURTYARD EDITION",
    origin: "멕시코",
    originEn: "MEXICO",
    region: "멕시코의 마당과 집",
    flag: "mexico",
    role: "반려 · 동반견",
    tagline: "멕시코에서 사람 곁을 지켜 온 작은 친구.",
    historyTitle: "작은 몸으로 오래 함께한 친구",
    history: "멕시코의 치와와주에서 이름을 얻은 반려견이에요.",
    height: "15–23",
    heightLabel: "어깨 높이 · 참고",
    weight: "1–3",
    lifespan: "14–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/chihuahua-front-v1.webp",
      alt: "멕시코의 따뜻한 돌마당에 서 있는 황갈색 치와와 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/chihuahua-back-v1.webp",
      alt: "멕시코 마당에 앉은 여성의 신발 옆에 서 있는 작은 치와와. 같은 바닥에서 체구를 비교하는 수채화",
      width: 1060,
      height: 1477,
    },
  },
  {
    slug: "german-spitz",
    name: "포메라니안",
    nameEn: "POMERANIAN",
    number: "02",
    edition: "GARDEN EDITION",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일의 집과 정원",
    flag: "germany",
    role: "알림 · 반려견",
    tagline: "집 안팎의 인기척을 알려 주던 작은 스피츠.",
    historyTitle: "작아진 스피츠, 여전한 귀 쫑긋",
    history: "독일 스피츠의 작은 유형으로, 사람 곁에서 집을 살폈어요.",
    height: "18–24",
    weight: "1.4–3.2",
    lifespan: "12–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/german-spitz-front-v1.webp",
      alt: "독일 벽돌집 정원 앞에 선 주황빛 포메라니안 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/german-spitz-back-v1.webp",
      alt: "독일 정원 벤치에 앉은 성인의 신발 옆에 선 포메라니안 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "yorkshire-terrier",
    name: "요크셔 테리어",
    nameEn: "YORKSHIRE TERRIER",
    number: "03",
    edition: "COTTAGE EDITION",
    origin: "영국 · 요크셔",
    originEn: "UNITED KINGDOM · YORKSHIRE",
    region: "영국 요크셔의 작업장",
    flag: "uk",
    role: "쥐잡이 · 반려견",
    tagline: "작업장 구석을 누비던 작은 쥐잡이.",
    historyTitle: "고운 털 아래, 씩씩한 일꾼",
    history: "영국의 공장과 광산에서 쥐를 잡던 테리어예요.",
    height: "20–23",
    heightLabel: "어깨 높이 · 참고",
    weight: "2.7–3.2",
    lifespan: "14–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/yorkshire-terrier-front-v1.webp",
      alt: "영국 돌집 작업장 앞에 선 푸른빛 털의 요크셔 테리어 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/yorkshire-terrier-back-v1.webp",
      alt: "영국 돌집 앞 의자에 앉은 성인의 신발 옆에 선 요크셔 테리어 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
]);
