import { z } from "zod";
import { cardSchema } from "./giant-cards";

export const extraSmallCards = z.array(cardSchema).parse([
  {
    slug: "chihuahua",
    name: "치와와",
    nameEn: "CHIHUAHUA",
    number: "01",
    edition: "COURTYARD EDITION",
    origin: "멕시코",
    originEn: "MEXICO",
    region: "멕시코의 마당과 집",
    flag: "mexico",
    role: "반려 · 동반견",
    tagline: "멕시코에서 사람 곁을 지켜 온 작은 친구.",
    historyTitle: "작은 몸으로 오래 함께한 친구",
    history: "멕시코의 치와와주에서 이름을 얻은 반려견이에요.",
    height: "15–23",
    heightLabel: "어깨 높이 · 참고",
    weight: "1–3",
    lifespan: "14–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/chihuahua-front-v1.webp",
      alt: "멕시코의 따뜻한 돌마당에 서 있는 황갈색 치와와 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/chihuahua-back-people-v3.webp",
      alt: "멕시코 마당에 앉은 여성의 신발 옆에 서 있는 작은 치와와. 같은 바닥에서 체구를 비교하는 수채화",
      width: 1060,
      height: 1477,
    },
  },
  {
    slug: "german-spitz",
    name: "포메라니안",
    nameEn: "POMERANIAN",
    number: "02",
    edition: "GARDEN EDITION",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일의 집과 정원",
    flag: "germany",
    role: "알림 · 반려견",
    tagline: "집 안팎의 인기척을 알려 주던 작은 스피츠.",
    historyTitle: "작아진 스피츠, 여전한 귀 쫑긋",
    history: "독일 스피츠의 작은 유형으로, 사람 곁에서 집을 살폈어요.",
    height: "18–24",
    weight: "1.4–3.2",
    lifespan: "12–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/german-spitz-front-v1.webp",
      alt: "독일 벽돌집 정원 앞에 선 주황빛 포메라니안 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/german-spitz-back-people-v3.webp",
      alt: "독일 정원 벤치에 앉은 성인의 신발 옆에 선 포메라니안 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "yorkshire-terrier",
    name: "요크셔 테리어",
    nameEn: "YORKSHIRE TERRIER",
    number: "03",
    edition: "COTTAGE EDITION",
    origin: "영국 · 요크셔",
    originEn: "UNITED KINGDOM · YORKSHIRE",
    region: "영국 요크셔의 작업장",
    flag: "uk",
    role: "쥐잡이 · 반려견",
    tagline: "작업장 구석을 누비던 작은 쥐잡이.",
    historyTitle: "고운 털 아래, 씩씩한 일꾼",
    history: "영국의 공장과 광산에서 쥐를 잡던 테리어예요.",
    height: "20–23",
    heightLabel: "어깨 높이 · 참고",
    weight: "2.7–3.2",
    lifespan: "14–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/yorkshire-terrier-front-v1.webp",
      alt: "영국 돌집 작업장 앞에 선 푸른빛 털의 요크셔 테리어 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/yorkshire-terrier-back-people-v3.webp",
      alt: "영국 돌집 앞 의자에 앉은 성인의 신발 옆에 선 요크셔 테리어 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "maltese",
    name: "말티즈",
    nameEn: "MALTESE",
    number: "04",
    edition: "COMPANION EDITION",
    origin: "중앙 지중해 · 이탈리아 관리",
    originEn: "CENTRAL MEDITERRANEAN",
    region: "지중해의 항구와 집",
    flag: "italy",
    role: "반려 · 동반견",
    tagline: "지중해 항구에서 사람 곁으로 이어진 친구.",
    historyTitle: "오래도록 사람 곁에서",
    history: "지중해권에서 오랫동안 사람과 함께 살아온 반려견이에요.",
    height: "20–25",
    weight: "3–4",
    lifespan: "12–15",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/maltese-front-v1.webp",
      alt: "지중해의 항구와 집 배경에 선 말티즈 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/maltese-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 말티즈. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "poodle",
    name: "토이푸들",
    nameEn: "TOY POODLE",
    number: "05",
    edition: "COMPANION EDITION",
    origin: "프랑스",
    originEn: "FRANCE",
    region: "프랑스 · 실버색",
    flag: "france",
    role: "반려 · 동반견",
    tagline: "물가를 누비던 푸들 계통의 작은 친구.",
    historyTitle: "물가에서 집 안으로",
    history: "물에서 사냥감을 가져오던 푸들 계통의 작은 반려견이에요.",
    height: "24–28",
    weight: "1.8–2.7",
    lifespan: "10–18",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/toy-poodle-silver-front-petite-v2.webp",
      alt: "프랑스 돌마당에 작고 아담한 체구로 서 있는 실버 토이푸들 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/toy-poodle-silver-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 토이푸들. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "bichon-frise",
    name: "비숑 프리제",
    nameEn: "BICHON FRISE",
    number: "06",
    edition: "COMPANION EDITION",
    origin: "프랑스 · 벨기에",
    originEn: "FRANCE · BELGIUM",
    region: "유럽의 집과 정원",
    flag: "france",
    secondaryFlag: "belgium",
    role: "반려 · 동반견",
    tagline: "유럽의 사람 곁에서 사랑받던 곱슬털 친구.",
    historyTitle: "궁정에서 함께한 친구",
    history: "유럽의 귀족 곁에서 사랑받던 곱슬털 반려견이에요.",
    height: "24–29",
    weight: "5.4–8.2",
    lifespan: "14–15",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/bichon-frise-front-v1.webp",
      alt: "유럽의 집과 정원 배경에 선 비숑 프리제 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/bichon-frise-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 비숑 프리제. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "shih-tzu",
    name: "시츄",
    nameEn: "SHIH TZU",
    number: "07",
    edition: "COMPANION EDITION",
    origin: "티베트 기원 · 중국 발전",
    originEn: "TIBETAN ROOTS · CHINA",
    region: "중국의 궁정과 안뜰",
    flag: "china",
    role: "궁정 · 반려견",
    tagline: "중국 궁정에서 사람과 함께하던 작은 친구.",
    historyTitle: "궁정 안의 작은 동반자",
    history: "티베트계 개에서 이어져 중국 궁정에서 함께 살던 반려견이에요.",
    height: "20–28",
    weight: "4.1–7.3",
    lifespan: "14–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/shih-tzu-front-v1.webp",
      alt: "중국의 궁정과 안뜰 배경에 선 시츄 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/shih-tzu-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 시츄. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "dachshund",
    name: "미니어처 닥스훈트",
    nameEn: "MINIATURE DACHSHUND",
    number: "08",
    edition: "COMPANION EDITION",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일의 숲과 굴",
    flag: "germany",
    role: "굴 사냥 · 반려견",
    tagline: "낮은 몸으로 땅속 길을 탐색하던 개.",
    historyTitle: "짧은 다리로 굴속까지",
    history: "굴속 사냥감을 쫓던 닥스훈트의 작은 유형이에요.",
    height: "13–15",
    weight: "≤5",
    lifespan: "12–16",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/miniature-dachshund-front-v1.webp",
      alt: "독일의 숲과 굴 배경에 선 미니어처 닥스훈트 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/miniature-dachshund-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 미니어처 닥스훈트. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "miniature-schnauzer",
    name: "미니어처 슈나우저",
    nameEn: "MINIATURE SCHNAUZER",
    number: "09",
    edition: "COMPANION EDITION",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일의 농가와 마당",
    flag: "germany",
    role: "쥐잡이 · 알림견",
    tagline: "농가의 작은 인기척을 놓치지 않던 개.",
    historyTitle: "수염 달린 농가의 일꾼",
    history: "독일 농가에서 쥐를 잡고 낯선 인기척을 알리던 개예요.",
    height: "30–35",
    weight: "4–8",
    lifespan: "12–15",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/miniature-schnauzer-front-v1.webp",
      alt: "독일의 농가와 마당 배경에 선 미니어처 슈나우저 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/miniature-schnauzer-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 미니어처 슈나우저. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "continental-toy-spaniel",
    name: "파피용",
    nameEn: "PAPILLON",
    number: "10",
    edition: "COMPANION EDITION",
    origin: "프랑스 · 벨기에",
    originEn: "FRANCE · BELGIUM",
    region: "유럽의 저택과 정원",
    flag: "france",
    secondaryFlag: "belgium",
    role: "반려 · 동반견",
    tagline: "나비 같은 귀로 사람 곁을 지켜 온 친구.",
    historyTitle: "그림 속 귀족의 곁에서",
    history: "유럽 귀족 곁에서 지내던 작은 스패니얼이에요.",
    height: "약 28",
    weight: "1.5–5",
    lifespan: "12–15",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/continental-toy-spaniel-front-v1.webp",
      alt: "유럽의 저택과 정원 배경에 선 파피용 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/continental-toy-spaniel-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 파피용. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "maltipoo",
    name: "말티푸",
    nameEn: "MALTIPOO",
    number: "11",
    edition: "COMPANION EDITION",
    origin: "말티즈 × 푸들",
    originEn: "MALTESE × POODLE",
    region: "사람과 함께하는 일상의 정원",
    flag: "none",
    role: "믹스 · 반려견",
    tagline: "말티즈와 푸들이 만나 저마다 다른 모습으로.",
    historyTitle: "두 계통이 만난 친구",
    history: "말티즈와 푸들 사이에서 태어난 믹스예요.",
    height: "",
    weight: "",
    lifespan: "13–16",
    theme: "woodland",
    sizeNote: "부모견에 따라\n체구가 달라요.",
    backNote: "그림은 한 개체의 예시예요. 털과 크기는 부모견에 따라 달라요.",
    front: {
      src: "/illustrations/card-studies/maltipoo-front-v1.webp",
      alt: "사람과 함께하는 일상의 정원 배경에 선 말티푸 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/maltipoo-back-people-v3.webp",
      alt: "일상복을 입은 성인의 신발 옆에 선 말티푸. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
]);
