import { z } from "zod";

const art = z.object({
  src: z.string(),
  alt: z.string(),
  width: z.number(),
  height: z.number(),
});
const cardSchema = z.object({
  slug: z.string(),
  name: z.string(),
  nameEn: z.string(),
  number: z.string(),
  edition: z.string(),
  origin: z.string(),
  originEn: z.string(),
  region: z.string(),
  flag: z
    .enum(["france", "switzerland", "germany", "ireland", "turkey", "mongolia"])
    .nullable(),
  role: z.string(),
  tagline: z.string(),
  historyTitle: z.string(),
  history: z.string(),
  height: z.string(),
  weight: z.string(),
  lifespan: z.string().nullable(),
  heightLabel: z.string().optional(),
  weightLabel: z.string().optional(),
  backNote: z.string().optional(),
  theme: z.enum(["alpine", "woodland"]),
  front: art,
  back: art,
});
export type GiantCard = z.infer<typeof cardSchema>;
const directory = "/illustrations/card-studies/";

export const giantCards = z.array(cardSchema).parse([
  {
    slug: "pyrenean-mountain-dog",
    name: "그레이트 피레니즈",
    nameEn: "PYRENEAN MOUNTAIN DOG",
    number: "01",
    edition: "ALPINE EDITION",
    origin: "프랑스 · 피레네산맥",
    originEn: "FRANCE · THE PYRENEES",
    region: "프랑스 피레네 지역",
    flag: "france",
    role: "산악 · 가축보호견",
    tagline: "피레네산맥에서 무리 곁을 지키던 개.",
    historyTitle: "양 떼의 든든한 경호원",
    history: "피레네산맥에서 양 떼를 지키던 개예요.",
    height: "65–80",
    weight: "39–54",
    lifespan: "10–12",
    theme: "alpine",
    front: {
      src: directory + "great-pyrenees-alpine-v1.webp",
      alt: "눈 덮인 피레네산맥 앞에 서 있는 하얀 그레이트 피레니즈 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: directory + "great-pyrenees-human-back-v1.webp",
      alt: "같은 눈밭에 나란히 선 어른과 그레이트 피레니즈. 강아지의 어깨가 사람의 허벅지 높이에 닿는 크기 차이를 그린 수채화",
      width: 1059,
      height: 1486,
    },
  },
  {
    slug: "saint-bernard",
    name: "세인트 버나드",
    nameEn: "SAINT BERNARD",
    number: "02",
    edition: "HOSPICE EDITION",
    origin: "스위스 · 알프스",
    originEn: "SWITZERLAND · THE ALPS",
    region: "스위스 알프스 지역",
    flag: "switzerland",
    role: "산악 · 구조견",
    tagline: "눈 덮인 산길에서 여행자를 찾던 개.",
    historyTitle: "눈길에서 사람을 찾던 친구",
    history: "알프스의 수도사들과 함께 길 잃은 여행자를 찾고 구조를 도왔어요.",
    height: "65–90",
    weight: "54–82",
    lifespan: "8–10",
    theme: "alpine",
    front: {
      src: directory + "saint-bernard-hospice-v1.webp",
      alt: "알프스의 돌로 지은 여행자 쉼터와 눈길 앞에 서 있는 갈색과 흰색 세인트 버나드 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: directory + "saint-bernard-human-back-v1.webp",
      alt: "같은 눈길에 나란히 선 어른과 세인트 버나드의 전신을 보여주는 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "great-dane",
    name: "그레이트 데인",
    nameEn: "GREAT DANE",
    number: "03",
    edition: "WOODLAND EDITION",
    origin: "독일",
    originEn: "GERMANY · THE WOODLANDS",
    region: "독일의 숲과 저택",
    flag: "germany",
    role: "사냥 · 경비견",
    tagline: "독일의 숲을 달리고 저택을 지키던 개.",
    historyTitle: "숲의 사냥꾼, 저택의 파수꾼",
    history: "독일에서 멧돼지 사냥을 돕고, 귀족의 저택을 지키기도 했어요.",
    height: "72–90",
    weight: "50–79",
    lifespan: "7–10",
    theme: "woodland",
    front: {
      src: directory + "great-dane-woodland-v2.webp",
      alt: "독일의 숲과 저택 앞에 긴 다리와 곧게 선 귀, 흰 가슴 무늬가 보이는 검은 그레이트 데인 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: directory + "great-dane-human-back-v2.webp",
      alt: "저택 앞 숲길에 나란히 선 어른과 곧게 선 귀, 흰 가슴 무늬의 검은 그레이트 데인 전신을 보여주는 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "irish-wolfhound",
    name: "아이리시 울프하운드",
    nameEn: "IRISH WOLFHOUND",
    number: "04",
    edition: "MOORLAND EDITION",
    origin: "아일랜드",
    originEn: "IRELAND · THE MOORS",
    region: "아일랜드의 들판",
    flag: "ireland",
    role: "사냥 · 시각하운드",
    tagline: "아일랜드의 넓은 들판을 달리던 사냥개.",
    historyTitle: "늑대를 쫓던 긴 다리",
    history: "아일랜드에서 늑대와 큰 사냥감을 쫓던 개예요.",
    height: "81–89",
    weight: "52–82",
    lifespan: "6–8",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/irish-wolfhound-landscape-v1.webp",
      alt: "돌담과 탑이 보이는 아일랜드 황야의 회색 거친 털 아이리시 울프하운드 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/irish-wolfhound-human-back-v1.webp",
      alt: "돌담과 탑이 보이는 아일랜드 황야의 회색 거친 털 아이리시 울프하운드와 어른이 같은 땅에 나란히 선 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "tibetan-mastiff",
    name: "티베탄 마스티프",
    nameEn: "TIBETAN MASTIFF",
    number: "05",
    edition: "HIGHLAND EDITION",
    origin: "티베트 고원",
    originEn: "THE TIBETAN PLATEAU",
    region: "티베트 고원과 수도원",
    flag: null,
    role: "고원 · 가축보호견",
    tagline: "높은 고원에서 가축과 집을 지키던 개.",
    historyTitle: "고원의 밤을 지키던 파수꾼",
    history: "티베트 고원에서 가축을 지키고 수도원과 집을 지켰어요.",
    height: "61 / 66",
    heightLabel: "암컷 / 수컷 · 최소 높이",
    weight: "36–72",
    lifespan: "12–15",
    theme: "alpine",
    front: {
      src: "/illustrations/card-studies/tibetan-mastiff-landscape-v1.webp",
      alt: "티베트 고원의 수도원과 천막 앞 검은색과 황갈색의 풍성한 목털을 가진 티베탄 마스티프 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/tibetan-mastiff-human-back-v1.webp",
      alt: "티베트 고원의 수도원과 천막 앞 검은색과 황갈색의 풍성한 목털을 가진 티베탄 마스티프와 어른이 같은 땅에 나란히 선 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "kangal-shepherd-dog",
    name: "캉갈 셰퍼드 도그",
    nameEn: "KANGAL SHEPHERD DOG",
    number: "06",
    edition: "PASTURE EDITION",
    origin: "튀르키예 · 아나톨리아",
    originEn: "TÜRKIYE · ANATOLIA",
    region: "아나톨리아의 목초지",
    flag: "turkey",
    role: "목초지 · 가축보호견",
    tagline: "양 떼 곁에서 초원을 지키던 개.",
    historyTitle: "양 떼 곁의 든든한 경호원",
    history: "튀르키예의 목초지에서 양 떼를 포식자로부터 지키던 개예요.",
    height: "65–78",
    weight: "40–60",
    lifespan: "10+",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/kangal-shepherd-dog-landscape-v1.webp",
      alt: "양 떼가 있는 아나톨리아 목초지의 검은 주둥이와 황갈색 털을 가진 캉갈 셰퍼드 도그 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/kangal-shepherd-dog-human-back-v1.webp",
      alt: "양 떼가 있는 아나톨리아 목초지의 검은 주둥이와 황갈색 털을 가진 캉갈 셰퍼드 도그와 어른이 같은 땅에 나란히 선 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "caucasian-shepherd-dog",
    name: "코카시안 셰퍼드",
    nameEn: "CAUCASIAN SHEPHERD DOG",
    number: "07",
    edition: "CAUCASUS EDITION",
    origin: "코카서스 지역",
    originEn: "THE CAUCASUS MOUNTAINS",
    region: "코카서스 산악지대",
    flag: null,
    role: "산악 · 가축보호견",
    tagline: "거친 산에서 무리와 집을 지키던 개.",
    historyTitle: "산속 무리를 지키던 수호자",
    history: "코카서스 지역에서 가축과 집을 지키던 개예요.",
    height: "67–75",
    heightLabel: "어깨 높이 · 표준 권장",
    weight: "45–77",
    lifespan: "10–12",
    theme: "alpine",
    front: {
      src: "/illustrations/card-studies/caucasian-shepherd-dog-landscape-v1.webp",
      alt: "코카서스 산악지대의 돌탑과 능선 앞 풍성한 회갈색 털과 자연스럽게 처진 귀의 코카시안 셰퍼드 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/caucasian-shepherd-dog-human-back-v1.webp",
      alt: "코카서스 산악지대의 돌탑과 능선 앞 풍성한 회갈색 털과 자연스럽게 처진 귀의 코카시안 셰퍼드와 어른이 같은 땅에 나란히 선 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "mongolian-bankhar",
    name: "몽골 방카르",
    nameEn: "MONGOLIAN BANKHAR",
    number: "08",
    edition: "STEPPE EDITION",
    origin: "몽골",
    originEn: "MONGOLIA · THE STEPPE",
    region: "몽골의 초원과 게르",
    flag: "mongolia",
    role: "초원 · 가축보호견",
    tagline: "유목민과 함께 초원을 지켜 온 개.",
    historyTitle: "유목민과 함께 살아온 친구",
    history: "몽골의 유목민과 함께 지내며 양과 염소 무리를 지켜 왔어요.",
    height: "76",
    heightLabel: "수컷 어깨 높이 · 참고",
    weight: "45 / 54",
    weightLabel: "암컷 / 수컷 무게 · 참고",
    lifespan: null,
    backNote: "토착 개체군이라 크기 차이가 커요. 그림은 비교 예시예요.",
    theme: "woodland",
    front: {
      src: "/illustrations/card-studies/mongolian-bankhar-landscape-v1.webp",
      alt: "게르와 가축이 보이는 몽골 초원의 검은색과 황갈색 털 몽골 방카르 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/mongolian-bankhar-human-back-v1.webp",
      alt: "게르와 가축이 보이는 몽골 초원의 검은색과 황갈색 털 몽골 방카르와 어른이 같은 땅에 나란히 선 크기 비교 수채화",
      width: 1060,
      height: 1484,
    },
  },
]);
