import { z } from "zod";
import { cardSchema } from "./giant-cards";
export const largeCards = z.array(cardSchema).parse([
  {
    slug: "golden-retriever",
    name: "골든 리트리버",
    nameEn: "GOLDEN RETRIEVER",
    origin: "영국 · 스코틀랜드",
    originEn: "SCOTLAND",
    region: "스코틀랜드의 호숫가",
    flag: "uk",
    role: "조렵 · 회수견",
    tagline: "물과 들판에서 사냥감을 찾아오던 개.",
    historyTitle: "물가에서 시작된 협력",
    history: "스코틀랜드에서 사냥감을 찾아 사람에게 가져오는 일을 도왔어요.",
    height: "55–61",
    weight: "25–34",
    lifespan: "10–12",
    number: "01",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/golden-retriever-large-front-v1.webp",
      alt: "스코틀랜드의 호숫가 배경에 선 골든 리트리버 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/golden-retriever-large-back-v1.webp",
      alt: "스코틀랜드의 호숫가에서 지역의 성인과 함께 선 골든 리트리버. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "labrador-retriever",
    name: "래브라도 리트리버",
    nameEn: "LABRADOR RETRIEVER",
    origin: "캐나다 기원 · 영국 정립",
    originEn: "CANADA · UNITED KINGDOM",
    region: "뉴펀들랜드의 어촌",
    flag: "uk",
    role: "수중 작업 · 회수견",
    tagline: "차가운 바다에서 사람의 일을 돕던 개.",
    historyTitle: "어촌에서 들판으로",
    history:
      "뉴펀들랜드의 물가 작업견을 바탕으로 영국에서 회수견으로 발전했어요.",
    height: "55–62",
    weight: "25–36",
    lifespan: "11–13",
    number: "02",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/labrador-retriever-large-front-v1.webp",
      alt: "뉴펀들랜드의 어촌 배경에 선 래브라도 리트리버 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/labrador-retriever-large-back-v1.webp",
      alt: "뉴펀들랜드의 어촌에서 지역의 성인과 함께 선 래브라도 리트리버. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1855,
    },
  },
  {
    slug: "samoyed",
    name: "사모예드",
    nameEn: "SAMOYED",
    origin: "러시아 북부 · 시베리아",
    originEn: "NORTHERN RUSSIA · SIBERIA",
    region: "북부 시베리아의 생활 터전",
    flag: "russia",
    role: "순록 돌봄 · 썰매견",
    tagline: "눈밭에서 사람과 함께 일하던 개.",
    historyTitle: "추운 땅에서 나눈 일상",
    history:
      "시베리아의 유목민 곁에서 순록을 돌보고 썰매를 끌며 생활을 도왔어요.",
    height: "48–60",
    weight: "16–29",
    lifespan: "12–14",
    number: "03",
    edition: "HERITAGE EDITION",
    theme: "alpine",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/samoyed-large-front-v1.webp",
      alt: "북부 시베리아의 생활 터전 배경에 선 사모예드 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/samoyed-large-back-v1.webp",
      alt: "북부 시베리아의 생활 터전에서 지역의 성인과 함께 선 사모예드. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1478,
    },
  },
  {
    slug: "siberian-husky",
    name: "시베리안 허스키",
    nameEn: "SIBERIAN HUSKY",
    origin: "시베리아 기원 · 미국 정립",
    originEn: "SIBERIA · UNITED STATES",
    region: "시베리아 북동부의 설원",
    flag: "usa",
    role: "장거리 · 썰매견",
    tagline: "가벼운 짐을 싣고 먼 눈길을 달리던 개.",
    historyTitle: "함께 달려 길을 잇다",
    history:
      "시베리아의 축치인 곁에서 썰매를 끌던 개들이 미국에서 품종으로 정립됐어요.",
    height: "51–60",
    weight: "16–27",
    lifespan: "12–14",
    number: "04",
    edition: "HERITAGE EDITION",
    theme: "alpine",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/siberian-husky-large-front-v1.webp",
      alt: "시베리아 북동부의 설원 배경에 선 시베리안 허스키 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/siberian-husky-large-back-v1.webp",
      alt: "시베리아 북동부의 설원에서 지역의 성인과 함께 선 시베리안 허스키. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1500,
    },
  },
  {
    slug: "german-shepherd-dog",
    name: "저먼 셰퍼드 독",
    nameEn: "GERMAN SHEPHERD DOG",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일의 양 목초지",
    flag: "germany",
    role: "목양 · 작업견",
    tagline: "양 떼를 돌보며 사람의 신호를 읽던 개.",
    historyTitle: "목초지에서 시작된 동료",
    history:
      "독일의 목양견들을 바탕으로 발전했고, 이후 여러 작업을 함께하게 됐어요.",
    height: "56–66",
    weight: "23–41",
    lifespan: "12–14",
    number: "05",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/german-shepherd-dog-large-front-v1.webp",
      alt: "독일의 양 목초지 배경에 선 저먼 셰퍼드 독 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/german-shepherd-dog-large-back-v1.webp",
      alt: "독일의 양 목초지에서 지역의 성인과 함께 선 저먼 셰퍼드 독. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "dobermann",
    name: "도베르만",
    nameEn: "DOBERMANN",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일 튀링겐의 마을 길",
    flag: "germany",
    role: "호위 · 경비견",
    tagline: "사람 곁에서 길을 함께 지키던 개.",
    historyTitle: "곁을 지키기 위해",
    history: "19세기 독일에서 사람을 보호하고 경비하는 일을 위해 길러졌어요.",
    height: "61–71",
    weight: "27–45",
    lifespan: "10–12",
    number: "06",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/dobermann-large-front-v1.webp",
      alt: "독일 튀링겐의 마을 길 배경에 선 도베르만 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/dobermann-large-back-v1.webp",
      alt: "독일 튀링겐의 마을 길에서 지역의 성인과 함께 선 도베르만. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1470,
    },
  },
  {
    slug: "rottweiler",
    name: "롯트와일러",
    nameEn: "ROTTWEILER",
    origin: "독일",
    originEn: "GERMANY",
    region: "독일 남부의 가축 시장",
    flag: "germany",
    role: "가축 몰이 · 경비견",
    tagline: "소 떼를 이끌고 물건을 지키던 개.",
    historyTitle: "시장을 오가던 일꾼",
    history:
      "독일 로트바일 지역에서 소를 몰고 주인의 물건을 지키는 일을 도왔어요.",
    height: "56–69",
    weight: "36–61",
    lifespan: "9–10",
    number: "07",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/rottweiler-large-front-v1.webp",
      alt: "독일 남부의 가축 시장 배경에 선 롯트와일러 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/rottweiler-large-back-v1.webp",
      alt: "독일 남부의 가축 시장에서 지역의 성인과 함께 선 롯트와일러. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1477,
    },
  },
  {
    slug: "dalmatian",
    name: "달마시안",
    nameEn: "DALMATIAN",
    origin: "크로아티아 · 달마티아",
    originEn: "CROATIA · DALMATIA",
    region: "달마티아의 시골길",
    flag: "croatia",
    role: "마차 동행견",
    tagline: "말과 마차 곁에서 길을 달리던 개.",
    historyTitle: "마차 옆의 점박이 동료",
    history: "마차와 함께 달리며 말과 사람 곁을 지키는 역할로 알려졌어요.",
    height: "48–61",
    weight: "20–32",
    lifespan: "11–13",
    number: "08",
    edition: "HERITAGE EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/dalmatian-large-front-v1.webp",
      alt: "달마티아의 시골길 배경에 선 달마시안 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/dalmatian-large-back-v1.webp",
      alt: "달마티아의 시골길에서 지역의 성인과 함께 선 달마시안. 체구 비교를 위한 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
]);
