import { z } from "zod";
import { cardSchema } from "./giant-cards";

export const mediumCards = z.array(cardSchema).parse([
  {
    slug: "korea-jindo-dog",
    name: "진돗개",
    nameEn: "KOREA JINDO DOG",
    origin: "대한민국 · 진도",
    originEn: "KOREA · JINDO",
    region: "진도의 돌담과 바닷길",
    flag: "korea",
    role: "사냥 · 경계견",
    tagline: "진도의 산과 마을을 누비던 개.",
    historyTitle: "섬에서 함께 살아온 사냥 친구",
    history: "진도에서 사람과 함께 사냥하고 집 주변을 살피던 개예요.",
    height: "45–55",
    weight: "15–23",
    lifespan: "14–15",
    number: "01",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/korea-jindo-dog-medium-front-v1.webp",
      alt: "진도의 돌담과 바닷길 배경에 선 진돗개 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/korea-jindo-dog-medium-back-v1.webp",
      alt: "대한민국 · 진도의 성인과 같은 바닥에 나란히 선 진돗개. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "shiba",
    name: "시바견",
    nameEn: "SHIBA INU",
    origin: "일본",
    originEn: "JAPAN",
    region: "일본의 산길과 숲",
    flag: "japan",
    role: "산지 · 사냥견",
    tagline: "일본의 산길에서 작은 사냥감을 찾던 개.",
    historyTitle: "산길을 누비던 작은 사냥꾼",
    history: "일본 산지에서 새와 작은 동물을 찾는 사냥을 도왔어요.",
    height: "34–42",
    weight: "8–10",
    lifespan: "13–16",
    number: "02",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/shiba-medium-front-v1.webp",
      alt: "일본의 산길과 숲 배경에 선 시바견 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/shiba-medium-back-v1.webp",
      alt: "일본의 성인과 같은 바닥에 나란히 선 시바견. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
  },
  {
    slug: "welsh-corgi-pembroke",
    name: "웰시 코기 펨브로크",
    nameEn: "PEMBROKE WELSH CORGI",
    origin: "영국 · 웨일스",
    originEn: "WALES · UNITED KINGDOM",
    region: "웨일스의 목장",
    flag: "uk",
    role: "목축 · 소몰이견",
    tagline: "짧은 다리로 소 떼의 길을 이끌던 개.",
    historyTitle: "낮은 키로 소 떼를 움직이다",
    history: "웨일스 농장에서 소 떼가 이동하도록 돕던 목축견이에요.",
    height: "25–30",
    weight: "9–12",
    lifespan: "12–13",
    number: "03",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/welsh-corgi-pembroke-medium-front-v1.webp",
      alt: "웨일스의 목장 배경에 선 웰시 코기 펨브로크 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/welsh-corgi-pembroke-medium-back-v1.webp",
      alt: "영국 · 웨일스의 성인과 같은 바닥에 나란히 선 웰시 코기 펨브로크. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1478,
    },
  },
  {
    slug: "beagle",
    name: "비글",
    nameEn: "BEAGLE",
    origin: "영국",
    originEn: "UNITED KINGDOM",
    region: "영국의 들판과 오솔길",
    flag: "uk",
    role: "후각 · 사냥견",
    tagline: "냄새를 따라 들판의 길을 찾던 개.",
    historyTitle: "코끝으로 길을 읽는 친구",
    history: "영국에서 무리와 함께 냄새를 따라 토끼를 찾던 사냥개예요.",
    height: "33–40",
    weight: "9–14",
    lifespan: "10–15",
    number: "04",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/beagle-medium-front-v1.webp",
      alt: "영국의 들판과 오솔길 배경에 선 비글 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/beagle-medium-back-v1.webp",
      alt: "영국의 성인과 같은 바닥에 나란히 선 비글. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1484,
    },
    backNote: "몸무게는 큰 체고 유형의 참고치예요. 개체마다 달라요.",
  },
  {
    slug: "border-collie",
    name: "보더콜리",
    nameEn: "BORDER COLLIE",
    origin: "영국 · 잉글랜드와 스코틀랜드 접경",
    originEn: "BRITISH BORDER COUNTRY",
    region: "영국 접경 지역의 양 목장",
    flag: "uk",
    role: "목양 · 작업견",
    tagline: "목자의 신호를 읽고 양 떼를 모으던 개.",
    historyTitle: "눈빛과 움직임으로 양 떼를 모으다",
    history: "영국 접경 지역에서 목자와 함께 양 떼를 모으고 이끌었어요.",
    height: "46–56",
    weight: "14–25",
    lifespan: "12–15",
    number: "05",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/border-collie-medium-front-v1.webp",
      alt: "영국 접경 지역의 양 목장 배경에 선 보더콜리 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/border-collie-medium-back-v1.webp",
      alt: "영국 · 잉글랜드와 스코틀랜드 접경의 성인과 같은 바닥에 나란히 선 보더콜리. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1855,
    },
  },
  {
    slug: "english-cocker-spaniel",
    name: "잉글리시 코커 스패니얼",
    nameEn: "ENGLISH COCKER SPANIEL",
    origin: "영국",
    originEn: "UNITED KINGDOM",
    region: "영국 숲 가장자리",
    flag: "uk",
    role: "조렵 · 회수견",
    tagline: "덤불 속 새를 찾아 사람에게 알리던 개.",
    historyTitle: "덤불을 헤치던 사냥의 동료",
    history: "영국에서 덤불 속 새를 날아오르게 하고 회수하는 일을 도왔어요.",
    height: "38–43",
    weight: "12–15.5",
    lifespan: "12–14",
    number: "06",
    edition: "FIELD EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/english-cocker-spaniel-medium-front-v1.webp",
      alt: "영국 숲 가장자리 배경에 선 잉글리시 코커 스패니얼 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/english-cocker-spaniel-medium-back-v1.webp",
      alt: "영국의 성인과 같은 바닥에 나란히 선 잉글리시 코커 스패니얼. 체구를 비교하는 수채화 예시",
      width: 1060,
      height: 1486,
    },
  },
  {
    slug: "japanese-spitz",
    name: "재패니즈 스피츠",
    nameEn: "JAPANESE SPITZ",
    origin: "일본",
    originEn: "JAPAN",
    region: "일본의 주택 정원",
    flag: "japan",
    role: "반려견",
    tagline: "하얀 털을 두르고 사람 곁에 자리 잡은 개.",
    historyTitle: "사람 곁에서 이어진 하얀 발자국",
    history:
      "20세기 초 일본에서 흰 스피츠 계열의 개들을 바탕으로 발전한 반려견이에요.",
    height: "30–38",
    weight: "4.5–11",
    lifespan: "10–14",
    number: "07",
    edition: "GARDEN EDITION",
    theme: "woodland",
    heightLabel: "어깨 높이 · 약",
    front: {
      src: "/illustrations/card-studies/japanese-spitz-medium-front-v1.webp",
      alt: "일본 주택 정원에 선 재패니즈 스피츠 성견 전신 수채화",
      width: 1254,
      height: 1254,
    },
    back: {
      src: "/illustrations/card-studies/japanese-spitz-medium-back-v1.webp",
      alt: "일본인 여성 보호자와 같은 바닥에 선 작은 재패니즈 스피츠의 체구 비교 수채화",
      width: 1060,
      height: 1477,
    },
  },
]);
