import type { Breed } from "./schema";

const completedAt = "2026-08-20";

export const detailBatchB = [
  {
    slug: "german-shepherd-dog",
    contentStatus: "mvp-editorial-draft",
    nameKo: "저먼 셰퍼드 독",
    nameEn: "German Shepherd Dog",
    tagline: "민첩한 몸보다 먼저 봐야 할 것은, 사람과 과제를 맞춰 온 작업견의 집중력과 생활 리듬이에요.",
    palette: { primary: "#d8c3a8", secondary: "#e8e2d5", ink: "#3f3228" },
    illustration: "/illustrations/v2/german-shepherd-dog-card.webp",
    catalog: {
      group: "herding",
      discoveryTags: ["다목적 작업견", "사람과의 협업", "구조화된 활동"],
    },
    historyVisual: {
      src: "/illustrations/v3/german-shepherd-dog-history.webp",
      alt: "독일의 목초지에서 목동과 저먼 셰퍼드 독이 양 떼의 이동을 돕는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "독일",
      lineage: "독일 목양견 계통",
      originalRole: "목양견·다목적 작업견",
      size: "중대형 · 약 55~65cm, 22~40kg",
      lifespan: "10년 이상(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "가축의 움직임을 살피고 사람의 지시에 맞춰 오래 움직이는 한편, 여러 서비스 과제를 수행하도록 선발되어 왔습니다.",
      today: "그 배경은 보호자에게 주의를 기울이거나 배운 과제를 반복하는 모습으로 이어질 수 있지만, 모든 개체가 같은 집중력이나 경계 반응을 보이는 것은 아닙니다.",
      guardianContext: "운동량만 채우기보다 냄새 찾기, 기다리기, 방향 전환처럼 생각하며 협업하는 시간을 함께 마련하고 낯선 환경은 낮은 강도부터 익혀 주세요.",
    },
    story: {
      opening: "저먼 셰퍼드 독은 19세기 말 독일에서 여러 지역의 목양견을 바탕으로 체계적으로 정립됐습니다. 목표는 한 가지 외모보다 다양한 일을 안정적으로 수행할 수 있는 작업 능력이었습니다.",
      roleToHome: "오늘날에는 목양뿐 아니라 탐지, 구조, 안내와 같은 여러 역할로 알려져 있습니다. 가정에서도 사람의 신호를 읽고 할 일을 찾는 모습이 두드러질 수 있어, 산책과 교육을 분리하기보다 하나의 협업 시간으로 설계하는 편이 좋습니다.",
      reality: "영리하다는 평가는 저절로 편한 반려견이 된다는 뜻이 아닙니다. 충분한 휴식, 예측 가능한 규칙, 단계적인 사회화와 큰 체격을 감당할 생활 동선까지 함께 준비해야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "지속적으로 움직이며 과제를 수행해 온 배경을 고려해 규칙적인 신체 활동이 필요해요." },
      mentalStimulation: { label: "높은 편", note: "냄새 찾기와 신호 구분처럼 사람과 함께 해결하는 과제가 잘 어울릴 수 있어요." },
      independence: { label: "중간", note: "스스로 상황을 살피는 면과 사람의 지시에 협력하는 면이 함께 나타날 수 있어요." },
      socialConnection: { label: "높은 편", note: "보호자와의 상호작용을 일과처럼 받아들이는 개체가 많지만 경험에 따라 차이가 있어요." },
      alerting: { label: "높은 편", note: "주변 변화와 접근을 빠르게 알아차릴 수 있어 소리와 방문객 적응을 일찍 시작하는 편이 좋아요." },
      grooming: { label: "중간", note: "속털이 있는 이중모라 평소 빗질과 털갈이 시기의 집중 관리가 필요해요." },
    },
    careNotes: [
      "성장기에는 미끄러운 바닥과 무리한 반복 점프를 줄이고, 체형과 근육 상태에 맞는 운동 강도를 수의사와 상의하세요.",
      "경계 행동을 품종의 당연한 성격으로 넘기지 말고 거리 확보와 보상 기반의 단계적 적응으로 관리하세요.",
      "오래 움직이는 시간만큼 자극 없이 편안히 쉬는 연습도 생활 계획에 포함하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 큰 체격의 성장과 관절·보행 상태, 피부나 소화의 변화는 개별 검진으로 확인해야 하며 품종 정보만으로 질환을 예측하거나 진단하지 않습니다.",
    daySnapshot: [
      { time: "아침", title: "리듬 있는 산책", description: "속도 변화와 냄새 탐색을 섞어 몸과 머리를 함께 써요." },
      { time: "낮", title: "짧은 협업 과제", description: "찾기와 기다리기를 짧게 반복한 뒤 충분히 쉬어요." },
      { time: "저녁", title: "주변 자극 정리", description: "사람과 개가 많은 곳에서는 거리를 조절하며 차분한 반응을 연습해요." },
    ],
    related: [
      { slug: "border-collie", reason: "협업형 작업견이라는 공통점과 하루 과제를 구성하는 방식의 차이를 비교해 보세요." },
      { slug: "korea-jindo-dog", reason: "중형 이상의 체격과 경계 반응을 보호자 협업과 독립성이라는 서로 다른 관점에서 볼 수 있어요." },
    ],
    sources: [
      { title: "FCI Standard No. 166: German Shepherd Dog", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/166g01-en.pdf", checkedAt: completedAt },
      { title: "German Shepherd Dog", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/german-shepherd-dog/", checkedAt: completedAt },
      { title: "German Shepherd Dog History: From Sheep Herding Dog to Popular Companion", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/german-shepherd-dog-history/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "korea-jindo-dog",
    contentStatus: "mvp-editorial-draft",
    nameKo: "진돗개",
    nameEn: "Korea Jindo Dog",
    tagline: "진도의 섬 환경과 사냥의 역사를 지녔지만, 오늘의 성격은 혈통 한 줄이 아니라 개체의 경험까지 함께 봐야 해요.",
    palette: { primary: "#ded7bd", secondary: "#ebe2cf", ink: "#3d3a2d" },
    illustration: "/illustrations/v2/korea-jindo-dog-card.webp",
    catalog: {
      group: "spitz-primitive",
      discoveryTags: ["한국 토종견", "사냥견의 배경", "개체별 관계 형성"],
    },
    historyVisual: {
      src: "/illustrations/v3/korea-jindo-dog-history.webp",
      alt: "진도의 돌담과 들길에서 사람과 진돗개가 함께 이동하는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "대한민국 진도",
      lineage: "아시아 스피츠 및 원시견 계통",
      originalRole: "사냥견",
      size: "중형 · 약 45~55cm, 15~23kg",
      lifespan: "공식 표준에 수명 범위 없음 · 편집 검토 중",
    },
    behaviorClues: {
      originalRole: "진도의 생활 환경에서 사람과 이동하고 주변을 살피며 사냥과 경계를 도왔던 역사로 소개됩니다. 다만 정확한 고대 기원에는 문헌 기록이 부족합니다.",
      today: "움직이는 대상을 유심히 보거나 낯선 상황에서 거리를 두고 확인하는 반응으로 나타날 수 있지만, 품종만으로 애착 대상이나 다른 동물에 대한 반응을 단정할 수 없습니다.",
      guardianContext: "충성심 같은 미담보다 실제 개체의 회복 속도, 자원 지키기, 접촉 선호와 다른 동물에 대한 반응을 관찰하고 안전한 거리에서 선택권을 주세요.",
    },
    story: {
      opening: "진돗개의 먼 기원을 확정할 문헌은 충분하지 않지만, 진도에서 오랜 기간 보존되어 온 한국의 대표적인 토종견이라는 점은 여러 공식 자료가 함께 전합니다.",
      roleToHome: "사냥과 경계의 역사에서는 주변을 세밀하게 확인하고 스스로 판단해야 하는 순간이 많았습니다. 가정에서는 이것이 낯선 자극을 곧바로 받아들이지 않거나 산책 중 특정 움직임에 집중하는 모습으로 보일 수 있습니다.",
      reality: "‘한 사람만 따른다’거나 ‘다른 동물을 싫어한다’는 식의 문장은 개별 반응을 가립니다. 어린 시기의 경험, 현재 환경과 학습 이력을 함께 확인하고 문턱 낮은 사회화와 안전 관리를 설계해야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "주변을 탐색하며 충분히 이동할 수 있는 규칙적인 산책과 활동이 필요해요." },
      mentalStimulation: { label: "중간", note: "냄새 추적과 선택형 탐색처럼 스스로 확인할 수 있는 과제를 제공할 수 있어요." },
      independence: { label: "높은 편", note: "사람을 좋아하는 정도와 별개로 스스로 거리를 조절하고 판단하려는 모습이 나타날 수 있어요." },
      socialConnection: { label: "개체별 확인 필요", note: "가족과 낯선 사람, 다른 동물에 대한 반응은 초기 경험과 개체차를 직접 확인해야 해요." },
      alerting: { label: "높은 편", note: "영역 주변의 변화와 접근에 빠르게 주의를 기울일 수 있어 관리 계획이 중요해요." },
      grooming: { label: "중간", note: "촘촘한 이중모는 평소 빗질과 계절성 털갈이 관리를 요구해요." },
    },
    careNotes: [
      "산책 중 작은 동물이나 빠르게 움직이는 대상에 대한 반응을 먼저 확인하고 리드와 출입문을 이중으로 관리하세요.",
      "억지로 만지거나 인사시키기보다 개가 거리를 선택하고 다시 접근할 시간을 주는 방식으로 신뢰를 쌓으세요.",
      "마당 생활만으로 필요한 탐색과 사회 경험이 채워지지 않으므로 사람과 함께하는 산책과 휴식을 마련하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 토종견이라는 이유로 건강을 일반화하지 않으며 피부·귀·치아·관절과 체중은 정기 검진에서 개별적으로 확인하세요.",
    daySnapshot: [
      { time: "아침", title: "냄새로 길 읽기", description: "한적한 길에서 충분히 냄새를 맡고 선택하며 걸어요." },
      { time: "낮", title: "혼자 쉬는 자리", description: "방해받지 않는 휴식 공간과 예측 가능한 일과를 마련해요." },
      { time: "저녁", title: "거리 두고 적응", description: "낯선 사람이나 동물은 바로 만나기보다 편안한 거리에서 관찰해요." },
    ],
    related: [
      { slug: "japanese-spitz", reason: "같은 스피츠형 외모 안에서도 역사적 역할과 낯선 자극을 다루는 맥락이 어떻게 다른지 볼 수 있어요." },
      { slug: "basenji", reason: "서로 다른 지역의 사냥 배경이 독립적인 탐색과 생활 관리에 어떻게 이어지는지 비교해 보세요." },
    ],
    sources: [
      { title: "FCI Standard No. 334: Korea Jindo Dog", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/334g05-en.pdf", checkedAt: completedAt },
      { title: "한국진도견", organization: "한국애견연맹", url: "https://www.thekkf.or.kr/new_home/03_kkf_service/03_approval_3.php?gid=5&idx=70", checkedAt: completedAt },
      { title: "Korean Jindo Dog", organization: "American Kennel Club", url: "https://www.akc.org/dog-breeds/korean-jindo-dog/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "siberian-husky",
    contentStatus: "mvp-editorial-draft",
    nameKo: "시베리안 허스키",
    nameEn: "Siberian Husky",
    tagline: "눈빛보다 먼저 기억할 것은, 무리를 이루어 먼 거리를 이동해 온 썰매견의 지구력과 더위 관리예요.",
    palette: { primary: "#cfdce0", secondary: "#e5edf0", ink: "#263b43" },
    illustration: "/illustrations/v2/siberian-husky-card.webp",
    catalog: {
      group: "northern-working",
      discoveryTags: ["북방 썰매견", "지구력 있는 이동", "더위와 이중모 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/siberian-husky-history.webp",
      alt: "시베리아 북동부의 설원에서 여러 마리의 썰매견이 사람과 이동하는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "FCI 표준상 기원국은 미국 · 역사적 뿌리는 시베리아 북동부",
      lineage: "북방 썰매견 계통",
      originalRole: "썰매견",
      size: "중형 · 약 50.5~60cm, 15.5~28kg",
      lifespan: "10년 이상(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "여러 마리가 하네스를 착용하고 함께 썰매를 끌며 비교적 가벼운 짐을 먼 거리까지 옮기는 역할에서 속도, 균형과 지구력이 중요했습니다.",
      today: "지속적으로 이동하려는 욕구와 다른 개와 보조를 맞추는 모습으로 이어질 수 있지만, 사회성이나 탈출 행동을 품종 이름만으로 예측해서는 안 됩니다.",
      guardianContext: "짧고 격한 운동만 반복하기보다 기온을 확인한 긴 호흡의 걷기와 탐색을 제공하고, 문·울타리·리드의 안전성을 일상적으로 점검하세요.",
    },
    story: {
      opening: "시베리안 허스키의 뿌리는 시베리아 북동부에서 사람과 함께 이동하던 썰매견에 닿아 있습니다. 20세기 초 미국으로 전해져 썰매 경주와 장거리 운송에서 알려졌으며, 오늘날 국제 표준은 미국을 기원국으로 기록합니다.",
      roleToHome: "먼 거리를 효율적으로 이동하던 몸은 산책 한 번의 속도보다 매일 이어지는 활동 리듬을 요구합니다. 무리 속에서 움직이던 경험은 다른 개나 사람에 대한 관심으로 보일 수 있으나 실제 반응은 사회화 이력에 좌우됩니다.",
      reality: "푸른 눈이나 북방 외모만으로 선택하기에는 털갈이, 더위, 이동 욕구와 안전 관리의 비중이 큽니다. 시원한 휴식 환경과 충분한 시간, 단단한 출입 관리가 가능한지 먼저 확인해야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "먼 거리를 이동하던 썰매견 배경을 고려해 꾸준하고 충분한 활동 계획이 필요해요." },
      mentalStimulation: { label: "중간", note: "경로 선택과 냄새 탐색, 함께 움직이는 활동이 단순 반복 운동보다 도움이 될 수 있어요." },
      independence: { label: "높은 편", note: "사람과 협력하면서도 이동 중 스스로 판단하는 모습이 나타날 수 있어요." },
      socialConnection: { label: "개체별 확인 필요", note: "무리 작업의 역사만으로 현재 개체의 사람·개 사회성을 보장할 수는 없어요." },
      alerting: { label: "개체별 확인 필요", note: "낯선 자극에 대한 소리와 경계 반응은 생활 경험에 따라 다르게 나타나요." },
      grooming: { label: "높은 편", note: "촘촘한 이중모와 큰 털갈이 폭을 감당할 정기적인 빗질이 필요해요." },
    },
    careNotes: [
      "더운 날에는 시간대와 노면 온도, 습도를 확인하고 활동 강도를 낮추며 시원한 물과 휴식 공간을 제공하세요.",
      "달리기 욕구를 고려해 현관·문·울타리와 리드 장비를 반복 점검하고 오프리드 활동은 안전하게 통제된 공간에서만 진행하세요.",
      "이중모를 짧게 미는 방식보다 피부와 털 상태에 맞는 빗질·건조 방법을 전문가와 상의하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 눈·피부·관절 상태는 품종명만으로 판단하지 말고 정기 검진과 보호자 관찰로 확인하며, 활동 뒤 회복이 평소와 다르면 수의사와 상의하세요.",
    daySnapshot: [
      { time: "아침", title: "선선할 때 길게", description: "기온이 낮을 때 냄새 탐색을 섞은 충분한 산책을 해요." },
      { time: "낮", title: "시원한 휴식", description: "실내 온도와 물을 확인하고 흥분을 낮추며 쉬어요." },
      { time: "저녁", title: "함께 움직이기", description: "당기기보다 보호자와 속도를 맞추는 짧은 과제를 연습해요." },
    ],
    related: [
      { slug: "samoyed", reason: "북방 작업견과 이중모라는 공통점 안에서 역사적 역할과 협업 방식의 차이를 볼 수 있어요." },
      { slug: "german-shepherd-dog", reason: "활동량이 높은 작업견이라도 필요한 과제가 지구력 중심인지 지시 협업 중심인지 비교할 수 있어요." },
    ],
    sources: [
      { title: "FCI Standard No. 270: Siberian Husky", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/270g05-en.pdf", checkedAt: completedAt },
      { title: "Siberian Husky", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/working/siberian-husky/", checkedAt: completedAt },
      { title: "Siberian Husky History: From Arctic Protector to Active Companion", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/siberian-husky-history/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "whippet",
    contentStatus: "mvp-editorial-draft",
    nameKo: "휘펫",
    nameEn: "Whippet",
    tagline: "가느다란 실루엣 안에는 순간적인 질주와 포근한 휴식을 번갈아 필요로 하는 사이트하운드의 리듬이 있어요.",
    palette: { primary: "#d9cec0", secondary: "#eee9df", ink: "#413832" },
    illustration: "/illustrations/v2/whippet-card.webp",
    catalog: {
      group: "sighthound",
      discoveryTags: ["시각 하운드", "순간적인 질주", "얇은 피모 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/whippet-history.webp",
      alt: "영국의 열린 들판에서 휘핏이 멀리 움직이는 대상을 바라보는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "영국",
      lineage: "중소형 시각 하운드 계통",
      originalRole: "시각 하운드",
      size: "중형 · 약 44~51cm",
      lifespan: "12년 이상(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "탁 트인 곳에서 눈으로 움직이는 대상을 포착하고 짧은 시간 빠르게 추적하는 데 알맞은 몸과 움직임을 지녔습니다.",
      today: "산책 중 작은 동물이나 빠른 움직임에 시선이 고정될 수 있지만, 실내에서도 늘 뛰어야 한다는 뜻은 아닙니다. 질주 뒤 조용히 쉬는 리듬도 중요합니다.",
      guardianContext: "안전하게 달릴 수 있는 통제된 공간과 일상 산책을 구분하고, 얇은 피모와 낮은 체지방을 고려해 추위·딱딱한 바닥·찰과상을 세심하게 관리하세요.",
    },
    story: {
      opening: "휘핏은 속도를 위해 군더더기 없이 다듬어진 영국의 시각 하운드입니다. 우아한 허리선과 긴 다리는 움직이는 대상을 눈으로 찾고 빠르게 가속하는 역할을 보여 줍니다.",
      roleToHome: "짧고 강한 질주 능력과 집 안에서의 차분한 휴식은 함께 존재할 수 있습니다. 다만 작은 움직임을 뒤쫓는 반응은 도심 산책과 다른 동물과의 생활에서 별도의 안전 계획을 요구합니다.",
      reality: "조용해 보인다는 인상만으로 운동과 안전 관리를 가볍게 볼 수 없습니다. 편안한 침구, 기온에 맞는 보호, 회수 신호와 리드 관리까지 갖춰져야 휘핏의 하루가 안정됩니다.",
    },
    tendencies: {
      activity: { label: "중간", note: "매일의 산책에 더해 안전하게 속도를 낼 기회와 충분한 회복 시간이 필요해요." },
      mentalStimulation: { label: "중간", note: "시각 탐색과 냄새 찾기를 짧게 섞되 과한 반복 훈련은 피하는 편이 좋아요." },
      independence: { label: "중간", note: "시각 자극에 몰입하는 순간에는 보호자 신호보다 추적이 앞설 수 있어요." },
      socialConnection: { label: "개체별 확인 필요", note: "사람 곁에서 쉬는 선호와 낯선 대상에 대한 반응은 개체마다 직접 확인해야 해요." },
      alerting: { label: "낮은 편", note: "경비 목적의 지속적인 짖음보다 움직임을 눈으로 쫓는 반응이 더 중요할 수 있어요." },
      grooming: { label: "낮은 편", note: "짧은 털의 빗질 부담은 적지만 피부와 추위 관리는 별도로 필요해요." },
    },
    careNotes: [
      "빠른 추적 반응을 고려해 일반 산책에서는 리드를 유지하고, 질주는 울타리가 완전히 확보된 공간에서만 허용하세요.",
      "얇은 피모와 체형에 맞춰 추운 날의 보온, 미끄럽지 않은 바닥과 푹신한 휴식 자리를 준비하세요.",
      "작은 동물과 함께 살 계획이라면 품종 설명이 아니라 실제 개체의 반응을 전문가와 평가하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 보행·피부와 운동 뒤 회복 변화는 정기 검진에서 개별적으로 확인하고, 검사나 마취 전에는 병력을 담당 수의사에게 정확히 알려주세요.",
    daySnapshot: [
      { time: "아침", title: "가볍게 몸 풀기", description: "냄새를 맡으며 걷고 관절과 근육을 천천히 깨워요." },
      { time: "낮", title: "푹신한 휴식", description: "찬 바닥을 피한 조용한 자리에서 충분히 쉬어요." },
      { time: "저녁", title: "안전한 속도", description: "통제된 공간에서 짧게 달린 뒤 천천히 회복해요." },
    ],
    related: [
      { slug: "greyhound", reason: "같은 시각 하운드의 질주와 휴식 리듬을 체격 차이와 함께 살펴보기 좋아요." },
      { slug: "basenji", reason: "짧은 피모와 사냥 배경은 닮았지만 자극을 추적하고 표현하는 방식은 다를 수 있어요." },
    ],
    sources: [
      { title: "FCI Standard No. 162: Whippet", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/162g10-en.pdf", checkedAt: completedAt },
      { title: "Whippet", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/whippet/", checkedAt: completedAt },
      { title: "Breed Weight Chart", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/nutrition/breed-weight-chart/", checkedAt: completedAt },
      { title: "Whippet History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/whippet-history/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "pyrenean-mountain-dog",
    contentStatus: "mvp-editorial-draft",
    nameKo: "그레이트 피레니즈",
    nameEn: "Pyrenean Mountain Dog",
    tagline: "거대한 흰 몸보다 먼저 봐야 할 것은, 산에서 무리를 지키며 스스로 판단해 온 가축보호견의 생활 조건이에요.",
    palette: { primary: "#dbe2dc", secondary: "#eee9dc", ink: "#33423d" },
    illustration: "/illustrations/v2/pyrenean-mountain-dog-card.webp",
    catalog: {
      group: "guardian-working",
      discoveryTags: ["가축보호견", "독립적인 판단", "초대형 생활 공간"],
    },
    historyVisual: {
      src: "/illustrations/v3/pyrenean-mountain-dog-history.webp",
      alt: "피레네산맥의 목초지에서 그레이트 피레니즈가 양 떼 주변을 지키는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "프랑스 피레네 지역",
      lineage: "산악 가축보호견 계통",
      originalRole: "가축보호견",
      size: "초대형 · 약 65~80cm",
      lifespan: "10년 미만(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "넓은 산지에서 사람의 즉각적인 지시 없이도 가축 곁을 지키고 위험을 판단하며 접근을 막는 역할을 해 왔습니다.",
      today: "집과 가족 주변의 소리나 접근을 오래 살피고 스스로 결정을 내리는 모습으로 나타날 수 있지만, 모든 개체의 경계 강도가 같지는 않습니다.",
      guardianContext: "경계 반응을 힘으로 억누르기보다 무엇에 주의를 두는지 기록하고 충분한 거리, 보호자에게 돌아보기와 방향 전환, 현관 대기를 보상으로 설계해야 합니다.",
    },
    story: {
      opening: "그레이트 피레니즈는 피레네산맥에서 가축 무리를 지키던 대형 보호견입니다. 오래전부터 성과 목초지의 경비에 쓰였다는 기록이 남아 있고, 크기만큼 스스로 상황을 판단하는 능력이 중요했습니다.",
      roleToHome: "오늘의 가정에서는 그 독립적인 판단이 낯선 사람이나 개, 소리를 오래 확인하는 행동으로 이어질 수 있습니다. 경계하지 않아도 되는 거리와 환경을 만들고 보호자에게 돌아오는 선택을 보상으로 알려야 합니다.",
      reality: "순한 흰 대형견이라는 인상만으로 선택하기에는, 큰 몸이 움직인 뒤 힘으로 제지하기 어려운 통제 현실과 공간·이동·피모 관리 부담이 큽니다. 성견의 실제 크기로 산책과 출입 동선을 미리 계산해야 합니다.",
    },
    tendencies: {
      activity: { label: "중간", note: "격한 속도 운동보다 넓은 범위를 차분히 이동하고 살피는 활동이 어울릴 수 있어요." },
      mentalStimulation: { label: "중간", note: "주변을 관찰하고 냄새로 확인하는 자율적 탐색 시간이 필요해요." },
      independence: { label: "높은 편", note: "사람의 즉각적인 지시 없이 상황을 판단하던 작업 배경이 있어요." },
      socialConnection: { label: "개체별 확인 필요", note: "보호 대상과의 애착, 낯선 사람과 동물에 대한 반응은 실제 개체를 확인해야 해요." },
      alerting: { label: "높은 편", note: "영역 주변의 소리와 접근을 알리는 행동이 생활 갈등으로 이어질 수 있어요." },
      grooming: { label: "높은 편", note: "풍성한 이중모와 큰 체표 면적 때문에 빗질·건조에 상당한 시간이 들어요." },
    },
    careNotes: [
      "성견의 크기로 현관, 엘리베이터, 차량과 동물병원 이동 경로를 미리 점검하세요.",
      "낯선 사람이나 개, 소리에 대한 반응을 기록하고 충분한 거리에서 돌아보기와 방향 전환을 보상으로 연습하세요.",
      "성장기 체중과 보행, 관절 부담을 확인하며 운동과 급여 계획을 수의사와 조정하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 성장 속도와 관절·보행, 체중은 개별 검진으로 확인하고 복부 팽창이나 급격한 컨디션 변화가 보이면 즉시 동물병원에 문의하세요.",
    daySnapshot: [
      { time: "아침", title: "천천히 영역 읽기", description: "서두르지 않고 주변 냄새와 변화를 확인하며 걸어요." },
      { time: "낮", title: "서늘한 휴식", description: "넓고 시원한 자리에서 관절을 편하게 두고 쉬어요." },
      { time: "저녁", title: "차분히 돌아오기", description: "자극과 거리를 두고 보호자에게 돌아와 방향을 바꾸는 연습을 해요." },
    ],
    related: [
      { slug: "samoyed", reason: "풍성한 흰 이중모는 닮았지만 가축 보호와 북방 협업이라는 역할의 차이가 커요." },
      { slug: "german-shepherd-dog", reason: "경계와 작업 능력이 사람의 지시 중심인지 독립적 판단 중심인지 비교할 수 있어요." },
    ],
    sources: [
      { title: "FCI Standard No. 137: Pyrenean Mountain Dog", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/137g02-en.pdf", checkedAt: completedAt },
      { title: "Pyrenean Mountain Dog", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/pastoral/pyrenean-mountain-dog/", checkedAt: completedAt },
      { title: "Official Standard of the Great Pyrenees", organization: "American Kennel Club", url: "https://images.akc.org/pdf/breeds/standards/GreatPyrenees.pdf", checkedAt: completedAt },
      { title: "Great Pyrenees History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/great-pyrenees-history/", checkedAt: "2026-08-29" },
      { title: "Is the Great Pyrenees a Good Fit for Your Lifestyle?", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/great-pyrenees-right-for-you/", checkedAt: "2026-09-01" },
      { title: "Humane Dog Training Position Statement", organization: "American Veterinary Society of Animal Behavior", url: "https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf", checkedAt: "2026-09-01" },
      { title: "Professional Dog Walkers’ Guidelines", organization: "RSPCA", url: "https://www.rspca.org.uk/webContent/staticImages/Downloads/DogWalkingGuide.pdf", checkedAt: "2026-09-01" },
    ],
  },
  {
    slug: "french-bulldog",
    contentStatus: "mvp-editorial-draft",
    nameKo: "프렌치 불도그",
    nameEn: "French Bulldog",
    tagline: "작고 친근한 인상만큼, 짧은 주둥이와 체형이 일상 속 호흡·더위·움직임에 주는 영향도 먼저 봐야 해요.",
    palette: { primary: "#d8c7b4", secondary: "#eadfce", ink: "#43362d" },
    illustration: "/illustrations/v2/french-bulldog-card.webp",
    catalog: {
      group: "companion",
      discoveryTags: ["도시형 반려견", "짧은 주둥이", "더위와 호흡 관찰"],
    },
    historyVisual: {
      src: "/illustrations/v3/french-bulldog-history.webp",
      alt: "19세기 파리의 거리에서 상인과 노동자 곁에 있는 작은 불도그를 그린 편집 수채화",
    },
    identity: {
      origin: "프랑스",
      lineage: "소형 불도그 계통",
      originalRole: "반려견",
      size: "소형 · 약 24~35cm, 8~14kg",
      lifespan: "10년 이상(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "조상인 영국 불도그 계통은 과거 투우 미끼 경기에 동원된 배경이 있어요. 현재의 프렌치 불도그는 그 관행이 금지된 뒤 소형 불도그가 프랑스로 건너가 반려견으로 정립된 견종이에요.",
      today: "사람과 가까운 곳에 머물고 짧은 놀이에 참여하는 모습이 나타날 수 있지만, 혼자 있는 어려움이나 다른 개에 대한 반응은 품종만으로 단정할 수 없습니다.",
      guardianContext: "성격 평가와 별개로 호흡 소리, 운동 뒤 회복, 수면 상태와 더위 반응을 세심하게 관찰하고 무리한 활동보다 짧고 자주 움직이는 일과를 구성하세요.",
    },
    story: {
      opening: "프렌치 불도그의 영국 불도그 조상은 소를 상대로 한 투우 미끼 경기에 동원된 계통과 연결됩니다. 1830년대 영국에서 이 관행이 금지된 뒤, 소형 불도그가 노팅엄의 레이스 노동자들과 프랑스로 건너가 19세기 파리에서 현재의 반려견으로 정립됐습니다.",
      roleToHome: "사람 가까이에 머물던 역사는 현대의 실내 생활과 연결되는 면이 있지만, 작은 체격이 곧 관리가 쉽다는 뜻은 아닙니다. 특히 짧은 얼굴 구조는 호흡과 체온 조절을 생활의 핵심 점검 항목으로 만듭니다.",
      reality: "귀여운 표정과 작은 몸만 보고 선택하기 전에 평소 호흡, 콧구멍의 개방성, 움직임과 회복, 피부 주름과 척추·보행 상태를 실제 개체와 수의 검진으로 확인해야 합니다.",
    },
    tendencies: {
      activity: { label: "중간", note: "긴 격한 운동보다 기온과 호흡 상태를 보며 짧고 규칙적으로 움직이는 편이 좋아요." },
      mentalStimulation: { label: "중간", note: "짧은 냄새 찾기와 차분한 상호작용으로 무리 없이 참여할 수 있어요." },
      independence: { label: "개체별 확인 필요", note: "사람 곁을 선호하는 정도와 혼자 쉬는 능력은 생활 경험에 따라 달라요." },
      socialConnection: { label: "높은 편", note: "반려견으로 자리 잡은 배경상 사람과 가까이 상호작용하는 개체가 많아요." },
      alerting: { label: "개체별 확인 필요", note: "방문객과 소리에 대한 짖음은 개체와 환경에 따라 직접 확인해야 해요." },
      grooming: { label: "중간", note: "짧은 털의 빗질과 별개로 피부 주름·귀·발과 건조 상태를 살펴야 해요." },
    },
    careNotes: [
      "더운 날이나 습도가 높은 날에는 야외 활동을 줄이고, 호흡이 평소와 다르거나 회복이 늦으면 즉시 쉬게 한 뒤 수의사에게 문의하세요.",
      "코골이와 큰 호흡음을 품종의 당연한 특징으로 넘기지 말고 수면과 운동 중 상태를 영상으로 기록해 진료에 활용하세요.",
      "미끄러운 바닥과 반복적인 높은 점프를 줄이고 체중·보행·척추 상태를 정기적으로 확인하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 단두형 구조와 관련된 호흡·눈·피부·척추 상태는 외모만으로 판단할 수 없으므로 입양 전 건강검진 기록과 개별 수의 상담을 우선하세요.",
    daySnapshot: [
      { time: "아침", title: "선선할 때 짧게", description: "호흡과 걸음 속도를 보며 천천히 산책해요." },
      { time: "낮", title: "호흡 편한 휴식", description: "서늘하고 통풍되는 곳에서 방해 없이 쉬어요." },
      { time: "저녁", title: "짧은 냄새 놀이", description: "흥분을 크게 올리지 않는 탐색으로 하루를 마무리해요." },
    ],
    related: [
      { slug: "maltese", reason: "도시의 소형 반려견이라는 공통점 안에서 피모와 건강 관리의 초점이 어떻게 다른지 볼 수 있어요." },
      { slug: "shih-tzu", reason: "짧은 얼굴을 가진 소형견이지만 피모, 움직임과 일상 관리의 차이를 비교할 수 있어요." },
    ],
    sources: [
      { title: "FCI Standard No. 101: French Bulldog", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/101g09-en.pdf", checkedAt: completedAt },
      { title: "French Bulldog", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/utility/french-bulldog/", checkedAt: completedAt },
      { title: "French Bulldog History: A Complicated Past From Brothels to Royals", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/breed-history-french-bulldog/", checkedAt: completedAt },
      { title: "Brachycephaly: health issues", organization: "Royal Veterinary College", url: "https://www.rvc.ac.uk/research/focus/brachycephaly/health-issues", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "basenji",
    contentStatus: "mvp-editorial-draft",
    nameKo: "바센지",
    nameEn: "Basenji",
    tagline: "‘짖지 않는 개’라는 한 문장보다, 중앙아프리카의 사냥견이 움직임과 소리를 표현하는 독특한 방식을 봐야 해요.",
    palette: { primary: "#d8bda6", secondary: "#eadfce", ink: "#44342b" },
    illustration: "/illustrations/v2/basenji-card.webp",
    catalog: {
      group: "spitz-primitive",
      discoveryTags: ["중앙아프리카 사냥견", "독립적인 탐색", "독특한 발성"],
    },
    historyVisual: {
      src: "/illustrations/v3/basenji-history.webp",
      alt: "중앙아프리카의 숲 가장자리에서 사냥꾼과 바센지가 길을 찾는 장면을 그린 편집 수채화",
    },
    identity: {
      origin: "중앙아프리카 · FCI 후원국 영국",
      lineage: "원시견형 사냥견 계통",
      originalRole: "사냥견",
      size: "중소형 · 약 40~43cm, 9.5~11kg",
      lifespan: "12년 이상(RKC 참고, 기관과 개체별 차이 있음)",
    },
    behaviorClues: {
      originalRole: "중앙아프리카에서 시각과 후각을 함께 사용해 사냥감을 찾고 사람의 사냥을 돕는 역할로 알려져 있습니다.",
      today: "주변 냄새와 움직임을 스스로 확인하고 빠르게 추적하려는 모습으로 이어질 수 있습니다. 일반적인 짖음이 적더라도 요들 같은 발성과 다른 소리를 낼 수 있습니다.",
      guardianContext: "‘조용하고 깨끗하다’는 별명만 믿기보다 탈출 경로, 작은 동물에 대한 반응, 반복 훈련을 받아들이는 방식과 혼자 쉬는 능력을 실제 개체에서 확인하세요.",
    },
    story: {
      opening: "바센지는 중앙아프리카에서 사람의 사냥을 도운 원시견형 견종입니다. 가볍고 긴 다리, 선 귀와 말린 꼬리는 주변을 빠르게 살피고 이동하는 몸의 역사를 보여 줍니다.",
      roleToHome: "‘짖지 않는 개’로 자주 소개되지만 소리를 내지 않는 것은 아닙니다. 일반적인 짖음 대신 요들처럼 들리는 소리를 비롯한 다양한 표현을 사용할 수 있고, 사냥 배경은 움직이는 대상에 대한 강한 관심으로 나타날 수 있습니다.",
      reality: "짧은 털과 작은 체격이 쉬운 생활을 보장하지 않습니다. 독립적인 선택을 존중하는 교육, 단단한 출입 관리, 추위에 대한 보호와 실제 개체의 사회 반응을 확인해야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "민첩하게 이동하고 탐색하던 사냥 배경을 고려해 충분한 활동이 필요해요." },
      mentalStimulation: { label: "높은 편", note: "냄새와 시각을 함께 쓰며 스스로 해결할 수 있는 탐색 과제를 제공할 수 있어요." },
      independence: { label: "높은 편", note: "반복적인 지시보다 상황을 확인하고 스스로 선택하려는 모습이 나타날 수 있어요." },
      socialConnection: { label: "개체별 확인 필요", note: "가족과 낯선 사람, 다른 동물에 대한 반응은 사회화 이력에 따라 달라요." },
      alerting: { label: "개체별 확인 필요", note: "전형적인 짖음의 빈도와 별개로 요들·낑낑거림 등 다양한 소리 표현이 가능해요." },
      grooming: { label: "낮은 편", note: "짧은 털의 빗질 부담은 비교적 적지만 피부와 추위는 살펴야 해요." },
    },
    careNotes: [
      "빠르게 움직이는 대상에 대한 반응과 탈출 가능성을 고려해 리드, 문과 울타리를 반복 점검하세요.",
      "같은 동작을 오래 반복하기보다 선택권이 있는 짧은 탐색과 보상 기반 교육으로 참여를 이끌어 주세요.",
      "짧은 피모를 고려해 추운 날에는 활동 시간과 보온을 조절하고 편안한 실내 휴식 자리를 마련하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 유전 질환 검사를 포함한 번식·입양 기록과 눈·신장·관절 등 개별 건강 상태를 수의사와 확인하고, 품종의 평균 정보로 진단하지 마세요.",
    daySnapshot: [
      { time: "아침", title: "탐색할 길 고르기", description: "안전한 범위에서 냄새와 경로를 스스로 선택하게 해요." },
      { time: "낮", title: "따뜻하게 쉬기", description: "추위를 피한 조용한 자리에서 방해 없이 쉬어요." },
      { time: "저녁", title: "짧은 문제 해결", description: "숨긴 먹이를 찾거나 다른 방법을 시도할 작은 과제를 줘요." },
    ],
    related: [
      { slug: "korea-jindo-dog", reason: "서로 다른 지역의 사냥견 배경이 독립성과 낯선 자극 반응에 어떻게 이어지는지 볼 수 있어요." },
      { slug: "whippet", reason: "사냥과 빠른 움직임이라는 공통점 안에서 시각·후각 사용과 실내 리듬의 차이를 비교해 보세요." },
    ],
    sources: [
      { title: "FCI Standard No. 43: Basenji", organization: "Fédération Cynologique Internationale", url: "https://www.fci.be/Nomenclature/Standards/043g05-en.pdf", checkedAt: completedAt },
      { title: "Basenji", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/hound/basenji/", checkedAt: completedAt },
      { title: "Basenji History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/basenji-history/", checkedAt: "2026-08-29" },
    ],
  },
] satisfies Breed[];
