import type { Breed } from "./schema";

const checkedAt = "2026-08-04";
type Level = Breed["tendencies"][keyof Breed["tendencies"]]["label"];
type DayStep = Breed["daySnapshot"][number];

type BatchGSeed = {
  slug: string; nameKo: string; nameEn: string; tagline: string;
  group: Breed["catalog"]["group"]; tags: [string, string, string]; colors: [string, string, string];
  origin: string; lineage: string; role: string; size: string; lifespan: string;
  originalRole: string; today: string; guardianContext: string;
  opening: string; roleToHome: string; reality: string;
  care: [string, string, string]; levels: [Level, Level, Level, Level, Level, Level];
  days: [DayStep, DayStep, DayStep]; related: [[string, string], [string, string]];
  fciUrl: string; akcUrl: string;
};

const seeds: BatchGSeed[] = [
  {
    slug: "australian-cattle-dog", nameKo: "오스트레일리안 캐틀 독", nameEn: "Australian Cattle Dog",
    tagline: "점박이 피모 아래에는 호주의 먼 거리를 이동하며 소의 방향을 바꾸던 단단한 작업견의 몸이 있어요.",
    group: "herding", tags: ["호주 소몰이견", "높은 지구력", "강한 작업 집중"], colors: ["#6f7f83", "#dde1d3", "#303333"],
    origin: "오스트레일리아", lineage: "호주에서 정립된 견고한 캐틀 독", role: "넓은 목장에서 소를 모으고 장거리 이동", size: "중형 · 약 43~51cm, 16~23kg", lifespan: "약 12~16년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "호주의 넓고 거친 목축지에서 소의 발굽 가까이 움직이며 무리를 통제하고 먼 거리를 이동시키도록 발달했습니다.",
    today: "빠르게 움직이는 발과 바퀴를 쫓거나 한 사람과 과제에 강하게 집중할 수 있지만 반응의 강도는 개체마다 달라요.",
    guardianContext: "반복 달리기만 시키지 말고 방향 전환·멈춤·냄새 탐색을 섞으며 사람과 동물을 몰거나 발뒤꿈치를 무는 행동을 예방하세요.",
    opening: "오스트레일리안 캐틀 독은 호주의 소 사육 산업과 함께 발달한 단단하고 민첩한 목양견입니다. 푸른색 또는 붉은색 점박이 이중모가 대표적입니다.",
    roleToHome: "독립적으로 소의 움직임을 읽고 보호자와 협력하던 배경은 높은 활동량과 빠른 판단, 과제 집중으로 이어질 수 있습니다.",
    reality: "중형 체격만 보고 생활 부담이 작다고 판단하기 어렵습니다. 매일 강도 있는 활동과 교육, 흥분 뒤 쉬는 연습이 필요해요.",
    care: ["긴 산책에 방향 전환과 냄새 과제를 함께 넣으세요.", "발이나 바퀴를 몰려는 행동은 거리와 대체 신호로 관리하세요.", "운동 뒤 발바닥과 관절, 체온과 회복 상태를 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "움직임과 신호", description: "충분히 걷고 방향·정지 신호를 맞춰요." }, { time: "낮", title: "완전한 회복", description: "흥분을 낮추고 방해 없이 쉬게 해요." }, { time: "저녁", title: "찾기 과제", description: "냄새와 문제 해결로 집중을 전환해요." }],
    related: [["australian-kelpie", "호주 목축 환경과 높은 지구력을 공유하지만 체형과 소·양 작업의 초점이 달라요."], ["border-collie", "강한 목양 집중을 공유하며 압박 방식과 일상 과제의 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/AUSTRALIAN-CATTLE-DOG-287.html", akcUrl: "https://www.akc.org/dog-breeds/australian-cattle-dog/",
  },
  {
    slug: "giant-schnauzer", nameKo: "자이언트 슈나우저", nameEn: "Giant Schnauzer",
    tagline: "큰 수염과 눈썹보다 먼저, 바이에른에서 소를 몰고 농장과 작업장을 지킨 강한 몸을 살펴보세요.",
    group: "guardian-working", tags: ["독일 대형 작업견", "소몰이와 경비", "높은 교육 책임"], colors: ["#4c4d4a", "#dce0d3", "#262827"],
    origin: "독일·바이에른", lineage: "가장 큰 슈나우저 품종", role: "소를 시장으로 이동시키고 농장·작업장을 경비", size: "대형 · 약 60~70cm, 25~43kg", lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 바이에른에서 농장의 소를 시장으로 몰고 가며 재산과 작업장을 지키는 크고 강한 작업견으로 발달했습니다.",
    today: "사람과 긴밀하게 과제를 수행하고 낯선 상황을 신중히 살피려는 모습이 나타날 수 있지만 경계와 사회성은 개체마다 달라요.",
    guardianContext: "성견의 힘을 다룰 보상 기반 교육과 안전 장비를 준비하고 낯선 사람·개와의 거리는 실제 반응에 맞춰 조절하세요.",
    opening: "자이언트 슈나우저는 단순히 미니어처 슈나우저를 크게 만든 견종이 아니라, 바이에른에서 별도로 발달한 대형 작업견입니다.",
    roleToHome: "소를 몰고 영역을 지키던 배경은 높은 활동과 협력 욕구, 주변 변화에 대한 경계로 이어질 수 있습니다.",
    reality: "큰 힘과 빠른 학습을 함께 다뤄야 하며 거친 이중모 관리도 필요합니다. 사회화·교육·운동 시간을 충분히 계산해야 해요.",
    care: ["힘으로 제압하지 말고 예측 가능한 규칙과 보상으로 교육하세요.", "낯선 대상과의 인사는 강요하지 말고 안전한 거리를 주세요.", "거친 이중모는 주기적으로 빗고 트리밍 계획을 세우세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "구조화된 긴 산책", description: "걷기와 기다리기, 냄새 찾기를 섞어요." }, { time: "낮", title: "차분한 관찰", description: "자극과 거리를 두고 편히 쉬게 해요." }, { time: "저녁", title: "협력과 털 관리", description: "짧은 과제 뒤 수염과 피모를 살펴요." }],
    related: [["miniature-schnauzer", "닮은 외형 뒤에 체격·힘과 원래 작업 규모가 크게 다르다는 점을 비교해 보세요."], ["rottweiler", "소몰이와 경비 배경을 공유하지만 체형과 피모·교육 부담이 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/GIANT-SCHNAUZER-181.html", akcUrl: "https://www.akc.org/dog-breeds/giant-schnauzer/",
  },
  {
    slug: "scottish-terrier", nameKo: "스코티시 테리어", nameEn: "Scottish Terrier",
    tagline: "짧은 다리와 단단한 실루엣에는 스코틀랜드의 거친 땅에서 굴과 바위틈을 살피던 끈기가 있어요.",
    group: "terrier", tags: ["스코틀랜드 테리어", "낮고 단단한 체형", "독립적인 탐색"], colors: ["#55534e", "#dde0d2", "#2b2a28"],
    origin: "영국·스코틀랜드", lineage: "스코틀랜드 저각 테리어", role: "굴과 바위틈의 여우·오소리와 해충 수색", size: "소형 · 약 25cm, 8~10kg", lifespan: "약 12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "스코틀랜드의 거친 지형에서 낮고 단단한 몸으로 굴과 바위틈을 조사하며 여우·오소리와 해충을 찾는 역할을 했습니다.",
    today: "작은 구멍과 냄새를 끈기 있게 조사하거나 낯선 대상과 거리를 두려는 모습이 나타날 수 있지만 반응은 개체마다 달라요.",
    guardianContext: "작은 동물 추적은 리드로 관리하고 반복 점프와 계단을 줄이며 거친 피모와 피부, 독립적인 휴식 욕구를 함께 살펴보세요.",
    opening: "스코티시 테리어는 스코틀랜드의 오래된 소형 작업 테리어 가운데 하나입니다. 낮은 몸과 강한 뼈, 거친 이중모는 작업 환경과 연결됩니다.",
    roleToHome: "굴속 대상을 끈기 있게 찾던 배경은 냄새 탐색과 한 과제에 몰입하는 모습으로 이어질 수 있습니다.",
    reality: "작은 체격이 자동으로 쉬운 사회성이나 낮은 활동을 뜻하지 않습니다. 추적·경계 관리와 정기적인 피모 손질이 필요해요.",
    care: ["냄새 찾기와 안전한 파기 대체 놀이를 제공하세요.", "작은 동물과 다른 개에 대한 반응은 개체별로 확인하세요.", "거친 이중모를 빗고 정기적인 트리밍 계획을 세우세요."],
    levels: ["중간", "높은 편", "높은 편", "중간", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "냄새 중심 산책", description: "짧은 다리의 속도에 맞춰 탐색해요." }, { time: "낮", title: "독립 휴식", description: "방해받지 않는 낮은 자리를 마련해요." }, { time: "저녁", title: "찾기와 빗질", description: "짧은 과제 뒤 피모와 피부를 봐요." }],
    related: [["jack-russell-terrier", "작업 테리어의 끈기를 공유하지만 체형과 이동 방식이 달라요."], ["airedale-terrier", "스코틀랜드 소형 테리어와 대형 수변 테리어의 작업 규모를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/SCOTTISH-TERRIER-73.html", akcUrl: "https://www.akc.org/dog-breeds/scottish-terrier/",
  },
  {
    slug: "norwegian-elkhound-grey", nameKo: "노르웨이지안 엘크하운드 그레이", nameEn: "Norwegian Elkhound Grey",
    tagline: "은회색 이중모와 말린 꼬리에는 노르웨이의 험한 숲에서 큰 사냥감을 추적하고 알리던 힘이 있어요.",
    group: "spitz-primitive", tags: ["노르웨이 사냥견", "큰 사냥감 추적", "풍부한 발성"], colors: ["#878b87", "#dce1d5", "#303333"],
    origin: "노르웨이", lineage: "북유럽 회색 스피츠형 사냥견", role: "숲과 산에서 무스 등 큰 사냥감을 추적하고 짖음으로 위치 알림", size: "중형 · 약 50~52cm, 22~25kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "노르웨이의 숲과 바위 지형에서 무스의 냄새를 멀리 추적하고 움직임과 짖음으로 사냥꾼에게 위치를 알렸습니다.",
    today: "냄새를 따라 멀리 이동하거나 목소리로 변화를 알리려는 모습이 나타날 수 있지만 추적과 발성의 강도는 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 알림 뒤 돌아오기와 조용함을 가르치며 빽빽한 이중모, 체중과 더운 날 활동을 관리하세요.",
    opening: "노르웨이지안 엘크하운드 그레이는 노르웨이의 단단한 회색 스피츠형 사냥견입니다. 이름의 ‘엘크’는 북유럽의 무스를 가리킵니다.",
    roleToHome: "험한 지형을 오래 추적하고 독립적으로 판단하던 배경은 높은 지구력과 탐색, 발성으로 이어질 수 있습니다.",
    reality: "중간 크기와 친근한 표정만으로 주거 적합성을 판단하기 어렵습니다. 추적 안전과 짖음, 많은 털을 감당할 수 있어야 해요.",
    care: ["숲길 산책에서도 튼튼한 리드와 안전한 울타리를 사용하세요.", "알림 뒤 돌아오기와 조용한 행동을 보상하세요.", "이중모를 자주 빗고 더운 날에는 활동 강도를 낮추세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "긴 숲길 탐색", description: "리드 안에서 냄새를 충분히 따라요." }, { time: "낮", title: "시원한 회복", description: "두꺼운 털이 식도록 편히 쉬게 해요." }, { time: "저녁", title: "알림 전환", description: "소리 뒤 돌아와 쉬는 행동을 연습해요." }],
    related: [["finnish-spitz", "북유럽 스피츠형 사냥견의 발성을 공유하지만 목표 사냥감과 체격이 달라요."], ["korea-jindo-dog", "독립적인 추적과 스피츠형 체형 안에서 관계·피모 부담을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/NORWEGIAN-ELKHOUND-GREY-242.html", akcUrl: "https://www.akc.org/dog-breeds/norwegian-elkhound/",
  },
  {
    slug: "bloodhound", nameKo: "블러드하운드", nameEn: "Bloodhound",
    tagline: "늘어진 귀와 주름은 표정 장식이 아니라 오래된 냄새길을 붙잡고 장거리를 따라가던 후각 작업과 연결돼요.",
    group: "scent-hound", tags: ["벨기에 대형 후각하운드", "장거리 냄새 추적", "귀·피부 관리"], colors: ["#8a5540", "#e2ddcf", "#332c29"],
    origin: "벨기에", lineage: "생 위베르 계통의 대형 후각하운드", role: "사냥감과 사람의 오래된 냄새길 추적", size: "대형 · 약 58~69cm, 36~50kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "유럽의 큰 후각하운드로 사냥감의 냄새를 장거리 추적했고 이후에는 잃어버린 사람을 찾는 맨트레일링에도 활용됐습니다.",
    today: "한번 찾은 냄새길을 끈기 있게 따라가거나 낮고 큰 목소리로 알릴 수 있지만 집중과 발성은 개체마다 달라요.",
    guardianContext: "냄새에 몰입할 때 통제 가능한 장비를 쓰고 큰 몸의 이동, 침, 긴 귀와 피부 주름, 식사 전후 운동 간격을 관리하세요.",
    opening: "블러드하운드는 벨기에의 생 위베르 하운드 전통과 연결되는 대형 후각하운드입니다. 이름은 공격성이 아니라 오랜 혈통 기록과 관련됩니다.",
    roleToHome: "오래된 냄새를 끝까지 따라가는 작업은 현대에도 강한 후각 집중과 긴 탐색 산책의 필요성으로 이어질 수 있습니다.",
    reality: "온순한 인상만큼 관리 규모가 큰 견종입니다. 강한 추적, 침과 발성, 귀·주름 관리와 대형견 의료 이동을 준비해야 해요.",
    care: ["튼튼한 하네스와 리드로 충분한 냄새 탐색을 제공하세요.", "긴 귀와 피부 주름을 매일 확인하고 완전히 말리세요.", "식사 전후 격한 운동을 피하고 복부 불편은 즉시 진료받으세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "긴 냄새길", description: "안전한 장비로 천천히 냄새를 따라요." }, { time: "낮", title: "넓은 휴식", description: "큰 몸을 받치는 시원한 자리를 줘요." }, { time: "저녁", title: "귀와 주름 확인", description: "습기와 붉어짐, 냄새를 살펴요." }],
    related: [["basset-hound", "강한 후각과 긴 귀를 공유하지만 체고와 이동·건강 관리 규모가 크게 달라요."], ["beagle", "무리 후각하운드의 탐색을 공유하며 힘과 발성, 생활 공간을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BLOODHOUND-84.html", akcUrl: "https://www.akc.org/dog-breeds/bloodhound/",
  },
  {
    slug: "vizsla", nameKo: "비즐라", nameEn: "Hungarian Short-Haired Pointer (Vizsla)",
    tagline: "황금빛 적갈색 단모 아래에는 헝가리의 들과 숲, 물에서 사람 가까이 협력한 포인팅견의 지구력이 있어요.",
    group: "pointing", tags: ["헝가리 포인팅견", "다목적 사냥", "높은 교감"], colors: ["#b76f48", "#dfe1d3", "#3b302b"],
    origin: "헝가리", lineage: "헝가리 단모 포인팅견", role: "들·숲·물가에서 탐색·포인팅과 회수", size: "중대형 · 약 53~61cm, 20~27kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "헝가리에서 사람 가까이 움직이며 들과 숲, 물가의 사냥감을 찾고 위치를 알린 뒤 회수하는 다목적 사냥견으로 발달했습니다.",
    today: "사람의 활동에 계속 참여하고 넓게 달리거나 냄새를 찾으려는 모습이 나타날 수 있지만 교감과 작업 욕구는 개체마다 달라요.",
    guardianContext: "긴 활동과 냄새·회수 과제를 제공하는 동시에 혼자 차분히 쉬는 연습을 하고 야생동물 추적은 안전하게 관리하세요.",
    opening: "비즐라는 헝가리에서 오랫동안 발달한 황금빛 적갈색의 다목적 포인팅견입니다. 가볍고 탄력 있는 몸으로 사람 가까이 일했습니다.",
    roleToHome: "포인팅과 회수 작업에서 사람과 밀접하게 협력한 배경은 높은 활동과 교감 욕구로 이어질 수 있습니다.",
    reality: "짧은 털은 손질만 줄일 뿐 운동과 교육 부담을 줄이지 않습니다. 긴 활동, 추적 관리와 독립 휴식이 필요해요.",
    care: ["긴 산책에 냄새 찾기와 포인팅·회수 과제를 섞으세요.", "혼자 쉬는 시간은 짧고 성공적인 단계부터 연습하세요.", "야생동물 추적은 리드와 안전한 울타리로 예방하세요."],
    levels: ["높은 편", "높은 편", "낮은 편", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "넓게 탐색하기", description: "달리기와 냄새 신호를 함께 구성해요." }, { time: "낮", title: "독립 휴식", description: "사람과 떨어져 편히 쉬는 연습을 해요." }, { time: "저녁", title: "찾기와 회수", description: "짧은 협력 과제로 집중을 채워요." }],
    related: [["weimaraner", "사람 가까이 일한 대형 포인팅견의 공통점과 체격·관계 리듬을 비교해 보세요."], ["german-short-haired-pointing-dog", "다목적 포인팅과 회수를 공유하며 피모·체형과 작업 범위가 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/HUNGARIAN-SHORT-HAIRED-POINTER-VIZSLA-57.html", akcUrl: "https://www.akc.org/dog-breeds/vizsla/",
  },
  {
    slug: "flat-coated-retriever", nameKo: "플랫 코티드 리트리버", nameEn: "Flat Coated Retriever",
    tagline: "윤기 나는 검은 장모 안에는 영국의 물과 들을 오가며 사냥감을 부드럽게 회수한 가벼운 체형이 있어요.",
    group: "retriever-spaniel", tags: ["영국 회수견", "물새 회수", "높은 활동과 교감"], colors: ["#3f4644", "#dce2d5", "#262a29"],
    origin: "영국", lineage: "장모 회수견", role: "물과 들에서 사냥감을 찾아 부드럽게 회수", size: "중대형 · 약 56~62cm, 27~32kg", lifespan: "약 8~10년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국에서 물새와 들새의 위치를 기억하고 물과 수풀을 통과해 사냥감을 부드러운 입으로 회수하는 작업견으로 발달했습니다.",
    today: "물건을 물어 오고 사람과 활기차게 활동하려는 모습이 나타날 수 있지만 회수와 물 선호는 개체와 경험에 따라 달라요.",
    guardianContext: "반복 투척만 늘리지 말고 찾기·기다리기·놓기와 휴식을 묶으며 긴 털과 귀는 물놀이 뒤 완전히 말리세요.",
    opening: "플랫 코티드 리트리버는 영국에서 정립된 비교적 가볍고 우아한 장모 회수견입니다. 대표적인 피모색은 검정과 리버입니다.",
    roleToHome: "물과 들에서 사람의 신호에 따라 회수하던 배경은 높은 활동과 교감, 물건을 운반하려는 행동으로 이어질 수 있습니다.",
    reality: "명랑한 이미지가 낮은 관리 난도를 뜻하지 않습니다. 충분한 운동과 젖은 피모 관리, 비교적 짧을 수 있는 수명도 고려해야 해요.",
    care: ["회수 놀이에 기다리기·놓기·휴식을 함께 넣으세요.", "물놀이는 안전한 출구를 마련하고 젖은 털과 귀를 말리세요.", "정기 검진 계획과 대형 활동견의 이동·의료 비용을 준비하세요."],
    levels: ["높은 편", "높은 편", "낮은 편", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "긴 탐색과 회수", description: "걷기와 찾기, 가져오기를 섞어요." }, { time: "낮", title: "차분한 회복", description: "활동 뒤 넓은 자리에서 쉬게 해요." }, { time: "저녁", title: "털과 귀 관리", description: "장식털과 귀의 습기를 확인해요." }],
    related: [["labrador-retriever", "영국 회수견의 협력을 공유하지만 체형과 피모·수명 범위가 달라요."], ["golden-retriever", "장모 회수견 사이에서 피모색보다 체형과 관리 부담을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/FLAT-COATED-RETRIEVER-121.html", akcUrl: "https://www.akc.org/dog-breeds/flat-coated-retriever/",
  },
  {
    slug: "coton-de-tulear", nameKo: "코톤 드 툴레아르", nameEn: "Coton de Tulear",
    tagline: "솜처럼 부드러운 털보다 먼저, 마다가스카르에서 사람 곁의 반려 역할로 정착한 작고 단단한 몸을 보세요.",
    group: "companion", tags: ["마다가스카르 반려견", "면 같은 피모", "높은 교감"], colors: ["#d8d3c3", "#e5e3d8", "#3b3934"],
    origin: "마다가스카르", lineage: "비숑과 관련된 소형 반려견", role: "툴레아르 지역에서 발달한 가정 반려견", size: "소형 · 약 23~28cm, 4~7kg", lifespan: "약 15~19년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "마다가스카르의 항구도시 툴레아르와 연결되어 사람 가까이에서 위안과 교감을 제공하는 소형 반려견으로 정착했습니다.",
    today: "사람을 따라다니고 놀이와 교감에 적극적으로 참여할 수 있지만 혼자 쉬는 능력과 사회성은 개체마다 달라요.",
    guardianContext: "검증되지 않은 난파선 전설보다 실제 생활을 보고, 독립 휴식을 단계적으로 연습하며 피부까지 닿는 피모·치아 관리를 준비하세요.",
    opening: "코톤 드 툴레아르는 마다가스카르의 툴레아르에서 이름을 얻은 작고 튼튼한 반려견입니다. 이름의 ‘코톤’은 면 같은 피모 질감을 뜻합니다.",
    roleToHome: "사람 곁에서 생활해 온 배경은 높은 교감과 일상 참여로 이어질 수 있습니다. 혼자 편히 쉬는 능력도 함께 길러야 해요.",
    reality: "작고 부드러운 외모가 관리가 가볍다는 뜻은 아닙니다. 엉킴이 생기기 쉬운 털과 치아, 분리 연습에 시간이 필요해요.",
    care: ["혼자 쉬는 시간을 짧고 성공적인 단계부터 연습하세요.", "피부까지 나누어 빗고 습기와 엉킴을 매일 확인하세요.", "작은 몸에 맞는 산책과 놀이, 치아 관리를 이어 가세요."],
    levels: ["중간", "높은 편", "낮은 편", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "가벼운 탐색", description: "작은 몸에 맞춰 냄새 산책을 해요." }, { time: "낮", title: "독립 휴식", description: "사람과 떨어진 자리에서도 편히 쉬어요." }, { time: "저녁", title: "놀이와 빗질", description: "짧게 교감한 뒤 털과 치아를 봐요." }],
    related: [["havanese", "비숑 관련 소형 반려견의 교감을 공유하며 피모 질감과 지역 역사가 달라요."], ["bichon-frise", "흰 소형 장모견 사이에서 털 구조와 손질 방식의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/COTON-DE-TULEAR-283.html", akcUrl: "https://www.akc.org/dog-breeds/coton-de-tulear/",
  },
  {
    slug: "afghan-hound", nameKo: "아프간 하운드", nameEn: "Afghan Hound",
    tagline: "길게 흐르는 피모 아래에는 아프가니스탄의 산악과 고원에서 시야로 사냥감을 쫓던 강한 시각하운드의 몸이 있어요.",
    group: "sighthound", tags: ["아프가니스탄 시각하운드", "험지 질주", "집중적인 장모 관리"], colors: ["#b99b79", "#dce0d5", "#39332e"],
    origin: "아프가니스탄 · 영국 후원", lineage: "장모 산악 시각하운드", role: "산악·고원에서 시야로 사냥감을 추적", size: "대형 · 약 64~74cm, 23~27kg", lifespan: "약 12~18년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "아프가니스탄의 산악과 고원에서 시야로 사냥감을 발견하고 험한 지형을 빠르고 독립적으로 추적하는 시각하운드로 발달했습니다.",
    today: "실내에서는 조용히 쉬다가도 빠른 움직임을 보면 추적하거나 스스로 거리를 조절할 수 있지만 반응은 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 높은 울타리 안에서 달릴 기회를 주며 긴 피모는 엉킴과 이물질을 피부까지 세심하게 관리하세요.",
    opening: "아프간 하운드는 아프가니스탄의 다양한 산악·고원 환경과 연결되는 대형 장모 시각하운드입니다. 영국이 FCI 표준의 후원국입니다.",
    roleToHome: "험한 지형에서 독립적으로 추적하던 배경은 폭발적인 질주와 독립적인 판단, 넓은 시야 자극에 대한 반응으로 이어질 수 있습니다.",
    reality: "우아한 피모와 실루엣은 큰 관리 책임을 동반합니다. 안전한 질주 공간, 추적 통제와 집중적인 목욕·건조·빗질이 필요해요.",
    care: ["빠른 대상을 향한 추적은 리드와 높은 울타리로 관리하세요.", "긴 피모를 피부까지 나누어 빗고 완전히 건조하세요.", "큰 몸이 편히 쉬고 차량·병원으로 이동할 공간을 준비하세요."],
    levels: ["높은 편", "중간", "높은 편", "중간", "낮은 편", "높은 편"],
    days: [{ time: "아침", title: "긴 산책과 관찰", description: "안전한 리드로 넓게 주변을 살펴요." }, { time: "낮", title: "조용한 휴식", description: "긴 몸을 받치는 넓은 자리를 줘요." }, { time: "저녁", title: "질주와 피모 관리", description: "안전하게 달린 뒤 털을 나누어 봐요." }],
    related: [["borzoi", "대형 장모 시각하운드의 우아한 실루엣과 서로 다른 지형·피모 구조를 비교해 보세요."], ["greyhound", "빠른 시각 추적을 공유하지만 피모 관리와 험지 적응의 차이가 커요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/AFGHAN-HOUND-228.html", akcUrl: "https://www.akc.org/dog-breeds/afghan-hound/",
  },
  {
    slug: "lhasa-apso", nameKo: "라사압소", nameEn: "Lhasa Apso",
    tagline: "바닥까지 흐르는 털 안에는 티베트의 집과 수도원 내부에서 작은 소리와 방문자를 알리던 단단한 감시견이 있어요.",
    group: "companion", tags: ["티베트 실내 감시견", "신중한 경계", "집중적인 장모 관리"], colors: ["#b49a72", "#e1dfd2", "#3a342d"],
    origin: "티베트 · 영국 후원", lineage: "티베트 소형 장모 반려·감시견", role: "궁전과 수도원 내부의 동행과 알림", size: "소형 · 약 25~28cm, 5~8kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "티베트의 궁전과 불교 수도원 내부에서 사람 곁에 지내며 작은 소리와 낯선 방문을 알리는 소형 감시·반려견 역할을 했습니다.",
    today: "낯선 사람을 바로 받아들이지 않거나 주변 소리에 또렷하게 반응할 수 있지만 경계와 친화성은 개체마다 달라요.",
    guardianContext: "억지 인사보다 선택할 거리를 주고 알림 뒤 조용함을 보상하며 긴 피모와 눈 주변, 귀·치아를 규칙적으로 관리하세요.",
    opening: "라사압소는 티베트의 고지대 생활과 연결되는 작고 단단한 장모견입니다. 궁전과 수도원 내부에서 동행과 알림 역할을 했습니다.",
    roleToHome: "실내의 작은 변화를 먼저 감지하던 배경은 낯선 소리와 방문자에 대한 경계로 이어질 수 있습니다.",
    reality: "소형 반려견이라는 말이 모두에게 즉시 사교적이라는 뜻은 아닙니다. 거리 조절 교육과 많은 피모 관리 시간을 준비해야 해요.",
    care: ["낯선 사람과의 인사를 강요하지 말고 선택할 거리를 주세요.", "알림 뒤 자리로 돌아와 조용히 쉬는 행동을 보상하세요.", "긴 털과 눈 주변, 귀·치아를 규칙적으로 관리하세요."],
    levels: ["중간", "높은 편", "높은 편", "중간", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "차분한 동네 산책", description: "붐비지 않는 길에서 냄새를 살펴요." }, { time: "낮", title: "독립적인 휴식", description: "방해받지 않는 낮은 자리를 줘요." }, { time: "저녁", title: "알림과 빗질", description: "조용함을 연습한 뒤 털을 살펴요." }],
    related: [["shih-tzu", "티베트·중국권 장모 반려견의 외형과 서로 다른 감시·궁정 역할을 비교해 보세요."], ["havanese", "작은 장모 반려견 사이에서 낯선 대상 반응과 피모 질감의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/LHASA-APSO-227.html", akcUrl: "https://www.akc.org/dog-breeds/lhasa-apso/",
  },
];

export const detailBatchGSlugs = seeds.map((seed) => seed.slug);

export const detailBatchG = seeds.map((seed) => ({
  slug: seed.slug,
  contentStatus: "mvp-editorial-draft",
  nameKo: seed.nameKo,
  nameEn: seed.nameEn,
  tagline: seed.tagline,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`,
  catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: { src: `/illustrations/v3/${seed.slug}-history.webp`, alt: `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: { originalRole: seed.originalRole, today: seed.today, guardianContext: seed.guardianContext },
  story: { opening: seed.opening, roleToHome: seed.roleToHome, reality: seed.reality },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "개체의 체력에 맞춘 규칙적인 산책과 놀이가 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 빗질과 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.care,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: seed.days,
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
  ],
})) satisfies Breed[];
