import type { Breed } from "./schema";

const checkedAt = "2026-08-04";
const historyAltOverrides: Partial<Record<string, string>> = {
  "italian-sighthound": "유럽의 저택 뜰에서 사람들 곁을 가볍게 달리는 작은 이탈리안 그레이하운드를 그린 편집 수채화",
  weimaraner: "중부 독일의 숲 가장자리에서 넓은 들을 향해 포인팅하며 사람과 협력하는 은회색 와이머라너를 그린 편집 수채화",
  "chow-chow": "중국 북부의 안뜰에서 열린 대문 너머 움직임을 살피는 붉은 차우차우를 그린 편집 수채화",
  "nova-scotia-duck-tolling-retriever": "노바스코샤 물가에서 갈대 뒤 사냥꾼과 협력해 나뭇가지를 물가로 옮기는 붉은 톨러를 그린 편집 수채화",
  "old-english-sheepdog": "영국의 돌담길에서 사람과 함께 양 떼를 이동시키는 올드 잉글리시 시프도그를 그린 편집 수채화",
  "cane-corso": "이탈리아 남부 농장의 열린 문 앞에서 사람과 가축 주변을 살피는 회색 카네 코르소를 그린 편집 수채화",
  "bull-terrier": "19세기 영국 전람회에서 관람객이 흰색 불테리어의 체형을 살피는 장면을 그린 편집 수채화",
  dalmatian: "말이 끄는 마차 곁에서 일정한 보폭으로 이동하는 흰 바탕에 검은 점이 있는 달마시안을 그린 편집 수채화",
  "continental-toy-spaniel": "유럽 저택의 응접실에서 귀족 여성 곁을 바라보는 흰색과 갈색 파피용을 그린 편집 수채화",
};

const historySources: Partial<Record<string, { title: string; organization: string; url: string; checkedAt: string }[]>> = {
  "italian-sighthound": [{ title: "Italian Greyhound History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/italian-greyhound-history/", checkedAt: "2026-08-29" }],
  weimaraner: [{ title: "Weimaraner Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/lifestyle/fun-facts-weimaraner/", checkedAt: "2026-08-29" }],
  "chow-chow": [{ title: "Chow Chow Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/lifestyle/fun-facts-chow-chow/", checkedAt: "2026-08-29" }],
  "nova-scotia-duck-tolling-retriever": [{ title: "Nova Scotia Duck Tolling Retriever History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/nova-scotia-duck-tolling-retriever-history/", checkedAt: "2026-08-29" }],
  "old-english-sheepdog": [{ title: "Old English Sheepdog Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/fun-facts-old-english-sheepdog/", checkedAt: "2026-08-29" }],
  "cane-corso": [{ title: "Cane Corso Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/cane-corso-history/", checkedAt: "2026-08-29" }],
  "bull-terrier": [{ title: "Bull Terrier Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/bull-terrier-history/", checkedAt: "2026-08-29" }],
  dalmatian: [{ title: "Dalmatian Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/dalmatian-history/", checkedAt: "2026-08-29" }],
  "continental-toy-spaniel": [{ title: "Papillon Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/news/pappy-anniversary-papillon-joins-akc-century-club/", checkedAt: "2026-08-29" }],
};
type Level = Breed["tendencies"][keyof Breed["tendencies"]]["label"];
type DayStep = Breed["daySnapshot"][number];

type BatchESeed = {
  slug: string;
  nameKo: string;
  nameEn: string;
  tagline: string;
  group: Breed["catalog"]["group"];
  tags: [string, string, string];
  colors: [string, string, string];
  origin: string;
  lineage: string;
  role: string;
  size: string;
  lifespan: string;
  originalRole: string;
  today: string;
  guardianContext: string;
  opening: string;
  roleToHome: string;
  reality: string;
  care: [string, string, string];
  levels: [Level, Level, Level, Level, Level, Level];
  days: [DayStep, DayStep, DayStep];
  related: [[string, string], [string, string]];
  fciUrl: string;
  akcUrl: string;
  evidenceUrl?: string;
};

const seeds: BatchESeed[] = [
  {
    slug: "dalmatian",
    nameKo: "달마시안",
    nameEn: "Dalmatian",
    tagline: "반점 무늬보다 먼저, 이동하는 사람과 마차 곁을 따르던 활동의 배경을 살펴보세요.",
    group: "scent-hound",
    tags: ["크로아티아 기원", "마차 동행의 역사", "높은 지구력"],
    colors: ["#d9d4c7", "#eef0e9", "#2f3331"],
    origin: "크로아티아·달마티아 지역",
    lineage: "FCI 하운드 관련 견종",
    role: "사냥·반려와 마차를 따라 이동한 코치 독",
    size: "중대형 · 약 54~62cm",
    lifespan: "약 11~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "말과 마차 가까이에서 장거리를 이동하고 주변 변화를 살피는 코치 독으로 알려진 역사적 배경이 있습니다.",
    today: "빠르게 달리고 오래 움직이려는 경향이나 주변 활동에 즉시 참여하려는 모습이 나타날 수 있지만 개체마다 강도는 달라요.",
    guardianContext: "운동 거리만 늘리지 말고 냄새 탐색과 신호 연습, 흥분 뒤 쉬는 능력을 함께 관찰하며 청각 반응도 개체별로 확인하세요.",
    opening: "달마시안은 크로아티아 달마티아 지역과 연결되는 기록을 가진 견종으로, 독특한 점무늬와 함께 마차 곁을 달린 코치 독의 역사로 널리 알려졌습니다.",
    roleToHome: "오래 움직이며 말과 마차를 따라가던 배경은 오늘날에도 지구력과 활동 참여 욕구로 이어질 수 있습니다. 사람과 함께할 구조화된 활동이 중요해요.",
    reality: "눈에 띄는 무늬만 보고 선택하기에는 운동과 교육에 필요한 시간이 큽니다. 충분한 활동, 안전한 통제와 청각 상태를 포함한 개별 건강 확인을 준비해야 해요.",
    care: ["매일 움직일 시간과 냄새 탐색·훈련 과제를 함께 마련하세요.", "달리는 활동은 안전한 리드와 울타리가 있는 환경에서 제공하세요.", "소리에 대한 반응과 의사소통 방식을 관찰하고 정기 검진에서 청각 상태를 상의하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "리듬 있는 긴 산책", description: "걷기와 냄새 탐색을 번갈아 해요." }, { time: "낮", title: "차분한 휴식", description: "활동 뒤 스스로 쉬는 시간을 보장해요." }, { time: "저녁", title: "협력 과제", description: "짧은 신호 연습과 찾기 놀이를 해요." }],
    related: [["weimaraner", "큰 운동 범위와 사냥 배경은 닮았지만 추적·포인팅 역할의 차이를 비교해 보세요."], ["labrador-retriever", "활동적인 중대형견 사이에서 협업 방식과 피모·급여 부담을 살펴보세요."]],
    fciUrl: "https://www.fci.be/Nomenclature/Standards/153g06-en.pdf",
    akcUrl: "https://www.akc.org/dog-breeds/dalmatian/",
  },
  {
    slug: "italian-sighthound",
    nameKo: "이탈리안 그레이하운드",
    nameEn: "Italian Sighthound",
    tagline: "작은 체구 안에도 시야로 움직임을 쫓는 하운드의 달리기 방식이 남아 있어요.",
    group: "sighthound",
    tags: ["이탈리아 소형 시각하운드", "빠른 움직임", "추위와 낙상 관리"],
    colors: ["#a9a49b", "#e4e2d8", "#383938"],
    origin: "이탈리아",
    lineage: "소형 단모 시각하운드",
    role: "소형 시각하운드이자 오랜 반려견",
    size: "소형 · 약 32~38cm, 5kg 이하",
    lifespan: "약 14~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "작은 시각하운드로 빠른 움직임을 포착하는 능력을 지녔고 유럽의 가정과 궁정에서 반려견으로도 오랫동안 생활했습니다.",
    today: "작고 빠른 대상을 쫓거나 짧게 전력 질주하려는 모습, 사람 가까이에서 따뜻하게 쉬려는 모습이 나타날 수 있어요.",
    guardianContext: "추적 반응은 안전한 리드로 관리하고 가는 다리와 얇은 피모를 고려해 높은 곳, 미끄러운 바닥과 추운 날씨를 함께 점검하세요.",
    opening: "이탈리안 그레이하운드는 고대 지중해권의 작은 시각하운드 계통에서 이어져 이탈리아 르네상스 시대에도 사랑받은 소형견입니다.",
    roleToHome: "시각 자극에 빠르게 반응하는 하운드의 면과 사람 곁에서 쉬어 온 반려견의 면이 공존합니다. 안전한 질주 기회와 조용한 휴식이 모두 필요해요.",
    reality: "작고 가벼워도 외부 활동이 필요하며 뼈가 가는 체형은 낙상과 거친 놀이를 더 조심해야 한다는 뜻입니다. 추위에 대비할 환경도 준비하세요.",
    care: ["소파와 침대 주변의 점프 동선과 미끄러운 바닥을 안전하게 정리하세요.", "작은 동물을 향한 추적은 리드와 울타리로 예방하세요.", "추운 날에는 짧게 활동하고 체온을 유지할 수 있는 휴식 환경을 마련하세요."],
    levels: ["중간", "중간", "낮은 편", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "가볍게 탐색하기", description: "안전한 길에서 냄새와 움직임을 살펴요." }, { time: "낮", title: "따뜻하게 쉬기", description: "바람과 차가운 바닥을 피한 자리를 줘요." }, { time: "저녁", title: "짧고 안전한 놀이", description: "미끄럽지 않은 곳에서 몸을 움직여요." }],
    related: [["whippet", "같은 단모 시각하운드 안에서 체격과 질주 규모, 추위 관리의 차이를 볼 수 있어요."], ["greyhound", "시각 추적과 실내 휴식의 공통점, 이동·공간 부담의 큰 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/Nomenclature/Standards/200g10-en.pdf",
    akcUrl: "https://www.akc.org/dog-breeds/italian-greyhound/",
  },
  {
    slug: "continental-toy-spaniel",
    nameKo: "파피용",
    nameEn: "Continental Toy Spaniel",
    tagline: "나비처럼 펼쳐진 귀만큼, 짧은 놀이와 신호 학습에 빠르게 참여하는 움직임도 살펴보세요.",
    group: "companion",
    tags: ["파피용·파렌", "높은 학습 자극", "작은 체격"],
    colors: ["#d8c09d", "#edf0df", "#473a31"],
    origin: "벨기에·프랑스",
    lineage: "콘티넨탈 토이 스패니얼 · 파피용과 파렌",
    role: "사람 곁의 소형 반려견",
    size: "초소형 · 약 28cm 이하, 체중 구분 있음",
    lifespan: "약 14~16년 (AKC 파피용 참고, 개체별 차이 있음)",
    originalRole: "유럽에서 사람 가까이 지내온 작은 토이 스패니얼이며, FCI는 직립 귀의 파피용과 늘어진 귀의 파렌을 한 견종의 두 바라이어티로 분류합니다.",
    today: "사람의 신호를 빠르게 배우고 놀이에 적극적으로 참여할 수 있지만 작은 체격과 높은 학습성만으로 쉬운 양육을 보장할 수는 없어요.",
    guardianContext: "긍정적인 짧은 교육과 독립 휴식을 함께 만들고 높은 곳의 낙상, 거친 상호작용과 귀 장식털 엉킴을 일상적으로 살펴보세요.",
    opening: "콘티넨탈 토이 스패니얼은 유럽에서 오래 사랑받은 작은 반려견입니다. 귀가 선 파피용과 귀가 늘어진 파렌은 별도 견종이 아니라 같은 표준의 두 모습입니다.",
    roleToHome: "사람 곁의 생활과 민첩한 움직임은 오늘날에도 높은 교감과 학습 참여로 이어질 수 있습니다. 작은 몸에도 산책과 탐색, 교육이 필요해요.",
    reality: "작은 체격은 생활 부담이 없다는 뜻이 아닙니다. 안전한 이동 동선, 혼자 쉬는 연습, 치아와 긴 귀 주변 피모를 관리할 시간을 계산해야 해요.",
    care: ["높은 가구와 계단에서의 낙상을 예방하고 거친 놀이를 감독하세요.", "짧은 산책과 학습 놀이를 매일의 루틴으로 제공하세요.", "귀 뒤와 다리 장식털의 엉킴, 치아 상태를 정기적으로 확인하세요."],
    levels: ["중간", "높은 편", "낮은 편", "높은 편", "중간", "중간"],
    days: [{ time: "아침", title: "작은 탐색 산책", description: "속도보다 냄새를 고를 시간을 줘요." }, { time: "낮", title: "독립 휴식", description: "사람과 떨어진 자리에서도 편히 쉬어요." }, { time: "저녁", title: "학습과 빗질", description: "짧은 신호 놀이 뒤 피모를 확인해요." }],
    related: [["cavalier-king-charles-spaniel", "유럽 토이 스패니얼의 교감과 서로 다른 체격·피모·건강 부담을 비교해 보세요."], ["chihuahua", "초소형 반려견 사이에서 학습 자극과 낯선 변화 반응의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/CONTINENTAL-TOY-SPANIEL-77.html",
    akcUrl: "https://www.akc.org/dog-breeds/papillon/",
  },
  {
    slug: "chow-chow",
    nameKo: "차우차우",
    nameEn: "Chow Chow",
    tagline: "풍성한 갈기보다 먼저, 낯선 움직임을 스스로 살피던 경비견의 배경을 확인해보세요.",
    group: "spitz-primitive",
    tags: ["중국 기원 스피츠형", "신중한 관계", "더위·피모 관리"],
    colors: ["#b98054", "#e1ddcc", "#44332a"],
    origin: "중국",
    lineage: "아시아 스피츠와 관련 견종",
    role: "경비·사냥과 반려 역할",
    size: "중형 · 약 46~56cm",
    lifespan: "약 8~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "중국에서 집과 영역을 지키고 사냥에도 활용되었으며, 사람 곁의 반려 역할을 함께해 온 스피츠형 견종입니다.",
    today: "낯선 접근을 서둘러 받아들이지 않거나 독립적으로 거리를 조절하려는 모습이 나타날 수 있지만 사회성과 반응은 개체마다 달라요.",
    guardianContext: "억지 인사보다 선택할 거리와 예측 가능한 루틴을 주고, 두꺼운 털 속 피부와 더운 날의 호흡·움직임을 세심하게 확인하세요.",
    opening: "차우차우는 중국에서 오랫동안 경비와 사냥, 동행 역할을 해온 견종으로 기록됩니다. 풍성한 털과 독특한 외형은 기능적인 움직임을 방해하지 않아야 합니다.",
    roleToHome: "주변과 낯선 대상을 신중히 살피던 배경은 오늘날 가정에서도 거리 조절과 경계 반응으로 나타날 수 있습니다. 차분한 사회화가 중요해요.",
    reality: "독립적이라는 평판을 방치해도 된다는 뜻으로 받아들이면 안 됩니다. 안전한 관계 교육, 더위 관리와 빽빽한 피모를 돌볼 시간이 필요해요.",
    care: ["낯선 사람이나 개와의 인사를 강요하지 말고 안전한 거리를 보장하세요.", "털을 층별로 나누어 빗고 피부의 습기와 엉킴을 확인하세요.", "기온과 습도가 높은 시간에는 활동을 줄이고 시원한 휴식 공간을 유지하세요."],
    levels: ["중간", "중간", "높은 편", "중간", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "조용한 관찰 산책", description: "붐비지 않는 길에서 거리를 선택해요." }, { time: "낮", title: "방해 없는 휴식", description: "시원하고 독립적인 자리를 보장해요." }, { time: "저녁", title: "피모와 피부 점검", description: "속털까지 나누어 상태를 살펴요." }],
    related: [["akita", "신중한 대형 스피츠형 견종 사이에서 체격과 관계 관리 부담을 비교해 보세요."], ["shiba", "동아시아 스피츠형 견종의 독립성과 털·활동 규모 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/Nomenclature/Standards/205g05-en.pdf",
    akcUrl: "https://www.akc.org/dog-breeds/chow-chow/",
  },
  {
    slug: "saint-bernard",
    nameKo: "세인트 버나드",
    nameEn: "St. Bernard",
    tagline: "산악 구조의 이미지보다 먼저, 초대형 몸을 매일 이동시키고 쉴 자리를 마련할 수 있는지 봐야 해요.",
    group: "guardian-working",
    tags: ["스위스 알프스", "호스피스 동행견", "초대형 체격"],
    colors: ["#b47d58", "#e4e0d2", "#40352f"],
    origin: "스위스",
    lineage: "알프스 대형 산악견·몰로시안 타입",
    role: "농장·경비와 알프스 고개 여행자 동행·수색",
    size: "초대형 · 약 65~90cm",
    lifespan: "약 8~10년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "그랑 생베르나르 고개의 호스피스에서 경비와 동행을 맡았고 눈과 안개 속에서 길을 잃은 여행자를 찾는 데 활용된 기록이 있습니다.",
    today: "사람 가까이에서 침착하게 머물 수 있지만 초대형 몸의 움직임과 힘은 작은 흥분이나 부딪힘도 큰 위험으로 만들 수 있어요.",
    guardianContext: "성장기 관절과 체중, 미끄러운 바닥, 차량·병원 이동 수단을 먼저 준비하고 더운 날 활동과 식사 전후 운동을 세심하게 관리하세요.",
    opening: "세인트 버나드는 스위스 알프스 고개의 호스피스에서 큰 산악견으로 기록되며, 여행자를 동행하고 눈 속에서 사람을 찾은 역사로 알려졌습니다.",
    roleToHome: "험한 환경에서 사람 곁을 지킨 큰 몸과 침착함은 인상적이지만, 현대 가정에서는 공간·이동·건강 관리의 규모가 가장 먼저 고려돼야 합니다.",
    reality: "온화하다는 이미지가 초대형견의 부담을 줄이지는 않습니다. 식비와 의료비, 침과 털, 더위, 짧을 수 있는 수명까지 감당 가능한지 확인해야 해요.",
    care: ["미끄럽지 않은 넓은 동선과 차량·병원 이동 계획을 준비하세요.", "더운 날 활동을 줄이고 시원한 실내에서 호흡 회복을 확인하세요.", "식사 전후 격한 운동을 피하고 갑작스러운 복부 팽창이나 불편은 즉시 진료받으세요."],
    levels: ["중간", "중간", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "느긋한 평지 산책", description: "관절에 무리 없이 꾸준히 걸어요." }, { time: "낮", title: "시원한 휴식", description: "몸 전체를 받쳐주는 넓은 자리를 줘요." }, { time: "저녁", title: "대형견 몸 점검", description: "보행과 피부, 호흡을 살펴요." }],
    related: [["newfoundland", "초대형 작업견의 온화한 이미지와 물·산악 환경에서의 역할 차이를 비교해 보세요."], ["bernese-mountain-dog", "스위스 대형견 사이에서 수명과 체격, 피모·이동 부담을 함께 살펴보세요."]],
    fciUrl: "https://www.fci.be/Nomenclature/Standards/061g02-en.pdf",
    akcUrl: "https://www.akc.org/dog-breeds/st-bernard/",
    evidenceUrl: "https://www.msdvetmanual.com/digestive-system/surgical-problems-of-the-gastrointestinal-tract-in-small-animals/gastric-dilation-and-volvulus-in-small-animals",
  },
  {
    slug: "weimaraner",
    nameKo: "와이머라너",
    nameEn: "Weimaraner",
    tagline: "은빛 털 뒤에는 들과 숲, 물을 오가며 사람과 과제를 수행한 작업 배경이 있어요.",
    group: "pointing",
    tags: ["독일 포인팅견", "높은 활동", "지속적인 협업"],
    colors: ["#8f9490", "#dfe3da", "#303735"],
    origin: "독일",
    lineage: "대형 대륙계 포인팅견",
    role: "사냥감 탐색·포인팅과 추적·회수",
    size: "중대형~대형 · 약 57~70cm",
    lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "독일에서 사냥감을 넓게 탐색하고 위치를 알리며 추적과 회수까지 사람과 협력하는 다목적 사냥견으로 발달했습니다.",
    today: "넓게 냄새를 탐색하고 사람의 활동에 계속 참여하려는 모습이 나타날 수 있으며 과제가 부족하면 스스로 자극을 찾을 수 있어요.",
    guardianContext: "달리기만 반복하기보다 냄새 탐색과 방향 신호, 기다림을 섞고 혼자 쉬는 시간과 작은 동물에 대한 실제 반응을 확인하세요.",
    opening: "와이머라너는 독일에서 정립된 포인팅견으로, 숲과 들에서 사냥감을 찾고 위치를 알리며 사람과 협력하는 여러 작업을 수행했습니다.",
    roleToHome: "지구력과 사람 가까이에서 일하는 성향은 현대 가정에서도 높은 활동과 참여 욕구로 이어질 수 있습니다. 몸과 머리를 함께 쓰는 일과가 필요해요.",
    reality: "매끈한 은빛 외모만 보고 선택하기에는 운동·교육 시간이 큽니다. 매일의 긴 활동, 혼자 쉬는 연습과 안전한 추적 관리가 필요해요.",
    care: ["긴 산책에 냄새 탐색과 신호 과제를 섞어 몸과 머리를 함께 사용하게 하세요.", "혼자 있는 시간은 짧고 성공적인 단계부터 점진적으로 연습하세요.", "야생동물과 작은 반려동물을 향한 반응은 리드와 울타리로 안전하게 관리하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "넓게 탐색하는 산책", description: "냄새를 따라가되 보호자와 신호를 맞춰요." }, { time: "낮", title: "독립 휴식", description: "활동 사이 차분히 쉬는 능력을 길러요." }, { time: "저녁", title: "포인팅견 과제", description: "찾기와 기다리기를 짧게 연습해요." }],
    related: [["dalmatian", "높은 지구력을 공유하지만 마차 동행과 포인팅 작업의 차이를 비교해 보세요."], ["german-shepherd-dog", "사람과 협력하는 대형 작업견 안에서 냄새 탐색과 지시 수행의 초점을 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/WEIMARANER-99.html",
    akcUrl: "https://www.akc.org/dog-breeds/weimaraner/",
  },
  {
    slug: "nova-scotia-duck-tolling-retriever",
    nameKo: "노바 스코샤 덕 톨링 리트리버",
    nameEn: "Nova Scotia Duck Tolling Retriever",
    tagline: "여우를 닮은 붉은 털보다 먼저, 물가를 오가며 유인과 회수를 반복한 역할을 보세요.",
    group: "retriever-spaniel",
    tags: ["캐나다 회수견", "오리 유인과 회수", "높은 학습 자극"],
    colors: ["#bb744d", "#dce5d8", "#453329"],
    origin: "캐나다·노바스코샤",
    lineage: "소형 리트리버",
    role: "물가에서 오리를 유인하고 물새를 회수",
    size: "중형 · 약 45~51cm",
    lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "물가에서 활기차게 움직여 오리의 관심을 끌고, 사냥 뒤에는 물새를 찾아 사람에게 가져오는 특수한 회수 작업을 수행했습니다.",
    today: "움직이는 장난감과 회수 놀이에 빠르게 집중하거나 흥분할 수 있지만 물과 회수를 좋아하는 정도는 개체와 경험에 따라 달라요.",
    guardianContext: "반복 투척만 늘리지 말고 냄새 찾기와 멈춤, 흥분 뒤 쉬는 연습을 묶고 물놀이는 안전한 출구와 구명 장비를 갖춰 시작하세요.",
    opening: "노바 스코샤 덕 톨링 리트리버는 캐나다 노바스코샤에서 물가의 오리를 유인하고 회수하는 독특한 작업을 위해 발달한 리트리버입니다.",
    roleToHome: "민첩한 움직임과 높은 집중력, 사람과의 협업은 오늘날에도 다양한 과제와 활동을 요구할 수 있습니다. 단순 산책만으로 충분하다고 보기 어려워요.",
    reality: "크기가 비교적 작다는 이유로 관리가 가벼운 리트리버는 아닙니다. 높은 활동과 학습 자극, 이중모와 젖은 털 관리까지 준비해야 해요.",
    care: ["회수 놀이에 찾기·멈춤·놓기 신호를 섞어 흥분을 조절하세요.", "물놀이는 안전한 수질과 출구, 구명조끼를 준비하고 억지로 입수시키지 마세요.", "젖은 이중모를 완전히 말리고 귀와 피부 상태를 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "중간"],
    days: [{ time: "아침", title: "활동적인 탐색", description: "냄새와 움직임을 이용한 과제를 해요." }, { time: "낮", title: "흥분 낮추기", description: "놀이 뒤 조용히 쉬는 시간을 만들어요." }, { time: "저녁", title: "회수와 피모 관리", description: "짧은 회수 놀이 뒤 털과 귀를 봐요." }],
    related: [["golden-retriever", "회수 작업은 닮았지만 체격과 유인 역할, 활동 리듬의 차이를 비교해 보세요."], ["labrador-retriever", "물새 회수견의 공통점과 피모·흥분·체격 관리의 차이를 살펴보세요."]],
    fciUrl: "https://fci.be/en/nomenclature/NOVA-SCOTIA-DUCK-TOLLING-RETRIEVER-312.html",
    akcUrl: "https://www.akc.org/dog-breeds/nova-scotia-duck-tolling-retriever/",
  },
  {
    slug: "old-english-sheepdog",
    nameKo: "올드 잉글리시 시프독",
    nameEn: "Old English Sheepdog",
    tagline: "얼굴을 덮는 털 뒤에는 무리의 움직임을 살피던 큰 목양견의 몸이 있어요.",
    group: "herding",
    tags: ["영국 목양견", "큰 체격과 움직임", "집중적인 장모 관리"],
    colors: ["#9fa5a2", "#e6e5da", "#343938"],
    origin: "영국",
    lineage: "대형 장모 목양견",
    role: "농경지에서 양과 가축을 이동시키는 목양 작업",
    size: "대형 · 수컷 약 61cm 이상, 암컷 56cm 이상",
    lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국 농경지에서 큰 몸과 지구력을 사용해 양과 가축의 이동을 돕는 목양견으로 발달한 배경이 있습니다.",
    today: "움직이는 대상을 따라가거나 몸으로 방향을 바꾸려는 모습, 가족 활동에 적극적으로 참여하려는 모습이 나타날 수 있어요.",
    guardianContext: "몰이 행동은 대상과 흥분도를 함께 관찰하고 긴 털 아래 눈·귀·피부와 발, 몸 전체의 엉킴을 매일 관리할 수 있는지 확인하세요.",
    opening: "올드 잉글리시 시프독은 영국의 큰 장모 목양견입니다. 풍성한 털과 독특한 걸음걸이 뒤에는 농경지에서 가축을 움직인 작업의 역사가 있습니다.",
    roleToHome: "큰 몸으로 움직임을 읽고 가축을 몰던 배경은 가정에서도 활동 참여와 움직임 자극에 대한 반응으로 이어질 수 있습니다.",
    reality: "털이 매력의 큰 부분이지만 동시에 가장 큰 일상 부담입니다. 큰 체격의 운동·이동 비용과 전신 빗질, 전문 미용 시간을 함께 계산해야 해요.",
    care: ["전신을 구역별로 나누어 피부까지 빗고 엉킴을 매일 확인하세요.", "가족이나 다른 동물을 몰려는 행동은 거리와 대체 신호로 관리하세요.", "큰 몸이 안전하게 돌고 쉴 공간과 미끄럽지 않은 바닥을 준비하세요."],
    levels: ["높은 편", "중간", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "움직임과 탐색", description: "충분히 걷고 냄새를 맡을 시간을 줘요." }, { time: "낮", title: "넓게 쉬기", description: "시원하고 방해받지 않는 자리를 줘요." }, { time: "저녁", title: "전신 빗질", description: "털을 나누어 피부와 엉킴을 확인해요." }],
    related: [["shetland-sheepdog", "풍성한 장모 목양견 사이에서 체격과 운동·미용 규모의 차이를 비교해 보세요."], ["border-collie", "영국 목양견의 공통점과 과제 집중·피모 관리 방식의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/OLD-ENGLISH-SHEEPDOG-16.html",
    akcUrl: "https://www.akc.org/dog-breeds/old-english-sheepdog/",
  },
  {
    slug: "cane-corso",
    nameKo: "카네 코르소",
    nameEn: "Italian Cane Corso",
    tagline: "짧은 털과 단단한 체격을 고르기 전에, 성견의 힘을 매일 안전하게 다룰 수 있는지 확인하세요.",
    group: "guardian-working",
    tags: ["이탈리아 다목적 작업견", "큰 힘", "신중한 사회화"],
    colors: ["#77736d", "#d9ddd4", "#2e302f"],
    origin: "이탈리아",
    lineage: "몰로시안·마스티프 타입 작업견",
    role: "재산·가족·가축을 지킨 다목적 농장견",
    size: "대형 · 약 60~68cm, 40~50kg",
    lifespan: "약 9~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "이탈리아 농촌에서 재산과 가족, 가축을 지키고 여러 작업을 수행한 민첩한 대형 몰로시안 견종으로 정립되었습니다.",
    today: "낯선 상황을 신중히 관찰하거나 몸으로 공간을 통제하려는 모습이 나타날 수 있지만 품종만으로 공격성을 예측할 수는 없어요.",
    guardianContext: "어릴 때부터 안전한 거리의 다양한 경험과 보상 기반 교육을 제공하고, 성견의 힘을 보호자가 다룰 장비·기술·전문 지원을 준비하세요.",
    opening: "카네 코르소는 이탈리아의 대형 다목적 작업견으로, 농장과 가정 가까이에서 재산·가족·가축을 지키는 역할을 해왔습니다.",
    roleToHome: "빠르게 상황을 살피고 큰 몸으로 개입하던 배경은 현대 가정에서 높은 통제 책임으로 이어집니다. 신중한 사회화와 협력 교육이 필수예요.",
    reality: "외모가 주는 강한 인상만으로 선택해서는 안 됩니다. 큰 힘과 주거 규정, 타인·동물과의 안전, 교육 비용과 의료 이동까지 먼저 확인해야 해요.",
    care: ["낯선 사람이나 개와의 인사를 강요하지 말고 안전한 거리를 보장하세요.", "힘으로 제압하지 말고 예측 가능한 규칙과 보상으로 협력 관계를 만드세요.", "주거 규정과 보험·이동 수단, 대형견을 지원할 교육 전문가를 입양 전에 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "낮은 편"],
    days: [{ time: "아침", title: "구조화된 산책", description: "걷기와 기다리기 신호를 함께 연습해요." }, { time: "낮", title: "차분한 관찰", description: "자극과 거리를 두고 스스로 쉬게 해요." }, { time: "저녁", title: "협력 과제", description: "자리 이동과 핸들링을 짧게 연습해요." }],
    related: [["rottweiler", "큰 힘과 경비·농장 배경을 공유하지만 체형과 협력 방식의 차이를 비교해 보세요."], ["dobermann", "사람 가까이에서 경계한 작업견 사이의 움직임과 생활 관리 부담을 살펴보세요."]],
    fciUrl: "https://fci.be/en/nomenclature/ITALIAN-CANE-CORSO-343.html",
    akcUrl: "https://www.akc.org/dog-breeds/cane-corso/",
  },
  {
    slug: "bull-terrier",
    nameKo: "불테리어",
    nameEn: "Bull Terrier",
    tagline: "독특한 머리 모양보다 먼저, 단단한 몸의 움직임을 차분히 전환시키는 연습이 가능한지 살펴보세요.",
    group: "terrier",
    tags: ["영국 불 타입 테리어", "힘과 끈기", "일관된 긍정 교육"],
    colors: ["#c9b99d", "#e3e3d7", "#3d3731"],
    origin: "영국",
    lineage: "불 타입 테리어",
    role: "19세기 영국에서 형성되어 반려·전시견으로 정착",
    size: "중형 · 표준상 고정 체고·체중 제한 없음",
    lifespan: "약 12~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 영국의 불 앤드 테리어 계통에서 형성되었고, 이후 독특한 외형과 균형 잡힌 체형을 갖춘 반려·전시견으로 정착했습니다.",
    today: "힘 있게 놀고 한 과제에 끈기 있게 몰입하거나 사람과 적극적으로 상호작용할 수 있지만 반응과 사회성은 개체마다 달라요.",
    guardianContext: "거친 몸놀이와 흥분을 안전하게 중단하는 신호를 가르치고 다른 개·작은 동물과의 관계는 품종 이미지가 아닌 실제 반응으로 판단하세요.",
    opening: "불테리어는 19세기 영국에서 불 타입 견종과 테리어 계통을 바탕으로 형성된 견종입니다. 오늘날에는 독특한 외형의 반려견으로 알려져 있습니다.",
    roleToHome: "테리어의 끈기와 단단한 몸은 활기찬 놀이와 높은 참여로 나타날 수 있습니다. 힘을 안전하게 조절하고 차분히 쉬는 교육이 중요해요.",
    reality: "유쾌한 이미지나 독특한 얼굴이 양육 난도를 설명하지는 않습니다. 충분한 활동, 일관된 교육과 다른 동물에 대한 실제 반응 확인이 필요해요.",
    care: ["흥분한 몸놀이를 멈추고 자리로 이동하는 신호를 보상 기반으로 연습하세요.", "다른 개와 작은 동물에 대한 반응은 안전한 거리와 장비 안에서 개체별로 확인하세요.", "반복 달리기만 시키지 말고 냄새 탐색과 씹기, 문제 해결 과제를 함께 제공하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "힘 있게 걷기", description: "충분히 움직이고 냄새를 탐색해요." }, { time: "낮", title: "씹기와 휴식", description: "안전한 씹을 거리 뒤 차분히 쉬어요." }, { time: "저녁", title: "중단 신호 연습", description: "놀이와 멈춤을 짧게 번갈아 해요." }],
    related: [["jack-russell-terrier", "테리어의 끈기와 활동성을 공유하지만 체격과 힘의 규모를 비교해 보세요."], ["boxer", "단단한 몸과 활기찬 교감의 공통점, 체형과 더위 관리의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BULL-TERRIER-11.html",
    akcUrl: "https://www.akc.org/dog-breeds/bull-terrier/",
  },
];

export const detailBatchESlugs = seeds.map((seed) => seed.slug);

export const detailBatchE = seeds.map((seed) => ({
  slug: seed.slug,
  contentStatus: "mvp-editorial-draft",
  nameKo: seed.nameKo,
  nameEn: seed.nameEn,
  tagline: seed.tagline,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`,
  catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: {
    src: `/illustrations/v3/${seed.slug}-history.webp`,
    alt: historyAltOverrides[seed.slug] ?? `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화`,
  },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: { originalRole: seed.originalRole, today: seed.today, guardianContext: seed.guardianContext },
  story: { opening: seed.opening, roleToHome: seed.roleToHome, reality: seed.reality },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "개체의 체력에 맞춘 규칙적인 산책과 놀이가 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 빗질과 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.care,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: seed.days,
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
    ...(historySources[seed.slug] ?? []),
    ...(seed.evidenceUrl ? [{ title: "Gastric Dilation and Volvulus in Small Animals", organization: "MSD Veterinary Manual", url: seed.evidenceUrl, checkedAt: "2026-08-29" }] : []),
  ],
})) satisfies Breed[];
