import type { Breed } from "./schema";
import { withTopicParticle } from "../../lib/korean-particles";

const checkedAt = "2026-08-04";
const healthDraft = "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 품종 경향만으로 질환을 예측하거나 진단하지 않으며, 개체의 호흡·보행·피부·눈·심장 변화를 발견하면 수의사와 상의하세요.";
type Label = Breed["tendencies"]["activity"]["label"];

type Draft = {
  slug: string; nameKo: string; nameEn: string; tagline: string; group: Breed["catalog"]["group"];
  tags: string[]; colors: [string, string, string]; origin: string; lineage: string; role: string; size: string; lifespan: string;
  history: string; present: string; guide: string; reality: string; care: [string, string, string];
  storyOpening?: string; storyContinuation?: string;
  levels: [Label, Label, Label, Label, Label, Label]; related: [string, string]; relatedCopy: [string, string];
  fci: string; rkc: string;
};

const drafts: Draft[] = [
  { slug: "german-spitz", nameKo: "저먼 스피츠", nameEn: "German Spitz", tagline: "한 품종 안의 여러 크기와 외모 너머로, 집과 농가의 변화를 재빨리 알리던 스피츠의 빠른 반응을 살펴봐요.", group: "spitz-primitive", tags: ["포메라니안 포함", "빠른 알림 반응", "풍성한 이중모"], colors: ["#d7aa77", "#e9dfc6", "#46372c"], origin: "독일", lineage: "유럽의 오래된 스피츠형 개에서 이어진 다섯 바라이어티", role: "농가와 집 주변을 살피던 알림견·반려견", size: "초소형부터 중형 이상까지 바라이어티별 차이 큼", lifespan: "약 12년 이상(RKC 참고, 개체별 차이 있음)", history: "집과 농가 주변의 소리와 방문을 빠르게 알아차리고 사람에게 알리는 역할을 해왔습니다.", present: "현대 가정에서도 작은 소리와 움직임에 빠르게 반응하거나 목소리로 표현할 수 있지만 경험과 개체에 따라 달라요.", guide: "창밖 자극을 줄인 휴식처와 조용히 자리로 돌아오는 연습을 준비하고, 두꺼운 털 속 피부까지 정기적으로 확인하세요.", storyOpening: "저먼 스피츠는 독일과 중부 유럽에서 집과 농가 주변을 살피고 낯선 방문이나 변화를 알리던 스피츠형 개들을 바탕으로 발전했습니다. 작은 직립 귀와 풍성하게 선 이중모, 등 위로 말린 꼬리 같은 공통된 외형이 여러 크기에서 이어졌습니다.", storyContinuation: "이후 크기에 따라 울프스피츠, 자이언트, 미디엄, 미니어처, 포메라이언의 다섯 바라이어티로 정리됐습니다. 오늘날에는 주로 반려견으로 지내지만 주변 소리와 움직임을 빠르게 알아차리고 목소리로 알리는 모습이 개체에 따라 나타날 수 있어요.", reality: "이 페이지의 대표 그림은 포메라니안 바라이어티예요. 저먼 스피츠는 크기별 생활 부담이 크게 달라 원하는 타입을 먼저 확인해야 합니다.", care: ["바라이어티의 성견 크기와 체형을 확인한 뒤 생활 공간을 계획하세요.", "털갈이철에는 속털까지 나누어 빗고 피부 상태를 함께 살피세요.", "알림 짖음은 혼내기보다 자극과 거리를 조절하고 대체 행동을 가르치세요."], levels: ["중간","중간","중간","높은 편","높은 편","높은 편"], related: ["japanese-spitz","maltese"], relatedCopy: ["스피츠형 외모와 알림 성향의 공통점, 체격과 계통 차이를 살펴보세요.","작은 흰 반려견과 비교해 피모 구조와 알림 성향의 차이를 확인해요."], fci: "097g05-en.pdf", rkc: "toy/pomeranian" },
  { slug: "shetland-sheepdog", nameKo: "셔틀랜드 시프독", nameEn: "Shetland Sheepdog", tagline: "작은 콜리 같은 외모 뒤에는 바람 센 섬에서 가축과 주변 변화를 세밀하게 읽던 목양견의 집중력이 있어요.", group: "herding", tags: ["섬 지역 목양견", "높은 학습 자극", "풍성한 장모"], colors: ["#b88b62", "#dce4d1", "#44362e"], origin: "영국·셰틀랜드 제도", lineage: "셰틀랜드의 소형 작업견과 콜리형 목양견 계통", role: "양과 농가 동물을 관리하고 변화를 알리던 목양견", size: "소형·중형 경계 · 약 35~37cm", lifespan: "12년 이상(RKC 참고, 개체별 차이 있음)", history: "바람이 거센 섬의 농가에서 가축의 움직임을 살피고 사람의 신호에 민첩하게 협력했습니다.", present: "사람의 표정과 움직임을 빨리 읽고 달리는 대상이나 소리에 반응할 수 있으나 모든 개체가 같은 몰이 행동을 보이지는 않아요.", guide: "냄새 찾기와 방향 전환 같은 짧은 협업 과제를 주고, 소리 자극에서 충분히 떨어져 차분해지는 경험을 쌓아 주세요.", storyOpening: "셔틀랜드 시프독은 스코틀랜드 북쪽의 셰틀랜드 제도에서 농가의 작은 가축을 관리하고 주변 변화를 알리던 소형 작업견을 바탕으로 발전했습니다. 거센 바람과 제한된 자원의 섬 환경에서는 크기가 작으면서도 민첩하게 움직이고 사람의 신호를 세밀하게 읽는 능력이 중요했습니다.", storyContinuation: "이후 콜리형 목양견의 영향과 영국 본토에서의 번식 과정을 거치며 작은 체격, 긴 쐐기형 머리와 풍성한 이중모를 지닌 오늘의 모습이 정리됐습니다. 현재는 반려견과 여러 도그 스포츠에서 만나지만 움직임과 소리에 빠르게 주의를 기울이는 모습이 개체에 따라 나타날 수 있어요.", reality: "작은 체격이 낮은 활동량을 뜻하지 않아요. 두뇌 활동과 알림 행동 관리, 긴 이중모 손질을 함께 계산해야 합니다.", care: ["빗질은 겉털만 훑지 말고 귀 뒤와 겨드랑이의 엉킴까지 확인하세요.", "움직이는 사람이나 자전거를 향한 추적은 거리 확보와 대체 행동으로 관리하세요.", "소리에 민감한 개체에게는 예측 가능한 조용한 휴식 공간을 마련하세요."], levels: ["높은 편","높은 편","중간","높은 편","높은 편","높은 편"], related: ["border-collie","australian-shepherd"], relatedCopy: ["목양 배경은 같지만 과제 강도와 생활 리듬의 차이를 비교해 보세요.","사람과 협력하는 목양견 사이의 체격·피모·활동 부담을 볼 수 있어요."], fci: "088g01-en.pdf", rkc: "pastoral/shetland-sheepdog" },
  { slug: "australian-shepherd", nameKo: "오스트레일리안 셰퍼드", nameEn: "Australian Shepherd", tagline: "이름과 달리 미국 목장에서 정립된, 사람의 신호와 가축의 움직임을 오래 읽어 온 활동적인 목양견이에요.", group: "herding", tags: ["미국 목장견", "높은 활동량", "지속적인 협업"], colors: ["#8d756b", "#d5e0d6", "#30383a"], origin: "미국", lineage: "미국 서부 목장에서 정립된 목양견", role: "가축을 이동시키고 목장 일에 협력한 작업견", size: "중형 · 약 46~58cm", lifespan: "10년 이상(RKC 참고, 개체별 차이 있음)", history: "넓은 목장에서 가축의 흐름을 읽고 먼 거리에서도 사람의 신호에 맞춰 오래 움직였습니다.", present: "움직임을 통제하려 하거나 과제가 없을 때 스스로 일을 만들 수 있지만 양육 환경과 개체 경험의 영향이 커요.", guide: "달리기만 반복하기보다 냄새 탐색, 신호 구분, 멈춤과 휴식을 한 세트로 구성해 흥분을 낮추는 능력도 길러 주세요.", storyOpening: "오스트레일리안 셰퍼드의 이름에는 여러 지역을 거친 목양견의 이동 역사가 남아 있지만, 오늘날 알려진 품종은 미국에서 정립됐습니다. 19세기 후반부터 20세기 미국 서부 목장에서 다양한 가축을 이동시키고 목장주와 오래 협력할 수 있는 다목적 작업견으로 발전했습니다.", storyContinuation: "넓은 목장에서 가축의 흐름을 읽고 먼 거리의 신호에 맞춰 방향을 바꾸는 능력, 민첩하고 지구력 있는 중형 체형이 중요하게 여겨졌습니다. 현재는 반려견과 여러 활동 분야에서 만나며 움직이는 대상을 세밀하게 살피거나 계속할 과제를 찾는 모습이 개체에 따라 나타날 수 있어요.", reality: "예쁜 털색만 보고 선택하기에는 활동과 학습 요구가 큽니다. 매일 함께할 시간과 과제를 현실적으로 확보해야 해요.", care: ["성장기에는 과도한 점프보다 균형 잡힌 평지 활동을 제공하세요.", "아이·자전거·다른 동물을 모으려는 행동은 안전거리와 대체 과제로 관리하세요.", "운동 뒤 스스로 쉬는 연습도 일상 루틴에 함께 포함하세요."], levels: ["높은 편","높은 편","중간","높은 편","높은 편","중간"], related: ["border-collie","shetland-sheepdog"], relatedCopy: ["높은 협업 욕구를 공유하지만 집중 방식과 개체별 리듬을 비교해요.","목양견의 공통점과 체격·피모 관리 부담의 차이를 볼 수 있어요."], fci: "342g01-en.pdf", rkc: "pastoral/australian-shepherd" },
  { slug: "rottweiler", nameKo: "롯트와일러", nameEn: "Rottweiler", tagline: "강한 인상보다 먼저, 가축과 짐을 지키며 사람 곁에서 침착하게 힘을 쓰던 작업견의 책임을 봐야 해요.", group: "guardian-working", tags: ["가축 몰이 배경", "큰 힘", "신중한 사회화"], colors: ["#766151", "#d9d6c8", "#292a27"], origin: "독일·로트바일", lineage: "로마 시대 몰이견 계통에서 독일 남부 작업견으로 정립", role: "가축 이동·경비와 수레 운반을 돕던 작업견", size: "대형 · 약 56~69cm", lifespan: "10년 이상(RKC 참고, 개체별 차이 있음)", history: "가축을 이동시키고 재산을 지키며 때로는 짐을 끄는 일에서 침착한 힘과 사람과의 협력이 요구됐습니다.", present: "낯선 상황을 신중히 관찰하거나 몸으로 공간을 통제할 수 있으나 품종만으로 공격성을 예측할 수는 없어요.", guide: "어릴 때부터 안전한 거리의 다양한 경험, 보상 기반 핸들링과 보호자가 통제할 수 있는 리드 기술을 준비하세요.", reality: "큰 힘은 작은 실수도 크게 만들 수 있습니다. 주거 규정, 교육 지원, 이동 동선과 의료비까지 입양 전에 확인해야 해요.", care: ["미끄러운 바닥을 줄이고 성장기 체중과 관절 부담을 꾸준히 확인하세요.", "낯선 사람이나 개와의 인사를 강요하지 말고 충분한 거리를 보장하세요.", "힘으로 제압하지 말고 예측 가능한 규칙과 보상으로 협력 관계를 만드세요."], levels: ["중간","중간","중간","높은 편","높은 편","낮은 편"], related: ["dobermann","boxer"], relatedCopy: ["경비·작업 배경을 공유하지만 체형과 반응 방식의 차이를 비교해요.","독일 작업견 사이의 활동성과 관계 형성 방식을 살펴보세요."], fci: "147g02-en.pdf", rkc: "working/rottweiler" },
  { slug: "boxer", nameKo: "복서", nameEn: "Boxer", tagline: "단단한 체형과 익살스러운 표정 안에, 가족과 가까이 움직이며 경계하고 협력해 온 독일 작업견의 활력이 있어요.", group: "guardian-working", tags: ["독일 작업견", "활기찬 교감", "더위 주의"], colors: ["#c58d62", "#e5ddc9", "#493529"], origin: "독일", lineage: "불렌바이서 계통을 바탕으로 19세기 말 정립", role: "사냥 보조에서 경비·작업견으로 전환", size: "중대형 · 약 53~63cm", lifespan: "10년 이상(RKC 참고, 개체별 차이 있음)", history: "큰 사냥감을 붙잡던 불렌바이서 계통에서 이어져, 이후 가축 상인과 정육업자를 돕고 사람과 재산을 지키는 작업견으로 정립됐습니다.", present: "가족과 몸으로 놀고 적극적으로 참여하려 할 수 있지만 흥분 수준과 타인에 대한 반응은 개체마다 달라요.", guide: "짧고 즐거운 훈련과 차분한 휴식을 번갈아 제공하고, 더운 날에는 호흡과 활동 시간을 세심히 조절하세요.", reality: "짧은 주둥이와 탄탄한 몸은 더위와 운동 강도를 더 신중히 봐야 한다는 뜻이기도 합니다.", care: ["더운 날과 습한 날에는 짧게 활동하고 호흡 회복 상태를 확인하세요.", "사람에게 뛰어오르는 행동은 어릴 때부터 네 발을 바닥에 두는 연습으로 바꿔 주세요.", "성장기 관절에 부담이 되는 반복 점프와 미끄러운 바닥을 줄이세요."], levels: ["높은 편","중간","중간","높은 편","중간","낮은 편"], related: ["rottweiler","boston-terrier"], relatedCopy: ["독일 작업견이라는 공통점과 체형·활동 리듬을 비교해요.","짧은 주둥이의 공통점과 체격 및 운동 부담의 큰 차이를 살펴보세요."], fci: "144g02-en.pdf", rkc: "working/boxer" },
  { slug: "great-dane", nameKo: "그레이트 덴", nameEn: "Great Dane", tagline: "압도적인 키 뒤에는 사냥과 영지 경비에서 사람 곁을 지켜 온 대형견의 역사와 거대한 일상 비용이 있어요.", group: "guardian-working", tags: ["초대형 체격", "독일계 대형견", "생활 공간 점검"], colors: ["#b69a78", "#dde1d7", "#393b39"], origin: "독일", lineage: "대형 사냥견과 마스티프형 계통을 바탕으로 정립", role: "큰 사냥감 추적과 영지 경비, 동반 역할", size: "초대형 · 약 72~90cm", lifespan: "10년 미만이 흔함(RKC 참고, 개체별 차이 있음)", history: "큰 사냥감을 상대하고 영지를 지키는 역할에서 긴 다리, 힘, 사람 곁에서의 침착함이 중요했습니다.", present: "가정에서는 사람 가까이 머무는 온화한 모습을 보일 수 있지만 체격만으로도 이동과 통제에 큰 준비가 필요해요.", guide: "넓고 미끄럽지 않은 동선, 큰 침대와 차량 이동 수단을 준비하고 성장기 운동과 급여를 수의사와 상의하세요.", reality: "차분해 보여도 초대형견의 식비·의료비·수명·주거 제약은 큽니다. 감당 가능한지를 외모보다 먼저 판단해야 해요.", care: ["성장기에는 대형견용 영양과 체형을 수의사와 정기적으로 확인하세요.", "미끄러운 바닥과 급격한 계단 이동을 줄이고 넉넉한 회전 공간을 확보하세요.", "식사 전후의 격한 운동을 피하고 갑작스러운 복부 팽창은 즉시 진료받으세요."], levels: ["중간","중간","중간","높은 편","중간","낮은 편"], related: ["greyhound","bernese-mountain-dog"], relatedCopy: ["긴 다리의 대형견이지만 역사와 활동 리듬이 어떻게 다른지 비교해요.","큰 체격이 만드는 공간·건강·비용 부담을 같은 기준으로 살펴보세요."], fci: "235g02-en.pdf", rkc: "working/great-dane" },
  { slug: "alaskan-malamute", nameKo: "알래스칸 말라뮤트", nameEn: "Alaskan Malamute", tagline: "늑대를 닮은 외모보다 먼저, 북극권에서 무거운 짐을 오래 옮긴 힘과 더위·탈출 관리의 현실을 봐야 해요.", group: "northern-working", tags: ["북극권 운반견", "강한 지구력", "두꺼운 이중모"], colors: ["#87918e", "#dce5df", "#303b3d"], origin: "미국·알래스카", lineage: "알래스카 원주민 공동체와 살아온 북방 스피츠형 썰매견", role: "무거운 화물과 썰매를 장거리로 운반", size: "대형 · 약 58~64cm", lifespan: "10년 이상(RKC 참고, 개체별 차이 있음)", history: "혹독한 북극 환경에서 공동체와 함께 무거운 짐을 안정적으로 옮기는 힘과 지구력이 중요했습니다.", present: "당기는 힘과 탐색·굴파기 욕구가 생활에서 나타날 수 있지만 개체의 경험과 환경에 따라 정도가 달라요.", guide: "선선한 시간에 꾸준히 움직이고, 튼튼한 장비와 탈출 방지 울타리, 파도 괜찮은 탐색 공간을 마련하세요.", reality: "산책 횟수만 늘리는 것으로 충분하지 않아요. 더위, 큰 힘, 털갈이와 다른 동물에 대한 실제 반응을 함께 관리해야 합니다.", care: ["기온과 습도가 높은 시간에는 활동을 피하고 시원한 실내를 유지하세요.", "문·울타리 아래와 잠금 장치를 확인해 탈출과 굴파기를 예방하세요.", "작은 동물과의 동거는 품종 이미지가 아닌 해당 개체의 실제 반응으로 판단하세요."], levels: ["높은 편","중간","높은 편","높은 편","중간","높은 편"], related: ["samoyed","akita"], relatedCopy: ["북방 작업견의 공통점과 운반·교감 방식의 차이를 비교해요.","대형 스피츠 사이의 활동, 관계, 더위 관리 부담을 살펴보세요."], fci: "243g05-en.pdf", rkc: "working/alaskan-malamute" },
  { slug: "jack-russell-terrier", nameKo: "잭 러셀 테리어", nameEn: "Jack Russell Terrier", tagline: "작은 몸 안에 땅속 목표를 끝까지 찾던 테리어의 속도와 집요함이 있어, 귀여움보다 할 일을 먼저 준비해야 해요.", group: "companion", tags: ["굴 사냥 테리어", "높은 추적 욕구", "작지만 활동적"], colors: ["#d4b486", "#e4e0ce", "#473a2f"], origin: "영국·잉글랜드", lineage: "19세기 폭스테리어 계통에서 발달", role: "여우를 굴에서 찾아내는 사냥 보조견", size: "소형 · 약 25~30cm", lifespan: "12년 이상(RKC 참고, 개체별 차이 있음)", history: "말을 탄 사냥대와 움직이며 냄새를 쫓고 좁은 굴까지 들어가 목표를 찾아내는 끈기와 민첩성이 요구됐습니다.", present: "작은 움직임을 쫓거나 땅을 파고 과제에 집요하게 몰입할 수 있지만 모든 개체의 강도는 같지 않아요.", guide: "긴 줄 산책과 냄새 찾기, 땅을 파도 되는 장소를 제공하고 흥분 뒤 자리로 돌아와 쉬는 연습을 함께 해주세요.", reality: "작은 체격은 쉬운 양육을 보장하지 않습니다. 활동과 추적 욕구를 채우지 못하면 보호자가 원치 않는 일이 생길 수 있어요.", care: ["야생동물과 작은 반려동물을 향한 추적은 리드와 울타리로 예방하세요.", "합법적이고 안전하게 땅을 팔 수 있는 대체 공간이나 노즈워크를 제공하세요.", "계속 공을 던지기보다 흥분을 낮추는 냄새 탐색과 휴식을 섞어 주세요."], levels: ["높은 편","높은 편","높은 편","중간","높은 편","낮은 편"], related: ["yorkshire-terrier","dachshund"], relatedCopy: ["작은 테리어의 빠른 반응과 활동·피모 부담 차이를 살펴보세요.","굴 사냥 배경을 공유하지만 체형과 움직임 방식은 크게 달라요."], fci: "345g03-en.pdf", rkc: "terrier/jack-russell-terrier" },
  { slug: "boston-terrier", nameKo: "보스턴 테리어", nameEn: "Boston Terrier", tagline: "단정한 턱시도 무늬와 사람 친화적인 도시 반려견의 역사 뒤에, 호흡과 눈을 세심히 볼 책임이 있어요.", group: "companion", tags: ["미국 도시 반려견", "사람과의 교감", "더위 주의"], colors: ["#9b9285", "#e6dfce", "#313332"], origin: "미국·보스턴", lineage: "19세기 미국에서 불독·테리어형 개를 바탕으로 반려견으로 정립", role: "도시 가정의 소형 반려견", size: "소형 · 약 7~11kg 이하 등급", lifespan: "10년 이상(RKC 참고, 개체별 차이 있음)", history: "보스턴의 도시 생활 속에서 사람 가까이 지내는 작고 단정한 반려견으로 점차 정립됐습니다.", present: "가족 활동에 적극적으로 참여하고 놀이를 즐길 수 있지만 호흡 능력과 흥분 회복은 개체별로 확인해야 해요.", guide: "더운 날 활동을 줄이고 목을 압박하지 않는 장비를 쓰며, 눈 주변과 호흡 소리의 변화를 일상적으로 살펴보세요.", reality: "작고 친근한 이미지가 건강 부담을 지우지는 않습니다. 외모보다 편안한 호흡과 기능적인 체형을 우선해야 해요.", care: ["더위와 습도가 높은 날에는 짧게 움직이고 호흡이 안정되는지 확인하세요.", "돌출된 눈이 가지나 거친 놀이에 다치지 않도록 환경을 정리하세요.", "코골이와 거친 숨을 정상으로 단정하지 말고 변화가 있으면 진료받으세요."], levels: ["중간","중간","중간","높은 편","중간","낮은 편"], related: ["french-bulldog","boxer"], relatedCopy: ["짧은 주둥이의 소형 반려견 사이에서 체형과 생활 부담을 비교해요.","계통의 접점과 체격·활동 요구의 큰 차이를 살펴보세요."], fci: "140g09-en.pdf", rkc: "utility/boston-terrier" },
  { slug: "newfoundland", nameKo: "뉴펀랜드", nameEn: "Newfoundland", tagline: "거대한 검은 몸과 온화한 인상 뒤에는 차가운 바다에서 어부와 함께 줄을 옮기고 사람을 도운 작업의 역사가 있어요.", group: "guardian-working", tags: ["캐나다 수상 작업견", "초대형 체격", "풍성한 피모"], colors: ["#69716e", "#d8e1db", "#293332"], origin: "캐나다·뉴펀들랜드", lineage: "북대서양 어촌의 대형 수상 작업견", role: "어망·줄 운반과 배 주변의 수상 작업 보조", size: "초대형 · 약 66~71cm, 50~68kg", lifespan: "10년 미만일 수 있음(RKC 참고, 개체별 차이 있음)", history: "차가운 항구에서 어부 곁을 지키고 물속의 줄이나 장비를 옮기는 데 큰 힘과 수영 능력을 사용했습니다.", present: "사람 가까이에서 침착하게 협력할 수 있지만 물을 좋아하는지는 개체 경험에 따라 다르며 억지 입수는 위험해요.", guide: "큰 몸이 편히 돌고 쉴 공간, 젖은 이중모를 완전히 말릴 시간과 미끄럼 방지 동선을 준비하세요.", reality: "온화하다는 평판만으로 선택할 수 없어요. 침·털·더위·초대형견 의료비와 짧을 수 있는 수명을 함께 받아들여야 합니다.", care: ["수영은 구명조끼와 안전한 출구를 갖춘 곳에서 개체의 선택을 존중하며 시작하세요.", "젖은 속털과 피부를 완전히 말려 습진과 엉킴을 예방하세요.", "성장기 체중과 관절, 심장 상태를 수의사와 정기적으로 확인하세요."], levels: ["중간","중간","중간","높은 편","중간","높은 편"], related: ["bernese-mountain-dog","great-dane"], relatedCopy: ["초대형 작업견의 공통점과 물·산악 환경에서의 역할 차이를 비교해요.","거대한 체격이 만드는 주거·비용·건강 부담을 함께 살펴보세요."], fci: "050g02-en.pdf", rkc: "working/newfoundland" },
];

const levelNote: Record<Label, string> = { "낮은 편": "상대적으로 부담이 낮을 수 있지만 개체별 확인이 필요해요.", "중간": "일상에서 꾸준히 충족하고 개체 반응을 살펴야 해요.", "높은 편": "충분한 시간과 구체적인 관리 계획이 필요해요.", "개체별 확인 필요": "품종만으로 판단하지 말고 해당 개체를 직접 확인하세요." };

const conciseLineages: Partial<Record<string, string>> = {
  "german-spitz": "독일 스피츠 계통",
  "shetland-sheepdog": "셰틀랜드 목양견 계통",
  "australian-shepherd": "미국 목장견 계통",
};

const conciseRoles: Partial<Record<string, string>> = {
  "german-spitz": "알림견·반려견",
  "shetland-sheepdog": "목양견·알림견",
  "australian-shepherd": "목양견",
};

const historyAltOverrides: Partial<Record<string, string>> = {
  "german-spitz": "유럽 농가 마당에서 집 주변을 살피는 주황색 포메라니안 바라이어티를 그린 편집 수채화",
  "jack-russell-terrier": "말을 탄 사냥대 곁의 생울타리와 땅 냄새를 살피는 흰색과 황갈색 잭 러셀 테리어를 그린 편집 수채화",
  rottweiler: "독일 로트바일의 가축 시장과 수레 곁에서 소 떼 이동과 운반을 돕는 롯트와일러를 그린 편집 수채화",
  boxer: "19세기 말 독일의 작업장 마당에서 상인 곁을 지키는 황갈색과 흰색 복서를 그린 편집 수채화",
  newfoundland: "뉴펀들랜드 항구에서 어부에게 젖은 줄과 어망을 옮기는 검은 뉴펀랜드를 그린 편집 수채화",
  "alaskan-malamute": "알래스카 북극권 해안 마을에서 무거운 짐을 실은 썰매를 사람과 함께 끄는 알래스칸 말라뮤트를 그린 편집 수채화",
  "boston-terrier": "미국 보스턴의 붉은 벽돌 주택가에서 가족과 함께 선 검정과 흰색 보스턴 테리어를 그린 편집 수채화",
};

const additionalSources: Partial<Record<string, Breed["sources"]>> = {
  "german-spitz": [{ title: "Pomeranian", organization: "American Kennel Club", url: "https://www.akc.org/dog-breeds/pomeranian/", checkedAt }],
  "shetland-sheepdog": [{ title: "Shetland Sheepdog", organization: "American Kennel Club", url: "https://www.akc.org/dog-breeds/shetland-sheepdog/", checkedAt }, { title: "Shetland Sheepdog History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/shetland-sheepdog-history/", checkedAt: "2026-08-29" }],
  "australian-shepherd": [{ title: "Australian Shepherd", organization: "American Kennel Club", url: "https://www.akc.org/dog-breeds/australian-shepherd/", checkedAt }, { title: "Australian Shepherd History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/australian-shepherd-history/", checkedAt: "2026-08-29" }],
  "jack-russell-terrier": [{ title: "Jack Russell Terrier", organization: "The Royal Kennel Club", url: "https://www.royalkennelclub.com/jackrussellterrier", checkedAt: "2026-08-29" }],
  "great-dane": [{ title: "Gastric Dilation and Volvulus in Small Animals", organization: "MSD Veterinary Manual", url: "https://www.msdvetmanual.com/digestive-system/surgical-problems-of-the-gastrointestinal-tract-in-small-animals/gastric-dilation-and-volvulus-in-small-animals", checkedAt: "2026-08-29" }],
  rottweiler: [{ title: "Rottweiler History: From Working Dog to Sporting, Therapy Dog", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/rottweiler-history/", checkedAt: "2026-08-29" }],
  boxer: [{ title: "Boxer History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/boxer-history/", checkedAt: "2026-08-29" }],
  newfoundland: [{ title: "Newfoundland Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/newfoundland-history/", checkedAt: "2026-08-29" }],
  "alaskan-malamute": [{ title: "Alaskan Malamute Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/lifestyle/alaskan-malamute-history-arctic-sled/", checkedAt: "2026-08-29" }],
  "boston-terrier": [{ title: "Boston Terrier Breed History", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/boston-terrier-history/", checkedAt: "2026-08-29" }],
};

export const detailBatchD = drafts.map((d) => ({
  slug: d.slug, contentStatus: "mvp-editorial-draft" as const, nameKo: d.nameKo, nameEn: d.nameEn, tagline: d.tagline,
  palette: { primary: d.colors[0], secondary: d.colors[1], ink: d.colors[2] }, illustration: `/illustrations/v2/${d.slug}-card.webp`,
  catalog: { group: d.group, discoveryTags: d.tags }, historyVisual: { src: `/illustrations/v3/${d.slug}-history.webp`, alt: historyAltOverrides[d.slug] ?? `${d.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: d.origin, lineage: conciseLineages[d.slug] ?? d.lineage, originalRole: conciseRoles[d.slug] ?? d.role, size: d.size, lifespan: d.lifespan },
  behaviorClues: { originalRole: d.history, today: d.present, guardianContext: d.guide },
  story: { opening: d.storyOpening ?? `${withTopicParticle(d.nameKo)} ${d.lineage}입니다. ${d.history}`, roleToHome: d.storyContinuation ?? `${d.present} ${d.guide}`, reality: d.reality },
  tendencies: {
    activity: { label: d.levels[0], note: `활동 요구는 ${d.levels[0]}으로 봅니다. ${levelNote[d.levels[0]]}` }, mentalStimulation: { label: d.levels[1], note: `두뇌 자극은 ${d.levels[1]}으로 봅니다. ${levelNote[d.levels[1]]}` },
    independence: { label: d.levels[2], note: `독립성은 ${d.levels[2]}으로 봅니다. ${levelNote[d.levels[2]]}` }, socialConnection: { label: d.levels[3], note: `사회적 교감은 ${d.levels[3]}으로 봅니다. ${levelNote[d.levels[3]]}` },
    alerting: { label: d.levels[4], note: `알림 반응은 ${d.levels[4]}으로 봅니다. ${levelNote[d.levels[4]]}` }, grooming: { label: d.levels[5], note: `피모 관리는 ${d.levels[5]}으로 봅니다. ${levelNote[d.levels[5]]}` },
  },
  careNotes: d.care, healthEditorialNote: healthDraft,
  daySnapshot: [{ time: "아침", title: "몸과 환경 확인", description: "날씨와 컨디션에 맞춰 산책을 시작해요." }, { time: "낮", title: "역할을 닮은 놀이", description: d.guide }, { time: "저녁", title: "쉬고 기록하기", description: "피모와 몸 상태를 보고 조용히 쉬어요." }],
  related: [{ slug: d.related[0], reason: d.relatedCopy[0] }, { slug: d.related[1], reason: d.relatedCopy[1] }],
  sources: [{ title: `FCI Standard: ${d.nameEn}`, organization: "Fédération Cynologique Internationale", url: `https://www.fci.be/Nomenclature/Standards/${d.fci}`, checkedAt }, { title: d.nameEn, organization: "The Royal Kennel Club", url: `https://www.royalkennelclub.com/search/breeds-a-to-z/breeds/${d.rkc}/`, checkedAt }, ...(additionalSources[d.slug] ?? [])],
})) satisfies Breed[];
