import type { Breed } from "./schema";

const completedAt = "2026-08-20";

export const detailBatchA = [
  {
    slug: "chihuahua",
    contentStatus: "mvp-editorial-draft",
    nameKo: "치와와",
    nameEn: "Chihuahua",
    tagline: "아주 작은 몸 안에 또렷한 경계심과 사람 곁을 찾는 일상이 함께 있어요.",
    palette: { primary: "#ead9c8", secondary: "#f7f1e8", ink: "#4b342b" },
    illustration: "/illustrations/v2/chihuahua-card.webp",
    catalog: {
      group: "companion",
      discoveryTags: ["초소형 반려견", "경계 신호", "보온과 안전"],
    },
    historyVisual: {
      src: "/illustrations/v3/chihuahua-history.webp",
      alt: "19세기 말 멕시코 북부의 마을에서 가족 곁에 서 있는 작은 치와와를 그린 편집 삽화",
    },
    identity: {
      origin: "멕시코",
      lineage: "멕시코의 소형 반려견 계통",
      originalRole: "반려견",
      size: "초소형 · 약 13~20cm, 2.7kg 이하",
      lifespan: "약 14~16년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "사람 곁에서 지내는 반려견으로 자리해 온 배경이 있으며, 작은 체구와 또렷한 주변 반응을 함께 살펴볼 필요가 있습니다.",
      today: "집에서는 초인종이나 복도 소리를 먼저 알아차리거나 익숙한 사람 가까이에 머무는 모습이 보일 수 있지만, 반응의 빈도와 강도는 개체마다 다릅니다.",
      guardianContext: "몸집이 작다는 이유만으로 돌봄이 쉽다고 판단하지 말고, 높은 곳과 미끄러운 바닥, 추운 날의 보온, 안기기와 신체 접촉에 대한 실제 반응을 확인하세요.",
    },
    story: {
      opening: "치와와는 멕시코 치와와주의 이름을 딴 초소형 반려견입니다. 고대 톨텍 문명에서 길렀다고 전해지는 테치치와의 연관성이 자주 거론되지만, 지금의 치와와로 이어지는 정확한 계보는 단순하게 확정하기 어렵습니다.",
      roleToHome: "19세기 중반 이후 멕시코를 찾은 사람들이 치와와주에서 작은 개들을 발견해 미국으로 데려가면서 지금의 이름으로 알려지기 시작했습니다. 이후 매끄러운 단모와 부드러운 장모 두 피모 유형을 가진 오늘날의 견종으로 자리 잡았습니다.",
      reality: "작은 체구는 좁은 집에서도 눈에 띄게 편해 보일 수 있지만 안전한 이동과 부드러운 신체 다루기, 추위 대비, 혼자 쉬는 연습은 별도로 필요합니다. 어린이와 다른 동물이 있는 집에서는 실제 만남의 속도와 상호작용을 직접 살펴보세요.",
    },
    tendencies: {
      activity: { label: "중간", note: "짧은 산책과 실내 놀이를 여러 번으로 나누어 제공할 수 있어요." },
      mentalStimulation: { label: "중간", note: "냄새 찾기와 짧은 협력 과제로 일상의 자극을 구성해보세요." },
      independence: { label: "개체별 확인 필요", note: "사람 곁을 찾는 정도와 혼자 쉬는 능력은 경험에 따라 크게 달라져요." },
      socialConnection: { label: "높은 편", note: "익숙한 사람과 가까이 지내려는 모습이 소개되지만 실제 선호는 확인해야 해요." },
      alerting: { label: "높은 편", note: "낯선 소리와 움직임에 빠르게 알림 반응을 보일 가능성을 살펴보세요." },
      grooming: { label: "개체별 확인 필요", note: "단모와 장모에 따라 빗질 빈도와 피모 관리 부담이 달라집니다." },
    },
    careNotes: [
      "소파와 침대 주변의 점프 높이, 미끄러운 바닥, 사람 발에 부딪히기 쉬운 동선을 먼저 점검하세요.",
      "안기기와 옷 입히기를 당연하게 여기지 말고 짧은 접촉부터 보상과 함께 적응시켜 주세요.",
      "추운 날에는 떨림과 움직임 변화를 관찰하며 산책 길이와 보온 방식을 개체에 맞게 조절하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 초소형 체구와 치아·관절 관리에 관한 개별 검진 계획은 견종명만으로 판단하지 말고 담당 동물병원과 상의해야 합니다.",
    daySnapshot: [
      { time: "아침", title: "짧고 안전한 바깥 확인", description: "기온과 바닥 상태를 확인한 뒤 천천히 냄새를 맡을 시간을 주세요." },
      { time: "낮", title: "혼자 쉬는 작은 연습", description: "보호자와 잠시 떨어져 편안한 자리에서 쉬는 시간을 짧게 쌓아가요." },
      { time: "저녁", title: "소리와 접촉 적응", description: "생활 소리를 낮은 강도부터 경험하고 발과 몸을 부드럽게 만지는 연습을 해요." },
    ],
    related: [
      { slug: "maltese", reason: "비슷한 초소형 반려견이지만 피모 관리와 낯선 자극에 대한 실제 반응을 나란히 확인해보세요." },
      { slug: "shih-tzu", reason: "사람 곁에서 지내온 배경은 닮았지만 체형과 운동·피모 관리 조건은 다르게 살펴봐야 해요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 218 — Chihuahua",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/218g09-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Chihuahua Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/chihuahua/",
        checkedAt: completedAt,
      },
      {
        title: "Chihuahua History: Where the Breed Originated",
        organization: "American Kennel Club",
        url: "https://www.akc.org/expert-advice/dog-breeds/chihuahua-history/",
        checkedAt: completedAt,
      },
      {
        title: "Chihuahua Club Flier",
        organization: "American Kennel Club",
        url: "https://cdn.akc.org/Chihuahua-club-flier.pdf",
        checkedAt: "2026-08-29",
      },
    ],
  },
  {
    slug: "shih-tzu",
    contentStatus: "mvp-editorial-draft",
    nameKo: "시추",
    nameEn: "Shih Tzu",
    tagline: "사람 가까이에서 지내온 작은 반려견에게는 얼굴과 피모를 돌보는 차분한 일상이 필요해요.",
    palette: { primary: "#e3d6c6", secondary: "#f5eee4", ink: "#43362e" },
    illustration: "/illustrations/v2/shih-tzu-card.webp",
    catalog: {
      group: "companion",
      discoveryTags: ["소형 반려견", "사람 곁의 생활", "높은 피모 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/shih-tzu-history.webp",
      alt: "20세기 초 중국 궁정의 정원에서 시종들과 함께 걷는 흰색과 금색의 시추를 그린 편집 삽화",
    },
    identity: {
      origin: "티베트에 뿌리를 두고 중국에서 발전",
      lineage: "티베트계 소형 반려견",
      originalRole: "반려견",
      size: "소형 · 27cm 이하, 4.5~8kg",
      lifespan: "약 10~18년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "사람 곁에서 지내는 반려견으로 발전했으며, 사냥이나 가축 작업보다 함께 생활하는 역할이 중심이었습니다.",
      today: "집 안에서 가족이 머무는 방을 따라다니거나 가까운 휴식 자리를 찾는 모습을 볼 수 있지만, 낯선 사람과 혼자 있는 시간에 대한 반응은 개체마다 다릅니다.",
      guardianContext: "친근해 보이는 외모만 보지 말고 빗질과 얼굴 주변 관리에 협조하는지, 더운 날의 활동과 휴식이 편안한지, 혼자 쉬는 연습이 어느 정도 필요한지 확인하세요.",
    },
    story: {
      opening: "시추는 티베트의 작은 개들에 뿌리를 두고 중국 황실에서 반려견으로 발전한 것으로 알려져 있습니다. 정확한 초기 계보를 하나로 단정하기는 어렵지만, 궁정 안에서 사람 가까이 생활해 온 역사는 여러 기록과 그림에 남아 있습니다.",
      roleToHome: "20세기 초 유럽에 소개된 뒤 라사 압소와 구분되는 별도의 견종으로 정리되었고, 오늘날에는 세계 여러 지역에서 반려견으로 함께하고 있습니다. 몸보다 길게 자라는 풍성한 피모와 짧고 넓은 주둥이는 지금의 시추를 알아보게 하는 특징입니다.",
      reality: "얼굴과 피모를 매일 관리할 시간, 더위와 실내 온도를 조절할 환경, 짧고 편안한 산책이 필요합니다. 관리 접촉을 싫어하는 개체는 천천히 적응시켜야 합니다.",
    },
    tendencies: {
      activity: { label: "중간", note: "짧은 산책과 실내 놀이를 무리하지 않게 나누어 제공할 수 있어요." },
      mentalStimulation: { label: "중간", note: "간단한 냄새 찾기와 선택 과제로 지루함을 줄여주세요." },
      independence: { label: "개체별 확인 필요", note: "사람 곁에 있으려는 정도와 혼자 쉬는 능력은 개별 경험을 확인해야 해요." },
      socialConnection: { label: "높은 편", note: "반려 역할의 역사가 있지만 사람과 동물에 대한 반응은 직접 살펴보세요." },
      alerting: { label: "중간", note: "문밖 소리나 방문객을 알리는 반응의 빈도는 생활 경험에 따라 달라져요." },
      grooming: { label: "높은 편", note: "긴 피모와 얼굴 주변을 편안하게 유지하려면 규칙적인 관리가 필요해요." },
    },
    careNotes: [
      "빗질과 눈·입 주변 닦기를 한 번에 오래 하기보다 짧은 단계와 보상으로 익숙하게 해주세요.",
      "더운 날에는 한낮 산책을 피하고 실내 온도와 호흡 상태를 관찰하며 활동 강도를 조절하세요.",
      "짧은 주둥이와 체형에 맞는 목줄·하네스 선택은 개별 신체 상태를 본 뒤 전문가와 상의하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 눈·피부·치아와 호흡 상태를 포함한 예방 관리 일정은 이 설명만으로 정하지 말고 개별 진료를 바탕으로 계획하세요.",
    daySnapshot: [
      { time: "아침", title: "기온을 본 짧은 산책", description: "더위와 호흡을 살피며 냄새 맡기 중심의 여유 있는 산책을 해요." },
      { time: "낮", title: "가까이, 또 따로 쉬기", description: "가족 곁의 휴식과 혼자 편안히 쉬는 시간을 모두 경험하게 해주세요." },
      { time: "저녁", title: "짧은 얼굴·피모 관리", description: "빗과 손길을 천천히 보여주고 편안한 범위까지만 관리해요." },
    ],
    related: [
      { slug: "maltese", reason: "사람 곁을 선호하는 소형 장모견이라는 공통점과 서로 다른 피모 구조를 함께 살펴보세요." },
      { slug: "poodle", reason: "실내 교감이 중요한 후보이지만 운동 자극과 미용 관리의 방식이 어떻게 다른지 비교해보세요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 208 — Shih Tzu",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/208g09-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Shih Tzu Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/shih-tzu/",
        checkedAt: completedAt,
      },
      {
        title: "Shih Tzu History: How the Breed Came to Be",
        organization: "American Kennel Club",
        url: "https://www.akc.org/expert-advice/dog-breeds/shih-tzu-history/",
        checkedAt: completedAt,
      },
    ],
  },
  {
    slug: "poodle",
    contentStatus: "mvp-editorial-draft",
    nameKo: "푸들",
    nameEn: "Poodle",
    tagline: "우아한 곱슬 피모 안에는 물에서 회수하던 움직임과 크기별로 다른 생활 조건이 있어요.",
    palette: { primary: "#d7d0e3", secondary: "#f2eef4", ink: "#342e40" },
    illustration: "/illustrations/v2/poodle-card.webp",
    catalog: {
      group: "retriever-spaniel",
      discoveryTags: ["물새 회수 배경", "높은 학습 자극", "크기별 차이"],
    },
    historyVisual: {
      src: "/illustrations/v3/poodle-history.webp",
      alt: "유럽의 습지에서 물에 뜨는 회수용 더미를 물고 사람에게 돌아오는 스탠더드 푸들을 그린 편집 삽화",
    },
    historyVisibility: "hidden",
    identity: {
      origin: "유럽, 특히 독일과 프랑스에서 발전",
      lineage: "워터 리트리버 계통",
      originalRole: "물새 회수견",
      size: "토이·미니어처·미디엄·스탠더드",
      lifespan: "크기와 출처에 따라 범위가 달라 편집 검토 중",
    },
    behaviorClues: {
      originalRole: "물속에서 사냥한 새를 찾아 사람에게 가져오는 워터 리트리버로 일했으며, 수영과 회수에 맞는 움직임이 중요했습니다.",
      today: "공이나 장난감을 가져오고 새로운 규칙이나 냄새 찾기 과제에 집중하는 모습이 보일 수 있지만, 물을 좋아하는 정도와 학습 속도는 개체마다 다릅니다.",
      guardianContext: "학습이 빠르다는 평판만 기대하지 말고 매일 제공할 운동과 문제 해결 활동, 흥분 뒤 쉬는 연습, 정기 미용 비용과 접촉 적응을 크기별 생활 조건과 함께 확인하세요.",
    },
    story: {
      opening: "푸들은 유럽에서 물새를 찾아 물에서 회수하는 작업견으로 발전했습니다. 독일의 워터도그 전통과 프랑스에서의 발전이 모두 역사에 등장하며, 프랑스어 이름 카니시는 암컷 오리를 뜻하는 말과 연결됩니다.",
      roleToHome: "촘촘한 곱슬 피모와 탄탄한 몸, 물속에서 자유롭게 움직이는 능력은 회수 작업에서 중요했습니다. 이후 서로 다른 크기로 선택 번식되며 스탠더드·미디엄·미니어처·토이 네 바라이어티가 자리 잡았습니다.",
      reality: "토이부터 스탠더드까지 크기가 크게 달라 같은 이름 아래에서도 필요한 공간과 운동 강도가 다릅니다. 반복 미용과 빗질에 드는 시간, 지루함을 줄일 과제, 충분히 쉬는 리듬까지 마련할 수 있는지 실제 개체 기준으로 판단하세요.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "특히 큰 바라이어티는 충분한 신체 활동과 회복 시간을 함께 계획해야 해요." },
      mentalStimulation: { label: "높은 편", note: "새 규칙과 냄새 찾기, 회수 놀이처럼 바뀌는 과제가 도움이 될 수 있어요." },
      independence: { label: "중간", note: "사람과 협력하면서도 스스로 탐색하는 시간의 균형을 확인해보세요." },
      socialConnection: { label: "높은 편", note: "협력 작업의 배경이 있지만 낯선 대상에 대한 편안함은 개체별로 달라요." },
      alerting: { label: "중간", note: "주변 변화에 반응하는 정도와 소리 표현은 생활 환경에서 직접 확인하세요." },
      grooming: { label: "높은 편", note: "계속 자라는 곱슬 피모는 빗질과 전문 미용을 정기적으로 요구해요." },
    },
    careNotes: [
      "토이·미니어처·스탠더드를 한 가지 생활 조건으로 묶지 말고 성견 크기와 활동량을 먼저 확인하세요.",
      "미용 도구와 발·귀 접촉을 짧고 긍정적으로 연습하고 실제 미용 주기와 비용을 미리 계산하세요.",
      "공부를 많이 시키는 것만큼 흥분을 낮추고 아무 일 없이 쉬는 연습도 하루 일정에 포함하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 바라이어티별로 점검할 항목과 권장 검사가 다를 수 있으므로 크기와 가족력을 확인해 담당 동물병원과 예방 계획을 세우세요.",
    daySnapshot: [
      { time: "아침", title: "움직임과 냄새 찾기", description: "크기에 맞는 산책 중 간단한 탐색 과제를 섞어 집중할 기회를 주세요." },
      { time: "낮", title: "짧은 새 규칙 배우기", description: "쉬운 과제를 성공하면 멈추고 조용히 회복하는 시간을 이어가요." },
      { time: "저녁", title: "빗질과 몸 확인", description: "엉키기 쉬운 부위를 살피며 편안한 범위에서 짧게 관리해요." },
    ],
    related: [
      { slug: "labrador-retriever", reason: "회수 작업이라는 공통 뿌리와 피모·크기·일상 자극의 차이를 나란히 확인할 수 있어요." },
      { slug: "maltese", reason: "가정에서 자주 만나는 후보이지만 운동 과제와 피모 관리 방식은 크게 다를 수 있어요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 172 — Poodle",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/172g09-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Poodle (Standard) Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/poodle-standard/",
        checkedAt: completedAt,
      },
      {
        title: "Poodle History: Origins of a Water Retriever",
        organization: "American Kennel Club",
        url: "https://www.akc.org/expert-advice/dog-breeds/poodle-history/",
        checkedAt: completedAt,
      },
    ],
  },
  {
    slug: "dachshund",
    contentStatus: "mvp-editorial-draft",
    nameKo: "닥스훈트",
    nameEn: "Dachshund",
    tagline: "긴 몸과 짧은 다리 너머에는 땅굴의 냄새를 따라 스스로 판단하던 사냥개의 시간이 남아 있어요.",
    palette: { primary: "#d8b58f", secondary: "#f1e4d2", ink: "#4b3024" },
    illustration: "/illustrations/v2/dachshund-card.webp",
    catalog: {
      group: "dachshund",
      discoveryTags: ["땅굴 사냥 배경", "냄새 추적", "점프 동선 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/dachshund-history.webp",
      alt: "독일의 숲 가장자리에서 낮은 자세로 땅굴 냄새를 추적하는 닥스훈트를 표현한 편집 삽화",
    },
    identity: {
      origin: "독일",
      lineage: "땅굴 사냥 하운드 계통",
      originalRole: "지상과 지하에서 사냥감을 추적하는 사냥견",
      size: "래빗·미니어처·스탠더드 세 크기와 세 피모의 아홉 바라이어티",
      lifespan: "약 12~16년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "낮고 긴 몸으로 땅굴에 들어가 냄새를 쫓고 사냥감 앞에서 스스로 판단해야 했던 역할은 끈질긴 탐색과 독립적인 선택을 이해하는 중요한 단서입니다.",
      today: "산책에서 한 냄새에 오래 머물거나 담요 아래를 파고 장난감을 숨기는 행동, 문밖 움직임을 소리로 알리는 장면이 보일 수 있지만 모든 개체가 같은 강도로 행동하지는 않습니다.",
      guardianContext: "짧은 다리를 귀여운 특징으로만 보지 말고 계단과 소파 점프, 미끄러운 바닥, 체중 관리 동선을 점검하세요. 냄새를 쫓을 때의 집중과 호출 반응은 안전한 장소에서 직접 확인해야 합니다.",
    },
    story: {
      opening: "닥스훈트라는 이름은 독일어로 오소리 개라는 뜻과 연결됩니다. 낮고 긴 몸은 단순한 외형이 아니라 땅굴 속 사냥감을 추적하도록 발전한 역할의 흔적이며, 크기와 피모 유형도 하나로만 설명하기 어렵습니다.",
      roleToHome: "어두운 굴에서 냄새를 쫓고 스스로 결정을 내려야 했던 일은 오늘날 끈질긴 냄새 탐색, 파기, 물건 찾기, 뚜렷한 알림 소리로 보일 수 있습니다. 이는 가능한 경향이지 모든 닥스훈트의 행동을 미리 정하는 규칙은 아닙니다.",
      reality: "코를 쓰는 탐색을 제공하고 집에서는 점프와 미끄럼을 줄여야 합니다. 고집으로 단정하지 말고 동기가 되는 보상과 짧은 단계로 협력 방식을 찾아보세요.",
    },
    tendencies: {
      activity: { label: "중간", note: "체형을 고려한 규칙적 산책과 냄새 탐색을 무리 없이 구성해야 해요." },
      mentalStimulation: { label: "높은 편", note: "추적과 찾기처럼 코를 쓰는 과제가 일상의 만족에 도움이 될 수 있어요." },
      independence: { label: "높은 편", note: "혼자 판단하던 역할의 배경이 있어 협력 동기를 세심하게 찾아야 해요." },
      socialConnection: { label: "개체별 확인 필요", note: "가족과 낯선 사람, 다른 동물에 대한 반응은 사회화 경험에 따라 달라요." },
      alerting: { label: "높은 편", note: "문밖의 소리와 움직임을 목소리로 알리는 경향을 생활 공간에서 확인하세요." },
      grooming: { label: "개체별 확인 필요", note: "단모·장모·와이어헤어에 따라 빗질과 전문 관리의 정도가 달라져요." },
    },
    careNotes: [
      "자주 오르내리는 소파와 침대에는 안정적인 경사로를 고려하고 계단·바닥 동선을 미끄럽지 않게 정리하세요.",
      "산책 중 냄새 추적에 몰입할 가능성을 고려해 몸에 맞는 장비와 이탈 방지 습관을 확인하세요.",
      "체중과 움직임의 변화는 외형만으로 판단하지 말고 정기 검진에서 개별 상태를 함께 살펴보세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 긴 몸과 짧은 다리만으로 질환을 진단할 수 없으며, 체중·점프 동선·움직임 변화에 관한 개별 관리 계획은 담당 동물병원과 상의하세요.",
    daySnapshot: [
      { time: "아침", title: "서두르지 않는 냄새 산책", description: "짧은 다리에 맞는 속도로 냄새 한 지점을 충분히 탐색하게 해주세요." },
      { time: "낮", title: "안전한 파기와 찾기", description: "담요나 노즈워크 장난감으로 허용된 탐색 행동을 마련해요." },
      { time: "저녁", title: "점프 없는 휴식 동선", description: "미끄럼과 높은 오르내림 없이 잠자리까지 이동할 수 있는지 확인해요." },
    ],
    related: [
      { slug: "beagle", reason: "냄새를 따라가는 즐거움은 닮았지만 체형과 무리 작업의 배경은 다르게 비교해볼 수 있어요." },
      { slug: "basenji", reason: "독립적으로 판단하는 사냥 배경과 소리 표현, 운동 방식의 차이를 함께 살펴보세요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 148 — Dachshund",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/148g04-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Dachshund Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/dachshund/",
        checkedAt: completedAt,
      },
      { title: "Dachshund History: The Badger Dog’s Fascinating Past", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/dachshund-history-badger-dog-breed/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "beagle",
    contentStatus: "mvp-editorial-draft",
    nameKo: "비글",
    nameEn: "Beagle",
    tagline: "명랑한 인상만 보기 전에, 무리와 함께 냄새 길을 오래 따라가던 하운드의 하루를 상상해보세요.",
    palette: { primary: "#d9c29d", secondary: "#eef0df", ink: "#3a3628" },
    illustration: "/illustrations/v2/beagle-card.webp",
    catalog: {
      group: "scent-hound",
      discoveryTags: ["후각 하운드", "무리 작업", "풍부한 목소리"],
    },
    historyVisual: {
      src: "/illustrations/v3/beagle-history.webp",
      alt: "영국의 들판에서 여러 마리가 함께 냄새 길을 추적하는 비글의 역할을 표현한 편집 삽화",
    },
    identity: {
      origin: "영국",
      lineage: "소형 후각 하운드 계통",
      originalRole: "토끼류의 냄새를 무리로 추적하는 후각 하운드",
      size: "소형~중소형",
      lifespan: "약 10~15년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "여러 마리가 함께 지면의 냄새를 따라 오랫동안 사냥감을 추적한 역할은 강한 후각 탐색과 동료의 움직임, 목소리를 활용하는 방식을 이해하는 단서가 됩니다.",
      today: "산책 중 냄새 하나에 깊이 몰입하거나 먹을거리를 빠르게 찾고, 흥분하거나 떨어져 있을 때 다양한 소리를 내는 장면이 나타날 수 있지만 빈도와 강도는 개체마다 다릅니다.",
      guardianContext: "사교적이라는 평판만 믿기보다 리드줄 안에서 냄새를 따라가는 힘, 먹을거리 관리, 혼자 쉬는 반응, 공동주택에서의 소리 민감도를 실제 생활 조건에서 확인하세요.",
    },
    story: {
      opening: "비글은 영국에서 작은 사냥감을 무리로 추적해 온 후각 하운드입니다. 이름의 어원에는 여러 설이 있어 이 초안에서는 확정하지 않으며, 코와 동료를 활용한 원래 작업에 초점을 맞춥니다.",
      roleToHome: "넓은 들판에서 냄새 길을 오래 따라가던 일은 오늘날 산책 중 멈춰 냄새를 분석하고, 숨긴 간식을 찾고, 목소리로 상태를 표현하는 장면으로 이어질 수 있습니다. 그러나 모든 비글이 같은 수준으로 짖거나 다른 개를 좋아하는 것은 아닙니다.",
      reality: "냄새를 충분히 맡고 안전하게 추적할 환경이 필요합니다. 냄새에 몰입할 순간을 대비해 이탈을 막고, 음식과 소리 문제는 벌보다 환경 설계와 연습으로 다뤄야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "지속적인 산책과 탐색 활동을 매일 제공할 수 있는지 먼저 계산해보세요." },
      mentalStimulation: { label: "높은 편", note: "후각 탐색과 추적 과제가 단순 반복 산책보다 만족을 높일 수 있어요." },
      independence: { label: "높은 편", note: "냄새에 몰입해 스스로 경로를 선택하는 순간을 안전하게 관리해야 해요." },
      socialConnection: { label: "높은 편", note: "무리 작업의 배경이 있지만 실제 개·사람 관계는 개체별로 확인하세요." },
      alerting: { label: "높은 편", note: "짖음과 하울링 등 다양한 목소리의 빈도와 촉발 상황을 살펴보세요." },
      grooming: { label: "낮은 편", note: "짧은 피모지만 털 빠짐과 피부·발 상태 확인은 규칙적으로 필요해요." },
    },
    careNotes: [
      "냄새를 따라 갑자기 방향을 바꿀 수 있으므로 몸에 맞는 산책 장비와 문·울타리의 이탈 방지를 확인하세요.",
      "음식과 쓰레기 접근을 막는 보관 구조를 만들고 먹을거리 찾기를 안전한 놀이로 전환해 주세요.",
      "공동주택에서는 혼자 있을 때와 복도 소리를 들을 때의 목소리를 미리 관찰하고 점진적으로 연습하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 귀·피부·체중을 포함한 일상 점검은 질환을 단정하기 위한 것이 아니며, 검진 주기와 예방 관리는 담당 동물병원과 상의하세요.",
    daySnapshot: [
      { time: "아침", title: "냄새 길을 고르는 산책", description: "보호자가 끌고 가기보다 안전한 범위에서 코로 경로를 읽게 해주세요." },
      { time: "낮", title: "숨긴 먹을거리 찾기", description: "하루 급여량 안에서 쉬운 후각 과제를 만들고 성공 뒤에는 쉬어요." },
      { time: "저녁", title: "목소리 뒤의 상황 기록", description: "어떤 소리와 거리에서 반응했는지 기록해 다음 환경 조절에 활용해요." },
    ],
    related: [
      { slug: "dachshund", reason: "냄새 추적이라는 공통점과 땅굴 작업·무리 작업, 체형 관리의 차이를 비교해보세요." },
      { slug: "english-cocker-spaniel", reason: "야외에서 코를 쓰는 즐거움은 닮았지만 사람과 협력하는 방식과 피모 관리는 다르게 나타나요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 161 — Beagle",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/161g06-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Beagle Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/beagle/",
        checkedAt: completedAt,
      },
      { title: "Beagle History: From Ancient Small Pack-Hounds to Snoopy", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/beagle-history/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "english-cocker-spaniel",
    contentStatus: "mvp-editorial-draft",
    nameKo: "잉글리시 코커 스패니얼",
    nameEn: "English Cocker Spaniel",
    tagline: "부드러운 귀와 표정 뒤에는 덤불을 누비며 새를 찾아 올리고 회수하던 민첩한 협력자의 시간이 있어요.",
    palette: { primary: "#d2b39a", secondary: "#efe5d9", ink: "#46362c" },
    illustration: "/illustrations/v2/english-cocker-spaniel-card.webp",
    catalog: {
      group: "retriever-spaniel",
      discoveryTags: ["조렵견", "탐색과 회수", "귀·피모 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/english-cocker-spaniel-history.webp",
      alt: "영국의 낮은 덤불에서 새의 위치를 찾아 사람과 협력하는 잉글리시 코커 스패니얼을 표현한 편집 삽화",
    },
    identity: {
      origin: "영국",
      lineage: "랜드 스패니얼 계통의 조렵견",
      originalRole: "새를 찾아 날아오르게 하고 회수하는 조렵견",
      size: "중소형",
      lifespan: "약 12~14년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "덤불 속을 민첩하게 탐색해 새를 찾아 올리고 사람에게 회수해 온 역할은 코를 쓰는 활동과 운반, 가까운 거리의 협력을 이해하는 단서가 됩니다.",
      today: "산책에서 풀숲 냄새를 세밀하게 확인하고 장난감을 입에 물어 옮기거나 보호자의 신호에 빠르게 참여하는 장면이 보일 수 있지만, 흥분도와 회수 선호는 개체마다 다릅니다.",
      guardianContext: "다정한 인상만으로 선택하지 말고 매일 제공할 활발한 탐색 시간, 흥분 뒤 진정하는 능력, 늘어진 귀와 긴 피모를 만지고 관리할 때의 실제 반응을 확인하세요.",
    },
    story: {
      opening: "잉글리시 코커 스패니얼은 영국에서 새 사냥을 돕던 랜드 스패니얼 계통의 조렵견입니다. 낮은 덤불을 누비며 새를 찾아 날아오르게 하고 회수하는 역할이 오늘의 체형과 활동 방식을 이해하는 출발점이 됩니다.",
      roleToHome: "사람 가까이에서 신호를 주고받으며 코로 대상을 찾고 입으로 운반하던 일은 장난감 회수, 풀숲 탐색, 함께 배우는 활동으로 이어질 수 있습니다. 협력견의 역사도 개별 개체의 친화성이나 교육 결과를 보증하지는 않습니다.",
      reality: "예쁜 장모와 늘어진 귀는 반복 관리가 필요한 생활 조건입니다. 충분한 신체 활동뿐 아니라 냄새 찾기와 회수 같은 목적 있는 과제, 흥분을 낮추는 휴식, 귀와 발을 편안하게 만질 수 있도록 돕는 연습이 함께 필요합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "민첩하게 움직이는 산책과 탐색 활동을 규칙적으로 제공해야 해요." },
      mentalStimulation: { label: "높은 편", note: "냄새 찾기와 운반·회수처럼 역할과 연결된 과제를 활용할 수 있어요." },
      independence: { label: "중간", note: "사람과 협력하면서도 냄새를 따라 탐색하는 시간을 균형 있게 마련하세요." },
      socialConnection: { label: "높은 편", note: "가까이 협력한 배경이 있지만 낯선 대상에 대한 반응은 직접 확인해야 해요." },
      alerting: { label: "중간", note: "환경 변화에 대한 소리 반응은 사회화와 생활 공간에 따라 달라질 수 있어요." },
      grooming: { label: "높은 편", note: "귀와 다리의 긴 장식털을 포함해 엉킴과 오염을 자주 살펴야 해요." },
    },
    careNotes: [
      "풀숲 활동 뒤에는 귀와 발, 피모에 이물질이 없는지 살피고 관리 접촉을 보상과 연결해 주세요.",
      "공 던지기만 반복하기보다 냄새 탐색과 천천히 운반하기, 멈춰 쉬기를 섞어 흥분을 조절하세요.",
      "같은 견종 안에서도 작업 계통과 전시 계통, 개별 성장 환경에 따른 차이를 입양 전에 확인하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 귀·눈·피부와 관절 상태를 포함한 검진 항목은 견종명만으로 진단하지 않으며, 가족력과 생활을 바탕으로 전문가와 계획해야 합니다.",
    daySnapshot: [
      { time: "아침", title: "풀숲 냄새 탐색", description: "안전한 산책로에서 코를 쓰고 방향을 선택할 시간을 충분히 주세요." },
      { time: "낮", title: "찾아 가져오는 협력", description: "부드러운 장난감을 찾아 보호자에게 가져오는 짧은 과제를 함께해요." },
      { time: "저녁", title: "귀와 피모 확인", description: "산책 뒤 이물질과 엉킴을 살피고 편안한 범위까지만 손질해요." },
    ],
    related: [
      { slug: "golden-retriever", reason: "조렵과 회수라는 연결점이 있지만 체격과 운동 규모, 피모 관리 조건을 다르게 살펴보세요." },
      { slug: "beagle", reason: "코를 활용하는 야외 활동은 닮았지만 무리 추적과 사람 가까이의 조렵 방식은 차이가 있어요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 5 — English Cocker Spaniel",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/005g08-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "English Cocker Spaniel Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/english-cocker-spaniel/",
        checkedAt: completedAt,
      },
      {
        title: "English Cocker Spaniel History",
        organization: "American Kennel Club",
        url: "https://www.akc.org/expert-advice/dog-breeds/english-cocker-spaniel-history/",
        checkedAt: "2026-08-29",
      },
    ],
  },
  {
    slug: "labrador-retriever",
    contentStatus: "mvp-editorial-draft",
    nameKo: "래브라도 리트리버",
    nameEn: "Labrador Retriever",
    tagline: "친근하다는 한 단어보다, 차가운 물에서 그물과 사냥감을 회수하던 힘과 협력 욕구를 먼저 보세요.",
    palette: { primary: "#c7b28d", secondary: "#e8e2d3", ink: "#3e3425" },
    illustration: "/illustrations/v2/labrador-retriever-card.webp",
    catalog: {
      group: "retriever-spaniel",
      discoveryTags: ["물새 회수", "사람과 협력", "큰 활동 규모"],
    },
    historyVisual: {
      src: "/illustrations/v3/labrador-retriever-history.webp",
      alt: "뉴펀들랜드의 물가에서 어부 곁을 오가며 물건을 회수하는 래브라도의 배경을 표현한 편집 삽화",
    },
    identity: {
      origin: "캐나다 뉴펀들랜드에서 기원하고 영국에서 견종으로 발전",
      lineage: "워터도그·리트리버 계통",
      originalRole: "어부를 돕고 물건·사냥감을 회수하는 리트리버",
      size: "중대형",
      lifespan: "약 11~13년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "뉴펀들랜드의 물가에서 어부를 돕고 이후 물새를 부드럽게 회수하도록 발전한 역할은 수영, 운반, 사람과 반복해서 협력하는 방식을 이해하는 단서입니다.",
      today: "장난감을 입에 물고 다니거나 던진 물건을 반복해 가져오고 물가와 사람에게 힘차게 접근하는 장면이 나타날 수 있지만, 모든 래브라도가 수영이나 낯선 사람을 좋아하는 것은 아닙니다.",
      guardianContext: "친화적인 가족견이라는 이미지에 기대지 말고 성견의 힘과 흥분도, 매일 필요한 운동·학습 시간, 먹을거리 접근, 어린이와 다른 동물을 만날 때의 실제 거리 조절을 확인하세요.",
    },
    story: {
      opening: "래브라도 리트리버의 출발점은 이름과 달리 캐나다 뉴펀들랜드의 물가입니다. 어부 곁에서 물건을 회수하던 개들이 영국으로 건너가 물새 회수견으로 발전했다는 공식 설명이 오늘의 행동을 읽는 배경이 됩니다.",
      roleToHome: "차가운 물에서 물건을 찾아 사람에게 가져오던 일은 오늘날 물건 운반, 반복 회수 놀이, 물가 탐색, 사람과 함께 과제를 수행하는 장면으로 이어질 수 있습니다. 역할의 역사가 곧 모든 개체의 사교성이나 순종성을 보증하지는 않습니다.",
      reality: "성견은 힘이 크고 젊을 때 활동과 흥분도 클 수 있습니다. 냄새 찾기·회수, 인사 전 기다리기, 충분한 수면을 함께 마련하고 음식과 물놀이 안전 기준도 세워야 합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "큰 체격에 맞는 충분한 운동과 관절에 무리 없는 회복을 함께 계획하세요." },
      mentalStimulation: { label: "높은 편", note: "회수와 냄새 찾기, 협력 과제를 번갈아 제공하면 도움이 될 수 있어요." },
      independence: { label: "중간", note: "사람과 협력하는 시간과 스스로 차분히 쉬는 시간을 모두 연습해야 해요." },
      socialConnection: { label: "높은 편", note: "사람 가까이 일한 배경이 있지만 실제 인사 방식과 편안함은 확인해야 해요." },
      alerting: { label: "중간", note: "경계 소리보다 접근과 흥분으로 표현할 수도 있어 장면별 관찰이 필요해요." },
      grooming: { label: "중간", note: "짧고 촘촘한 이중모의 털 빠짐과 물놀이 뒤 건조 관리를 고려하세요." },
    },
    careNotes: [
      "성견의 체중과 당기는 힘을 감당할 산책 장비, 보호자의 신체 조건, 이동 수단을 미리 점검하세요.",
      "물에 익숙할 것이라고 가정하지 말고 얕고 안전한 곳에서 스스로 들어갈 선택권과 구명 장비를 고려하세요.",
      "먹을거리 보상은 하루 급여량에 포함하고 음식과 쓰레기에 접근하지 못하도록 생활 공간을 정리하세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 관절·눈·체중과 가족력에 관한 확인은 질환을 예측하는 진단이 아니며, 성장 단계별 검진과 운동 계획을 전문가와 상의하세요.",
    daySnapshot: [
      { time: "아침", title: "큰 몸을 깨우는 산책", description: "당기지 않고 걷는 연습과 충분한 냄새 탐색을 함께 구성해요." },
      { time: "낮", title: "찾아 부드럽게 가져오기", description: "물건을 쫓는 것에서 끝내지 않고 건네고 쉬는 순서까지 연습해요." },
      { time: "저녁", title: "흥분을 낮추는 휴식", description: "가족 활동이 이어져도 자기 자리에서 깊게 쉴 시간을 확보해 주세요." },
    ],
    related: [
      { slug: "golden-retriever", reason: "회수견의 공통 배경과 피모·체형, 인사 방식의 실제 차이를 같은 기준으로 볼 수 있어요." },
      { slug: "poodle", reason: "물에서 회수한 역사와 높은 학습 자극은 닮았지만 크기 선택과 미용 부담이 다르게 나타나요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 122 — Labrador Retriever",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/122g08-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Labrador Retriever Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/labrador-retriever/",
        checkedAt: completedAt,
      },
      { title: "Labrador Retriever History: From Water Dogs to Beloved Companions", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/labrador-retriever-history/", checkedAt: "2026-08-29" },
    ],
  },
  {
    slug: "golden-retriever",
    contentStatus: "mvp-editorial-draft",
    nameKo: "골든 리트리버",
    nameEn: "Golden Retriever",
    tagline: "부드러운 표정만으로 결정하기 전에, 스코틀랜드의 물가에서 새를 회수하던 활동과 돌봄 규모를 보세요.",
    palette: { primary: "#d9bd7e", secondary: "#f2e6ca", ink: "#44341f" },
    illustration: "/illustrations/v2/golden-retriever-card.webp",
    catalog: {
      group: "retriever-spaniel",
      discoveryTags: ["물새 회수", "협력 활동", "장모 관리"],
    },
    historyVisual: {
      src: "/illustrations/v3/golden-retriever-history.webp",
      alt: "스코틀랜드의 습지와 물가에서 새를 회수해 사람에게 돌아오는 골든 리트리버를 표현한 편집 삽화",
    },
    identity: {
      origin: "스코틀랜드",
      lineage: "건도그·리트리버 계통",
      originalRole: "물과 육지에서 사냥한 새를 회수하는 리트리버",
      size: "중대형",
      lifespan: "약 10~12년(AKC 참고, 개체차·출처차 있음)",
    },
    behaviorClues: {
      originalRole: "스코틀랜드의 습지와 물가에서 사냥한 새를 손상시키지 않고 찾아오도록 사람과 협력한 역할은 탐색과 운반, 반복 훈련을 즐길 가능성을 이해하는 단서입니다.",
      today: "장난감을 입에 물고 가족을 따라오거나 냄새를 찾아 물가와 풀밭을 탐색하고, 낯선 사람에게 빠르게 다가가려는 장면이 보일 수 있지만 반응은 개체와 경험에 따라 달라집니다.",
      guardianContext: "언제나 순하고 쉬운 가족견이라는 이미지를 내려놓고 성견의 힘과 활동량, 흥분한 인사, 장모와 젖은 귀 관리, 혼자 차분히 쉬는 능력을 실제 환경에서 확인하세요.",
    },
    story: {
      opening: "골든 리트리버는 19세기 스코틀랜드에서 물과 육지를 오가며 새를 회수할 목적으로 발전한 건도그입니다. 사람과 가까이 협력하며 대상을 찾아 부드럽게 운반한 역사는 오늘의 생활 요구를 읽는 출발점입니다.",
      roleToHome: "냄새를 따라 대상을 찾고 입에 물어 사람에게 돌아오는 작업은 장난감 운반, 회수 놀이, 물가 탐색, 반복 학습으로 이어질 수 있습니다. 유명한 친화성 이미지도 낯선 사람·어린이·동물에 대한 개별 반응을 대신 확인해주지는 않습니다.",
      reality: "충분한 운동뿐 아니라 젖은 피모 건조, 빗질, 이동 공간과 노년기 돌봄까지 준비해야 합니다. 뛰는 시간만큼 흥분을 낮추고 혼자 쉬는 연습도 중요합니다.",
    },
    tendencies: {
      activity: { label: "높은 편", note: "지속적인 산책과 회수·탐색 활동, 충분한 회복 시간을 함께 마련하세요." },
      mentalStimulation: { label: "높은 편", note: "냄새 찾기와 물건 운반, 협력 학습을 다양하게 제공하면 도움이 돼요." },
      independence: { label: "중간", note: "함께 활동하는 즐거움과 보호자 없이 차분히 쉬는 능력을 모두 살펴보세요." },
      socialConnection: { label: "높은 편", note: "사람과 가까이 일한 역사가 있지만 대상별 편안함은 개체마다 달라요." },
      alerting: { label: "중간", note: "소리 경계보다 반가운 접근으로 나타날 수 있어 인사 장면을 직접 확인하세요." },
      grooming: { label: "높은 편", note: "긴 이중모의 빗질과 털 빠짐, 물놀이 뒤 완전한 건조를 계획해야 해요." },
    },
    careNotes: [
      "반가운 인사에서도 큰 몸으로 뛰어오를 수 있으므로 네 발을 바닥에 두고 기다리는 연습을 일찍 시작하세요.",
      "수영을 당연히 좋아한다고 가정하지 말고 안전한 수심과 출구, 구명 장비를 갖춘 뒤 선택하게 해주세요.",
      "빗질과 귀·발 건조에 필요한 주당 시간, 중대형견 이동과 노년기 보조 동선을 미리 계산해보세요.",
    ],
    healthEditorialNote: "건강 항목은 수의학 전문가 검수 전인 편집 초안입니다. 관절·눈·심장과 가족력 등 공식 권장 검사의 세부 범위는 전문가 검토 뒤 보강하며, 개별 예방 계획은 담당 동물병원과 세워야 합니다.",
    daySnapshot: [
      { time: "아침", title: "탐색이 있는 긴 산책", description: "속도만 높이지 말고 냄새를 읽고 보호자와 방향을 맞추게 해주세요." },
      { time: "낮", title: "회수 뒤 내려놓고 쉬기", description: "물건을 가져온 다음 차분히 건네고 휴식하는 순서까지 함께 연습해요." },
      { time: "저녁", title: "피모 확인과 깊은 휴식", description: "엉킴과 습기를 살핀 뒤 방해받지 않는 자리에서 충분히 쉬게 해요." },
    ],
    related: [
      { slug: "labrador-retriever", reason: "물새 회수의 공통 배경과 피모·체형, 가정 내 관리 방식의 차이를 비교해보세요." },
      { slug: "english-cocker-spaniel", reason: "새를 찾고 회수하던 협력은 닮았지만 체격과 덤불 탐색, 피모 관리 규모가 달라요." },
      { slug: "flat-coated-retriever", reason: "활기찬 회수 협력을 공유하지만 성숙 과정과 긴 피모 관리, 일상 리듬을 함께 비교해보세요." },
      { slug: "nova-scotia-duck-tolling-retriever", reason: "물새 회수 배경은 닮았지만 더 작은 체격과 톨링 작업, 활동 자극의 차이를 살펴보세요." },
    ],
    sources: [
      {
        title: "FCI Standard No. 111 — Golden Retriever",
        organization: "Fédération Cynologique Internationale",
        url: "https://www.fci.be/Nomenclature/Standards/111g08-en.pdf",
        checkedAt: completedAt,
      },
      {
        title: "Golden Retriever Dog Breed Information",
        organization: "American Kennel Club",
        url: "https://www.akc.org/dog-breeds/golden-retriever/",
        checkedAt: completedAt,
      },
      { title: "Golden Retriever History: Behind the Breed’s Unfashionable Past", organization: "American Kennel Club", url: "https://www.akc.org/expert-advice/dog-breeds/golden-retriever-history/", checkedAt: "2026-08-29" },
    ],
  },
] satisfies Breed[];
