import type { Breed } from "./schema";

const checkedAt = "2026-08-04";
const historyAltOverrides: Partial<Record<string, string>> = {
  "german-short-haired-pointing-dog": "독일의 들과 얕은 습지가 만나는 곳에서 새의 위치를 향해 멈춰 서고 사람과 협력하는 갈색 로안 저먼 쇼트헤어드 포인터를 그린 편집 수채화",
  "airedale-terrier": "영국 요크셔 에어 계곡의 강둑과 덤불 사이에서 냄새를 찾는 에어데일 테리어를 그린 편집 수채화",
  "miniature-pinscher": "독일의 오래된 마구간에서 바닥 가까운 작은 해충의 흔적을 살피는 검정과 황갈색 미니어처 핀셔를 그린 편집 수채화",
  "australian-kelpie": "건조한 호주의 넓은 방목지에서 사람의 신호에 맞춰 양 떼 바깥을 도는 오스트레일리안 켈피를 그린 편집 수채화",
  "basset-hound": "영국의 울타리 길에서 사람들보다 앞서 코를 낮추고 냄새를 따라가는 삼색 바셋 하운드를 그린 편집 수채화",
  borzoi: "러시아의 넓은 초원에서 말을 탄 사냥대 곁에 서서 먼 지형을 살피는 흰색과 황갈색 보르조이를 그린 편집 수채화",
};
type Level = Breed["tendencies"][keyof Breed["tendencies"]]["label"];
type DayStep = Breed["daySnapshot"][number];

type BatchFSeed = {
  slug: string; nameKo: string; nameEn: string; tagline: string;
  group: Breed["catalog"]["group"]; tags: [string, string, string]; colors: [string, string, string];
  origin: string; lineage: string; role: string; size: string; lifespan: string;
  originalRole: string; today: string; guardianContext: string;
  opening: string; roleToHome: string; reality: string;
  care: [string, string, string]; levels: [Level, Level, Level, Level, Level, Level];
  days: [DayStep, DayStep, DayStep]; related: [[string, string], [string, string]];
  fciUrl: string; akcUrl: string; historyUrl?: string;
};

const seeds: BatchFSeed[] = [
  {
    slug: "australian-kelpie", nameKo: "오스트레일리안 켈피", nameEn: "Australian Kelpie",
    tagline: "가벼운 체형 안에는 넓고 건조한 목장에서 양 떼의 흐름을 읽던 긴 작업 리듬이 있어요.",
    group: "herding", tags: ["호주 목양견", "높은 지구력", "움직임 통제"], colors: ["#7f5239", "#dce2d3", "#332c27"],
    origin: "오스트레일리아", lineage: "스코틀랜드계 콜리 타입에서 발달한 목양견", role: "넓은 목장에서 양을 모으고 이동시키는 작업", size: "중형 · 약 43~51cm, 16~23kg", lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "호주의 넓고 덥고 건조한 목장에서 장시간 양 떼의 움직임을 읽고 방향을 바꾸는 목양 작업을 위해 발달했습니다.",
    today: "움직이는 대상에 빠르게 반응하거나 스스로 다음 과제를 찾는 모습이 나타날 수 있지만 강도와 방식은 개체마다 달라요.",
    guardianContext: "달리기만 늘리기보다 냄새 탐색과 방향 전환, 멈춤과 휴식을 묶고 사람·자전거·다른 동물을 몰려는 실제 반응을 살펴보세요.",
    opening: "오스트레일리안 켈피는 호주의 광대한 목축 환경에서 양 떼를 효율적으로 이동시키는 목양견으로 발달했습니다. 작고 민첩한 몸은 긴 작업을 이어 가는 데 쓰였습니다.",
    roleToHome: "멀리 움직이는 가축과 보호자의 신호를 함께 읽던 배경은 오늘날에도 높은 활동량과 과제 참여로 이어질 수 있습니다.",
    reality: "중형이라는 크기만으로 생활 부담이 작다고 판단하기 어렵습니다. 매일 몸과 머리를 함께 쓰는 시간, 흥분 뒤 쉬는 연습이 필요해요.",
    care: ["긴 산책에 냄새 찾기와 방향 신호를 섞어 주세요.", "사람이나 동물을 몰려는 행동은 거리와 대체 과제로 관리하세요.", "활동 뒤 물과 그늘, 방해받지 않는 회복 시간을 보장하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "움직임과 방향 과제", description: "충분히 걷고 짧은 신호를 맞춰요." }, { time: "낮", title: "완전한 휴식", description: "흥분을 낮추고 조용히 쉬게 해요." }, { time: "저녁", title: "찾기와 멈춤", description: "냄새 과제와 정지 신호를 번갈아 해요." }],
    related: [["border-collie", "높은 목양 집중력을 공유하지만 작업 거리와 움직임의 리듬을 비교해 보세요."], ["australian-shepherd", "목양 배경과 높은 참여 욕구를 공유하며 체격과 피모 관리의 차이가 있어요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/AUSTRALIAN-KELPIE-293.html", akcUrl: "https://www.akc.org/dog-breeds/australian-kelpie/", historyUrl: "https://www.akc.org/expert-advice/lifestyle/fun-facts-australian-kelpie/",
  },
  {
    slug: "miniature-pinscher", nameKo: "미니어처 핀셔", nameEn: "Miniature Pinscher",
    tagline: "작은 몸과 높이 드는 걸음 뒤에는 독일의 집과 마구간에서 주변을 살피던 민첩함이 있어요.",
    group: "guardian-working", tags: ["독일 소형 핀셔", "민첩한 움직임", "주변 경계"], colors: ["#8f4d36", "#e5ddcc", "#312a27"],
    origin: "독일", lineage: "독일 핀셔·슈나우저 계통의 소형견", role: "집과 마구간의 해충을 찾고 주변을 알리는 역할", size: "초소형 · 약 25~32cm, 3.6~4.5kg", lifespan: "약 12~16년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "독일의 집과 마구간에서 작은 해충을 찾고 주변 변화를 알리는 민첩한 소형견으로 발달한 배경이 있습니다.",
    today: "작은 움직임을 빠르게 쫓거나 소리와 낯선 변화에 또렷하게 반응할 수 있지만 추적과 경계의 정도는 개체마다 달라요.",
    guardianContext: "작은 체격을 이유로 활동과 교육을 생략하지 말고 추적 반응, 짖음, 높은 곳에서의 낙상과 추위 대처를 함께 확인하세요.",
    opening: "미니어처 핀셔는 독일에서 오래된 소형 핀셔 타입으로 발달했습니다. 도베르만의 축소판이 아니라 별개의 역사와 균형을 가진 견종입니다.",
    roleToHome: "재빠르게 주변을 살피고 작은 대상을 쫓던 배경은 현대 가정에서 민첩한 놀이와 경계 알림으로 나타날 수 있습니다.",
    reality: "초소형견도 산책과 학습, 안전 관리가 필요합니다. 빠른 움직임과 독립적인 선택을 힘으로 누르기보다 협력 신호를 가르쳐야 해요.",
    care: ["짧은 산책과 냄새 찾기를 매일 제공하세요.", "문소리와 낯선 움직임에는 조용한 대체 행동을 보상하세요.", "추운 날과 높은 가구, 미끄러운 바닥의 위험을 줄이세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "낮은 편"],
    days: [{ time: "아침", title: "경쾌한 탐색", description: "작은 몸에 맞는 속도로 냄새를 찾아요." }, { time: "낮", title: "따뜻한 휴식", description: "바람 없는 낮은 자리에서 쉬어요." }, { time: "저녁", title: "알림 전환 연습", description: "소리 뒤 자리로 오는 신호를 배워요." }],
    related: [["dobermann", "핀셔 계통의 날렵한 외형은 닮았지만 역사와 체격, 생활 부담은 크게 달라요."], ["chihuahua", "초소형 반려견 사이에서 활동량과 경계 반응, 추위 관리의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/MINIATURE-PINSCHER-185.html", akcUrl: "https://www.akc.org/dog-breeds/miniature-pinscher/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/miniature-pinscher-history/",
  },
  {
    slug: "airedale-terrier", nameKo: "에어데일 테리어", nameEn: "Airedale Terrier",
    tagline: "가장 큰 테리어의 체격에는 강가와 들을 오가며 여러 과제를 맡았던 다목적성이 담겨 있어요.",
    group: "terrier", tags: ["영국 에어 계곡", "대형 테리어", "다목적 작업"], colors: ["#a7774d", "#d9dfd1", "#33302a"],
    origin: "영국·요크셔 에어 계곡", lineage: "워터사이드 테리어 계통의 대형 테리어", role: "강가의 수렵과 해충 관리 등 다목적 작업", size: "중대형 · 약 58cm, 23~32kg", lifespan: "약 11~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국 요크셔의 에어 계곡에서 강가와 농촌을 오가며 수렵과 해충 관리 등 여러 일을 수행하는 큰 테리어로 발달했습니다.",
    today: "냄새와 움직임을 끈기 있게 조사하거나 힘 있게 놀이에 참여할 수 있지만 집중 대상과 사회성은 개체마다 달라요.",
    guardianContext: "추적과 흥분을 안전한 리드와 중단 신호로 관리하고, 단단한 체격의 활동량과 거친 이중모 손질 시간을 함께 계산하세요.",
    opening: "에어데일 테리어는 영국 요크셔의 에어 계곡에서 발달한 가장 큰 테리어입니다. 물가와 육지를 오가는 다목적 작업 배경을 지녔습니다.",
    roleToHome: "여러 환경에서 스스로 탐색하고 사람과 일하던 배경은 다양한 활동과 문제 해결을 요구하는 모습으로 이어질 수 있습니다.",
    reality: "테리어의 끈기와 큰 몸이 함께 있으므로 짧은 놀이만으로는 부족할 수 있습니다. 교육과 운동, 정기적인 피모 관리가 필요해요.",
    care: ["걷기·찾기·학습을 번갈아 지루함을 줄이세요.", "작은 동물과 다른 개에 대한 반응은 안전한 거리에서 확인하세요.", "빗질과 트리밍으로 거친 이중모와 피부 상태를 관리하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "긴 탐색 산책", description: "물가나 숲길의 냄새를 충분히 맡아요." }, { time: "낮", title: "씹기와 회복", description: "안전한 씹을 거리 뒤 쉬게 해요." }, { time: "저녁", title: "협력과 빗질", description: "짧은 과제 뒤 피모를 나눠 살펴요." }],
    related: [["jack-russell-terrier", "테리어의 탐색과 끈기를 공유하지만 체격과 힘의 규모가 크게 달라요."], ["miniature-schnauzer", "거친 피모와 해충 관리 배경 안에서 활동량과 몸집 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/AIREDALE-TERRIER-7.html", akcUrl: "https://www.akc.org/dog-breeds/airedale-terrier/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/history-of-the-airedale-terrier-behind-the-breed/",
  },
  {
    slug: "welsh-corgi-cardigan", nameKo: "웰시 코기 카디건", nameEn: "Welsh Corgi (Cardigan)",
    tagline: "긴 꼬리와 낮은 체형은 웨일스 농장에서 소의 발길을 피하며 이동을 돕던 몸의 기록이에요.",
    group: "herding", tags: ["웨일스 목양견", "낮고 긴 체형", "가축 이동"], colors: ["#8d6047", "#dce1d3", "#342e2a"],
    origin: "영국·웨일스", lineage: "오래된 웨일스 저각 목양견", role: "소와 가축을 이동시키고 농장을 지키는 역할", size: "중소형 · 약 27~32cm, 11~17kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "웨일스 농장에서 낮은 몸으로 소의 발길을 피하며 가축을 이동시키고 농장 주변을 살피는 목양 작업을 했습니다.",
    today: "움직이는 발이나 바퀴를 따라가고 주변 변화를 알리려는 모습이 나타날 수 있지만 몰이와 짖음의 강도는 개체마다 달라요.",
    guardianContext: "낮고 긴 허리에 무리가 가지 않도록 체중과 점프·계단을 관리하고, 몰이 행동은 거리와 대체 신호로 전환해 주세요.",
    opening: "카디건 웰시 코기는 웨일스의 오래된 저각 목양견으로, 긴 꼬리와 둥근 귀가 펨브로크와 구별되는 대표적 특징입니다.",
    roleToHome: "가축의 움직임을 가까이서 읽던 배경은 가정에서도 발이나 바퀴를 따라가는 행동, 주변 변화를 알리는 반응으로 이어질 수 있습니다.",
    reality: "다리가 짧아도 활동이 적은 견종은 아닙니다. 허리를 보호할 환경과 체중 관리, 충분한 탐색과 교육 시간을 준비해야 해요.",
    care: ["미끄러운 바닥과 반복적인 높은 점프를 줄이세요.", "사람의 발이나 바퀴를 몰려는 행동에 대체 신호를 가르치세요.", "이중모 빗질과 체중·보행 상태를 꾸준히 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "낮고 길게 걷기", description: "무리 없는 길에서 냄새를 충분히 맡아요." }, { time: "낮", title: "허리 편한 휴식", description: "낮고 미끄럽지 않은 자리를 줘요." }, { time: "저녁", title: "몰이 전환 놀이", description: "움직임 대신 장난감 찾기에 집중해요." }],
    related: [["welsh-corgi-pembroke", "같은 웨일스 목양견 안에서 꼬리·체형과 역사적 계통의 차이를 살펴보세요."], ["dachshund", "낮고 긴 체형의 공통점과 목양·지하 수렵이라는 역할 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/WELSH-CORGI-CARDIGAN-38.html", akcUrl: "https://www.akc.org/dog-breeds/cardigan-welsh-corgi/",
  },
  {
    slug: "finnish-spitz", nameKo: "핀니시 스피츠", nameEn: "Finnish Spitz",
    tagline: "여우빛 털과 곧은 귀에는 숲의 새를 찾아 목소리로 위치를 알리던 북유럽 사냥 방식이 남아 있어요.",
    group: "spitz-primitive", tags: ["핀란드 국견", "새 사냥 알림", "풍부한 발성"], colors: ["#bb7044", "#dfe4d5", "#3e3028"],
    origin: "핀란드", lineage: "북유럽 스피츠형 사냥견", role: "숲에서 새를 찾아 짖음으로 위치를 알리는 사냥", size: "중소형 · 약 39~50cm, 9~15kg", lifespan: "약 13~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "핀란드 숲에서 나무 위의 새를 찾아 시선과 짖음으로 사냥꾼에게 위치를 알리는 독특한 작업을 수행했습니다.",
    today: "새와 작은 움직임을 오래 관찰하거나 목소리로 변화를 알리는 모습이 나타날 수 있지만 발성의 빈도와 추적 반응은 개체마다 달라요.",
    guardianContext: "짖음을 억누르기보다 알림 뒤 돌아오기와 조용한 행동을 가르치고 야생동물 추적은 리드와 울타리로 예방하세요.",
    opening: "핀니시 스피츠는 핀란드의 북유럽 스피츠형 사냥견입니다. 숲의 새를 찾아 나무 아래에서 짖어 위치를 알린 역사로 알려져 있습니다.",
    roleToHome: "멀리 있는 움직임을 보고 목소리로 알리던 배경은 오늘날에도 높은 관찰과 발성으로 나타날 수 있습니다.",
    reality: "아름다운 붉은 피모만큼 발성과 추적 관리가 중요한 견종입니다. 조용함을 요구하는 주거 환경과 맞는지 실제 개체 반응을 확인하세요.",
    care: ["알림 짖음 뒤 보호자에게 돌아오는 행동을 보상하세요.", "새와 작은 동물 추적은 안전한 리드와 울타리로 관리하세요.", "이중모는 정기적으로 빗고 더운 날 활동을 조절하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "숲길 탐색", description: "시선과 냄새를 쓰며 천천히 걸어요." }, { time: "낮", title: "조용함 연습", description: "소리 뒤 편한 자리로 돌아와 쉬어요." }, { time: "저녁", title: "찾기와 빗질", description: "짧은 탐색 뒤 속털을 살펴요." }],
    related: [["shiba", "북방 스피츠형의 민첩함을 공유하지만 발성과 원래 사냥 방식이 달라요."], ["korea-jindo-dog", "스피츠형 사냥견 사이에서 체격, 경계와 사람 관계의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/SUOMENPYSTYKORVA-FINNISH-SPITZ-49.html", akcUrl: "https://www.akc.org/dog-breeds/finnish-spitz/",
  },
  {
    slug: "basset-hound", nameKo: "바셋 하운드", nameEn: "Basset Hound",
    tagline: "느긋해 보이는 낮은 몸은 땅 가까이의 냄새를 무리와 함께 오래 따라가도록 만들어진 형태예요.",
    group: "scent-hound", tags: ["프랑스계 후각하운드", "지속적인 냄새 추적", "낮고 무거운 체형"], colors: ["#b17a52", "#e4dfcf", "#3d342d"],
    origin: "프랑스에서 기원해 영국에서 정립", lineage: "저각 후각하운드", role: "사람이 걸어서 따라가는 무리 사냥의 냄새 추적", size: "중형 · 약 38cm 이하, 18~29kg", lifespan: "약 12~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "짧은 다리로 땅 가까이의 냄새를 오래 따라가며 사람이 걸어서 뒤따를 수 있는 속도로 무리 사냥을 하는 후각하운드입니다.",
    today: "흥미로운 냄새를 끈기 있게 따라가거나 목소리로 알릴 수 있지만 산책 속도와 발성은 개체와 경험에 따라 달라요.",
    guardianContext: "리드 없이 냄새를 쫓지 않도록 관리하고 체중, 긴 귀와 피부 주름, 낮고 무거운 몸의 관절과 보행을 꾸준히 살펴보세요.",
    opening: "바셋 하운드는 프랑스계 저각 후각하운드에서 기원해 영국에서 정립된 견종입니다. 낮은 몸으로 냄새를 오래 따라가는 역할을 했습니다.",
    roleToHome: "냄새길을 끝까지 확인하는 배경은 산책에서 느린 탐색과 강한 집중으로 이어질 수 있습니다. 속도보다 안전한 냄새 경험이 중요해요.",
    reality: "느긋한 인상과 달리 후각 탐색 욕구와 발성이 클 수 있습니다. 무거운 몸의 체중·관절 관리와 귀·피부 관리도 매일의 부담이에요.",
    care: ["산책에서는 튼튼한 리드로 안전한 냄새 탐색을 허용하세요.", "체중과 보행을 관찰하고 반복 계단·점프를 줄이세요.", "긴 귀와 피부 주름을 건조하게 유지하며 자주 확인하세요."],
    levels: ["중간", "높은 편", "높은 편", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "느린 냄새 산책", description: "속도를 재촉하지 않고 냄새길을 따라요." }, { time: "낮", title: "낮은 자리 휴식", description: "관절이 편한 바닥에서 쉬게 해요." }, { time: "저녁", title: "귀와 피부 확인", description: "습기와 붉어짐, 냄새를 살펴요." }],
    related: [["beagle", "무리 후각하운드의 공통점과 체형·속도·귀 관리의 차이를 비교해 보세요."], ["dachshund", "낮은 몸과 냄새 추적의 공통점, 지하 수렵과 무리 추적의 차이가 있어요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BASSET-HOUND-163.html", akcUrl: "https://www.akc.org/dog-breeds/basset-hound/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/basset-hound-history/",
  },
  {
    slug: "german-short-haired-pointing-dog", nameKo: "저먼 쇼트헤어드 포인터", nameEn: "German Short-Haired Pointing Dog",
    tagline: "유선형 몸에는 들과 물을 넓게 탐색하고 위치 알림부터 회수까지 협력한 다목적성이 있어요.",
    group: "pointing", tags: ["독일 포인팅견", "다목적 사냥", "매우 높은 활동"], colors: ["#8b6350", "#dce1d4", "#302e2b"],
    origin: "독일", lineage: "독일 단모 포인팅견", role: "사냥감 탐색·포인팅·추적과 회수", size: "중대형 · 약 53~64cm, 20~32kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "독일의 들과 숲, 물가에서 사냥감을 찾고 위치를 알리며 추적과 회수까지 수행하는 다목적 포인팅견으로 발달했습니다.",
    today: "넓게 탐색하고 빠르게 달리며 사람과 계속 과제를 수행하려는 모습이 나타날 수 있지만 작업 욕구는 개체마다 달라요.",
    guardianContext: "단순한 반복 달리기보다 냄새 찾기와 멈춤·회수·휴식을 묶고 야생동물과 작은 동물에 대한 실제 추적 반응을 관리하세요.",
    opening: "저먼 쇼트헤어드 포인터는 독일에서 정립된 다목적 사냥견입니다. 들과 숲, 물을 오가며 탐색과 포인팅, 회수 작업을 맡았습니다.",
    roleToHome: "오래 움직이면서 사람과 신호를 맞추던 배경은 높은 지구력과 참여 욕구로 이어질 수 있습니다. 매일 구조화된 활동이 필요해요.",
    reality: "짧은 털이 관리 부담 전체를 줄여 주지는 않습니다. 많은 운동과 교육, 안전한 추적 관리와 혼자 쉬는 연습이 필요합니다.",
    care: ["긴 활동에 냄새 탐색과 방향·정지 신호를 섞으세요.", "야생동물 추적은 리드와 안전한 울타리로 예방하세요.", "활동 뒤 발과 피부, 귀를 확인하고 충분히 회복시키세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "넓은 탐색", description: "긴 산책에서 냄새와 신호를 함께 써요." }, { time: "낮", title: "회복과 독립 휴식", description: "활동 뒤 조용히 쉬는 능력을 길러요." }, { time: "저녁", title: "찾기와 회수", description: "짧은 과제로 협력 리듬을 맞춰요." }],
    related: [["weimaraner", "독일 다목적 포인팅견의 공통점과 체형·피모, 협업 리듬을 비교해 보세요."], ["labrador-retriever", "회수 작업을 공유하지만 포인팅과 물새 회수라는 역할 초점이 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/GERMAN-SHORT-HAIRED-POINTING-DOG-119.html", akcUrl: "https://www.akc.org/dog-breeds/german-shorthaired-pointer/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/german-shorthaired-pointer-history/",
  },
  {
    slug: "english-springer-spaniel", nameKo: "잉글리시 스프링거 스패니얼", nameEn: "English Springer Spaniel",
    tagline: "풍성한 귀와 단단한 몸에는 숲과 들의 덤불에서 새를 날려 보내고 회수하던 리듬이 있어요.",
    group: "retriever-spaniel", tags: ["영국 플러싱견", "새를 찾아 날림", "사람과 가까운 협업"], colors: ["#835b43", "#e3e2d6", "#352f2b"],
    origin: "영국", lineage: "랜드 스패니얼 계통", role: "덤불의 새를 찾아 날려 보내고 회수하는 사냥", size: "중형 · 약 48~51cm, 18~23kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국의 들과 덤불에서 사람 가까이 움직이며 새를 찾아 날아오르게 하고, 사냥 뒤 회수하는 작업을 수행했습니다.",
    today: "냄새를 따라 수풀을 조사하고 물건을 물어 오는 놀이에 적극적으로 참여할 수 있지만 집중과 흥분의 정도는 개체마다 달라요.",
    guardianContext: "회수 놀이에는 놓기와 멈춤을 함께 가르치고 긴 귀와 발 장식털은 산책·물놀이 뒤 습기와 이물질을 확인하세요.",
    opening: "잉글리시 스프링거 스패니얼은 영국의 랜드 스패니얼 계통에서 발달했습니다. 이름처럼 덤불의 새를 찾아 날아오르게 하는 작업을 맡았습니다.",
    roleToHome: "사람 가까이에서 냄새를 찾고 회수하던 배경은 높은 교감과 탐색·놀이 참여로 이어질 수 있습니다.",
    reality: "부드러운 인상만큼 꾸준한 운동과 과제가 필요합니다. 젖거나 엉키기 쉬운 귀와 장식털을 관리할 시간도 준비해야 해요.",
    care: ["산책에서 수풀 냄새를 찾을 시간을 충분히 주세요.", "회수 놀이에는 기다리기와 놓기, 휴식을 함께 넣으세요.", "긴 귀와 발·다리 장식털을 말리고 이물질을 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "수풀 냄새 찾기", description: "사람 가까이에서 지그재그로 탐색해요." }, { time: "낮", title: "차분한 회복", description: "놀이 뒤 방해 없이 쉬게 해요." }, { time: "저녁", title: "회수와 귀 관리", description: "짧게 가져온 뒤 털과 귀를 살펴요." }],
    related: [["english-cocker-spaniel", "영국 스패니얼의 탐색과 회수를 공유하며 체격과 작업 범위가 달라요."], ["nova-scotia-duck-tolling-retriever", "회수와 높은 참여 욕구는 닮았지만 플러싱·톨링 역할을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/ENGLISH-SPRINGER-SPANIEL-125.html", akcUrl: "https://www.akc.org/dog-breeds/english-springer-spaniel/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/english-springer-spaniel-history/",
  },
  {
    slug: "havanese", nameKo: "하바니즈", nameEn: "Havanese",
    tagline: "부드럽게 흐르는 털 안에는 쿠바 가정에서 사람 가까이 지내온 작지만 단단한 반려견의 몸이 있어요.",
    group: "companion", tags: ["쿠바 반려견", "높은 교감", "장모 관리"], colors: ["#c3a47e", "#e7e2d5", "#40372f"],
    origin: "쿠바", lineage: "비숑과 관련된 소형 반려견", role: "쿠바 가정의 소형 반려견", size: "소형 · 약 22~29cm, 3~6kg", lifespan: "약 14~16년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "서지중해의 비숑 계통과 연결되며 쿠바에서 고유하게 발달해 가정의 사람 가까이 지낸 소형 반려견입니다.",
    today: "사람을 따라다니고 교감과 놀이에 적극적으로 참여할 수 있지만 혼자 있는 능력과 낯선 대상 반응은 개체마다 달라요.",
    guardianContext: "늘 함께 있는 것만으로 해결하지 말고 짧은 독립 휴식을 단계적으로 연습하며 긴 피모와 눈 주변, 치아 상태를 관리하세요.",
    opening: "하바니즈는 쿠바에서 고유하게 발달한 소형 반려견입니다. 부드러운 장모와 탄력 있는 걸음, 사람 가까이 지내온 역사를 지녔습니다.",
    roleToHome: "가족 곁에서 생활해 온 배경은 높은 교감과 일상 참여로 이어질 수 있습니다. 동시에 혼자 편히 쉬는 능력도 차근차근 가르쳐야 해요.",
    reality: "작고 사교적인 이미지가 쉬운 양육을 뜻하지는 않습니다. 분리 연습과 매일의 피모·치아 관리, 적절한 산책이 필요해요.",
    care: ["혼자 쉬는 시간을 짧고 성공적인 단계부터 연습하세요.", "긴 털은 피부까지 나누어 빗고 눈 주변을 깨끗하게 유지하세요.", "작은 체격에 맞는 산책과 학습 놀이, 치아 관리를 이어 가세요."],
    levels: ["중간", "높은 편", "낮은 편", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "가벼운 동네 탐색", description: "작은 몸에 맞는 속도로 냄새를 맡아요." }, { time: "낮", title: "독립 휴식", description: "사람과 떨어진 편한 자리에서 쉬어요." }, { time: "저녁", title: "교감과 빗질", description: "짧은 놀이 뒤 털과 치아를 봐요." }],
    related: [["bichon-frise", "비숑 계통의 교감과 장모 관리를 공유하며 피모 질감과 체형이 달라요."], ["maltese", "오랜 소형 반려견 사이에서 피모·활동과 관계 방식의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/HAVANESE-250.html", akcUrl: "https://www.akc.org/dog-breeds/havanese/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/havanese-history-bouncing-back-from-exile/",
  },
  {
    slug: "borzoi", nameKo: "보르조이", nameEn: "Borzoi - Russian Hunting Sighthound",
    tagline: "길고 우아한 실루엣 안에는 러시아의 넓은 땅에서 시야로 사냥감을 쫓던 큰 시각하운드의 속도가 있어요.",
    group: "sighthound", tags: ["러시아 시각하운드", "큰 질주 범위", "독립적인 추적"], colors: ["#c4b49d", "#dde2d7", "#34312e"],
    origin: "러시아", lineage: "장모 시각하운드", role: "넓은 지형에서 시야로 큰 사냥감을 추적", size: "대형 · 수컷 71cm 이상, 암컷 66cm 이상, 약 27~48kg", lifespan: "약 9~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "러시아의 넓은 영지에서 시야로 토끼와 여우, 늑대 같은 사냥감을 발견해 빠르게 추적하는 장모 시각하운드로 발달했습니다.",
    today: "실내에서는 조용히 쉬다가도 빠르게 움직이는 대상을 보면 즉시 추적하려는 모습이 나타날 수 있지만 반응은 개체마다 달라요.",
    guardianContext: "오프리드 추적은 피하고 높고 안전한 울타리 안에서 달릴 기회를 제공하며 큰 가슴과 긴 몸에 맞는 식사·운동 간격과 이동 수단을 준비하세요.",
    opening: "보르조이는 러시아에서 수세기 동안 발달한 대형 장모 시각하운드입니다. 넓은 지형에서 사냥감을 보고 빠르게 따라가는 역할을 했습니다.",
    roleToHome: "폭발적인 질주와 독립적인 추적 판단은 현대 생활에서 안전한 울타리와 리드 관리의 중요성으로 이어집니다.",
    reality: "우아하고 조용한 모습만으로 선택하기에는 큰 몸의 이동과 추적 관리 부담이 큽니다. 안전한 달리기 공간과 의료 계획이 필요해요.",
    care: ["빠른 대상을 향한 추적은 리드와 높은 울타리로 관리하세요.", "큰 몸이 편히 눕고 차량·병원으로 이동할 공간을 준비하세요.", "식사 전후 격한 운동을 피하고 갑작스러운 복부 불편은 즉시 진료받으세요."],
    levels: ["높은 편", "중간", "높은 편", "중간", "낮은 편", "중간"],
    days: [{ time: "아침", title: "긴 산책과 관찰", description: "안전한 리드로 넓게 주변을 살펴요." }, { time: "낮", title: "깊고 조용한 휴식", description: "긴 몸을 받치는 넓은 자리를 줘요." }, { time: "저녁", title: "안전한 질주", description: "울타리 안에서 짧게 달리고 회복해요." }],
    related: [["greyhound", "대형 시각하운드의 질주와 실내 휴식을 공유하며 피모와 체형이 달라요."], ["whippet", "빠른 시각 추적은 닮았지만 크기와 이동·공간 부담의 차이가 큽니다."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BORZOI-RUSSIAN-HUNTING-SIGHTHOUND-193.html", akcUrl: "https://www.akc.org/dog-breeds/borzoi/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/borzoi-history/",
  },
];

export const detailBatchFSlugs = seeds.map((seed) => seed.slug);

export const detailBatchF = seeds.map((seed) => ({
  slug: seed.slug,
  contentStatus: "mvp-editorial-draft",
  nameKo: seed.nameKo,
  nameEn: seed.nameEn,
  tagline: seed.tagline,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`,
  catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: { src: `/illustrations/v3/${seed.slug}-history.webp`, alt: historyAltOverrides[seed.slug] ?? `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: { originalRole: seed.originalRole, today: seed.today, guardianContext: seed.guardianContext },
  story: { opening: seed.opening, roleToHome: seed.roleToHome, reality: seed.reality },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "개체의 체력에 맞춘 규칙적인 산책과 놀이가 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 빗질과 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.care,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: seed.days,
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
    ...(seed.historyUrl ? [{ title: `${seed.nameEn} breed history`, organization: "American Kennel Club", url: seed.historyUrl, checkedAt: "2026-08-29" }] : []),
  ],
})) satisfies Breed[];
