import type { Breed } from "./schema";

const checkedAt = "2026-08-04";
type Level = Breed["tendencies"][keyof Breed["tendencies"]]["label"];
type DayStep = Breed["daySnapshot"][number];

type BatchHSeed = {
  slug: string; nameKo: string; nameEn: string; tagline: string;
  group: Breed["catalog"]["group"]; tags: [string, string, string]; colors: [string, string, string];
  origin: string; lineage: string; role: string; size: string; lifespan: string;
  originalRole: string; today: string; guardianContext: string;
  opening: string; roleToHome: string; reality: string;
  care: [string, string, string]; levels: [Level, Level, Level, Level, Level, Level];
  days: [DayStep, DayStep, DayStep]; related: [[string, string], [string, string]];
  fciUrl: string; akcUrl: string;
};

const seeds: BatchHSeed[] = [
  {
    slug: "beauceron", nameKo: "보스롱", nameEn: "Beauceron",
    tagline: "검정과 황갈색의 큰 몸에는 프랑스 평원에서 가축의 흐름을 읽고 무리를 지키던 목양견의 침착한 힘이 있어요.",
    group: "herding", tags: ["프랑스 목양견", "큰 체격과 힘", "이중 며느리발톱"], colors: ["#4b4039", "#d9ddd0", "#292725"],
    origin: "프랑스", lineage: "프랑스 저지대의 대형 목양견", role: "양 떼를 몰고 지키며 농장 주변을 경계", size: "대형 · 약 61~70cm, 32~50kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "프랑스의 넓은 평원에서 가축 떼의 방향을 조절하고 이동 중인 무리와 농장을 지키는 다목적 목양견으로 발달했습니다.",
    today: "주변 움직임을 빠르게 읽고 사람과 긴 과제에 집중하거나 낯선 상황을 신중히 살필 수 있지만 반응의 강도는 개체마다 달라요.",
    guardianContext: "성견의 큰 힘을 다룰 보상 기반 교육과 충분한 활동을 준비하고, 낯선 사람·동물과의 거리는 실제 반응에 맞춰 조절하세요.",
    opening: "보스롱은 프랑스에서 정립된 크고 단단한 단모 목양견입니다. 검정·황갈색 피모와 뒷다리의 이중 며느리발톱이 대표적인 특징입니다.",
    roleToHome: "넓은 지역에서 무리의 움직임을 판단하고 사람과 협력하던 배경은 높은 활동량과 과제 집중, 주변 변화에 대한 경계로 이어질 수 있습니다.",
    reality: "침착해 보이는 외형이 낮은 관리 난도를 뜻하지 않습니다. 큰 힘, 목양 행동과 경계를 안전하게 다룰 교육·사회화·운동 시간이 필요해요.",
    care: ["긴 산책에 방향 전환과 냄새·신호 과제를 함께 넣으세요.", "낯선 대상과의 인사는 강요하지 말고 선택할 거리를 주세요.", "큰 몸의 발과 관절, 뒷다리 며느리발톱 상태를 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "낮은 편"],
    days: [{ time: "아침", title: "움직임과 신호", description: "충분히 걷고 방향·정지 신호를 맞춰요." }, { time: "낮", title: "차분한 관찰", description: "자극과 거리를 두고 넓게 쉬게 해요." }, { time: "저녁", title: "협력 과제", description: "냄새 찾기와 짧은 학습으로 집중해요." }],
    related: [["german-shepherd-dog", "큰 목양·작업견의 협력을 공유하지만 목양 방식과 체형의 차이를 살펴보세요."], ["rottweiler", "가축 이동과 경비 배경을 공유하며 피모와 움직임, 생활 관리가 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BEAUCE-SHEEPDOG-44.html", akcUrl: "https://www.akc.org/dog-breeds/beauceron/",
  },
  {
    slug: "bullmastiff", nameKo: "불마스티프", nameEn: "Bullmastiff",
    tagline: "짧은 주둥이와 묵직한 몸에는 영국 영지의 밤길에서 침입자를 찾아 막아 서던 경비견의 절제된 힘이 있어요.",
    group: "guardian-working", tags: ["영국 야간 경비견", "초대형 근육질", "조용한 경계"], colors: ["#a87854", "#dfddd0", "#332b28"],
    origin: "영국", lineage: "마스티프와 불도그 계통을 바탕으로 정립된 경비견", role: "19세기 영지에서 밀렵자를 추적하고 제지", size: "대형 · 약 61~69cm, 45~59kg", lifespan: "약 7~9년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 영국의 사냥터 관리인과 함께 밤에 영지를 순찰하며 침입자를 찾아 따라가고 달아나지 못하도록 붙잡는 역할을 했습니다.",
    today: "낯선 움직임을 조용히 관찰하거나 큰 몸으로 사람과 공간 사이를 막을 수 있지만 경계와 친화성은 개체마다 달라요.",
    guardianContext: "큰 체중을 힘으로 제압하지 말고 어릴 때부터 보상 기반 신호를 익히며, 더위·호흡과 식사 전후 활동을 세심하게 관리하세요.",
    opening: "불마스티프는 영국에서 정립된 크고 강한 단모 경비견입니다. 황갈색·적색·브린들 피모와 어두운 마스크가 대표적입니다.",
    roleToHome: "사람 곁에서 넓은 영역을 살피고 필요한 순간에 움직이던 배경은 차분한 관찰과 낯선 변화에 대한 경계로 이어질 수 있습니다.",
    reality: "활동이 조용해 보여도 체격이 만드는 통제·이동·의료 부담은 큽니다. 사회화와 안전한 보행, 침과 더위 관리까지 준비해야 해요.",
    care: ["당기지 않고 걷기와 자리로 이동하는 신호를 일찍 가르치세요.", "더운 시간 활동을 줄이고 호흡과 회복 상태를 살피세요.", "식사 전후 격한 운동을 피하고 복부 불편은 즉시 진료받으세요."],
    levels: ["중간", "중간", "중간", "높은 편", "높은 편", "낮은 편"],
    days: [{ time: "아침", title: "서늘한 산책", description: "차분한 보행과 냄새 탐색을 해요." }, { time: "낮", title: "넓은 휴식", description: "큰 몸을 받치는 시원한 자리를 줘요." }, { time: "저녁", title: "경계 전환", description: "관찰 뒤 자리로 돌아와 쉬는 연습을 해요." }],
    related: [["rottweiler", "큰 경비견의 힘과 침착함을 공유하지만 체형과 작업 방식의 차이를 비교해 보세요."], ["cane-corso", "영역 경계 배경을 공유하며 주둥이·체격과 일상 활동 리듬이 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BULLMASTIFF-157.html", akcUrl: "https://www.akc.org/dog-breeds/bullmastiff/",
  },
  {
    slug: "border-terrier", nameKo: "보더 테리어", nameEn: "Border Terrier",
    tagline: "작고 거친 털의 몸에는 영국과 스코틀랜드 국경의 언덕에서 말과 함께 달리고 굴을 살피던 민첩함이 있어요.",
    group: "terrier", tags: ["국경 지대 테리어", "작고 민첩한 체형", "강한 굴 탐색"], colors: ["#9a7554", "#deddd1", "#34302b"],
    origin: "영국·스코틀랜드 국경", lineage: "국경 언덕 농장의 소형 작업 테리어", role: "말을 따라 이동하며 여우 굴과 농장 해충을 수색", size: "소형 · 약 30~38cm, 5~7kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국과 스코틀랜드 국경의 언덕 농장에서 말을 따라갈 만큼 긴 다리로 이동하고, 좁은 굴에 들어가 여우와 해충을 찾아내도록 발달했습니다.",
    today: "작은 구멍과 냄새를 끈기 있게 조사하거나 빠른 작은 동물을 쫓으려 할 수 있지만 추적과 사회성은 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 안전한 파기·냄새 놀이를 제공하며, 거친 이중모는 피부까지 확인하고 주기적으로 관리하세요.",
    opening: "보더 테리어는 영국과 스코틀랜드의 국경 지대에서 발달한 작고 단단한 작업 테리어입니다. 수달을 닮았다고 표현되는 머리와 거친 피모가 특징입니다.",
    roleToHome: "말을 따라 언덕을 이동하고 굴을 조사하던 배경은 작은 체격에 비해 높은 지구력과 냄새·파기 행동으로 이어질 수 있습니다.",
    reality: "작고 친근한 인상이 추적 욕구를 없애 주지는 않습니다. 안전한 리드, 충분한 탐색과 거친 피모 손질이 필요해요.",
    care: ["냄새 찾기와 안전한 파기 대체 놀이를 제공하세요.", "작은 동물 추적은 리드와 빈틈없는 울타리로 관리하세요.", "거친 이중모를 빗고 피부와 귀, 발을 규칙적으로 확인하세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "언덕길 탐색", description: "작은 몸의 속도에 맞춰 충분히 걸어요." }, { time: "낮", title: "조용한 회복", description: "파고들 수 있는 편안한 자리를 줘요." }, { time: "저녁", title: "찾기와 피모 확인", description: "냄새 과제 뒤 털과 발을 살펴요." }],
    related: [["jack-russell-terrier", "작은 작업 테리어의 추적과 지구력을 공유하며 체형과 작업 환경이 달라요."], ["scottish-terrier", "국경의 민첩한 테리어와 낮고 단단한 스코틀랜드 테리어를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BORDER-TERRIER-10.html", akcUrl: "https://www.akc.org/dog-breeds/border-terrier/",
  },
  {
    slug: "icelandic-sheepdog", nameKo: "아이슬란딕 시프도그", nameEn: "Icelandic Sheepdog",
    tagline: "선 귀와 말린 꼬리에는 아이슬란드 농장의 거친 지형에서 양과 말을 찾아 모으고 소리로 알리던 리듬이 있어요.",
    group: "spitz-primitive", tags: ["아이슬란드 목양 스피츠", "풍부한 발성", "두꺼운 이중모"], colors: ["#bd8054", "#e1dfd2", "#38322d"],
    origin: "아이슬란드", lineage: "북유럽 정착민의 개와 연결되는 목양 스피츠", role: "농장에서 양·말을 모으고 흩어진 가축의 위치를 알림", size: "중소형 · 약 42~46cm, 9~14kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "북유럽 정착민과 함께 아이슬란드에 들어온 개의 후손으로, 거친 농경지에서 양과 말을 모으고 흩어진 가축을 찾아 소리로 알렸습니다.",
    today: "사람과 동물의 움직임을 따라가거나 주변 변화를 또렷한 목소리로 알릴 수 있지만 목양과 발성의 강도는 개체마다 달라요.",
    guardianContext: "알림 뒤 돌아와 조용히 쉬는 행동을 보상하고, 가축·자전거를 몰려는 행동과 풍부한 이중모의 털갈이·더위 부담을 관리하세요.",
    opening: "아이슬란딕 시프도그는 아이슬란드에서 발달한 약간 긴 몸의 북유럽 목양 스피츠입니다. 선 귀와 말린 꼬리, 두꺼운 방수성 피모가 특징입니다.",
    roleToHome: "넓은 농장에서 가축의 위치와 움직임을 소리로 전달하던 배경은 높은 활동과 사람과의 협력, 풍부한 알림 행동으로 이어질 수 있습니다.",
    reality: "밝은 표정이 조용한 생활을 보장하지 않습니다. 매일 움직일 시간과 발성 교육, 많은 털을 감당할 수 있어야 해요.",
    care: ["알림 뒤 보호자에게 돌아와 조용히 쉬는 행동을 보상하세요.", "움직이는 대상 몰이는 거리와 대체 신호로 예방하세요.", "이중모를 자주 빗고 더운 날에는 활동 강도를 낮추세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "움직임과 탐색", description: "넉넉히 걷고 방향 신호를 맞춰요." }, { time: "낮", title: "시원한 휴식", description: "두꺼운 털이 식도록 편히 쉬게 해요." }, { time: "저녁", title: "알림 전환", description: "소리 뒤 돌아와 쉬는 행동을 연습해요." }],
    related: [["finnish-spitz", "북유럽 스피츠의 외형과 발성을 공유하지만 사냥과 목양이라는 역할이 달라요."], ["shetland-sheepdog", "섬 환경의 목양과 풍부한 알림을 공유하며 체형과 피모를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/ICELANDIC-SHEEPDOG-289.html", akcUrl: "https://www.akc.org/dog-breeds/icelandic-sheepdog/",
  },
  {
    slug: "rhodesian-ridgeback", nameKo: "로디지안 리지백", nameEn: "Rhodesian Ridgeback",
    tagline: "등을 거슬러 자라는 리지와 긴 다리에는 남부 아프리카의 넓은 지형에서 냄새와 시야로 멀리 추적하던 힘이 있어요.",
    group: "scent-hound", tags: ["남부 아프리카 하운드", "등의 리지", "장거리 추적"], colors: ["#b97549", "#dfded1", "#3a2e28"],
    origin: "남아프리카", lineage: "토착 리지드 독과 유럽계 사냥견의 계통", role: "넓은 지형에서 사냥감을 추적하고 거리를 두며 위치를 알림", size: "대형 · 약 61~69cm, 32~39kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "남부 아프리카의 넓고 거친 지형에서 여러 마리가 냄새와 시야로 사냥감을 추적하고, 안전한 거리를 유지하며 위치를 알리는 역할을 했습니다.",
    today: "먼 곳의 움직임을 보고 빠르게 추적하거나 익숙하지 않은 상황을 독립적으로 판단할 수 있지만 추적과 경계는 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 높은 울타리 안에서 달릴 기회를 주며, 큰 몸의 사회화와 등 피부·발·관절 상태를 살펴보세요.",
    opening: "로디지안 리지백은 남부 아프리카에서 정립된 크고 운동성 높은 하운드입니다. 등 중앙에서 반대 방향으로 자라는 털의 리지가 이름의 유래입니다.",
    roleToHome: "넓은 지역에서 거리를 유지하며 추적하던 배경은 폭발적인 질주, 넓은 시야 자극에 대한 반응과 독립적인 판단으로 이어질 수 있습니다.",
    reality: "짧은 털과 조용한 실내 모습만으로 생활 부담을 판단하기 어렵습니다. 안전한 질주 공간, 추적 통제와 대형견 이동 계획이 필요해요.",
    care: ["빠른 대상을 향한 추적은 리드와 높은 울타리로 관리하세요.", "짧은 훈련과 넓은 탐색 뒤 충분한 회복 시간을 주세요.", "리지 주변 피부와 큰 몸의 발·관절 상태를 확인하세요."],
    levels: ["높은 편", "중간", "높은 편", "중간", "중간", "낮은 편"],
    days: [{ time: "아침", title: "넓은 시야 산책", description: "안전한 리드로 길게 걷고 주변을 살펴요." }, { time: "낮", title: "조용한 회복", description: "긴 몸을 받치는 넓은 자리를 줘요." }, { time: "저녁", title: "추적 전환", description: "냄새 찾기 뒤 돌아오기 신호를 맞춰요." }],
    related: [["basenji", "아프리카 지역과 독립적인 사냥 배경을 공유하지만 체격과 추적 방식이 달라요."], ["greyhound", "빠른 시각 추적과 긴 다리를 공유하며 지구력·피모·역할을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/RHODESIAN-RIDGEBACK-146.html", akcUrl: "https://www.akc.org/dog-breeds/rhodesian-ridgeback/",
  },
  {
    slug: "english-setter", nameKo: "잉글리시 세터", nameEn: "English Setter",
    tagline: "흰 바탕의 섬세한 점과 장식털 아래에는 영국의 들에서 새의 위치를 찾아 조용히 멈춰 알리던 탄력 있는 몸이 있어요.",
    group: "pointing", tags: ["영국 세팅독", "들새 탐색", "벨턴 무늬와 장식털"], colors: ["#9f8e79", "#e3e2d7", "#37332f"],
    origin: "영국", lineage: "오랜 세팅 스패니얼 계통에서 정립된 포인팅견", role: "들에서 새를 탐색하고 낮게 멈춰 위치를 표시", size: "중대형 · 약 58~69cm, 20~36kg", lifespan: "약 12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국의 들에서 넓게 냄새를 찾고 새를 발견하면 몸을 낮춰 멈추는 ‘세팅’ 동작으로 위치를 알려 사냥꾼과 협력했습니다.",
    today: "넓은 공간을 부드럽게 달리며 냄새를 찾거나 사람과 긴 활동에 참여하려 할 수 있지만 작업 욕구와 사회성은 개체마다 달라요.",
    guardianContext: "긴 탐색과 돌아오기 교육을 함께 제공하고 야생동물 추적은 리드로 관리하며, 장식털과 긴 귀는 외출 뒤 이물질·습기를 확인하세요.",
    opening: "잉글리시 세터는 영국에서 오랫동안 발달한 우아하고 탄력 있는 포인팅견입니다. 흰 바탕에 작은 색점이 퍼진 벨턴 무늬가 대표적입니다.",
    roleToHome: "들새를 넓게 탐색하고 사람의 위치를 확인하며 일하던 배경은 높은 활동량과 냄새 탐색, 협력 욕구로 이어질 수 있습니다.",
    reality: "부드러운 인상과 별개로 매일 충분한 운동이 필요합니다. 추적 안전과 장식털·귀 관리 시간을 함께 계산해야 해요.",
    care: ["긴 산책에 냄새 찾기와 멈춤·돌아오기 신호를 섞으세요.", "야생동물 추적은 리드와 안전한 울타리로 예방하세요.", "귀와 가슴·다리 장식털의 습기와 이물질을 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "들길 탐색", description: "넉넉히 걷고 냄새와 멈춤 신호를 맞춰요." }, { time: "낮", title: "차분한 회복", description: "활동 뒤 방해 없이 길게 쉬게 해요." }, { time: "저녁", title: "귀와 장식털", description: "찾기 놀이 뒤 습기와 엉킴을 봐요." }],
    related: [["german-short-haired-pointing-dog", "넓은 들의 포인팅 작업을 공유하지만 피모와 체형, 움직임이 달라요."], ["vizsla", "사람과 협력하는 포인팅견의 활동성을 공유하며 피모 관리 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/ENGLISH-SETTER-2.html", akcUrl: "https://www.akc.org/dog-breeds/english-setter/",
  },
  {
    slug: "chesapeake-bay-retriever", nameKo: "체서피크 베이 리트리버", nameEn: "Chesapeake Bay Retriever",
    tagline: "짙은 갈색의 물결진 피모에는 차갑고 거친 체서피크만에서 물새를 되찾아 오던 강한 회수견의 몸이 있어요.",
    group: "retriever-spaniel", tags: ["미국 수상 회수견", "차가운 물 적응", "강한 방수성 피모"], colors: ["#6f503b", "#dbddd2", "#302b27"],
    origin: "미국", lineage: "체서피크만에서 정립된 수상 회수견", role: "차갑고 거친 물에서 물새를 찾아 반복 회수", size: "중대형 · 약 53~66cm, 25~36kg", lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 미국 체서피크만의 차갑고 거친 물에서 물새의 위치를 기억하고 수영해 반복해서 회수하도록 강인한 작업견으로 발달했습니다.",
    today: "물건을 찾고 물에서 오래 활동하거나 익숙한 사람과 집중해 일하려 할 수 있지만 물 선호와 낯선 대상 반응은 개체마다 달라요.",
    guardianContext: "회수 놀이에는 기다리기·놓기·휴식을 묶고, 물놀이는 안전한 출구와 수온을 확인하며 젖은 귀와 빽빽한 피모를 완전히 말리세요.",
    opening: "체서피크 베이 리트리버는 미국 체서피크만의 거친 수상 환경에서 정립된 강하고 균형 잡힌 회수견입니다. 갈색 계열의 짧고 물결진 방수성 피모가 특징입니다.",
    roleToHome: "차가운 물에서 독립적으로 판단하며 여러 번 회수하던 배경은 높은 활동과 끈기, 물건을 운반하려는 행동으로 이어질 수 있습니다.",
    reality: "리트리버라는 이름이 모든 개체의 사회성을 보장하지 않습니다. 충분한 활동, 안전한 물놀이와 피모·귀 관리가 필요해요.",
    care: ["회수 놀이에 기다리기·놓기·완전한 휴식을 함께 넣으세요.", "물놀이 전 수온과 출구를 확인하고 무리한 반복을 피하세요.", "젖은 귀와 빽빽한 피모를 확인하고 완전히 말리세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "중간", "중간"],
    days: [{ time: "아침", title: "탐색과 회수", description: "걷기와 찾기, 가져오기를 균형 있게 해요." }, { time: "낮", title: "완전한 회복", description: "활동 뒤 시원한 자리에서 길게 쉬어요." }, { time: "저녁", title: "피모와 귀 확인", description: "물기와 이물질을 살피고 잘 말려요." }],
    related: [["labrador-retriever", "북미 회수견의 물 작업을 공유하지만 체형과 피모, 낯선 대상 반응이 달라요."], ["flat-coated-retriever", "물과 들의 회수 작업을 공유하며 피모 구조와 작업 스타일을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/CHESAPEAKE-BAY-RETRIEVER-263.html", akcUrl: "https://www.akc.org/dog-breeds/chesapeake-bay-retriever/",
  },
  {
    slug: "portuguese-water-dog", nameKo: "포르투갈 워터 도그", nameEn: "Portuguese Water Dog",
    tagline: "곱슬거리거나 물결진 피모 아래에는 포르투갈 어선과 해안 사이를 헤엄치며 사람의 일을 돕던 단단한 몸이 있어요.",
    group: "retriever-spaniel", tags: ["포르투갈 어업 작업견", "강한 수영 능력", "곱슬·물결 피모"], colors: ["#403c39", "#dde0d4", "#262625"],
    origin: "포르투갈", lineage: "포르투갈 해안의 수상 작업견", role: "어구 회수와 배 사이 전달 등 어부의 작업 보조", size: "중형 · 약 43~57cm, 16~27kg", lifespan: "약 11~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "포르투갈 해안에서 어부와 함께 배를 타고 물에 뛰어들어 잃어버린 어구를 회수하거나 배와 육지 사이의 전달을 돕는 수상 작업견이었습니다.",
    today: "물에서 활동하고 물건을 찾아 가져오거나 사람 가까이 과제에 참여하려 할 수 있지만 물 선호와 교감 방식은 개체마다 달라요.",
    guardianContext: "수영은 안전한 출구와 구명 장비를 준비하고, 반복 회수 뒤 쉬는 연습과 곱슬·물결 피모의 빗질·건조·정기 미용을 계획하세요.",
    opening: "포르투갈 워터 도그는 포르투갈 해안의 어업과 함께 발달한 단단한 중형 수상 작업견입니다. 곱슬형과 물결형 피모가 모두 있습니다.",
    roleToHome: "어부 가까이에서 수영과 회수를 반복하던 배경은 높은 활동량과 물건 운반, 사람과의 협력 욕구로 이어질 수 있습니다.",
    reality: "털 빠짐이 적다고 손질이 적은 것은 아닙니다. 충분한 활동과 독립 휴식, 자라는 피모의 빗질·미용 시간이 필요해요.",
    care: ["회수 놀이에는 기다리기와 놓기, 휴식을 함께 넣으세요.", "수영 전 출구와 수온을 확인하고 필요하면 구명조끼를 사용하세요.", "피부까지 나누어 빗고 젖은 털과 귀를 완전히 말리세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "긴 활동과 찾기", description: "걷기와 회수 과제를 함께 구성해요." }, { time: "낮", title: "독립 휴식", description: "사람과 떨어져 편히 쉬는 연습을 해요." }, { time: "저녁", title: "피모와 귀 관리", description: "젖은 곳과 엉킴을 피부까지 확인해요." }],
    related: [["poodle", "수상 회수 배경과 자라는 곱슬 피모를 공유하며 체형과 역할의 차이를 보세요."], ["newfoundland", "물에서 사람과 일한 역사를 공유하지만 체격과 원래 작업 규모가 크게 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/PORTUGUESE-WATER-DOG-37.html", akcUrl: "https://www.akc.org/dog-breeds/portuguese-water-dog/",
  },
  {
    slug: "chinese-crested-dog", nameKo: "차이니즈 크레스티드 도그", nameEn: "Chinese Crested Dog",
    tagline: "맨살과 부드러운 볏털이 먼저 보이지만, 정확한 기원은 단정하기 어려운 작고 섬세한 반려견의 역사도 함께 살펴봐요.",
    group: "companion", tags: ["헤어리스·파우더퍼프", "작고 섬세한 체형", "피부·치아 관리"], colors: ["#c49b86", "#e4e0d7", "#3b312e"],
    origin: "정확한 기원은 불확실함 · 중국 후원", lineage: "헤어리스와 파우더퍼프 두 변종을 지닌 소형 반려견", role: "사람 곁에서 생활한 소형 반려견", size: "소형 · 약 28~33cm, 대체로 5.5kg 이하", lifespan: "약 13~18년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "정확한 발생지와 이동 경로는 확정하기 어렵습니다. 여러 지역을 거쳐 오늘의 두 피모 변종을 지닌 소형 반려견으로 정립되었습니다.",
    today: "사람 가까이에서 놀이와 교감에 참여하거나 낯선 환경을 조심스럽게 살필 수 있지만 사회성과 독립성은 개체마다 달라요.",
    guardianContext: "헤어리스는 햇빛·추위와 피부 자극을, 파우더퍼프는 엉킴을 관리하고 작은 치아와 발을 규칙적으로 확인하세요.",
    opening: "차이니즈 크레스티드 도그는 헤어리스와 전신에 부드러운 털이 난 파우더퍼프 두 변종이 있는 소형 반려견입니다. 정확한 기원 이야기는 불확실성을 남겨 두어야 합니다.",
    roleToHome: "오랜 반려 생활의 배경은 사람과의 가까운 교감으로 이어질 수 있지만 혼자 쉬는 능력과 낯선 대상 반응은 실제 개체를 살펴야 합니다.",
    reality: "털이 적다고 관리가 없는 것은 아닙니다. 피부 보호와 체온 조절, 치아 관리 또는 파우더퍼프의 빗질까지 생활에 포함해야 해요.",
    care: ["헤어리스 피부는 강한 햇빛·추위와 마찰 자극에서 보호하세요.", "파우더퍼프 피모는 피부까지 빗고 완전히 건조하세요.", "작은 치아와 발, 피부 상태를 규칙적으로 확인하세요."],
    levels: ["중간", "중간", "중간", "높은 편", "중간", "중간"],
    days: [{ time: "아침", title: "짧은 탐색", description: "기온과 피부 상태에 맞춰 산책해요." }, { time: "낮", title: "따뜻한 휴식", description: "부드럽고 안정된 자리에서 쉬게 해요." }, { time: "저녁", title: "교감과 상태 확인", description: "놀이 뒤 피부·털과 치아를 살펴요." }],
    related: [["chihuahua", "작고 사람 가까이 생활하는 반려견이지만 체형과 피모·체온 관리가 달라요."], ["havanese", "높은 교감의 소형 반려견 사이에서 피모 구조와 손질 방식을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/CHINESE-CRESTED-DOG-288.html", akcUrl: "https://www.akc.org/dog-breeds/chinese-crested/",
  },
  {
    slug: "saluki", nameKo: "살루키", nameEn: "Saluki",
    tagline: "가느다란 몸과 긴 다리에는 중동의 넓고 건조한 지형에서 시야로 사냥감을 찾아 빠르게 좇던 오래된 협력의 흔적이 있어요.",
    group: "sighthound", tags: ["중동 시각하운드", "빠른 장거리 추적", "페더드·스무스 변종"], colors: ["#c5a47d", "#e0dfd3", "#39322d"],
    origin: "중동 · FCI 후원", lineage: "중동 여러 지역의 오래된 시각하운드", role: "사막과 초원에서 가젤·토끼류를 시야로 추적", size: "대형 · 약 58~71cm, 18~29kg", lifespan: "약 10~17년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "중동의 사막과 초원에서 사람과 함께 이동하며 먼 곳의 사냥감을 시야로 발견하고 빠르게 추적하는 시각하운드로 오랫동안 길러졌습니다.",
    today: "실내에서는 조용히 쉬다가도 빠른 움직임을 보면 폭발적으로 추적하거나 스스로 거리를 조절할 수 있지만 반응은 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 높은 울타리 안에서 안전하게 달릴 기회를 주며, 얇은 체형의 체온·피부와 귀·꼬리 장식털을 살펴보세요.",
    opening: "살루키는 중동 여러 지역과 연결되는 오래된 시각하운드입니다. 매끈한 몸에 귀와 꼬리 장식털이 있는 페더드형과 스무스형이 있습니다.",
    roleToHome: "넓은 지형에서 시야로 사냥감을 좇던 배경은 빠른 질주와 움직임 자극에 대한 반응, 독립적인 판단으로 이어질 수 있습니다.",
    reality: "조용하고 가벼운 인상이 낮은 운동 필요를 뜻하지 않습니다. 추적을 통제할 환경과 안전한 질주, 부드러운 휴식 공간이 필요해요.",
    care: ["빠른 대상을 향한 추적은 리드와 높은 울타리로 관리하세요.", "안전한 질주 뒤 충분히 걷고 길게 회복하게 하세요.", "얇은 피부와 체온, 귀·꼬리 장식털의 엉킴을 확인하세요."],
    levels: ["높은 편", "중간", "높은 편", "중간", "낮은 편", "중간"],
    days: [{ time: "아침", title: "넓은 시야 산책", description: "안전한 리드로 길게 걷고 주변을 봐요." }, { time: "낮", title: "부드러운 휴식", description: "긴 몸을 받치는 따뜻한 자리를 줘요." }, { time: "저녁", title: "안전한 질주", description: "울타리 안에서 달린 뒤 천천히 회복해요." }],
    related: [["afghan-hound", "아시아의 오래된 시각하운드로서 험지 추적을 공유하지만 피모 구조가 크게 달라요."], ["greyhound", "빠른 시각 추적과 긴 다리를 공유하며 체형과 역사적 환경을 비교해 보세요."]],
    fciUrl: "https://fci.be/en/nomenclature/SALUKI-269.html", akcUrl: "https://www.akc.org/dog-breeds/saluki/",
  },
];

export const detailBatchHSlugs = seeds.map((seed) => seed.slug);

export const detailBatchH = seeds.map((seed) => ({
  slug: seed.slug,
  contentStatus: "mvp-editorial-draft",
  nameKo: seed.nameKo,
  nameEn: seed.nameEn,
  tagline: seed.tagline,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`,
  catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: { src: `/illustrations/v3/${seed.slug}-history.webp`, alt: `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: { originalRole: seed.originalRole, today: seed.today, guardianContext: seed.guardianContext },
  story: { opening: seed.opening, roleToHome: seed.roleToHome, reality: seed.reality },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "개체의 체력에 맞춘 규칙적인 산책과 놀이가 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 빗질과 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.care,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: seed.days,
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
  ],
})) satisfies Breed[];
