import type { Breed } from "./schema";
import { withTopicParticle } from "../../lib/korean-particles";

const checkedAt = "2026-08-05";
type Level = "낮은 편" | "중간" | "높은 편";
type Seed = {
  slug: string; nameKo: string; nameEn: string; group: Breed["catalog"]["group"];
  tags: string[]; colors: [string, string, string]; origin: string; lineage: string; role: string;
  size: string; lifespan: string; levels: [Level, Level, Level, Level, Level, Level];
  focus: string[]; related: [string, string][]; fciUrl: string; akcUrl: string;
};

const seeds: Seed[] = [
  { slug: "australian-silky-terrier", nameKo: "오스트레일리안 실키 테리어", nameEn: "Australian Silky Terrier", group: "terrier", tags: ["작은 호주 테리어", "긴 실키 피모", "해충 추적"], colors: ["#9a765a", "#e3d7c9", "#352e29"], origin: "호주", lineage: "영국 테리어와 호주 토종 작업견 계통", role: "가정과 농장에서 작은 해충을 통제하는 작업", size: "소형 · 약 23~26cm, 3.5~4.5kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)", levels: ["중간", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["작은 동물을 향한 추적을 리드와 울타리로 관리하세요.", "긴 실키 피모가 엉키지 않도록 매일 짧게 빗질하세요."], related: [["yorkshire-terrier", "작은 장모 테리어의 피모와 사람 곁 생활을 비교해 보세요."], ["jack-russell-terrier", "작은 몸에서 나타나는 테리어의 추적 욕구를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/AUSTRALIAN-SILKY-TERRIER-236.html", akcUrl: "https://www.akc.org/dog-breeds/australian-terrier/" },
  { slug: "finnish-lapponian-dog", nameKo: "핀니시 라포니안 독", nameEn: "Finnish Lapponian Dog", group: "northern-working", tags: ["핀란드 북부 목양견", "순록과 협력", "풍성한 이중모"], colors: ["#806b58", "#dfd6c6", "#332d29"], origin: "핀란드 라플란드", lineage: "사미 지역의 순록 목양견", role: "순록을 몰고 북부 마을과 목장을 지키는 협력", size: "중형 · 약 41~52cm, 15~24kg", lifespan: "약 12~14년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["추운 계절에도 매일 냄새와 움직임을 살피는 시간을 주세요.", "두꺼운 이중모와 발가락 사이를 계절에 맞춰 관리하세요."], related: [["shetland-sheepdog", "사람과 가축의 움직임을 읽는 목양 협력을 비교해 보세요."], ["samoyed", "북부 환경의 이중모와 사람 곁 생활을 공유하지만 역할이 달라요."]], fciUrl: "https://www.fci.be/en/nomenclature/FINNISH-LAPPONIAN-DOG-189.html", akcUrl: "https://www.akc.org/dog-breeds/finnish-lapphund/" },
  { slug: "swedish-vallhund", nameKo: "스웨디시 발훈트", nameEn: "Swedish Vallhund", group: "herding", tags: ["스웨덴 농장견", "짧은 다리 목양", "경계와 협력"], colors: ["#85705b", "#ded5c6", "#342e29"], origin: "스웨덴", lineage: "스웨덴 서부의 오래된 소몰이견", role: "소의 발뒤꿈치를 살피고 농장 주변을 지키는 작업", size: "소형·중형 · 약 30~35cm, 9~14kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "낮은 편"], focus: ["발목을 향한 몰이 행동을 사람과 동물에게 연습시키지 마세요.", "짧은 다리에 맞춰 계단과 점프를 줄이고 체중을 관리하세요."], related: [["welsh-corgi-pembroke", "짧은 다리의 소몰이견과 발목 몰이 경향을 비교해 보세요."], ["australian-cattle-dog", "농장에서 움직임을 통제한 역사와 활동 욕구를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/SWEDISH-VALLHUND-14.html", akcUrl: "https://www.akc.org/dog-breeds/swedish-vallhund/" },
  { slug: "italian-volpino", nameKo: "볼피노 이탈리아노", nameEn: "Italian Volpino", group: "spitz-primitive", tags: ["이탈리아 스피츠", "작은 경계견", "풍성한 흰 피모"], colors: ["#c9bfae", "#f0ece3", "#3a342f"], origin: "이탈리아", lineage: "중부 유럽 스피츠와 이탈리아 가정견 계통", role: "가정과 농장의 작은 경계·동행", size: "소형 · 약 25~30cm, 4~5kg", lifespan: "약 14~16년 (FCI 참고, 개체별 차이 있음)", levels: ["중간", "중간", "중간", "높은 편", "높은 편", "높은 편"], focus: ["작은 몸과 큰 목소리를 함께 고려해 이웃과 생활을 조율하세요.", "풍성한 피모를 피부까지 확인하며 정기적으로 빗질하세요."], related: [["german-spitz", "유럽 스피츠의 경계와 피모 특징을 비교해 보세요."], ["japanese-spitz", "흰 스피츠의 사람 곁 생활과 체격 차이를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/VOLPINO-ITALIANO-195.html", akcUrl: "https://www.akc.org/dog-breeds/italian-volpino/" },
  { slug: "eurasier", nameKo: "유라시어", nameEn: "Eurasier", group: "spitz-primitive", tags: ["독일 반려 스피츠", "가족과의 유대", "이중모"], colors: ["#94765d", "#dfd8cb", "#352f2b"], origin: "독일", lineage: "차우차우·울프스피츠·사모예드 계통", role: "가정 안에서 사람과 안정적으로 동행하는 반려", size: "중형 · 약 48~60cm, 18~32kg", lifespan: "약 12~14년 (FCI 참고, 개체별 차이 있음)", levels: ["중간", "중간", "중간", "높은 편", "중간", "높은 편"], focus: ["가족과 가까이 지내되 혼자 회복하는 시간을 존중하세요.", "계절성 털갈이와 피부 상태를 꾸준히 관리하세요."], related: [["chow-chow", "차우차우 계통과 독립적인 교감 방식을 비교해 보세요."], ["samoyed", "북부 스피츠의 피모와 사람 협력을 함께 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/EURASIAN-291.html", akcUrl: "https://www.akc.org/dog-breeds/eurasier/" },
  { slug: "american-akita", nameKo: "아메리칸 아키타", nameEn: "American Akita", group: "spitz-primitive", tags: ["북미 대형 스피츠", "독립적인 경계", "큰 체격"], colors: ["#8a6c54", "#ddd3c3", "#312c28"], origin: "미국", lineage: "아키타 계통에서 북미에서 발전한 대형견", role: "가정과 재산을 지키며 사람과 동행", size: "대형 · 약 61~71cm, 32~59kg", lifespan: "약 10~14년 (AKC 참고, 개체별 차이 있음)", levels: ["중간", "중간", "높은 편", "중간", "높은 편", "높은 편"], focus: ["다른 동물과 낯선 사람의 거리를 보호자가 세심하게 설계하세요.", "큰 몸과 이중모, 더위와 체중을 생활 계획에 넣으세요."], related: [["akita", "아키타 계통의 체형과 독립성을 공유하며 크기와 등록 기준이 달라요."], ["tibetan-mastiff", "큰 스피츠형 경계견의 생활 책임을 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/AKITA-255.html", akcUrl: "https://www.akc.org/dog-breeds/akita/" },
  { slug: "hokkaido", nameKo: "홋카이도견", nameEn: "Hokkaido", group: "spitz-primitive", tags: ["일본 북부 사냥견", "용맹한 경계", "이중모"], colors: ["#8b6f5b", "#ded5c5", "#302b27"], origin: "일본 홋카이도", lineage: "아이누 지역의 산악 사냥견", role: "산악 지형에서 곰과 사슴을 추적하고 경계", size: "중형 · 약 45~52cm, 20~30kg", lifespan: "약 12~15년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "높은 편", "중간", "높은 편", "높은 편"], focus: ["추적과 경계 반응을 높은 울타리와 리드로 관리하세요.", "더운 계절의 이중모와 회복 상태를 특별히 살피세요."], related: [["shiba", "일본 산악 사냥견의 독립성과 크기 차이를 비교해 보세요."], ["akita", "일본 스피츠형 사냥·경계견의 체격과 생활 조건을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/HOKKAIDO-261.html", akcUrl: "https://www.akc.org/dog-breeds/hokkaido/" },
  { slug: "kai", nameKo: "카이견", nameEn: "Kai", group: "spitz-primitive", tags: ["일본 산악견", "줄무늬 피모", "사냥 추적"], colors: ["#6e6258", "#d9d1c3", "#2f2b27"], origin: "일본 야마나시", lineage: "일본 산악 지역의 카이 켄 계통", role: "산악 지형에서 멧돼지와 사슴을 추적", size: "중형 · 약 45~56cm, 14~27kg", lifespan: "약 12~15년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "높은 편", "중간", "중간", "낮은 편"], focus: ["작은 동물과 빠른 움직임을 안전하게 관리하세요.", "독립적인 선택 뒤 호출로 돌아오는 연습을 짧게 반복하세요."], related: [["shikoku", "일본 산악 사냥견의 체형과 추적 욕구를 비교해 보세요."], ["korea-jindo-dog", "동아시아 산악견의 독립성과 사람과의 거리 조절을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/KAI-317.html", akcUrl: "https://www.akc.org/dog-breeds/kai-ken/" },
  { slug: "kishu", nameKo: "키슈견", nameEn: "Kishu", group: "spitz-primitive", tags: ["일본 사냥견", "산악 추적", "차분한 독립성"], colors: ["#b9b2a5", "#eeece4", "#38332e"], origin: "일본 기이 반도", lineage: "일본 산악 지역의 오래된 사냥견", role: "산에서 멧돼지와 사슴을 추적", size: "중형 · 약 43~55cm, 14~27kg", lifespan: "약 11~13년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "높은 편", "중간", "중간", "낮은 편"], focus: ["추적 본능을 안전한 냄새 찾기와 긴 리드로 전환하세요.", "낯선 자극에서 스스로 판단할 시간을 주고 강요하지 마세요."], related: [["shikoku", "일본 산악 사냥견의 독립성과 활동 반경을 비교해 보세요."], ["basenji", "원시견의 자기 주도성과 사람과의 협력 방식을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/KISHU-318.html", akcUrl: "https://www.akc.org/dog-breeds/kishu-ken/" },
  { slug: "shikoku", nameKo: "시코쿠견", nameEn: "Shikoku", group: "spitz-primitive", tags: ["일본 산악 사냥견", "민첩한 움직임", "추적과 회복"], colors: ["#8f6f57", "#dfd4c3", "#322d29"], origin: "일본 시코쿠", lineage: "시코쿠 산악 지역의 사냥견", role: "험한 지형에서 멧돼지를 추적", size: "중형 · 약 43~55cm, 15~25kg", lifespan: "약 11~13년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "높은 편", "중간", "높은 편", "낮은 편"], focus: ["빠른 방향 전환과 추적을 안전한 공간에서만 허용하세요.", "충분히 움직인 뒤 조용히 회복하는 루틴을 마련하세요."], related: [["shiba", "일본 산악견의 추적과 독립성을 공유하며 체격을 비교해 보세요."], ["akita", "일본 스피츠의 경계와 사람과의 거리 조절을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/SHIKOKU-319.html", akcUrl: "https://www.akc.org/dog-breeds/shikoku/" },
  { slug: "canaan-dog", nameKo: "카나안 독", nameEn: "Canaan Dog", group: "spitz-primitive", tags: ["중동 원시견", "영역 경계", "환경 적응"], colors: ["#a37e5c", "#e4d9c9", "#352f2a"], origin: "이스라엘", lineage: "중동에서 자연 선택과 훈련으로 발전한 원시견", role: "가축과 정착지를 지키고 메신저·탐지 작업", size: "중형 · 약 50~60cm, 18~25kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)", levels: ["중간", "높은 편", "높은 편", "중간", "높은 편", "낮은 편"], focus: ["낯선 사람과 소리에 대한 경계를 거리와 예측 가능한 루틴으로 관리하세요.", "혼자 쉬는 선택을 존중하되 안전한 호출을 반복하세요."], related: [["basenji", "원시견의 자기 주도성과 환경 경계를 비교해 보세요."], ["korea-jindo-dog", "독립적인 동아시아·중동 원시견의 생활 차이를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/CANAAN-DOG-273.html", akcUrl: "https://www.akc.org/dog-breeds/canaan-dog/" },
  { slug: "yakutian-laika", nameKo: "야쿠티안 라이카", nameEn: "Yakutian Laika", group: "northern-working", tags: ["시베리아 썰매견", "추운 기후", "사람과의 협력"], colors: ["#a08c77", "#e4dfd4", "#332f2a"], origin: "러시아 사하", lineage: "야쿠트 지역의 썰매·사냥 작업견", role: "썰매를 끌고 사냥과 순록 작업을 보조", size: "중형 · 약 53~59cm, 20~30kg", lifespan: "약 10~13년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["기온이 맞지 않는 계절에는 운동량보다 더위와 발 상태를 우선하세요.", "무리 작업의 협력 욕구를 냄새 찾기와 팀 과제로 연결하세요."], related: [["siberian-husky", "썰매 작업과 지구력을 공유하며 피모와 생활 자극을 비교해 보세요."], ["samoyed", "북부 작업견의 협력과 이중모 관리 부담을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/YAKUTIAN-LAIKA-365.html", akcUrl: "https://www.akc.org/dog-breeds/yakutian-laika/" },
  { slug: "harrier", nameKo: "해리어", nameEn: "Harrier", group: "scent-hound", tags: ["영국 무리 사냥견", "긴 냄새 추적", "지구력"], colors: ["#a87f61", "#e2d8c9", "#38312b"], origin: "영국", lineage: "비글·폭스하운드와 연결된 중형 센트하운드", role: "무리를 이루어 토끼와 작은 사냥감을 냄새로 추적", size: "중형 · 약 48~53cm, 20~27kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"], focus: ["냄새를 따라가려는 힘을 긴 리드와 울타리로 관리하세요.", "지루하지 않게 냄새 산책과 회복일을 번갈아 주세요."], related: [["beagle", "무리 냄새 추적과 사람 곁 생활의 균형을 비교해 보세요."], ["english-foxhound", "영국 센트하운드의 지구력과 생활 반경을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/HARRIER-295.html", akcUrl: "https://www.akc.org/dog-breeds/harrier/" },
  { slug: "english-foxhound", nameKo: "잉글리시 폭스하운드", nameEn: "English Foxhound", group: "scent-hound", tags: ["영국 여우 사냥견", "무리 추적", "넓은 활동 공간"], colors: ["#ab8062", "#e7ddd0", "#3b322c"], origin: "영국", lineage: "영국의 오래된 폭스하운드 계통", role: "무리로 여우 냄새를 따라 넓은 지형을 추적", size: "대형 · 약 58~64cm, 25~34kg", lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"], focus: ["안전한 울타리와 리드 없이는 냄새 추적을 허용하지 마세요.", "가정에서 충분한 보행과 냄새 활동을 제공할 수 있는지 먼저 확인하세요."], related: [["harrier", "영국 무리 사냥견의 지구력과 냄새 추적을 비교해 보세요."], ["beagle", "작은 체격의 센트하운드와 생활 공간 차이를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/ENGLISH-FOXHOUND-159.html", akcUrl: "https://www.akc.org/dog-breeds/english-foxhound/" },
  { slug: "petit-basset-griffon-vendeen", nameKo: "페티 바셋 그리폰 방데앙", nameEn: "Petit Basset Griffon Vendeen", group: "scent-hound", tags: ["프랑스 소형 센트하운드", "거친 털", "끈질긴 추적"], colors: ["#a27d60", "#e3dacd", "#39312b"], origin: "프랑스 방데", lineage: "방데 지역의 작은 거친 털 사냥견", role: "가시덤불과 바위 지형에서 작은 사냥감을 냄새로 추적", size: "소형 · 약 34~38cm, 11~18kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["작은 몸을 과소평가하지 말고 추적과 파기를 안전하게 전환하세요.", "거친 털과 귀에 붙은 이물질을 산책 뒤 확인하세요."], related: [["beagle", "작은 사냥감 냄새 추적과 사람 곁 생활을 비교해 보세요."], ["border-terrier", "거친 지형을 다니는 소형견의 피모와 추적을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/PETIT-BASSET-GRiffON-VENDEEN-163.html", akcUrl: "https://www.akc.org/dog-breeds/petit-basset-griffon-vendeen/" },
  { slug: "finnish-hound", nameKo: "핀니시 하운드", nameEn: "Finnish Hound", group: "scent-hound", tags: ["핀란드 사냥견", "계절성 추적", "지구력 산책"], colors: ["#9f7254", "#e6d9cb", "#352e29"], origin: "핀란드", lineage: "스칸디나비아와 유럽 사냥견을 바탕으로 한 센트하운드", role: "토끼와 여우의 냄새를 따라 숲을 추적", size: "중형 · 약 52~61cm, 20~25kg", lifespan: "약 10~12년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "중간", "중간", "낮은 편"], focus: ["긴 냄새 추적을 짧은 안전한 구간으로 나누세요.", "추운 날 발바닥과 습기를 산책 후 확인하세요."], related: [["beagle", "센트하운드의 냄새 집중과 활동량을 비교해 보세요."], ["harrier", "북유럽 사냥견의 지구력과 무리 생활을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/FINNISH-HOUND-51.html", akcUrl: "https://www.fci.be/en/nomenclature/FINNISH-HOUND-51.html" },
  { slug: "alpine-dachsbracke", nameKo: "알파인 닥스브라케", nameEn: "Alpine Dachsbracke", group: "scent-hound", tags: ["알프스 추적견", "짧은 다리", "부상 사냥감 추적"], colors: ["#8d6651", "#ddd2c5", "#332d29"], origin: "오스트리아 알프스", lineage: "닥스훈트와 브라케 계통의 산악 사냥견", role: "산악 지형에서 부상한 사냥감의 냄새를 추적", size: "소형·중형 · 약 34~42cm, 15~18kg", lifespan: "약 12~14년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "중간", "중간", "낮은 편"], focus: ["짧은 다리와 허리에 맞춰 계단·점프를 줄이세요.", "냄새 찾기와 긴 리드 산책으로 추적 욕구를 안전하게 채우세요."], related: [["dachshund", "짧은 다리와 냄새 추적의 공통점, 허리 관리 차이를 비교해 보세요."], ["basset-hound", "낮은 체형의 센트하운드와 보행 관리 부담을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/ALPINE-DACHSBRACKE-254.html", akcUrl: "https://www.fci.be/en/nomenclature/ALPINE-DACHSBRACKE-254.html" },
  { slug: "bavarian-mountain-scent-hound", nameKo: "바바리안 마운틴 센트 하운드", nameEn: "Bavarian Mountain Scent Hound", group: "scent-hound", tags: ["독일 산악 추적견", "정밀한 후각", "긴 리드 생활"], colors: ["#9a6d53", "#e0d4c7", "#362d28"], origin: "독일 바이에른", lineage: "하노버 하운드와 산악 브라케 계통", role: "산악에서 부상한 사냥감의 흔적을 정밀하게 추적", size: "중형 · 약 44~52cm, 17~30kg", lifespan: "약 10~14년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "중간", "중간", "낮은 편"], focus: ["냄새를 따라가는 선택을 긴 리드와 안전한 수색 과제로 연결하세요.", "산악 활동 뒤 발·귀·피부의 이물질을 확인하세요."], related: [["bloodhound", "부상 사냥감의 흔적을 좇는 후각 작업과 생활 책임을 비교해 보세요."], ["dachshund", "작은 사냥감 추적과 후각 집중의 차이를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/BAVARIAN-MOUNTAIN-SCENT-HOUND-217.html", akcUrl: "https://www.fci.be/en/nomenclature/BAVARIAN-MOUNTAIN-SCENT-HOUND-217.html" },
  { slug: "german-wire-haired-pointing-dog", nameKo: "저먼 와이어헤어드 포인터", nameEn: "German Wire-Haired Pointing Dog", group: "pointing", tags: ["독일 포인팅견", "육지·물 겸용", "거친 털"], colors: ["#6f6258", "#d8d0c2", "#332d29"], origin: "독일", lineage: "독일의 다양한 포인팅·거친 털 사냥견", role: "사냥감의 위치를 알리고 육지와 물에서 회수", size: "중형·대형 · 약 57~68cm, 25~32kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["냄새·회수 과제를 매일 제공하되 야생동물 추적은 통제하세요.", "거친 털과 귀, 물 활동 뒤 피부를 말리세요."], related: [["german-short-haired-pointing-dog", "독일 포인팅 협력과 운동량을 공유하며 피모가 달라요."], ["vizsla", "사람과 함께 탐색하고 회수하는 방식의 차이를 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/GERMAN-WIRE-HAIRED-POINTING-DOG-98.html", akcUrl: "https://www.akc.org/dog-breeds/german-wirehaired-pointer/" },
  { slug: "italian-pointing-dog", nameKo: "브라코 이탈리아노", nameEn: "Italian Pointing Dog", group: "pointing", tags: ["이탈리아 포인팅견", "느린 탐색", "사람과 협력"], colors: ["#b88968", "#e4d7c8", "#3b302b"], origin: "이탈리아", lineage: "이탈리아의 오래된 포인팅견", role: "사냥감의 냄새와 위치를 천천히 찾아 알림", size: "대형 · 약 55~67cm, 25~40kg", lifespan: "약 10~12년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "낮은 편"], focus: ["속도보다 넓은 냄새 산책과 회복을 조합하세요.", "큰 귀와 피부 주름, 관절 상태를 정기적으로 살피세요."], related: [["english-setter", "포인팅과 사람 협력을 공유하며 체형과 피모가 달라요."], ["german-short-haired-pointing-dog", "사냥감 위치를 알리고 회수하는 생활 조건을 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/BRACCO-ITALIANO-165.html", akcUrl: "https://www.fci.be/en/nomenclature/BRACCO-ITALIANO-165.html" },
  { slug: "small-munsterlander", nameKo: "스몰 문스터랜더", nameEn: "Small Munsterlander", group: "pointing", tags: ["독일 소형 포인팅견", "육지·물 회수", "긴 피모"], colors: ["#7f6250", "#e2d8cb", "#352e2a"], origin: "독일", lineage: "독일 문스터랜더 포인팅견 계통", role: "사냥감 위치를 알리고 다양한 지형에서 회수", size: "중형 · 약 50~56cm, 18~27kg", lifespan: "약 12~14년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["회수와 냄새 탐색을 대체 과제로 꾸준히 제공하세요.", "긴 피모와 귀를 물·숲 활동 뒤 완전히 말리세요."], related: [["english-cocker-spaniel", "작은 조렵견의 회수와 사람 협력을 비교해 보세요."], ["german-short-haired-pointing-dog", "포인팅과 회수의 활동량·피모 차이를 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/SMALL-MUNSTERLANDER-102.html", akcUrl: "https://www.fci.be/en/nomenclature/SMALL-MUNSTERLANDER-102.html" },
  { slug: "wire-haired-pointing-griffon-korthals", nameKo: "와이어헤어드 포인팅 그리폰 코르탈스", nameEn: "Wire-Haired Pointing Griffon Korthals", group: "pointing", tags: ["거친 털 포인팅견", "습지 회수", "탐색 협력"], colors: ["#85725f", "#ddd6ca", "#332e2a"], origin: "프랑스·네덜란드", lineage: "코르탈스가 정립한 거친 털 포인팅 계통", role: "육지와 물에서 사냥감의 위치를 알리고 회수", size: "중형 · 약 50~60cm, 20~27kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["물과 풀밭에서 냄새·회수 과제를 제공하되 야생 추적은 통제하세요.", "거친 털과 발가락 사이에 붙은 씨앗을 확인하세요."], related: [["german-wire-haired-pointing-dog", "거친 털과 육지·물 사냥 협력을 공유해요."], ["lagotto-romagnolo", "물 활동과 후각 탐색, 피모 관리의 차이를 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/WIREHAIRED-POINTING-GRIFFON-KORTHALS-107.html", akcUrl: "https://www.akc.org/dog-breeds/wirehaired-pointing-griffon/" },
  { slug: "english-pointer", nameKo: "잉글리시 포인터", nameEn: "English Pointer", group: "pointing", tags: ["영국 포인팅견", "빠른 탐색", "운동과 회복"], colors: ["#b58b6b", "#e6ddd1", "#3a312c"], origin: "영국", lineage: "유럽 포인팅견을 바탕으로 한 영국 사냥견", role: "넓은 들판에서 사냥감의 위치를 빠르게 알림", size: "중형·대형 · 약 61~69cm, 20~30kg", lifespan: "약 12~17년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "중간", "중간", "낮은 편"], focus: ["질주할 수 있는 안전한 공간과 충분한 회복을 함께 확보하세요.", "시각·냄새 추적을 대체하는 짧은 탐색 과제를 주세요."], related: [["english-setter", "영국 포인팅견의 들판 탐색과 사람 협력을 비교해 보세요."], ["greyhound", "긴 다리와 질주를 공유하지만 역할과 회복 방식이 달라요."]], fciUrl: "https://www.fci.be/en/nomenclature/ENGLISH-POINTER-1.html", akcUrl: "https://www.akc.org/dog-breeds/pointer/" },
  { slug: "curly-coated-retriever", nameKo: "컬리 코티드 리트리버", nameEn: "Curly-Coated Retriever", group: "retriever-spaniel", tags: ["영국 수상 리트리버", "곱슬 피모", "회수 협력"], colors: ["#4f4038", "#d4c5b5", "#2b2826"], origin: "영국", lineage: "푸들과 워터 스패니얼 계통을 포함한 리트리버", role: "물새를 물에서 회수하는 사냥 협력", size: "대형 · 약 58~69cm, 27~43kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "중간"], focus: ["물과 회수 과제를 제공하되 젖은 피모를 완전히 말리세요.", "곱슬 피모의 피부와 귀를 규칙적으로 확인하세요."], related: [["labrador-retriever", "물새 회수와 사람 협력을 공유하며 피모 관리가 달라요."], ["flat-coated-retriever", "활기찬 회수와 긴 몸의 체형 차이를 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/CURLY-COATED-RETRIEVER-110.html", akcUrl: "https://www.akc.org/dog-breeds/curly-coated-retriever/" },
  { slug: "clumber-spaniel", nameKo: "클럼버 스패니얼", nameEn: "Clumber Spaniel", group: "retriever-spaniel", tags: ["영국 중량 스패니얼", "느린 탐색", "긴 귀·피모"], colors: ["#e4d7c4", "#f2ece0", "#3d3028"], origin: "영국", lineage: "영국 귀족 사냥터의 무거운 스패니얼", role: "숲과 덤불에서 사냥감을 찾아내고 회수", size: "중형·대형 · 약 43~51cm, 25~39kg", lifespan: "약 10~12년 (AKC 참고, 개체별 차이 있음)", levels: ["중간", "중간", "중간", "높은 편", "중간", "높은 편"], focus: ["짧고 느린 냄새 산책과 체중 관리로 관절 부담을 줄이세요.", "귀·눈·긴 피모를 산책 뒤 꼼꼼히 확인하세요."], related: [["english-cocker-spaniel", "덤불 속 조렵과 회수 협력, 체격 차이를 비교해 보세요."], ["basset-hound", "낮은 무게중심과 느린 냄새 탐색의 생활 부담을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/CLUMBER-SPANIEL-109.html", akcUrl: "https://www.akc.org/dog-breeds/clumber-spaniel/" },
  { slug: "american-cocker-spaniel", nameKo: "아메리칸 코커 스패니얼", nameEn: "American Cocker Spaniel", group: "retriever-spaniel", tags: ["미국 소형 조렵견", "사람과의 교감", "긴 귀·피모"], colors: ["#b37d57", "#e7d8c8", "#3b302a"], origin: "미국", lineage: "영국 코커에서 미국에서 발전한 스패니얼", role: "작은 사냥감을 찾아내고 회수하는 조렵", size: "소형·중형 · 약 34~39cm, 9~14kg", lifespan: "약 10~14년 (AKC 참고, 개체별 차이 있음)", levels: ["중간", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["귀를 젖은 채 두지 말고 물·풀밭 활동 뒤 말리세요.", "사람과의 교감을 짧은 회수·찾기 과제로 연결하세요."], related: [["english-cocker-spaniel", "코커 계통의 조렵과 피모 관리를 공유하며 체격이 달라요."], ["cavalier-king-charles-spaniel", "긴 귀와 사람 곁 생활의 공통점, 역할 차이를 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/AMERICAN-COCKER-SPANIEL-167.html", akcUrl: "https://www.akc.org/dog-breeds/cocker-spaniel/" },
  { slug: "barbet", nameKo: "바베", nameEn: "Barbet", group: "retriever-spaniel", tags: ["프랑스 워터도그", "곱슬 피모", "물새 회수"], colors: ["#6c5b4e", "#d5c8b8", "#312c28"], origin: "프랑스", lineage: "유럽의 오래된 곱슬 털 워터도그", role: "습지에서 물새를 찾고 회수하는 수상 작업", size: "중형 · 약 53~65cm, 17~28kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["물 활동과 냄새 찾기를 안전하게 제공하고 완전히 말리세요.", "곱슬 피모가 엉키지 않도록 피부까지 나누어 빗질하세요."], related: [["poodle", "유럽 워터도그 계통과 곱슬 피모 관리의 차이를 살펴보세요."], ["portuguese-water-dog", "물새 회수와 사람 협력의 생활 조건을 비교해 보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/BARBET-105.html", akcUrl: "https://www.akc.org/dog-breeds/barbet/" },
  { slug: "irish-water-spaniel", nameKo: "아이리시 워터 스패니얼", nameEn: "Irish Water Spaniel", group: "retriever-spaniel", tags: ["아일랜드 수상견", "곱슬 방수 피모", "물새 회수"], colors: ["#5b483e", "#cdbbaa", "#2b2826"], origin: "아일랜드", lineage: "아일랜드의 오래된 워터 스패니얼", role: "습지와 강에서 물새를 회수", size: "대형 · 약 51~59cm, 20~30kg", lifespan: "약 12~13년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["물 활동 뒤 귀·피부와 곱슬 피모를 완전히 말리세요.", "회수 욕구를 안전한 장난감과 냄새 과제로 전환하세요."], related: [["curly-coated-retriever", "곱슬 피모와 수상 회수의 공통점, 체형 차이를 비교해 보세요."], ["poodle", "워터도그 계통의 학습과 피모 관리 방식을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/IRISH-WATER-SPANIEL-124.html", akcUrl: "https://www.akc.org/dog-breeds/irish-water-spaniel/" },
  { slug: "spanish-water-dog", nameKo: "스페니시 워터 도그", nameEn: "Spanish Water Dog", group: "retriever-spaniel", tags: ["스페인 워터도그", "곱슬 피모", "목양과 회수"], colors: ["#8d6f56", "#dfd5c7", "#332d28"], origin: "스페인", lineage: "이베리아 반도의 오래된 목양·수상견", role: "가축을 몰고 물새와 어망을 회수하는 다목적 작업", size: "중형 · 약 40~50cm, 14~22kg", lifespan: "약 12~14년 (FCI 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"], focus: ["목양과 회수의 끈기를 냄새·찾기 과제로 안전하게 전환하세요.", "곱슬 털을 빗질 방식과 미용 계획에 맞춰 관리하세요."], related: [["portuguese-water-dog", "이베리아 수상견의 협력과 곱슬 피모를 비교해 보세요."], ["lagotto-romagnolo", "수상 작업에서 다른 탐색 역할로 이어진 배경을 살펴보세요."]], fciUrl: "https://www.fci.be/en/nomenclature/SPANISH-WATER-DOG-336.html", akcUrl: "https://www.akc.org/dog-breeds/spanish-water-dog/" },
  { slug: "american-water-spaniel", nameKo: "아메리칸 워터 스패니얼", nameEn: "American Water Spaniel", group: "retriever-spaniel", tags: ["미국 중서부 수상견", "물새 회수", "곱슬·웨이브 피모"], colors: ["#6d5344", "#d8c9b9", "#302a27"], origin: "미국 위스콘신", lineage: "미국 중서부의 작은 워터 스패니얼", role: "강과 습지에서 물새와 작은 사냥감을 회수", size: "중형 · 약 38~46cm, 11~20kg", lifespan: "약 10~14년 (AKC 참고, 개체별 차이 있음)", levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "중간"], focus: ["물과 회수 욕구를 안전한 수영·찾기 과제로 연결하세요.", "귀와 웨이브 피모를 물 활동 뒤 충분히 말리세요."], related: [["english-cocker-spaniel", "작은 조렵견의 회수와 사람 협력을 비교해 보세요."], ["labrador-retriever", "물새 회수의 공통점과 체격·운동량 차이를 살펴보세요."]], fciUrl: "https://www.akc.org/dog-breeds/american-water-spaniel/", akcUrl: "https://www.akc.org/dog-breeds/american-water-spaniel/" },
];

const roleHome = (seed: Seed) => {
  if (seed.group === "terrier") return "작은 동물을 찾고 몰아내던 끈기는 가정에서 빠른 추적과 끈질긴 놀이로 나타날 수 있습니다. 멈춤과 회복을 함께 가르쳐야 해요.";
  if (seed.group === "herding") return "무리와 사람의 움직임을 읽고 협력하던 배경은 가정에서 높은 학습 욕구와 주변을 살피는 행동으로 이어질 수 있습니다.";
  if (seed.group === "scent-hound") return "냄새를 따라 넓은 지형을 이동하던 배경은 가정에서 긴 탐색과 호출·울타리 관리의 책임으로 이어질 수 있습니다.";
  if (seed.group === "pointing") return "사냥감의 위치를 알리고 사람과 협력하던 배경은 가정에서 탐색·회수 과제와 충분한 활동으로 연결될 수 있습니다.";
  if (seed.group === "retriever-spaniel") return "물과 덤불에서 사냥감을 찾아 회수하던 배경은 가정에서 냄새·운반·물놀이 욕구로 나타날 수 있습니다.";
  return "북부와 산악 환경에서 스스로 판단하던 배경은 가정에서 독립적인 관찰과 영역 경계로 나타날 수 있어요.";
};

const makeBreed = (seed: Seed): Breed => ({
  slug: seed.slug, contentStatus: "mvp-editorial-draft", nameKo: seed.nameKo, nameEn: seed.nameEn,
  tagline: `${seed.nameKo}의 매력은 ${seed.role}의 역사와 오늘의 생활 조건을 함께 살필 때 더 선명해져요.`,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`, catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: { src: `/illustrations/v3/${seed.slug}-history.webp`, alt: `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: {
    originalRole: `${withTopicParticle(seed.nameKo)} ${seed.role}이라는 역할과 환경 속에서 형성된 견종입니다. 과거 역할은 현재 개체의 행동을 결정하지 않지만 살펴볼 단서가 될 수 있어요.`,
    today: `현재 가정에서는 ${seed.role}의 흔적이 움직임·탐색·경계 방식으로 다르게 나타날 수 있습니다. 사회성과 반응은 개체마다 달라요.`,
    guardianContext: `보호자는 ${seed.nameKo}의 체격과 활동, 자극 반응에 맞는 거리와 회복 시간을 준비해야 합니다. 품종만으로 성격을 단정하지 마세요.`,
  },
  story: {
    opening: `${withTopicParticle(seed.nameKo)} ${seed.origin}에서 ${seed.role}이라는 역사적 배경을 지닌 견종입니다. ${seed.lineage}라는 배경을 알면 외형만으로는 보이지 않는 생활 조건을 생각할 수 있어요.`,
    roleToHome: roleHome(seed),
    reality: `귀엽거나 강인해 보이는 인상만으로는 충분하지 않습니다. ${seed.nameKo}와 살려면 ${seed.size}에 맞는 공간과 일상, 교육·관리 비용을 미리 확인해야 해요.`,
  },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "신체 구조와 컨디션에 맞춘 규칙적인 산책이 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.focus,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: [
    { time: "아침", title: "몸과 냄새 깨우기", description: "견종의 체력과 기온에 맞춰 걷고 냄새를 살펴요." },
    { time: "낮", title: "차분한 회복", description: "자극에서 벗어나 조용히 쉬는 시간을 보장해요." },
    { time: "저녁", title: "협력 과제", description: "짧은 학습과 핸들링 뒤 편하게 마무리해요." },
  ],
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
  ],
});

export const detailBatchKSlugs = seeds.map((seed) => seed.slug);
export const detailBatchK = seeds.map(makeBreed) satisfies Breed[];
