import type { Breed } from "./schema";

const checkedAt = "2026-08-05";
const historyAltOverrides: Partial<Record<string, string>> = {
  "dutch-shepherd-dog": "네덜란드 농경지의 밭 경계를 따라 양 떼를 작물에서 떨어뜨리는 브린들 더치 셰퍼드 독을 그린 편집 수채화",
  mastiff: "영국 영지의 대문 가까이에서 낯선 접근을 감시하는 검은 마스크의 거대한 마스티프를 그린 편집 수채화",
  "soft-coated-wheaten-terrier": "아일랜드 농가에서 해충을 찾고 가축 이동과 집 주변 알림을 돕는 밀빛 위튼 테리어를 그린 편집 수채화",
  otterhound: "영국의 강과 하천에서 물속 냄새를 따라가는 거친 방수 털과 물갈퀴 발의 오터하운드를 그린 편집 수채화",
  leonberger: "독일 레온베르크의 물가 마을에서 사람 곁에 서서 수레를 끄는 레온베르거를 그린 편집 수채화",
  briard: "프랑스의 넓은 저지대 목초지에서 목자와 함께 양 떼의 이동을 살피는 황갈색 브리아드를 그린 편집 수채화",
  "collie-rough": "스코틀랜드 언덕 목초지에서 목동의 신호에 맞춰 양 떼 바깥을 움직이는 세이블 러프 콜리를 그린 편집 수채화",
  puli: "헝가리 목초지에서 목동의 신호에 맞춰 양 떼 앞을 가로지르는 검은 성견 풀리를 그린 편집 수채화",
};
type Level = Breed["tendencies"][keyof Breed["tendencies"]]["label"];
type DayStep = Breed["daySnapshot"][number];

type BatchISeed = {
  slug: string; nameKo: string; nameEn: string; tagline: string;
  group: Breed["catalog"]["group"]; tags: [string, string, string]; colors: [string, string, string];
  origin: string; lineage: string; role: string; size: string; lifespan: string;
  originalRole: string; today: string; guardianContext: string;
  opening: string; roleToHome: string; reality: string;
  care: [string, string, string]; levels: [Level, Level, Level, Level, Level, Level];
  days: [DayStep, DayStep, DayStep]; related: [[string, string], [string, string]];
  fciUrl: string; akcUrl: string; historyUrl?: string; healthUrl?: string;
};

const seeds: BatchISeed[] = [
  {
    slug: "dutch-shepherd-dog", nameKo: "더치 셰퍼드 독", nameEn: "Dutch Shepherd Dog",
    tagline: "브린들 피모의 탄탄한 몸에는 네덜란드 농경지 경계를 순찰하며 양 떼와 농장 일을 두루 맡던 지구력이 있어요.",
    group: "herding", tags: ["네덜란드 목양견", "다목적 농장 작업", "세 가지 피모 변종"], colors: ["#776652", "#daddd0", "#302d29"],
    origin: "네덜란드", lineage: "네덜란드 농촌의 다목적 목양견", role: "양 떼를 작물에서 떨어뜨리고 가축 이동·농장 경계", size: "중대형 · 약 55~62cm, 19~34kg", lifespan: "약 11~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "네덜란드 농촌에서 길과 밭의 경계를 오가며 양 떼가 작물을 침범하지 않게 하고, 젖소를 모으거나 수레를 돕고 농장을 알렸습니다.",
    today: "움직임의 경계를 빠르게 읽고 사람과 긴 과제에 몰입하거나 주변 변화를 예민하게 알릴 수 있지만 강도는 개체마다 달라요.",
    guardianContext: "반복 달리기만 늘리지 말고 방향·멈춤·탐색을 섞으며, 사람이나 동물을 몰려는 행동과 낯선 대상 경계를 안전한 거리에서 관리하세요.",
    opening: "더치 셰퍼드 독은 네덜란드 농촌의 여러 일을 맡아 온 균형 잡힌 목양견입니다. 단모·장모·거친 털 변종이 있으며 브린들 무늬가 대표적입니다.",
    roleToHome: "밭 경계를 순찰하고 다양한 작업을 전환하던 배경은 높은 지구력과 빠른 학습, 움직임 변화에 대한 민감성으로 이어질 수 있습니다.",
    reality: "중형 체격만으로 생활 부담이 작다고 판단하기 어렵습니다. 충분한 활동과 학습, 경계 뒤 쉬는 연습을 꾸준히 제공해야 해요.",
    care: ["긴 산책에 방향 전환과 냄새·신호 과제를 함께 넣으세요.", "움직이는 대상 몰이는 거리와 대체 행동으로 예방하세요.", "피모 변종에 맞춰 빗질과 피부·발 상태를 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "경계 따라 걷기", description: "충분히 걷고 방향·정지 신호를 맞춰요." }, { time: "낮", title: "완전한 휴식", description: "자극에서 떨어져 길게 쉬게 해요." }, { time: "저녁", title: "협력 과제", description: "냄새 찾기와 짧은 학습을 섞어요." }],
    related: [["german-shepherd-dog", "다목적 목양·작업 배경을 공유하지만 체형과 피모 변종이 달라요."], ["australian-kelpie", "민첩한 목양견 사이에서 브린들 피모와 농장 작업 리듬을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/DUTCH-SHEPHERD-DOG-223.html", akcUrl: "https://www.akc.org/dog-breeds/dutch-shepherd/",
  },
  {
    slug: "briard", nameKo: "브리아드", nameEn: "Briard",
    tagline: "길고 물결진 털 아래에는 프랑스 평원에서 큰 양 떼를 몰고 지키던 넓은 보폭과 독립적인 판단이 있어요.",
    group: "herding", tags: ["프랑스 대형 목양견", "가축 이동과 보호", "긴 물결 피모"], colors: ["#9a7753", "#deddd1", "#352f2a"],
    origin: "프랑스", lineage: "오래된 프랑스 대형 목양견", role: "넓은 지역에서 양 떼를 몰고 이동 중 보호", size: "대형 · 약 56~69cm, 25~45kg", lifespan: "약 12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "프랑스의 넓은 농경지에서 큰 양 떼의 방향을 조절하고 이동 중인 무리와 농장을 살피는 목양·보호 역할을 함께 맡았습니다.",
    today: "가족의 움직임을 따라다니며 주변을 살피거나 긴 과제에 집중할 수 있지만 목양·경계와 사회성은 개체마다 달라요.",
    guardianContext: "큰 몸을 다룰 보상 기반 교육과 낯선 대상과의 거리를 준비하고, 눈을 덮는 장모와 이중 며느리발톱을 규칙적으로 확인하세요.",
    opening: "브리아드는 프랑스에서 오랫동안 가축을 몰고 지킨 크고 민첩한 목양견입니다. 길고 물결진 검정·회색·황갈색 피모와 뒷다리 이중 며느리발톱이 특징입니다.",
    roleToHome: "넓은 범위의 무리를 스스로 판단하며 보호자와 협력하던 배경은 높은 활동과 관계 집중, 주변 변화에 대한 경계로 이어질 수 있습니다.",
    reality: "풍성한 털과 다정한 인상 뒤에는 대형 작업견의 힘과 손질 부담이 있습니다. 운동·교육·사회화와 긴 피모 관리 시간을 함께 계산해야 해요.",
    care: ["긴 산책과 방향·기다리기 신호를 매일 구성하세요.", "낯선 사람과 동물의 인사는 강요하지 말고 거리를 주세요.", "장모를 피부까지 빗고 눈 주변과 며느리발톱을 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "넓은 움직임", description: "긴 산책과 방향 신호를 함께해요." }, { time: "낮", title: "차분한 관찰", description: "자극과 거리를 두고 쉬게 해요." }, { time: "저녁", title: "협력과 빗질", description: "짧은 과제 뒤 피모를 나누어 봐요." }],
    related: [["beauceron", "프랑스 목양·보호 배경을 공유하지만 피모와 움직임의 인상이 크게 달라요."], ["old-english-sheepdog", "큰 장모 목양견 사이에서 피모 구조와 원래 작업 지역을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BRIARD-113.html", akcUrl: "https://www.akc.org/dog-breeds/briard/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/briard-breed-history-thomas-jefferson/",
  },
  {
    slug: "collie-rough", nameKo: "러프 콜리", nameEn: "Collie Rough",
    tagline: "길게 흐르는 세이블 피모에는 스코틀랜드의 열린 목초지에서 양의 움직임을 읽고 사람과 협력한 가벼운 몸이 있어요.",
    group: "herding", tags: ["스코틀랜드 목양견", "가볍고 긴 체형", "풍성한 이중모"], colors: ["#b27a4e", "#e0dfd3", "#37302b"],
    origin: "영국·스코틀랜드", lineage: "스코틀랜드 목양 콜리의 장모형", role: "목초지에서 양 떼를 모으고 이동", size: "대형 · 약 56~66cm, 23~34kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "스코틀랜드의 언덕과 목초지에서 사람의 신호를 읽으며 양 떼를 모으고 이동시키는 가볍고 지구력 있는 목양견으로 발달했습니다.",
    today: "사람의 움직임과 목소리에 민감하게 반응하고 가족 활동에 참여하거나 알림 행동을 보일 수 있지만 강도는 개체마다 달라요.",
    guardianContext: "목양 행동과 발성은 차분한 대체 행동으로 전환하고, 풍성한 털은 귀 뒤와 팔꿈치까지 나누어 빗으며 더운 날 활동을 조절하세요.",
    opening: "러프 콜리는 스코틀랜드 목양견에서 정립된 길고 우아한 장모 콜리입니다. 좁고 매끈한 머리와 풍성한 갈기, 긴 꼬리가 대표적입니다.",
    roleToHome: "멀리 움직이는 양과 사람의 신호를 함께 읽던 배경은 협력 욕구와 움직임 민감성, 주변 변화를 알리는 행동으로 이어질 수 있습니다.",
    reality: "우아하고 부드러운 이미지가 손질과 활동 책임을 줄이지 않습니다. 매일의 산책·교육과 풍성한 이중모 관리가 필요해요.",
    care: ["움직이는 대상을 몰려는 행동은 거리와 대체 신호로 관리하세요.", "알림 뒤 보호자에게 돌아와 쉬는 행동을 보상하세요.", "귀 뒤와 겨드랑이·장식털을 피부까지 나누어 빗으세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "목초지형 산책", description: "넉넉히 걷고 방향 신호를 맞춰요." }, { time: "낮", title: "조용한 회복", description: "시원한 자리에서 길게 쉬게 해요." }, { time: "저녁", title: "알림과 빗질", description: "조용함을 연습하고 털을 살펴요." }],
    related: [["shetland-sheepdog", "비슷한 콜리형 외모 뒤의 체격과 생활 부담 차이를 비교해 보세요."], ["border-collie", "스코틀랜드 목양 배경을 공유하지만 응시·작업 집중과 피모 관리가 달라요."]],
    fciUrl: "https://fci.be/en/nomenclature/COLLIE-ROUGH-156.html", akcUrl: "https://www.akc.org/dog-breeds/collie/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/collie-history-queen-victoria-lassie-beyond/",
  },
  {
    slug: "puli", nameKo: "풀리", nameEn: "Puli",
    tagline: "자연스럽게 엉겨 줄을 이루는 피모 안에는 헝가리 목초지에서 양 사이를 빠르게 오가던 작고 강한 목양견이 있어요.",
    group: "herding", tags: ["헝가리 목양견", "민첩한 몰이", "코드형 피모"], colors: ["#4b4842", "#dcddd2", "#272725"],
    origin: "헝가리", lineage: "아시아계 기원과 연결되는 헝가리 목양견", role: "양 떼 가까이에서 빠르게 방향을 바꾸며 몰이", size: "중형 · 약 41~43cm, 11~16kg", lifespan: "약 10~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "헝가리 목동과 함께 양 떼 사이를 민첩하게 오가며 무리의 방향을 바꾸고 흩어진 개체를 모으는 역할을 했습니다.",
    today: "빠른 움직임을 따라가거나 사람과 과제에 적극적으로 참여하고 소리로 변화를 알릴 수 있지만 강도는 개체마다 달라요.",
    guardianContext: "몰이와 발성은 대체 행동으로 전환하고, 코드형 피모는 피부까지 분리해 습기·이물질을 확인하며 목욕 뒤 완전히 건조하세요.",
    opening: "풀리는 헝가리의 작지만 강한 목양견입니다. 성장하며 자연스럽게 코드 형태를 이루는 풍성한 피모와 민첩한 움직임이 독특합니다.",
    roleToHome: "양 사이를 빠르게 판단하며 움직이던 배경은 높은 활동과 문제 해결, 움직임과 소리에 대한 민감성으로 이어질 수 있습니다.",
    reality: "독특한 피모는 장식이 아니라 큰 관리 책임입니다. 활동과 교육뿐 아니라 코드를 나누고 씻고 완전히 말릴 시간과 공간이 필요해요.",
    care: ["방향 전환과 냄새 찾기로 목양 에너지를 안전하게 사용하세요.", "알림 뒤 조용히 쉬는 행동을 보상하세요.", "코드를 피부까지 분리하고 젖은 피모를 완전히 말리세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "민첩한 탐색", description: "걷기와 방향 과제를 함께해요." }, { time: "낮", title: "완전한 휴식", description: "흥분을 낮추고 편히 쉬게 해요." }, { time: "저녁", title: "코드 확인", description: "피부와 습기, 이물질을 살펴요." }],
    related: [["border-collie", "높은 목양 집중을 공유하지만 체격과 피모·몰이 방식이 달라요."], ["old-english-sheepdog", "풍성한 피모의 목양견 사이에서 코드 구조와 관리 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/PULI-55.html", akcUrl: "https://www.akc.org/dog-breeds/puli/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/puli-history/",
  },
  {
    slug: "schnauzer", nameKo: "스탠더드 슈나우저", nameEn: "Schnauzer",
    tagline: "수염과 눈썹이 선명한 중형 체형에는 독일 농장에서 해충을 찾고 수레와 마구간을 살피던 다목적성이 있어요.",
    group: "guardian-working", tags: ["독일 중형 농장견", "해충 수색과 경계", "거친 피모"], colors: ["#77756d", "#dedfd4", "#2f302e"],
    origin: "독일", lineage: "세 슈나우저 크기의 원형이 된 중형 핀셔형 작업견", role: "농장 해충 수색·수레 동행·마구간 경계", size: "중형 · 약 44~50cm, 14~23kg", lifespan: "약 13~16년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "독일 농장과 시장길에서 마구간의 해충을 찾고 수레를 따라가며 재산과 주변 변화를 알리는 다목적 작업견으로 발달했습니다.",
    today: "냄새를 끈기 있게 조사하고 빠른 작은 동물을 추적하거나 낯선 움직임을 알릴 수 있지만 반응은 개체마다 달라요.",
    guardianContext: "작은 동물 추적과 발성은 리드·거리와 대체 행동으로 관리하고, 거친 이중모와 수염은 주기적으로 빗고 트리밍하세요.",
    opening: "스탠더드 슈나우저는 미니어처와 자이언트보다 먼저 정립된 독일의 중형 농장 작업견입니다. 사각 체형과 거친 털, 수염과 눈썹이 특징입니다.",
    roleToHome: "해충 수색과 경계를 번갈아 수행하던 배경은 높은 탐색 욕구와 빠른 학습, 주변 변화에 대한 알림으로 이어질 수 있습니다.",
    reality: "중형이라는 이유로 과제와 손질이 적게 필요한 것은 아닙니다. 꾸준한 활동·교육과 정기적인 피모 관리가 필요해요.",
    care: ["냄새 찾기와 놓기·돌아오기 신호를 함께 연습하세요.", "작은 동물 추적은 리드와 안전한 울타리로 관리하세요.", "거친 이중모와 수염을 빗고 트리밍 계획을 세우세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "농장견식 탐색", description: "냄새와 움직임 과제를 섞어 걸어요." }, { time: "낮", title: "차분한 대기", description: "소리에서 떨어져 편히 쉬게 해요." }, { time: "저녁", title: "수염과 피모", description: "짧은 학습 뒤 털을 살펴요." }],
    related: [["miniature-schnauzer", "같은 외형 특징 뒤의 체격과 원래 작업 규모 차이를 비교해 보세요."], ["giant-schnauzer", "슈나우저 계열 안에서 힘과 경비 책임, 피모 관리의 차이를 살펴보세요."]],
    fciUrl: "https://fci.be/en/nomenclature/SCHNAUZER-182.html", akcUrl: "https://www.akc.org/dog-breeds/standard-schnauzer/",
    historyUrl: "https://www.akc.org/expert-advice/lifestyle/fun-facts-standard-schnauzer/",
  },
  {
    slug: "shar-pei", nameKo: "샤페이", nameEn: "Shar Pei",
    tagline: "작은 귀와 거친 ‘모래 피부’ 피모에는 중국 남부 농촌에서 집과 농장을 살피던 단단한 중형견의 역사가 있어요.",
    group: "guardian-working", tags: ["중국 농장·경비견", "거친 단모와 주름", "신중한 사회화"], colors: ["#b7835e", "#dfddd1", "#392f29"],
    origin: "중국 · FCI 후원", lineage: "중국 남부의 오래된 중형 몰로서형 개", role: "농장과 가정 주변의 경계·다목적 작업", size: "중형 · 약 46~51cm, 20~27kg", lifespan: "약 8~12년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "중국 남부 농촌에서 가정과 농장 주변을 살피고 다양한 생활 작업에 참여한 단단한 중형견으로 전해집니다. 해로운 오락의 역사로 품종 전체를 정의하지 않습니다.",
    today: "익숙한 가족과 공간을 중요하게 여기고 낯선 사람이나 개를 신중히 살필 수 있지만 사회성과 경계는 개체마다 달라요.",
    guardianContext: "낯선 대상과의 인사를 강요하지 말고 보상 기반 사회화를 진행하며, 눈·귀와 피부 주름의 습기·마찰을 규칙적으로 확인하세요.",
    opening: "샤페이는 중국에서 발달한 작고 단단한 귀, 넓은 주둥이와 거친 단모가 특징인 중형견입니다. 성견의 주름은 머리와 어깨를 중심으로 과장되지 않아야 합니다.",
    roleToHome: "가정과 영역을 살피던 배경은 낯선 변화에 대한 신중함과 독립적인 판단으로 이어질 수 있습니다.",
    reality: "독특한 외형은 특별한 관리 책임을 동반합니다. 사회적 거리 조절과 눈·귀·피부 상태를 세심하게 살필 시간과 의료 계획이 필요해요.",
    care: ["낯선 사람과 개의 인사는 강요하지 말고 거리를 주세요.", "눈과 귀, 주름 사이의 붉어짐·습기·냄새를 확인하세요.", "더운 날에는 호흡과 피부 상태에 맞춰 활동을 줄이세요."],
    levels: ["중간", "중간", "높은 편", "중간", "높은 편", "중간"],
    days: [{ time: "아침", title: "조용한 산책", description: "붐비지 않는 길에서 냄새를 살펴요." }, { time: "낮", title: "독립 휴식", description: "방해받지 않는 자리를 마련해요." }, { time: "저녁", title: "피부 상태 확인", description: "눈·귀와 주름을 부드럽게 살펴요." }],
    related: [["chow-chow", "중국계 피모·혀 특징과 신중함을 공유하지만 체형과 털 관리가 달라요."], ["bullmastiff", "몰로서형 힘과 경계를 공유하되 체격·주름과 운동 부담이 크게 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/SHAR-PEI-309.html", akcUrl: "https://www.akc.org/dog-breeds/chinese-shar-pei/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/chinese-shar-pei-history/",
  },
  {
    slug: "mastiff", nameKo: "마스티프", nameEn: "Mastiff",
    tagline: "압도적으로 큰 몸과 검은 마스크에는 영국의 집과 재산 곁에서 조용히 버티며 지킨 대형 경비견의 무게가 있어요.",
    group: "guardian-working", tags: ["영국 초대형 경비견", "묵직한 체형", "큰 생활·의료 부담"], colors: ["#b78b63", "#dedbd0", "#362e29"],
    origin: "영국", lineage: "오래된 영국 마스티프형 경비견", role: "집과 영지의 감시·보호", size: "초대형 · 약 70cm 이상, 54~104kg", lifespan: "약 6~10년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국에서 집과 영지, 재산 가까이에 머물며 낯선 접근을 감시하고 존재감으로 막는 대형 경비견으로 이어져 왔습니다.",
    today: "주변을 조용히 관찰하거나 큰 몸으로 공간을 막을 수 있지만 낯선 대상 반응과 활동성은 개체마다 달라요.",
    guardianContext: "성견의 체중을 다룰 보행·이동 교육과 넓은 장비를 준비하고, 더위·호흡과 식사 전후 활동, 관절과 발을 세심하게 관리하세요.",
    opening: "마스티프는 매우 크고 뼈가 굵은 영국의 몰로서형 경비견입니다. 황갈색·살구색·브린들 피모와 검은 마스크가 대표적입니다.",
    roleToHome: "공간 가까이에 머물며 조용히 감시하던 배경은 침착한 관찰과 낯선 변화에 대한 경계로 이어질 수 있습니다.",
    reality: "느긋해 보이는 생활도 작은 부담을 뜻하지 않습니다. 사료·장비·차량·주거 공간과 초대형견 의료 이동까지 현실적으로 준비해야 해요.",
    care: ["당기지 않고 걷기와 자리 이동 신호를 일찍 가르치세요.", "식사 전후 격한 운동을 피하고 복부 불편은 즉시 진료받으세요.", "미끄럼을 줄이고 발·관절·호흡과 회복 상태를 살피세요."],
    levels: ["중간", "중간", "중간", "높은 편", "높은 편", "낮은 편"],
    days: [{ time: "아침", title: "서늘한 보행", description: "차분하게 걷고 주변 냄새를 봐요." }, { time: "낮", title: "넓은 휴식", description: "큰 몸을 받치는 자리를 마련해요." }, { time: "저녁", title: "이동 신호", description: "자리와 차량 이동을 짧게 연습해요." }],
    related: [["bullmastiff", "영국 마스티프형 체격을 공유하지만 형성 시기와 크기·활동 리듬이 달라요."], ["great-dane", "초대형견의 생활 부담을 공유하며 골격과 원래 역할의 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/MASTIFF-264.html", akcUrl: "https://www.akc.org/dog-breeds/mastiff/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/mastiff-history/",
  },
  {
    slug: "leonberger", nameKo: "레온베르거", nameEn: "Leonberger",
    tagline: "사자빛 장모와 검은 마스크에는 19세기 독일 레온베르크에서 사람 곁의 큰 생활견으로 정립된 온화한 힘이 있어요.",
    group: "guardian-working", tags: ["독일 초대형 생활견", "풍성한 방수성 피모", "사람 곁의 협력"], colors: ["#b47e4f", "#dcded2", "#352e29"],
    origin: "독일·레온베르크", lineage: "19세기에 정립된 대형 산악·수상견 계통의 생활견", role: "가정과 농장 곁의 동행·경계와 다양한 작업", size: "초대형 · 약 65~80cm, 41~77kg", lifespan: "약 7년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 독일 레온베르크에서 크고 인상적인 생활·동행견으로 정립되었고, 농장과 수레·수상 작업 등 사람 곁의 여러 역할에도 활용됐습니다.",
    today: "사람 가까이 머물며 물과 야외 활동에 참여하거나 큰 몸으로 주변을 살필 수 있지만 활동과 사회성은 개체마다 달라요.",
    guardianContext: "성견 크기에 맞는 교육·차량·의료 이동을 준비하고, 두꺼운 장모는 물놀이 뒤 완전히 말리며 더운 날 활동을 줄이세요.",
    opening: "레온베르거는 독일 레온베르크에서 19세기에 정립된 거대한 장모견입니다. 황금빛·적갈색 피모와 검은 마스크, 풍성한 갈기가 대표적입니다.",
    roleToHome: "가정과 작업 현장에서 사람 가까이 지내 온 배경은 높은 교감과 협력 욕구로 이어질 수 있습니다.",
    reality: "온화한 인상과 별개로 주거 공간, 털, 침, 더위와 초대형견 의료·이동 부담이 큽니다. 비교적 짧은 수명도 고려해야 해요.",
    care: ["큰 힘을 다룰 보행·기다리기·차량 이동을 일찍 연습하세요.", "물놀이 뒤 귀와 이중모를 피부까지 완전히 말리세요.", "더운 날 활동을 줄이고 발·관절과 회복 상태를 살피세요."],
    levels: ["중간", "중간", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "서늘한 긴 산책", description: "큰 보폭에 맞춰 천천히 걸어요." }, { time: "낮", title: "시원한 회복", description: "넓고 서늘한 자리에서 쉬게 해요." }, { time: "저녁", title: "협력과 빗질", description: "이동 신호 뒤 피모를 살펴요." }],
    related: [["newfoundland", "거대한 장모와 물 작업을 공유하지만 기원과 체형·피모색이 달라요."], ["saint-bernard", "초대형 생활견의 공간·의료 부담을 공유하며 피모와 역사적 역할을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/LEONBERGER-145.html", akcUrl: "https://www.akc.org/dog-breeds/leonberger/", historyUrl: "https://www.akc.org/expert-advice/dog-breeds/history-behind-the-leonberger/",
  },
  {
    slug: "west-highland-white-terrier", nameKo: "웨스트 하이랜드 화이트 테리어", nameEn: "West Highland White Terrier",
    tagline: "하얀 거친 털과 작은 몸에는 스코틀랜드 서부의 바위와 굴에서 설치류를 찾던 단단한 테리어의 끈기가 있어요.",
    group: "terrier", tags: ["스코틀랜드 소형 테리어", "굴과 해충 수색", "흰 거친 이중모"], colors: ["#d9d7cb", "#e4e2d8", "#373531"],
    origin: "영국·스코틀랜드", lineage: "스코틀랜드 저각 작업 테리어", role: "바위틈과 굴에서 설치류·작은 사냥감 수색", size: "소형 · 약 25~28cm, 7~9kg", lifespan: "약 13~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "스코틀랜드 서부의 거친 땅과 바위틈에서 작은 몸으로 굴을 조사하고 농장 주변의 설치류를 찾는 작업 테리어로 발달했습니다.",
    today: "작은 구멍과 냄새를 끈기 있게 조사하거나 빠른 동물을 추적할 수 있지만 추적과 사회성은 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 안전한 파기 놀이를 제공하며, 흰 거친 이중모와 피부·귀 상태를 규칙적으로 관리하세요.",
    opening: "웨스트 하이랜드 화이트 테리어는 스코틀랜드 서부에서 발달한 작고 단단한 흰 작업 테리어입니다. 선 귀와 당근 모양 꼬리, 거친 이중모가 특징입니다.",
    roleToHome: "굴과 바위틈을 포기하지 않고 살피던 배경은 높은 탐색 욕구와 파기, 빠른 움직임 추적으로 이어질 수 있습니다.",
    reality: "하얗고 작은 외모가 낮은 활동이나 쉬운 교육을 뜻하지 않습니다. 추적 안전과 테리어다운 독립성, 피모·피부 관리를 준비해야 해요.",
    care: ["냄새 찾기와 안전한 파기 대체 놀이를 제공하세요.", "작은 동물 추적은 리드와 빈틈없는 울타리로 관리하세요.", "거친 이중모와 피부·귀 상태를 규칙적으로 확인하세요."],
    levels: ["중간", "높은 편", "높은 편", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "냄새 중심 산책", description: "작은 몸의 속도에 맞춰 탐색해요." }, { time: "낮", title: "독립 휴식", description: "방해받지 않는 자리를 마련해요." }, { time: "저녁", title: "찾기와 피모", description: "짧은 과제 뒤 피부와 털을 봐요." }],
    related: [["scottish-terrier", "스코틀랜드 저각 테리어의 끈기를 공유하며 체형과 피모색이 달라요."], ["border-terrier", "작은 굴 작업 테리어 사이에서 다리 길이와 대표 피모색을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/WEST-HIGHLAND-WHITE-TERRIER-85.html", akcUrl: "https://www.akc.org/dog-breeds/west-highland-white-terrier/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/fun-facts-west-highland-white-terrier/",
  },
  {
    slug: "staffordshire-bull-terrier", nameKo: "스태퍼드셔 불 테리어", nameEn: "Staffordshire Bull Terrier",
    tagline: "낮고 근육질인 몸에는 영국 산업도시의 거친 과거를 지나 사람 곁의 생활견으로 이어진 복합적인 역사가 있어요.",
    group: "terrier", tags: ["영국 불 타입 테리어", "작고 강한 체형", "개체별 사회성 확인"], colors: ["#8c7060", "#deddd2", "#322d2a"],
    origin: "영국·스태퍼드셔", lineage: "불도그와 테리어 계통에서 정립된 소형 불 타입 테리어", role: "과거 해로운 오락에 이용된 뒤 가정 반려견으로 보존", size: "중소형 · 약 36~41cm, 11~17kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "19세기 영국에서 불도그와 테리어 계통이 결합되어 해로운 동물 오락에 이용된 역사가 있습니다. 이후 책임 있는 보존을 통해 사람 곁의 반려견으로 이어졌습니다.",
    today: "사람과 강하게 교감하고 몸을 사용하는 놀이를 즐길 수 있지만 다른 개와의 사회성·흥분 조절은 개체와 경험을 직접 확인해야 해요.",
    guardianContext: "품종명만으로 공격성을 단정하지 말고 실제 반응을 보며, 튼튼한 장비와 보상 기반 교육으로 흥분·교차 상황을 안전하게 관리하세요.",
    opening: "스태퍼드셔 불 테리어는 영국에서 정립된 작고 매우 근육질인 불 타입 테리어입니다. 넓은 머리와 짧은 단모, 낮지만 민첩한 몸이 특징입니다.",
    roleToHome: "과거의 선택 배경이 오늘의 개체 행동을 보장하지는 않습니다. 현재 생활에서는 실제 사회성, 놀이 강도와 회복 능력을 구체적으로 살펴야 합니다.",
    reality: "친근하거나 강인하다는 품종 이미지 어느 쪽도 개체를 대신하지 않습니다. 안전한 사회화와 힘 조절, 지역 법규·주거 조건을 함께 확인해야 해요.",
    care: ["다른 개와의 거리는 실제 반응을 보며 단계적으로 조절하세요.", "몸을 쓰는 놀이에는 놓기·멈춤·휴식을 함께 가르치세요.", "짧은 털의 피부와 발, 운동 뒤 호흡·회복을 확인하세요."],
    levels: ["높은 편", "중간", "중간", "높은 편", "중간", "낮은 편"],
    days: [{ time: "아침", title: "구조화된 산책", description: "거리 조절과 냄새 탐색을 함께해요." }, { time: "낮", title: "차분한 회복", description: "흥분 뒤 방해 없이 쉬게 해요." }, { time: "저녁", title: "놀이와 멈춤", description: "놓기·기다리기 뒤 휴식해요." }],
    related: [["bull-terrier", "불 타입 테리어의 역사적 맥락을 공유하지만 머리·체형과 생활 리듬이 달라요."], ["boston-terrier", "불도그·테리어 계통의 도시 반려견 사이에서 체격과 활동 차이를 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/STAFFORDSHIRE-BULL-TERRIER-76.html", akcUrl: "https://www.akc.org/dog-breeds/staffordshire-bull-terrier/",
  },
  {
    slug: "soft-coated-wheaten-terrier", nameKo: "소프트 코티드 휘튼 테리어", nameEn: "Irish Soft Coated Wheaten Terrier",
    tagline: "잘 익은 밀빛의 부드러운 털 아래에는 아일랜드 농장에서 가축과 집, 해충 일을 두루 맡던 단단한 테리어가 있어요.",
    group: "terrier", tags: ["아일랜드 농장 테리어", "다목적 작업", "부드러운 밀빛 피모"], colors: ["#c4a06f", "#dfded2", "#3a322b"],
    origin: "아일랜드", lineage: "아일랜드의 중형 장각 농장 테리어", role: "농장 해충 수색·가축 보조·집 주변 알림", size: "중형 · 약 43~48cm, 14~18kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "아일랜드 농가에서 설치류를 찾고 가축 이동을 돕고 집 주변의 변화를 알리는 다목적 농장 테리어로 생활했습니다.",
    today: "사람과 활기차게 놀고 냄새를 찾거나 빠른 작은 동물을 쫓으려 할 수 있지만 추적과 사회성은 개체마다 달라요.",
    guardianContext: "추적은 리드로 관리하고 흥분 뒤 쉬는 연습을 하며, 부드럽게 자라는 피모는 피부까지 자주 빗고 습기를 완전히 말리세요.",
    opening: "소프트 코티드 휘튼 테리어는 아일랜드의 튼튼한 중형 농장견입니다. 성견의 부드럽고 물결진 밀빛 피모가 다른 거친 털 테리어와 구별됩니다.",
    roleToHome: "여러 농장 일을 전환하던 배경은 높은 활동과 탐색, 사람과 함께 과제를 수행하려는 모습으로 이어질 수 있습니다.",
    reality: "털 빠짐이 적다는 말이 손질이 적다는 뜻은 아닙니다. 매일의 활동과 흥분 조절, 엉킴을 막는 잦은 빗질이 필요해요.",
    care: ["냄새 찾기와 가져오기·놓기 과제를 함께 제공하세요.", "빠른 작은 동물 추적은 리드와 울타리로 관리하세요.", "부드러운 피모를 피부까지 빗고 젖은 털을 말리세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "농장견식 탐색", description: "걷기와 냄새 찾기를 길게 해요." }, { time: "낮", title: "차분한 회복", description: "흥분을 낮추고 편히 쉬게 해요." }, { time: "저녁", title: "놀이와 빗질", description: "협력 놀이 뒤 피모를 살펴요." }],
    related: [["airedale-terrier", "다목적 농장 테리어의 체력과 협력을 공유하지만 체격·피모가 달라요."], ["border-terrier", "작업 테리어의 탐색을 공유하며 체격과 부드러운 장모 관리의 차이를 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/IRISH-SOFT-COATED-WHEATEN-TERRIER-40.html", akcUrl: "https://www.akc.org/dog-breeds/soft-coated-wheaten-terrier/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/soft-coated-wheaten-terrier-history-ireland/",
  },
  {
    slug: "karelian-bear-dog", nameKo: "카렐리안 베어 도그", nameEn: "Karelian Bear Dog",
    tagline: "검정과 흰색의 선명한 몸에는 핀란드 숲에서 큰 사냥감의 흔적을 찾아 소리와 거리로 위치를 알리던 담대함이 있어요.",
    group: "spitz-primitive", tags: ["핀란드 북유럽 사냥견", "큰 사냥감 추적", "강한 발성과 독립성"], colors: ["#363b39", "#dfe1d6", "#242625"],
    origin: "핀란드", lineage: "카렐리아 지역의 북유럽 스피츠형 사냥견", role: "숲에서 큰 사냥감을 추적하고 거리 두며 위치 알림", size: "중형 · 수컷 약 54~60cm·25~28kg, 암컷 약 49~55cm·17~20kg", lifespan: "약 11~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "핀란드와 카렐리아의 숲에서 큰 사냥감의 냄새를 찾아 독립적으로 이동하고, 안전한 거리를 유지하며 짖음으로 위치를 알렸습니다.",
    today: "냄새를 따라 멀리 움직이고 야생동물을 추적하거나 강한 목소리로 알릴 수 있지만 강도는 개체마다 달라요.",
    guardianContext: "오프리드 활동을 피하고 높은 울타리와 튼튼한 장비를 사용하며, 다른 동물·개와의 거리는 실제 반응에 맞춰 관리하세요.",
    opening: "카렐리안 베어 도그는 핀란드의 강건한 흑백 북유럽 사냥 스피츠입니다. 선 귀와 말린 꼬리, 중형의 탄탄한 몸이 특징입니다.",
    roleToHome: "넓은 숲에서 독립적으로 큰 사냥감을 찾던 배경은 높은 추적 욕구와 지구력, 풍부한 발성으로 이어질 수 있습니다.",
    reality: "중형 체격만으로 일반 주거에 쉽게 맞는다고 보기 어렵습니다. 추적 안전과 발성, 개체별 사회성을 다룰 경험과 환경이 필요해요.",
    care: ["숲에서도 튼튼한 리드와 빈틈없는 높은 울타리를 사용하세요.", "야생동물과 다른 개에 대한 반응을 개체별로 확인하세요.", "알림 뒤 돌아오기와 조용히 쉬는 행동을 보상하세요."],
    levels: ["높은 편", "높은 편", "높은 편", "중간", "높은 편", "중간"],
    days: [{ time: "아침", title: "긴 숲길 추적", description: "리드 안에서 냄새를 충분히 따라요." }, { time: "낮", title: "독립 회복", description: "시원하고 조용한 자리에서 쉬어요." }, { time: "저녁", title: "알림 전환", description: "소리 뒤 돌아와 쉬는 연습을 해요." }],
    related: [["norwegian-elkhound-grey", "큰 사냥감 추적과 발성을 공유하지만 체형·피모색과 작업 방식이 달라요."], ["finnish-spitz", "핀란드 사냥 스피츠의 발성을 공유하며 목표 사냥감과 체격을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/KARELIAN-BEAR-DOG-48.html", akcUrl: "https://www.akc.org/dog-breeds/karelian-bear-dog/",
  },
  {
    slug: "norwegian-lundehund", nameKo: "노르웨이안 룬데훈트", nameEn: "Norwegian Lundehund",
    tagline: "여섯 발가락과 유연한 관절에는 노르웨이 외딴 섬의 좁은 바위틈을 오르내리며 퍼핀 둥지를 찾던 특별한 적응이 있어요.",
    group: "spitz-primitive", tags: ["노르웨이 섬 사냥견", "여섯 기능성 발가락", "높은 관절 유연성"], colors: ["#b37349", "#dfe0d4", "#372e29"],
    origin: "노르웨이·베뢰위", lineage: "노르웨이 해안 섬의 소형 북유럽 사냥 스피츠", role: "절벽 바위틈의 퍼핀 둥지 접근", size: "소형 · 약 30~38cm, 9~14kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "노르웨이 베뢰위 섬의 가파른 절벽에서 여분의 기능성 발가락과 유연한 몸으로 좁은 바위틈에 접근해 퍼핀을 찾도록 길러졌습니다. 오늘날 퍼핀은 보호 대상입니다.",
    today: "좁은 공간을 탐색하고 높은 곳을 오르거나 스스로 문제를 풀려 할 수 있지만 활동과 사회성은 개체마다 달라요.",
    guardianContext: "특별한 관절 구조를 묘기처럼 강요하지 말고 추락·틈새를 막으며, 소화기와 체중 상태는 개별 수의 진료 계획으로 관리하세요.",
    opening: "노르웨이안 룬데훈트는 노르웨이 외딴 섬에서 발달한 작고 유연한 스피츠입니다. 각 발의 여섯 개 이상 기능성 발가락과 접히는 귀가 특징입니다.",
    roleToHome: "절벽의 좁은 틈을 스스로 판단해 이동하던 배경은 높은 문제 해결과 탐색, 독특한 움직임으로 이어질 수 있습니다.",
    reality: "희귀하고 독특한 외형은 쉬운 반려를 뜻하지 않습니다. 안전한 환경 설계와 개별 건강·영양 관리, 독립적인 탐색 욕구를 함께 고려해야 해요.",
    care: ["높은 가구와 좁은 틈의 추락·끼임 위험을 점검하세요.", "관절 가동 범위를 억지로 시험하거나 묘기를 강요하지 마세요.", "체중·식욕·변 상태의 변화는 수의사와 상의하세요."],
    levels: ["높은 편", "높은 편", "높은 편", "중간", "높은 편", "중간"],
    days: [{ time: "아침", title: "안전한 탐색", description: "낮은 장애물과 냄새 길을 살펴요." }, { time: "낮", title: "조용한 휴식", description: "틈과 낙상 위험 없는 자리에서 쉬어요." }, { time: "저녁", title: "상태 기록", description: "발과 식욕·변화를 확인해요." }],
    related: [["icelandic-sheepdog", "북대서양 스피츠 외형을 공유하지만 목양과 절벽 탐색이라는 역할이 달라요."], ["karelian-bear-dog", "북유럽 사냥 스피츠 사이에서 체격과 목표 환경의 극적인 차이를 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/NORWEGIAN-LUNDEHUND-265.html", akcUrl: "https://www.akc.org/dog-breeds/norwegian-lundehund/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/norwegian-lundehund-history-behind-the-breed/",
  },
  {
    slug: "xoloitzcuintle", nameKo: "숄로이츠퀸틀레", nameEn: "Xoloitzcuintle",
    tagline: "매끈한 피부와 선 귀에는 멕시코에서 수천 년 동안 사람 곁의 동행과 경계를 이어 온 오래된 생활견의 흔적이 있어요.",
    group: "spitz-primitive", tags: ["멕시코 원시견", "헤어리스·코티드", "세 가지 크기"], colors: ["#746861", "#dedbd1", "#302c2a"],
    origin: "멕시코", lineage: "고대 메소아메리카와 연결되는 원시견", role: "가정의 동행·알림과 문화적 생활", size: "소형~중형 · 약 25~58cm, 4.5~25kg", lifespan: "약 13~18년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "멕시코에서 오랜 세월 사람의 가정과 공동체 곁에 살며 동행하고 주변을 알리는 역할을 했고 문화적·의례적 의미도 기록되어 있습니다.",
    today: "익숙한 사람 가까이 머물며 낯선 변화를 신중히 알릴 수 있지만 독립성과 사회성은 크기·피모보다 개체 경험에 따라 달라요.",
    guardianContext: "헤어리스는 햇빛·추위와 피부 자극을, 코티드는 피모 상태를 관리하고 치아·발을 규칙적으로 확인하세요.",
    opening: "숄로이츠퀸틀레는 멕시코의 오래된 견종으로 소형·중형·표준 세 크기와 헤어리스·코티드 형태가 있습니다. 선 귀와 매끈한 몸선이 대표적입니다.",
    roleToHome: "사람 곁의 생활과 알림 역할은 가까운 교감과 낯선 변화에 대한 관찰로 이어질 수 있습니다.",
    reality: "털이 없다는 이유로 관리가 가볍지는 않습니다. 피부 보호와 체온 조절, 치아 관리 또는 코티드형의 피모 관리를 준비해야 해요.",
    care: ["헤어리스 피부를 강한 햇빛·추위와 마찰에서 보호하세요.", "낯선 대상과의 인사는 강요하지 말고 선택할 거리를 주세요.", "치아와 발, 피부 또는 코티드 피모 상태를 확인하세요."],
    levels: ["중간", "중간", "높은 편", "높은 편", "높은 편", "중간"],
    days: [{ time: "아침", title: "기온 맞춤 산책", description: "피부와 날씨에 맞춰 냄새를 살펴요." }, { time: "낮", title: "따뜻한 휴식", description: "부드럽고 안정된 자리에서 쉬게 해요." }, { time: "저녁", title: "피부와 치아", description: "자극과 건조함을 부드럽게 확인해요." }],
    related: [["chinese-crested-dog", "헤어리스 형태를 공유하지만 크기 체계와 지역 역사가 달라요."], ["basenji", "오래된 지역 생활견의 독립성을 공유하며 체형과 환경 적응을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/XOLOITZCUINTLE-234.html", akcUrl: "https://www.akc.org/dog-breeds/xoloitzcuintli/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/xoloitzcuintli-history/",
  },
  {
    slug: "otterhound", nameKo: "오터하운드", nameEn: "Otterhound",
    tagline: "거친 방수성 털과 물갈퀴 발에는 영국 강을 따라 오래된 냄새를 물속까지 추적하던 크고 느긋한 후각하운드가 있어요.",
    group: "scent-hound", tags: ["영국 수변 후각하운드", "물속 냄새 추적", "희귀한 대형견"], colors: ["#786c5c", "#daddd2", "#312e2a"],
    origin: "영국", lineage: "대형 거친 털 무리 후각하운드", role: "강과 하천에서 수달의 흔적을 무리로 추적", size: "대형 · 약 61~69cm, 36~52kg", lifespan: "약 10~13년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "영국의 강과 하천에서 무리로 이동하며 오래된 냄새를 육지와 물속에서 추적했습니다. 수달 사냥은 오늘날 영국에서 금지된 과거 활동입니다.",
    today: "냄새를 따라 멀리 이동하고 물에 들어가거나 큰 목소리로 알릴 수 있지만 추적·발성·물 선호는 개체마다 달라요.",
    guardianContext: "튼튼한 리드와 안전한 물 출구를 준비하고, 젖은 거친 이중모와 긴 귀를 완전히 말리며 큰 몸의 이동 공간을 확보하세요.",
    opening: "오터하운드는 영국의 크고 거친 털을 가진 수변 후각하운드입니다. 넓은 코, 긴 귀, 물갈퀴가 발달한 큰 발과 방수성 이중모가 특징입니다.",
    roleToHome: "물과 육지를 오가며 오래된 냄새를 끝까지 따라가던 배경은 강한 추적과 지구력, 풍부한 발성으로 이어질 수 있습니다.",
    reality: "희귀하고 느긋한 인상 뒤에 큰 공간과 냄새 추적·발성·젖은 피모 관리 부담이 있습니다. 오프리드 안전도 중요해요.",
    care: ["긴 냄새 산책에서도 튼튼한 하네스와 리드를 사용하세요.", "물놀이 전 안전한 출구를 확인하고 무리한 수영을 피하세요.", "젖은 이중모와 긴 귀를 피부까지 확인하고 말리세요."],
    levels: ["높은 편", "높은 편", "높은 편", "높은 편", "높은 편", "높은 편"],
    days: [{ time: "아침", title: "긴 냄새길", description: "리드 안에서 천천히 흔적을 따라요." }, { time: "낮", title: "넓은 회복", description: "큰 몸을 받치는 시원한 자리를 줘요." }, { time: "저녁", title: "귀와 피모", description: "습기와 이물질을 확인하고 말려요." }],
    related: [["bloodhound", "강한 장거리 후각을 공유하지만 수변 적응과 피모 구조가 달라요."], ["airedale-terrier", "영국 수변 작업의 연결점이 있지만 체격과 하운드·테리어 방식이 달라요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/OTTERHOUND-294.html", akcUrl: "https://www.akc.org/dog-breeds/otterhound/",
  },
  {
    slug: "brittany-spaniel", nameKo: "브리트니", nameEn: "Brittany Spaniel",
    tagline: "주황과 흰색의 가벼운 몸에는 프랑스 브르타뉴의 작은 들과 수풀에서 새를 찾고 멈춰 알리던 빠른 협력이 있어요.",
    group: "pointing", tags: ["프랑스 포인팅견", "빠른 들새 탐색", "작고 가벼운 체형"], colors: ["#c07a45", "#e1dfd3", "#382f29"],
    origin: "프랑스·브르타뉴", lineage: "프랑스 스패니얼형 대륙 포인팅견", role: "들·수풀에서 새를 탐색하고 포인팅·회수", size: "중형 · 약 44~52cm, 14~18kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "프랑스 브르타뉴의 비교적 작은 밭과 수풀에서 빠르게 새를 찾고 위치를 멈춰 알리며 필요하면 회수하는 다목적 조렵견으로 발달했습니다.",
    today: "넓게 달리며 냄새를 찾고 사람과 빠르게 과제를 전환하려 할 수 있지만 포인팅·추적 욕구는 개체마다 달라요.",
    guardianContext: "충분한 움직임과 냄새·회수 과제를 제공하면서 야생동물 추적은 리드로 관리하고, 흥분 뒤 쉬는 연습을 함께하세요.",
    opening: "브리트니는 프랑스 브르타뉴에서 발달한 작고 가벼운 포인팅견입니다. 세터보다 작고 스패니얼보다 다리가 긴 균형 잡힌 체형이 특징입니다.",
    roleToHome: "좁은 들과 수풀을 빠르게 탐색하며 사람과 협력하던 배경은 높은 활동과 냄새 집중, 빠른 학습으로 이어질 수 있습니다.",
    reality: "중형 체격과 밝은 표정이 낮은 운동량을 뜻하지 않습니다. 매일 충분한 야외 활동과 추적 안전, 차분한 회복이 필요해요.",
    care: ["긴 산책에 냄새 찾기와 포인팅·회수 과제를 섞으세요.", "야생동물 추적은 리드와 안전한 울타리로 예방하세요.", "귀와 장식털의 이물질·습기를 외출 뒤 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "중간"],
    days: [{ time: "아침", title: "빠른 들길 탐색", description: "걷기와 냄새·멈춤을 함께해요." }, { time: "낮", title: "완전한 회복", description: "활동 뒤 방해 없이 쉬게 해요." }, { time: "저녁", title: "찾기와 회수", description: "짧은 협력 과제로 집중해요." }],
    related: [["english-setter", "새 위치를 알리는 작업을 공유하지만 체격과 피모·탐색 범위가 달라요."], ["english-springer-spaniel", "들새 작업과 회수를 공유하며 포인팅과 플러싱의 차이를 살펴보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/BRITTANY-SPANIEL-95.html", akcUrl: "https://www.akc.org/dog-breeds/brittany/",
    historyUrl: "https://www.akc.org/expert-advice/lifestyle/fun-facts-brittany/",
  },
  {
    slug: "irish-red-setter", nameKo: "아이리시 레드 세터", nameEn: "Irish Red Setter",
    tagline: "윤기 나는 적갈색 장모 아래에는 아일랜드의 습한 들에서 넓게 새를 찾고 멈춰 알리던 빠르고 우아한 몸이 있어요.",
    group: "pointing", tags: ["아일랜드 세터", "넓은 들새 탐색", "적갈색 장식털"], colors: ["#a55233", "#deddd2", "#382b27"],
    origin: "아일랜드", lineage: "아일랜드의 붉은 세팅독", role: "들에서 새를 탐색하고 세팅 자세로 위치 표시", size: "대형 · 약 64~69cm, 27~32kg", lifespan: "약 12~15년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "아일랜드의 습한 들과 초지에서 넓게 냄새를 찾고 새를 발견하면 멈춰 위치를 알리는 빠른 세팅독으로 정립되었습니다.",
    today: "넓은 공간을 달리며 냄새를 찾고 사람과 활기차게 활동하려 할 수 있지만 집중과 교감 방식은 개체마다 달라요.",
    guardianContext: "긴 활동과 돌아오기 교육을 함께 제공하고 야생동물 추적은 리드로 관리하며, 귀와 가슴·다리 장식털을 규칙적으로 확인하세요.",
    opening: "아이리시 레드 세터는 아일랜드에서 정립된 크고 우아한 적갈색 포인팅견입니다. 긴 다리와 깊은 가슴, 풍성한 귀·꼬리 장식털이 특징입니다.",
    roleToHome: "넓은 들을 빠르게 탐색하며 사람의 위치를 확인하던 배경은 높은 활동량과 냄새 탐색, 협력 욕구로 이어질 수 있습니다.",
    reality: "화려한 장모와 밝은 이미지가 낮은 관리 난도를 뜻하지 않습니다. 긴 야외 활동과 추적 통제, 장식털 관리가 필요해요.",
    care: ["긴 산책에 냄새 찾기와 멈춤·돌아오기 신호를 섞으세요.", "야생동물 추적은 리드와 안전한 울타리로 예방하세요.", "귀와 가슴·다리·꼬리 장식털의 엉킴을 확인하세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "넓은 들길 산책", description: "길게 걷고 냄새와 멈춤을 맞춰요." }, { time: "낮", title: "차분한 회복", description: "활동 뒤 방해 없이 쉬게 해요." }, { time: "저녁", title: "장식털 관리", description: "찾기 놀이 뒤 귀와 털을 봐요." }],
    related: [["english-setter", "세팅 작업과 장모를 공유하지만 피모색과 지역·탐색 스타일이 달라요."], ["vizsla", "사람과 긴밀히 일하는 포인팅견의 활동성을 공유하며 피모 관리 차이가 커요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/IRISH-RED-SETTER-120.html", akcUrl: "https://www.akc.org/dog-breeds/irish-setter/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/meet-setter-breeds/",
  },
  {
    slug: "lagotto-romagnolo", nameKo: "라고토 로마뇰로", nameEn: "Lagotto Romagnolo",
    tagline: "곱슬 피모와 뛰어난 코에는 이탈리아 로마냐 습지의 회수견에서 들과 숲의 트러플 탐색견으로 바뀐 역사가 있어요.",
    group: "retriever-spaniel", tags: ["이탈리아 수상견", "트러플 탐색", "곱슬 방수성 피모"], colors: ["#9a765a", "#dfded3", "#352f2b"],
    origin: "이탈리아·로마냐", lineage: "로마냐 습지의 오래된 수상견", role: "물새 회수에서 트러플 냄새 탐색으로 전환", size: "중형 · 약 41~48cm, 11~16kg", lifespan: "약 15~17년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "로마냐 습지에서 물새를 회수하던 수상견으로 시작했고 습지가 줄어든 뒤 뛰어난 후각을 바탕으로 들과 숲의 트러플을 찾는 전문견으로 전환되었습니다.",
    today: "땅의 냄새를 집중해 찾고 파거나 사람과 탐색 과제를 수행하려 할 수 있지만 물·파기 선호는 개체마다 달라요.",
    guardianContext: "안전한 냄새 찾기와 파기 대체 공간을 제공하고, 자라는 곱슬 피모와 귀는 숲·물 활동 뒤 이물질과 습기를 확인하세요.",
    opening: "라고토 로마뇰로는 이탈리아 로마냐의 곱슬 털 수상견이자 오늘날 대표적인 트러플 탐색견입니다. 작고 튼튼한 사각 체형이 특징입니다.",
    roleToHome: "수상 회수에서 땅속 냄새 탐색으로 역할을 바꾼 배경은 높은 후각 집중과 사람과의 학습 욕구로 이어질 수 있습니다.",
    reality: "곰 인형 같은 외모와 낮은 털 빠짐이 관리가 쉽다는 뜻은 아닙니다. 탐색 과제와 피모·귀 관리, 정기 미용이 필요해요.",
    care: ["냄새 찾기와 안전한 파기 상자로 탐색 욕구를 채우세요.", "숲 활동 뒤 발과 곱슬 피모의 이물질을 확인하세요.", "귀와 피모를 완전히 말리고 정기 미용 계획을 세우세요."],
    levels: ["높은 편", "높은 편", "중간", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "냄새 보물찾기", description: "걸으며 땅의 냄새를 충분히 살펴요." }, { time: "낮", title: "조용한 회복", description: "탐색 뒤 편히 쉬게 해요." }, { time: "저녁", title: "피모와 귀", description: "이물질과 습기를 피부까지 확인해요." }],
    related: [["portuguese-water-dog", "곱슬 수상견의 협력을 공유하지만 체격과 현대 전문 역할이 달라요."], ["poodle", "수상 회수 계통과 높은 학습 욕구를 공유하며 체형·피모 관리 방식을 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/ROMAGNA-WATER-DOG-298.html", akcUrl: "https://www.akc.org/dog-breeds/lagotto-romagnolo/",
    historyUrl: "https://www.akc.org/expert-advice/lifestyle/5-facts-lagotto-romagnolo/",
  },
  {
    slug: "pekingese", nameKo: "페키니즈", nameEn: "Pekingese",
    tagline: "낮고 묵직한 작은 몸과 풍성한 갈기에는 중국 궁정 안에서 사람 가까이 생활한 오랜 반려견의 역사가 있어요.",
    group: "companion", tags: ["중국 궁정 반려견", "낮고 단단한 체형", "장모·호흡 관리"], colors: ["#c09669", "#e0ded3", "#382f29"],
    origin: "중국 · 영국 후원", lineage: "중국 궁정의 소형 장모 반려견", role: "궁정과 가정 내부의 동행·반려", size: "초소형 · 약 15~23cm, 최대 약 6.4kg", lifespan: "약 12~14년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "중국 궁정에서 사람 가까이 생활하며 동행과 위안을 제공한 소형 반려견으로 오랫동안 길러졌습니다.",
    today: "익숙한 사람 가까이 머물면서도 스스로 거리를 정하거나 낯선 소리를 알릴 수 있지만 사회성과 독립성은 개체마다 달라요.",
    guardianContext: "짧은 주둥이의 호흡과 더위를 우선 관리하고, 낮은 몸의 계단·점프를 줄이며 눈·얼굴 주름과 풍성한 피모를 규칙적으로 살피세요.",
    opening: "페키니즈는 중국 궁정에서 발달한 작고 낮은 장모 반려견입니다. 넓은 앞가슴과 갈기 같은 피모, 짧은 주둥이와 깃털 꼬리가 특징입니다.",
    roleToHome: "사람 가까이 지내면서 독립적인 품위를 유지한 반려 배경은 교감과 자기 거리 조절이 함께 나타나는 모습으로 이어질 수 있습니다.",
    reality: "작은 체격이 관리가 쉽다는 뜻은 아닙니다. 호흡·더위·눈과 피부, 장모와 낮은 허리의 생활 환경을 세심하게 준비해야 해요.",
    care: ["더운 시간 활동을 피하고 호흡과 회복 상태를 살피세요.", "계단과 높은 점프를 줄이고 미끄럽지 않은 동선을 만드세요.", "눈·얼굴 주름과 장모를 매일 부드럽게 확인하세요."],
    levels: ["낮은 편", "중간", "높은 편", "높은 편", "중간", "높은 편"],
    days: [{ time: "아침", title: "서늘한 짧은 산책", description: "호흡에 맞춰 천천히 냄새를 봐요." }, { time: "낮", title: "독립 휴식", description: "시원하고 낮은 자리에서 쉬게 해요." }, { time: "저녁", title: "얼굴과 털", description: "눈·주름과 장모를 살펴요." }],
    related: [["shih-tzu", "중국 궁정권 장모 반려견의 역사를 공유하지만 체형과 얼굴·피모 구조가 달라요."], ["lhasa-apso", "작고 독립적인 장모 반려견 사이에서 감시 배경과 낮은 체형을 비교해 보세요."]],
    fciUrl: "https://fci.be/en/nomenclature/PEKINGESE-207.html", akcUrl: "https://www.akc.org/dog-breeds/pekingese/", healthUrl: "https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/advanced-techniques/brachycephaly-expertise",
  },
  {
    slug: "irish-wolfhound", nameKo: "아이리시 울프하운드", nameEn: "Irish Wolfhound",
    tagline: "거친 털과 매우 긴 다리에는 아일랜드의 열린 땅에서 큰 사냥감을 시야로 추적하던 거대한 하운드의 역사가 있어요.",
    group: "sighthound", tags: ["아일랜드 거대 시각하운드", "큰 사냥감 추적", "매우 큰 생활 공간"], colors: ["#858078", "#dddcd2", "#302f2d"],
    origin: "아일랜드", lineage: "아일랜드의 오래된 거친 털 대형 하운드", role: "넓은 지형에서 늑대와 큰 사냥감 추적", size: "초대형 · 약 76~81cm 이상, 48~54kg 이상", lifespan: "약 6~8년 (AKC 참고, 개체별 차이 있음)",
    originalRole: "아일랜드의 열린 지형에서 시야로 늑대와 큰 사냥감을 찾아 빠르게 추적하도록 길러진 거대한 거친 털 시각하운드입니다.",
    today: "실내에서는 조용히 쉬다가도 먼 움직임을 보고 빠르게 추적할 수 있지만 추적과 다른 동물에 대한 반응은 개체마다 달라요.",
    guardianContext: "오프리드 추적을 피하고 높은 울타리 안에서 안전하게 움직이게 하며, 성장기·성견의 관절과 식사 전후 활동, 차량·의료 이동을 준비하세요.",
    opening: "아이리시 울프하운드는 가장 키가 큰 견종 가운데 하나인 아일랜드의 거친 털 시각하운드입니다. 길고 강한 다리와 깊은 가슴, 긴 머리가 특징입니다.",
    roleToHome: "넓은 땅에서 큰 사냥감을 시야로 추적하던 배경은 폭발적인 질주와 독립적인 판단으로 이어질 수 있습니다.",
    reality: "차분한 성격 이미지가 작은 생활 부담을 뜻하지 않습니다. 초대형 주거·차량·의료 비용과 비교적 짧은 수명을 현실적으로 고려해야 해요.",
    care: ["빠른 대상을 향한 추적은 리드와 높은 울타리로 관리하세요.", "식사 전후 격한 운동을 피하고 복부 불편은 즉시 진료받으세요.", "큰 몸을 받치는 휴식 공간과 차량·병원 이동을 준비하세요."],
    levels: ["중간", "중간", "높은 편", "높은 편", "낮은 편", "중간"],
    days: [{ time: "아침", title: "긴 보폭 산책", description: "안전한 리드로 천천히 넓게 걸어요." }, { time: "낮", title: "넓은 휴식", description: "긴 몸을 받치는 부드러운 자리를 줘요." }, { time: "저녁", title: "안전한 움직임", description: "짧게 움직인 뒤 충분히 회복해요." }],
    related: [["borzoi", "대형 시각하운드의 질주와 휴식을 공유하지만 피모·지역 역사가 달라요."], ["greyhound", "시야 추적과 긴 다리를 공유하며 체격 규모와 거친 피모 차이를 비교해 보세요."]],
    fciUrl: "https://www.fci.be/en/nomenclature/IRISH-WOLFHOUND-160.html", akcUrl: "https://www.akc.org/dog-breeds/irish-wolfhound/",
    historyUrl: "https://www.akc.org/expert-advice/dog-breeds/irish-wolfhound-history-behind-the-breed/",
  },
];

export const detailBatchISlugs = seeds.map((seed) => seed.slug);

export const detailBatchI = seeds.map((seed) => ({
  slug: seed.slug,
  contentStatus: "mvp-editorial-draft",
  nameKo: seed.nameKo,
  nameEn: seed.nameEn,
  tagline: seed.tagline,
  palette: { primary: seed.colors[0], secondary: seed.colors[1], ink: seed.colors[2] },
  illustration: `/illustrations/v2/${seed.slug}-card.webp`,
  catalog: { group: seed.group, discoveryTags: seed.tags },
  historyVisual: { src: `/illustrations/v3/${seed.slug}-history.webp`, alt: historyAltOverrides[seed.slug] ?? `${seed.nameKo}의 원래 역할과 생활 환경을 표현한 편집 수채화` },
  identity: { origin: seed.origin, lineage: seed.lineage, originalRole: seed.role, size: seed.size, lifespan: seed.lifespan },
  behaviorClues: { originalRole: seed.originalRole, today: seed.today, guardianContext: seed.guardianContext },
  story: { opening: seed.opening, roleToHome: seed.roleToHome, reality: seed.reality },
  tendencies: {
    activity: { label: seed.levels[0], note: seed.levels[0] === "높은 편" ? "매일 충분한 움직임과 회복 시간을 함께 구성해야 합니다." : "개체의 체력과 신체 구조에 맞춘 규칙적인 산책이 필요합니다." },
    mentalStimulation: { label: seed.levels[1], note: seed.levels[1] === "높은 편" ? "냄새 탐색과 학습 과제를 매일의 생활에 포함하는 편이 좋습니다." : "짧은 찾기와 신호 놀이로 일상에 변화를 줄 수 있습니다." },
    independence: { label: seed.levels[2], note: "사람과의 거리와 혼자 쉬는 능력은 개체와 경험에 따라 다르므로 실제 생활에서 확인하세요." },
    socialConnection: { label: seed.levels[3], note: "사람과의 관계 방식은 사회화와 생활 경험에 따라 달라질 수 있습니다." },
    alerting: { label: seed.levels[4], note: "소리와 낯선 변화에 대한 반응은 환경과 개체에 따라 달라질 수 있습니다." },
    grooming: { label: seed.levels[5], note: seed.levels[5] === "높은 편" ? "피부까지 확인하는 규칙적인 빗질과 피모 관리 시간이 필요합니다." : "정기적인 피부·발·귀 상태 확인이 필요합니다." },
  },
  careNotes: seed.care,
  healthEditorialNote: "건강 항목은 공식 견종 자료를 바탕으로 정리한 편집 초안이며 수의학 검수 전입니다. 품종만으로 질환을 단정하지 않고 개별 진료를 대신하지 않습니다.",
  daySnapshot: seed.days,
  related: seed.related.map(([slug, reason]) => ({ slug, reason })),
  sources: [
    { title: `${seed.nameEn} breed standard`, organization: "Fédération Cynologique Internationale", url: seed.fciUrl, checkedAt },
    { title: `${seed.nameEn} Dog Breed Information`, organization: "American Kennel Club", url: seed.akcUrl, checkedAt },
    ...(seed.historyUrl ? [{ title: `${seed.nameEn} breed history`, organization: "American Kennel Club", url: seed.historyUrl, checkedAt: "2026-08-29" }] : []),
    ...(seed.healthUrl ? [{ title: `${seed.nameEn} brachycephaly evidence`, organization: "Royal Veterinary College", url: seed.healthUrl, checkedAt: "2026-08-29" }] : []),
  ],
})) satisfies Breed[];
