import type { FciGroupNumber, MasterBreed } from "./master-schema";

export type VerificationFlag = "ko-name-review" | "fci-varieties";

export type MasterInventorySeed = readonly [
  slug: string,
  nameKo: string,
  nameEn: string,
  groupNo: FciGroupNumber | null,
  registryStatus: Exclude<MasterBreed["registryStatus"], "verification-needed">,
  detailPriority: MasterBreed["detailPriority"],
  verificationFlags?: readonly VerificationFlag[],
];

export const masterInventorySeeds = [
  ["australian-kelpie", "오스트레일리안 켈피", "Australian Kelpie", 1, "definitive", "later"],
  ["belgian-shepherd-dog", "벨지안 셰퍼드 독", "Belgian Shepherd Dog", 1, "definitive", "later", ["fci-varieties"]],
  ["czechoslovakian-wolfdog", "체코슬로바키안 울프독", "Czechoslovakian Wolfdog", 1, "definitive", "later", ["ko-name-review"]],
  ["beauceron", "보스롱", "Beauce Sheepdog", 1, "definitive", "later", ["ko-name-review"]],
  ["briard", "브리아드", "Briard", 1, "definitive", "later"],
  ["german-shepherd-dog", "저먼 셰퍼드 독", "German Shepherd Dog", 1, "definitive", "next"],
  ["bearded-collie", "비어디드 콜리", "Bearded Collie", 1, "definitive", "later"],
  ["border-collie", "보더콜리", "Border Collie", 1, "definitive", "core"],
  ["collie-rough", "러프 콜리", "Collie Rough", 1, "definitive", "later"],
  ["old-english-sheepdog", "올드 잉글리시 시프독", "Old English Sheepdog", 1, "definitive", "later"],
  ["shetland-sheepdog", "셔틀랜드 시프독", "Shetland Sheepdog", 1, "definitive", "later"],
  ["puli", "풀리", "Puli", 1, "definitive", "later"],
  ["white-swiss-shepherd-dog", "화이트 스위스 셰퍼드 독", "White Swiss Shepherd Dog", 1, "definitive", "later"],
  ["dutch-shepherd-dog", "더치 셰퍼드 독", "Dutch Shepherd Dog", 1, "definitive", "later"],
  ["australian-shepherd", "오스트레일리안 셰퍼드", "Australian Shepherd", 1, "definitive", "later"],
  ["australian-cattle-dog", "오스트레일리안 캐틀 독", "Australian Cattle Dog", 1, "definitive", "later"],
  ["bouvier-des-flandres", "부비에 데 플랑드르", "Bouvier des Flandres", 1, "definitive", "later", ["ko-name-review"]],
  ["welsh-corgi-cardigan", "웰시 코기 카디건", "Welsh Corgi (Cardigan)", 1, "definitive", "later"],
  ["welsh-corgi-pembroke", "웰시 코기 펨브로크", "Welsh Corgi (Pembroke)", 1, "definitive", "later"],
  ["miniature-american-shepherd", "미니어처 아메리칸 셰퍼드", "Miniature American Shepherd", 1, "provisional", "later"],
  ["dobermann", "도베르만", "Dobermann", 2, "definitive", "later"],
  ["miniature-pinscher", "미니어처 핀셔", "Miniature Pinscher", 2, "definitive", "later"],
  ["giant-schnauzer", "자이언트 슈나우저", "Giant Schnauzer", 2, "definitive", "later"],
  ["schnauzer", "스탠더드 슈나우저", "Schnauzer", 2, "definitive", "later"],
  ["miniature-schnauzer", "미니어처 슈나우저", "Miniature Schnauzer", 2, "definitive", "later"],
  ["shar-pei", "샤페이", "Shar Pei", 2, "definitive", "later"],
  ["dogo-argentino", "도고 아르헨티노", "Dogo Argentino", 2, "definitive", "later"],
  ["dogue-de-bordeaux", "도그 드 보르도", "Dogue de Bordeaux", 2, "definitive", "later", ["ko-name-review"]],
  ["boxer", "복서", "Boxer", 2, "definitive", "later"],
  ["great-dane", "그레이트 덴", "Great Dane", 2, "definitive", "later"],
  ["rottweiler", "롯트와일러", "Rottweiler", 2, "definitive", "later"],
  ["bulldog", "불독", "Bulldog", 2, "definitive", "later"],
  ["bullmastiff", "불마스티프", "Bullmastiff", 2, "definitive", "later"],
  ["mastiff", "마스티프", "Mastiff", 2, "definitive", "later"],
  ["cane-corso", "카네 코르소", "Italian Cane Corso", 2, "definitive", "later"],
  ["neapolitan-mastiff", "네아폴리탄 마스티프", "Neapolitan Mastiff", 2, "definitive", "later"],
  ["newfoundland", "뉴펀랜드", "Newfoundland", 2, "definitive", "later"],
  ["leonberger", "레온베르거", "Leonberger", 2, "definitive", "later"],
  ["pyrenean-mountain-dog", "그레이트 피레니즈", "Pyrenean Mountain Dog", 2, "definitive", "next"],
  ["saint-bernard", "세인트 버나드", "St. Bernard", 2, "definitive", "later"],
  ["tibetan-mastiff", "티베탄 마스티프", "Tibetan Mastiff", 2, "definitive", "later"],
  ["bernese-mountain-dog", "버니즈 마운틴 독", "Bernese Mountain Dog", 2, "definitive", "later"],
  ["continental-bulldog", "컨티넨탈 불독", "Continental Bulldog", 2, "provisional", "later", ["ko-name-review"]],
  ["airedale-terrier", "에어데일 테리어", "Airedale Terrier", 3, "definitive", "later"],
  ["border-terrier", "보더 테리어", "Border Terrier", 3, "definitive", "later"],
  ["smooth-fox-terrier", "스무드 폭스 테리어", "Fox Terrier (Smooth)", 3, "definitive", "later"],
  ["wire-fox-terrier", "와이어 폭스 테리어", "Fox Terrier (Wire)", 3, "definitive", "later"],
  ["soft-coated-wheaten-terrier", "소프트 코티드 휘튼 테리어", "Irish Soft Coated Wheaten Terrier", 3, "definitive", "later"],
  ["kerry-blue-terrier", "케리 블루 테리어", "Kerry Blue Terrier", 3, "definitive", "later"],
  ["cairn-terrier", "케언 테리어", "Cairn Terrier", 3, "definitive", "later"],
  ["jack-russell-terrier", "잭 러셀 테리어", "Jack Russell Terrier", 3, "definitive", "later"],
  ["norfolk-terrier", "노퍽 테리어", "Norfolk Terrier", 3, "definitive", "later"],
  ["norwich-terrier", "노리치 테리어", "Norwich Terrier", 3, "definitive", "later"],
  ["scottish-terrier", "스코티시 테리어", "Scottish Terrier", 3, "definitive", "later"],
  ["west-highland-white-terrier", "웨스트 하이랜드 화이트 테리어", "West Highland White Terrier", 3, "definitive", "later"],
  ["bull-terrier", "불테리어", "Bull Terrier", 3, "definitive", "later"],
  ["miniature-bull-terrier", "미니어처 불테리어", "Miniature Bull Terrier", 3, "definitive", "later"],
  ["staffordshire-bull-terrier", "스태퍼드셔 불 테리어", "Staffordshire Bull Terrier", 3, "definitive", "later"],
  ["american-staffordshire-terrier", "아메리칸 스태포드셔 테리어", "American Staffordshire Terrier", 3, "definitive", "later"],
  ["australian-silky-terrier", "오스트레일리안 실키 테리어", "Australian Silky Terrier", 3, "definitive", "later"],
  ["yorkshire-terrier", "요크셔 테리어", "Yorkshire Terrier", 3, "definitive", "later"],
  ["dachshund", "닥스훈트", "Dachshund", 4, "definitive", "next", ["fci-varieties"]],
  ["samoyed", "사모예드", "Samoyed", 5, "definitive", "core"],
  ["alaskan-malamute", "알래스칸 말라뮤트", "Alaskan Malamute", 5, "definitive", "later"],
  ["siberian-husky", "시베리안 허스키", "Siberian Husky", 5, "definitive", "next"],
  ["finnish-spitz", "핀니시 스피츠", "Finnish Spitz", 5, "definitive", "later"],
  ["karelian-bear-dog", "카렐리안 베어 도그", "Karelian Bear Dog", 5, "definitive", "later"],
  ["norwegian-elkhound-grey", "노르웨이지안 엘크하운드 그레이", "Norwegian Elkhound Grey", 5, "definitive", "later", ["ko-name-review"]],
  ["norwegian-lundehund", "노르웨이안 룬데훈트", "Norwegian Lundehund", 5, "definitive", "later", ["ko-name-review"]],
  ["finnish-lapponian-dog", "핀니시 라포니안 독", "Finnish Lapponian Dog", 5, "definitive", "later", ["ko-name-review"]],
  ["icelandic-sheepdog", "아이슬란딕 시프도그", "Icelandic Sheepdog", 5, "definitive", "later"],
  ["swedish-vallhund", "스웨디시 발훈트", "Swedish Vallhund", 5, "definitive", "later", ["ko-name-review"]],
  ["german-spitz", "저먼 스피츠", "German Spitz", 5, "definitive", "later", ["fci-varieties"]],
  ["italian-volpino", "볼피노 이탈리아노", "Italian Volpino", 5, "definitive", "later", ["ko-name-review"]],
  ["chow-chow", "차우차우", "Chow Chow", 5, "definitive", "later"],
  ["eurasier", "유라시어", "Eurasian", 5, "definitive", "later", ["ko-name-review"]],
  ["akita", "아키타", "Akita", 5, "definitive", "later"],
  ["american-akita", "아메리칸 아키타", "American Akita", 5, "definitive", "later"],
  ["hokkaido", "홋카이도견", "Hokkaido", 5, "definitive", "later"],
  ["japanese-spitz", "재패니즈 스피츠", "Japanese Spitz", 5, "definitive", "core"],
  ["kai", "카이견", "Kai", 5, "definitive", "later"],
  ["kishu", "키슈견", "Kishu", 5, "definitive", "later"],
  ["shiba", "시바견", "Shiba", 5, "definitive", "later"],
  ["shikoku", "시코쿠견", "Shikoku", 5, "definitive", "later"],
  ["korea-jindo-dog", "진돗개", "Korea Jindo Dog", 5, "definitive", "next"],
  ["basenji", "바센지", "Basenji", 5, "definitive", "next"],
  ["canaan-dog", "카나안 독", "Canaan Dog", 5, "definitive", "later"],
  ["xoloitzcuintle", "숄로이츠퀸틀레", "Xoloitzcuintle", 5, "definitive", "later", ["ko-name-review"]],
  ["yakutian-laika", "야쿠티안 라이카", "Yakutian Laika", 5, "provisional", "later", ["ko-name-review"]],
  ["bloodhound", "블러드하운드", "Bloodhound", 6, "definitive", "later"],
  ["basset-hound", "바셋 하운드", "Basset Hound", 6, "definitive", "later"],
  ["beagle", "비글", "Beagle", 6, "definitive", "next"],
  ["harrier", "해리어", "Harrier", 6, "definitive", "later"],
  ["english-foxhound", "잉글리시 폭스하운드", "English Foxhound", 6, "definitive", "later"],
  ["otterhound", "오터하운드", "Otterhound", 6, "definitive", "later"],
  ["petit-basset-griffon-vendeen", "페티 바셋 그리폰 방데앙", "Petit Basset Griffon Vendeen", 6, "definitive", "later", ["ko-name-review"]],
  ["finnish-hound", "핀니시 하운드", "Finnish Hound", 6, "definitive", "later"],
  ["alpine-dachsbracke", "알파인 닥스브라케", "Alpine Dachsbracke", 6, "definitive", "later", ["ko-name-review"]],
  ["bavarian-mountain-scent-hound", "바바리안 마운틴 센트 하운드", "Bavarian Mountain Scent Hound", 6, "definitive", "later"],
  ["dalmatian", "달마시안", "Dalmatian", 6, "definitive", "later"],
  ["rhodesian-ridgeback", "로디지안 리지백", "Rhodesian Ridgeback", 6, "definitive", "later"],
  ["german-short-haired-pointing-dog", "저먼 쇼트헤어드 포인터", "German Short-Haired Pointing Dog", 7, "definitive", "later"],
  ["german-wire-haired-pointing-dog", "저먼 와이어헤어드 포인터", "German Wire-Haired Pointing Dog", 7, "definitive", "later"],
  ["weimaraner", "와이머라너", "Weimaraner", 7, "definitive", "later"],
  ["vizsla", "비즐라", "Hungarian Short-Haired Pointer (Vizsla)", 7, "definitive", "later"],
  ["italian-pointing-dog", "브라코 이탈리아노", "Italian Pointing Dog", 7, "definitive", "later", ["ko-name-review"]],
  ["brittany-spaniel", "브리트니", "Brittany Spaniel", 7, "definitive", "later"],
  ["small-munsterlander", "스몰 문스터랜더", "Kleiner Münsterländer", 7, "definitive", "later", ["ko-name-review"]],
  ["wire-haired-pointing-griffon-korthals", "와이어헤어드 포인팅 그리폰 코르탈스", "Wire-Haired Pointing Griffon Korthals", 7, "definitive", "later", ["ko-name-review"]],
  ["english-pointer", "잉글리시 포인터", "English Pointer", 7, "definitive", "later"],
  ["english-setter", "잉글리시 세터", "English Setter", 7, "definitive", "later"],
  ["irish-red-setter", "아이리시 레드 세터", "Irish Red Setter", 7, "definitive", "later"],
  ["nova-scotia-duck-tolling-retriever", "노바 스코샤 덕 톨링 리트리버", "Nova Scotia Duck Tolling Retriever", 8, "definitive", "later"],
  ["curly-coated-retriever", "컬리 코티드 리트리버", "Curly Coated Retriever", 8, "definitive", "later"],
  ["flat-coated-retriever", "플랫 코티드 리트리버", "Flat Coated Retriever", 8, "definitive", "later"],
  ["golden-retriever", "골든 리트리버", "Golden Retriever", 8, "definitive", "next"],
  ["labrador-retriever", "래브라도 리트리버", "Labrador Retriever", 8, "definitive", "next"],
  ["chesapeake-bay-retriever", "체서피크 베이 리트리버", "Chesapeake Bay Retriever", 8, "definitive", "later"],
  ["clumber-spaniel", "클럼버 스패니얼", "Clumber Spaniel", 8, "definitive", "later"],
  ["english-cocker-spaniel", "잉글리시 코커 스패니얼", "English Cocker Spaniel", 8, "definitive", "next"],
  ["english-springer-spaniel", "잉글리시 스프링거 스패니얼", "English Springer Spaniel", 8, "definitive", "later"],
  ["american-cocker-spaniel", "아메리칸 코커 스패니얼", "American Cocker Spaniel", 8, "definitive", "later"],
  ["barbet", "바베", "French Water Dog", 8, "definitive", "later", ["ko-name-review"]],
  ["irish-water-spaniel", "아이리시 워터 스패니얼", "Irish Water Spaniel", 8, "definitive", "later"],
  ["lagotto-romagnolo", "라고토 로마뇰로", "Romagna Water Dog", 8, "definitive", "later"],
  ["portuguese-water-dog", "포르투갈 워터 도그", "Portuguese Water Dog", 8, "definitive", "later"],
  ["spanish-water-dog", "스페니시 워터 도그", "Spanish Water Dog", 8, "definitive", "later"],
  ["american-water-spaniel", "아메리칸 워터 스패니얼", "American Water Spaniel", 8, "definitive", "later"],
  ["bichon-frise", "비숑 프리제", "Bichon Frise", 9, "definitive", "later"],
  ["maltese", "몰티즈", "Maltese", 9, "definitive", "core"],
  ["havanese", "하바니즈", "Havanese", 9, "definitive", "later"],
  ["bolognese", "볼로네즈", "Bolognese", 9, "definitive", "later"],
  ["coton-de-tulear", "코톤 드 툴레아르", "Coton de Tulear", 9, "definitive", "later"],
  ["poodle", "푸들", "Poodle", 9, "definitive", "next", ["fci-varieties"]],
  ["chinese-crested-dog", "차이니즈 크레스티드 도그", "Chinese Crested Dog", 9, "definitive", "later"],
  ["lhasa-apso", "라사압소", "Lhasa Apso", 9, "definitive", "later"],
  ["shih-tzu", "시추", "Shih Tzu", 9, "definitive", "next"],
  ["tibetan-spaniel", "티베탄 스패니얼", "Tibetan Spaniel", 9, "definitive", "later"],
  ["tibetan-terrier", "티베탄 테리어", "Tibetan Terrier", 9, "definitive", "later"],
  ["chihuahua", "치와와", "Chihuahua", 9, "definitive", "next"],
  ["cavalier-king-charles-spaniel", "캐벌리어 킹 찰스 스패니얼", "Cavalier King Charles Spaniel", 9, "definitive", "later"],
  ["pekingese", "페키니즈", "Pekingese", 9, "definitive", "later"],
  ["japanese-chin", "재패니즈 친", "Japanese Chin", 9, "definitive", "later"],
  ["continental-toy-spaniel", "파피용", "Continental Toy Spaniel", 9, "definitive", "later", ["fci-varieties"]],
  ["pug", "퍼그", "Pug", 9, "definitive", "later"],
  ["french-bulldog", "프렌치 불도그", "French Bulldog", 9, "definitive", "next"],
  ["boston-terrier", "보스턴 테리어", "Boston Terrier", 9, "definitive", "later"],
  ["prague-ratter", "프라하 라터", "Prague Ratter", 9, "provisional", "later", ["ko-name-review"]],
  ["afghan-hound", "아프간 하운드", "Afghan Hound", 10, "definitive", "later"],
  ["saluki", "살루키", "Saluki", 10, "definitive", "later"],
  ["borzoi", "보르조이", "Borzoi - Russian Hunting Sighthound", 10, "definitive", "later"],
  ["irish-wolfhound", "아이리시 울프하운드", "Irish Wolfhound", 10, "definitive", "later"],
  ["greyhound", "그레이하운드", "Greyhound", 10, "definitive", "core"],
  ["whippet", "휘펫", "Whippet", 10, "definitive", "next"],
  ["italian-sighthound", "이탈리안 그레이하운드", "Italian Sighthound", 10, "definitive", "later"],
  ["azawakh", "아자와크", "Azawakh", 10, "definitive", "later", ["ko-name-review"]],
  ["sloughi", "슬루기", "Sloughi", 10, "definitive", "later", ["ko-name-review"]],
  ["galgo-espanol", "스페니시 그레이하운드", "Spanish Greyhound", 10, "definitive", "later"],
  ["american-pit-bull-terrier", "아메리칸 핏불 테리어", "American Pit Bull Terrier", null, "non-fci", "later"],
  ["american-bully", "아메리칸 불리", "American Bully", null, "non-fci", "later"],
] satisfies readonly MasterInventorySeed[];
