import type { FciGroupNumber, MasterBreed } from "./master-schema";

export type VerificationFlag = "ko-name-review" | "fci-varieties";

export type MasterInventorySeed = readonly [
  slug: string,
  nameKo: string,
  nameEn: string,
  groupNo: FciGroupNumber | null,
  registryStatus: Exclude<MasterBreed["registryStatus"], "verification-needed">,
  detailPriority: MasterBreed["detailPriority"],
  verificationFlags?: readonly VerificationFlag[],
];

export const masterInventorySeeds = [
  ["australian-kelpie", "오스트레일리안 켈피", "Australian Kelpie", 1, "definitive", "later"],
  ["belgian-shepherd-dog", "벨지안 셰퍼드 독", "Belgian Shepherd Dog", 1, "definitive", "later", ["fci-varieties"]],
  ["czechoslovakian-wolfdog", "체코슬로바키안 울프독", "Czechoslovakian Wolfdog", 1, "definitive", "later", ["ko-name-review"]],
  ["beauceron", "보스롱", "Beauce Sheepdog", 1, "definitive", "later", ["ko-name-review"]],
  ["briard", "브리아드", "Briard", 1, "definitive", "later"],
  ["german-shepherd-dog", "저먼 셰퍼드 독", "German Shepherd Dog", 1, "definitive", "next"],
  ["bearded-collie", "비어디드 콜리", "Bearded Collie", 1, "definitive", "later"],
  ["border-collie", "보더콜리", "Border Collie", 1, "definitive", "core"],
  ["collie-rough", "러프 콜리", "Collie Rough", 1, "definitive", "later"],
  ["old-english-sheepdog", "올드 잉글리시 시프독", "Old English Sheepdog", 1, "definitive", "later"],
  ["shetland-sheepdog", "셔틀랜드 시프독", "Shetland Sheepdog", 1, "definitive", "later"],
  ["puli", "풀리", "Puli", 1, "definitive", "later"],
  ["white-swiss-shepherd-dog", "화이트 스위스 셰퍼드 독", "White Swiss Shepherd Dog", 1, "definitive", "later"],
  ["dutch-shepherd-dog", "더치 셰퍼드 독", "Dutch Shepherd Dog", 1, "definitive", "later"],
  ["australian-shepherd", "오스트레일리안 셰퍼드", "Australian Shepherd", 1, "definitive", "later"],
  ["australian-cattle-dog", "오스트레일리안 캐틀 독", "Australian Cattle Dog", 1, "definitive", "later"],
  ["bouvier-des-flandres", "부비에 데 플랑드르", "Bouvier des Flandres", 1, "definitive", "later", ["ko-name-review"]],
  ["welsh-corgi-cardigan", "웰시 코기 카디건", "Welsh Corgi (Cardigan)", 1, "definitive", "later"],
  ["welsh-corgi-pembroke", "웰시 코기 펨브로크", "Welsh Corgi (Pembroke)", 1, "definitive", "later"],
  ["miniature-american-shepherd", "미니어처 아메리칸 셰퍼드", "Miniature American Shepherd", 1, "provisional", "later"],
  ["dobermann", "도베르만", "Dobermann", 2, "definitive", "later"],
  ["miniature-pinscher", "미니어처 핀셔", "Miniature Pinscher", 2, "definitive", "later"],
  ["giant-schnauzer", "자이언트 슈나우저", "Giant Schnauzer", 2, "definitive", "later"],
  ["schnauzer", "스탠더드 슈나우저", "Schnauzer", 2, "definitive", "later"],
  ["miniature-schnauzer", "미니어처 슈나우저", "Miniature Schnauzer", 2, "definitive", "later"],
  ["shar-pei", "샤페이", "Shar Pei", 2, "definitive", "later"],
  ["dogo-argentino", "도고 아르헨티노", "Dogo Argentino", 2, "definitive", "later"],
  ["dogue-de-bordeaux", "도그 드 보르도", "Dogue de Bordeaux", 2, "definitive", "later", ["ko-name-review"]],
  ["boxer", "복서", "Boxer", 2, "definitive", "later"],
  ["great-dane", "그레이트 덴", "Great Dane", 2, "definitive", "later"],
  ["rottweiler", "롯트와일러", "Rottweiler", 2, "definitive", "later"],
  ["bulldog", "불독", "Bulldog", 2, "definitive", "later"],
  ["bullmastiff", "불마스티프", "Bullmastiff", 2, "definitive", "later"],
  ["mastiff", "마스티프", "Mastiff", 2, "definitive", "later"],
  ["cane-corso", "카네 코르소", "Italian Cane Corso", 2, "definitive", "later"],
  ["neapolitan-mastiff", "네아폴리탄 마스티프", "Neapolitan Mastiff", 2, "definitive", "later"],
  ["newfoundland", "뉴펀랜드", "Newfoundland", 2, "definitive", "later"],
  ["leonberger", "레온베르거", "Leonberger", 2, "definitive", "later"],
  ["pyrenean-mountain-dog", "그레이트 피레니즈", "Pyrenean Mountain Dog", 2, "definitive", "next"],
  ["saint-bernard", "세인트 버나드", "St. Bernard", 2, "definitive", "later"],
  ["tibetan-mastiff", "티베탄 마스티프", "Tibetan Mastiff", 2, "definitive", "later"],
  ["bernese-mountain-dog", "버니즈 마운틴 독", "Bernese Mountain Dog", 2, "definitive", "later"],
  ["continental-bulldog", "컨티넨탈 불독", "Continental Bulldog", 2, "provisional", "later", ["ko-name-review"]],
  ["airedale-terrier", "에어데일 테리어", "Airedale Terrier", 3, "definitive", "later"],
  ["border-terrier", "보더 테리어", "Border Terrier", 3, "definitive", "later"],
  ["smooth-fox-terrier", "스무드 폭스 테리어", "Fox Terrier (Smooth)", 3, "definitive", "later"],
  ["wire-fox-terrier", "와이어 폭스 테리어", "Fox Terrier (Wire)", 3, "definitive", "later"],
  ["soft-coated-wheaten-terrier", "소프트 코티드 휘튼 테리어", "Irish Soft Coated Wheaten Terrier", 3, "definitive", "later"],
  ["kerry-blue-terrier", "케리 블루 테리어", "Kerry Blue Terrier", 3, "definitive", "later"],
  ["cairn-terrier", "케언 테리어", "Cairn Terrier", 3, "definitive", "later"],
  ["jack-russell-terrier", "잭 러셀 테리어", "Jack Russell Terrier", 3, "definitive", "later"],
  ["norfolk-terrier", "노퍽 테리어", "Norfolk Terrier", 3, "definitive", "later"],
  ["norwich-terrier", "노리치 테리어", "Norwich Terrier", 3, "definitive", "later"],
  ["scottish-terrier", "스코티시 테리어", "Scottish Terrier", 3, "definitive", "later"],
  ["west-highland-white-terrier", "웨스트 하이랜드 화이트 테리어", "West Highland White Terrier", 3, "definitive", "later"],
  ["bull-terrier", "불테리어", "Bull Terrier", 3, "definitive", "later"],
  ["miniature-bull-terrier", "미니어처 불테리어", "Miniature Bull Terrier", 3, "definitive", "later"],
  ["staffordshire-bull-terrier", "스태퍼드셔 불 테리어", "Staffordshire Bull Terrier", 3, "definitive", "later"],
  ["american-staffordshire-terrier", "아메리칸 스태포드셔 테리어", "American Staffordshire Terrier", 3, "definitive", "later"],
  ["australian-silky-terrier", "오스트레일리안 실키 테리어", "Australian Silky Terrier", 3, "definitive", "later"],
  ["yorkshire-terrier", "요크셔 테리어", "Yorkshire Terrier", 3, "definitive", "later"],
  ["dachshund", "닥스훈트", "Dachshund", 4, "definitive", "next", ["fci-varieties"]],
  ["samoyed", "사모예드", "Samoyed", 5, "definitive", "core"],
  ["alaskan-malamute", "알래스칸 말라뮤트", "Alaskan Malamute", 5, "definitive", "later"],
  ["siberian-husky", "시베리안 허스키", "Siberian Husky", 5, "definitive", "next"],
  ["finnish-spitz", "핀니시 스피츠", "Finnish Spitz", 5, "definitive", "later"],
  ["karelian-bear-dog", "카렐리안 베어 도그", "Karelian Bear Dog", 5, "definitive", "later"],
  ["norwegian-elkhound-grey", "노르웨이지안 엘크하운드 그레이", "Norwegian Elkhound Grey", 5, "definitive", "later", ["ko-name-review"]],
  ["norwegian-lundehund", "노르웨이안 룬데훈트", "Norwegian Lundehund", 5, "definitive", "later", ["ko-name-review"]],
  ["finnish-lapponian-dog", "핀니시 라포니안 독", "Finnish Lapponian Dog", 5, "definitive", "later", ["ko-name-review"]],
  ["icelandic-sheepdog", "아이슬란딕 시프도그", "Icelandic Sheepdog", 5, "definitive", "later"],
  ["swedish-vallhund", "스웨디시 발훈트", "Swedish Vallhund", 5, "definitive", "later", ["ko-name-review"]],
  ["german-spitz", "저먼 스피츠", "German Spitz", 5, "definitive", "later", ["fci-varieties"]],
  ["italian-volpino", "볼피노 이탈리아노", "Italian Volpino", 5, "definitive", "later", ["ko-name-review"]],
  ["chow-chow", "차우차우", "Chow Chow", 5, "definitive", "later"],
  ["eurasier", "유라시어", "Eurasian", 5, "definitive", "later", ["ko-name-review"]],
  ["akita", "아키타", "Akita", 5, "definitive", "later"],
  ["american-akita", "아메리칸 아키타", "American Akita", 5, "definitive", "later"],
  ["hokkaido", "홋카이도견", "Hokkaido", 5, "definitive", "later"],
  ["japanese-spitz", "재패니즈 스피츠", "Japanese Spitz", 5, "definitive", "core"],
  ["kai", "카이견", "Kai", 5, "definitive", "later"],
  ["kishu", "키슈견", "Kishu", 5, "definitive", "later"],
  ["shiba", "시바견", "Shiba", 5, "definitive", "later"],
  ["shikoku", "시코쿠견", "Shikoku", 5, "definitive", "later"],
  ["korea-jindo-dog", "진돗개", "Korea Jindo Dog", 5, "definitive", "next"],
  ["basenji", "바센지", "Basenji", 5, "definitive", "next"],
  ["canaan-dog", "카나안 독", "Canaan Dog", 5, "definitive", "later"],
  ["xoloitzcuintle", "숄로이츠퀸틀레", "Xoloitzcuintle", 5, "definitive", "later", ["ko-name-review"]],
  ["yakutian-laika", "야쿠티안 라이카", "Yakutian Laika", 5, "provisional", "later", ["ko-name-review"]],
  ["bloodhound", "블러드하운드", "Bloodhound", 6, "definitive", "later"],
  ["basset-hound", "바셋 하운드", "Basset Hound", 6, "definitive", "later"],
  ["beagle", "비글", "Beagle", 6, "definitive", "next"],
  ["harrier", "해리어", "Harrier", 6, "definitive", "later"],
  ["english-foxhound", "잉글리시 폭스하운드", "English Foxhound", 6, "definitive", "later"],
  ["otterhound", "오터하운드", "Otterhound", 6, "definitive", "later"],
  ["petit-basset-griffon-vendeen", "페티 바셋 그리폰 방데앙", "Petit Basset Griffon Vendeen", 6, "definitive", "later", ["ko-name-review"]],
  ["finnish-hound", "핀니시 하운드", "Finnish Hound", 6, "definitive", "later"],
  ["alpine-dachsbracke", "알파인 닥스브라케", "Alpine Dachsbracke", 6, "definitive", "later", ["ko-name-review"]],
  ["bavarian-mountain-scent-hound", "바바리안 마운틴 센트 하운드", "Bavarian Mountain Scent Hound", 6, "definitive", "later"],
  ["dalmatian", "달마시안", "Dalmatian", 6, "definitive", "later"],
  ["rhodesian-ridgeback", "로디지안 리지백", "Rhodesian Ridgeback", 6, "definitive", "later"],
  ["german-short-haired-pointing-dog", "저먼 쇼트헤어드 포인터", "German Short-Haired Pointing Dog", 7, "definitive", "later"],
  ["german-wire-haired-pointing-dog", "저먼 와이어헤어드 포인터", "German Wire-Haired Pointing Dog", 7, "definitive", "later"],
  ["weimaraner", "와이머라너", "Weimaraner", 7, "definitive", "later"],
  ["vizsla", "비즐라", "Hungarian Short-Haired Pointer (Vizsla)", 7, "definitive", "later"],
  ["italian-pointing-dog", "브라코 이탈리아노", "Italian Pointing Dog", 7, "definitive", "later", ["ko-name-review"]],
  ["brittany-spaniel", "브리트니", "Brittany Spaniel", 7, "definitive", "later"],
  ["small-munsterlander", "스몰 문스터랜더", "Kleiner Münsterländer", 7, "definitive", "later", ["ko-name-review"]],
  ["wire-haired-pointing-griffon-korthals", "와이어헤어드 포인팅 그리폰 코르탈스", "Wire-Haired Pointing Griffon Korthals", 7, "definitive", "later", ["ko-name-review"]],
  ["english-pointer", "잉글리시 포인터", "English Pointer", 7, "definitive", "later"],
  ["english-setter", "잉글리시 세터", "English Setter", 7, "definitive", "later"],
  ["irish-red-setter", "아이리시 레드 세터", "Irish Red Setter", 7, "definitive", "later"],
  ["nova-scotia-duck-tolling-retriever", "노바 스코샤 덕 톨링 리트리버", "Nova Scotia Duck Tolling Retriever", 8, "definitive", "later"],
  ["curly-coated-retriever", "컬리 코티드 리트리버", "Curly Coated Retriever", 8, "definitive", "later"],
  ["flat-coated-retriever", "플랫 코티드 리트리버", "Flat Coated Retriever", 8, "definitive", "later"],
  ["golden-retriever", "골든 리트리버", "Golden Retriever", 8, "definitive", "next"],
  ["labrador-retriever", "래브라도 리트리버", "Labrador Retriever", 8, "definitive", "next"],
  ["chesapeake-bay-retriever", "체서피크 베이 리트리버", "Chesapeake Bay Retriever", 8, "definitive", "later"],
  ["clumber-spaniel", "클럼버 스패니얼", "Clumber Spaniel", 8, "definitive", "later"],
  ["english-cocker-spaniel", "잉글리시 코커 스패니얼", "English Cocker Spaniel", 8, "definitive", "next"],
  ["english-springer-spaniel", "잉글리시 스프링거 스패니얼", "English Springer Spaniel", 8, "definitive", "later"],
  ["american-cocker-spaniel", "아메리칸 코커 스패니얼", "American Cocker Spaniel", 8, "definitive", "later"],
  ["barbet", "바베", "French Water Dog", 8, "definitive", "later", ["ko-name-review"]],
  ["irish-water-spaniel", "아이리시 워터 스패니얼", "Irish Water Spaniel", 8, "definitive", "later"],
  ["lagotto-romagnolo", "라고토 로마뇰로", "Romagna Water Dog", 8, "definitive", "later"],
  ["portuguese-water-dog", "포르투갈 워터 도그", "Portuguese Water Dog", 8, "definitive", "later"],
  ["spanish-water-dog", "스페니시 워터 도그", "Spanish Water Dog", 8, "definitive", "later"],
  ["american-water-spaniel", "아메리칸 워터 스패니얼", "American Water Spaniel", 8, "definitive", "later"],
  ["bichon-frise", "비숑 프리제", "Bichon Frise", 9, "definitive", "later"],
  ["maltese", "몰티즈", "Maltese", 9, "definitive", "core"],
  ["havanese", "하바니즈", "Havanese", 9, "definitive", "later"],
  ["bolognese", "볼로네즈", "Bolognese", 9, "definitive", "later"],
  ["coton-de-tulear", "코톤 드 툴레아르", "Coton de Tulear", 9, "definitive", "later"],
  ["poodle", "푸들", "Poodle", 9, "definitive", "next", ["fci-varieties"]],
  ["chinese-crested-dog", "차이니즈 크레스티드 도그", "Chinese Crested Dog", 9, "definitive", "later"],
  ["lhasa-apso", "라사압소", "Lhasa Apso", 9, "definitive", "later"],
  ["shih-tzu", "시추", "Shih Tzu", 9, "definitive", "next"],
  ["tibetan-spaniel", "티베탄 스패니얼", "Tibetan Spaniel", 9, "definitive", "later"],
  ["tibetan-terrier", "티베탄 테리어", "Tibetan Terrier", 9, "definitive", "later"],
  ["chihuahua", "치와와", "Chihuahua", 9, "definitive", "next"],
  ["cavalier-king-charles-spaniel", "캐벌리어 킹 찰스 스패니얼", "Cavalier King Charles Spaniel", 9, "definitive", "later"],
  ["pekingese", "페키니즈", "Pekingese", 9, "definitive", "later"],
  ["japanese-chin", "재패니즈 친", "Japanese Chin", 9, "definitive", "later"],
  ["continental-toy-spaniel", "파피용", "Continental Toy Spaniel", 9, "definitive", "later", ["fci-varieties"]],
  ["pug", "퍼그", "Pug", 9, "definitive", "later"],
  ["french-bulldog", "프렌치 불도그", "French Bulldog", 9, "definitive", "next"],
  ["boston-terrier", "보스턴 테리어", "Boston Terrier", 9, "definitive", "later"],
  ["prague-ratter", "프라하 라터", "Prague Ratter", 9, "provisional", "later", ["ko-name-review"]],
  ["afghan-hound", "아프간 하운드", "Afghan Hound", 10, "definitive", "later"],
  ["saluki", "살루키", "Saluki", 10, "definitive", "later"],
  ["borzoi", "보르조이", "Borzoi - Russian Hunting Sighthound", 10, "definitive", "later"],
  ["irish-wolfhound", "아이리시 울프하운드", "Irish Wolfhound", 10, "definitive", "later"],
  ["greyhound", "그레이하운드", "Greyhound", 10, "definitive", "core"],
  ["whippet", "휘펫", "Whippet", 10, "definitive", "next"],
  ["italian-sighthound", "이탈리안 그레이하운드", "Italian Sighthound", 10, "definitive", "later"],
  ["azawakh", "아자와크", "Azawakh", 10, "definitive", "later", ["ko-name-review"]],
  ["sloughi", "슬루기", "Sloughi", 10, "definitive", "later", ["ko-name-review"]],
  ["galgo-espanol", "스페니시 그레이하운드", "Spanish Greyhound", 10, "definitive", "later"],
  ["american-pit-bull-terrier", "아메리칸 핏불 테리어", "American Pit Bull Terrier", null, "non-fci", "later"],
  ["american-bully", "아메리칸 불리", "American Bully", null, "non-fci", "later"],
  ["bergamasco-shepherd", "베르가마스코 셰퍼드", "Bergamasco Shepherd", 1, "definitive", "later"],
  ["mudi", "무디", "Mudi", 1, "definitive", "later"],
  ["schipperke", "스키퍼키", "Schipperke", 1, "definitive", "later"],
  ["slovakian-cuvac", "슬로바키안 쿠바츠", "Slovakian Cuvac", 1, "definitive", "later"],
  ["polish-lowland-sheepdog", "폴리시 로랜드 시프도그", "Polish Lowland Sheepdog", 1, "definitive", "later"],
  ["appenzeller-cattle-dog", "아펜첼러 캐틀 도그", "Appenzeller Cattle Dog", 2, "definitive", "later"],
  ["entlebucher-mountain-dog", "엔틀레부허 마운틴 도그", "Entlebucher Mountain Dog", 2, "definitive", "later"],
  ["greater-swiss-mountain-dog", "그레이터 스위스 마운틴 도그", "Greater Swiss Mountain Dog", 2, "definitive", "later"],
  ["german-pinscher", "저먼 핀셔", "German Pinscher", 2, "definitive", "later"],
  ["kangal-shepherd-dog", "캉갈 셰퍼드 도그", "Kangal Shepherd Dog", 2, "definitive", "later"],
  ["bedlington-terrier", "베들링턴 테리어", "Bedlington Terrier", 3, "definitive", "later"],
  ["parson-russell-terrier", "파슨 러셀 테리어", "Parson Russell Terrier", 3, "definitive", "later"],
  ["sealyham-terrier", "실리햄 테리어", "Sealyham Terrier", 3, "definitive", "later"],
  ["manchester-terrier", "맨체스터 테리어", "Manchester Terrier", 3, "definitive", "later"],
  ["cesky-terrier", "체스키 테리어", "Cesky Terrier", 3, "definitive", "later"],
  ["thai-ridgeback", "타이 리지백", "Thai Ridgeback", 5, "definitive", "later"],
  ["portuguese-podengo", "포르투기즈 포뎅고", "Portuguese Podengo", 5, "definitive", "later", ["fci-varieties"]],
  ["greenland-dog", "그린란드 도그", "Greenland Dog", 5, "definitive", "later"],
  ["peruvian-hairless-dog", "페루비안 헤어리스 도그", "Peruvian Hairless Dog", 5, "definitive", "later", ["fci-varieties"]],
  ["cirneco-dell-etna", "치르네코 델에트나", "Cirneco dell'Etna", 5, "definitive", "later"],
  ["gascon-saintongeois", "가스콩 생통주아", "Gascon Saintongeois", 6, "definitive", "later"],
  ["grand-basset-griffon-vendeen", "그랑 바셋 그리폰 방데앙", "Grand Basset Griffon Vendeen", 6, "definitive", "later"],
  ["schweizer-laufhund", "슈바이처 라우프훈트", "Schweizer Laufhund", 6, "definitive", "later"],
  ["porcelaine", "포셀린", "Porcelaine", 6, "definitive", "later"],
  ["petit-bleu-de-gascogne", "프티 블뢰 드 가스코뉴", "Petit Bleu de Gascogne", 6, "definitive", "later"],
  ["gordon-setter", "고든 세터", "Gordon Setter", 7, "definitive", "later"],
  ["german-long-haired-pointer", "저먼 롱헤어드 포인터", "German Long-Haired Pointer", 7, "definitive", "later"],
  ["french-spaniel", "프렌치 스패니얼", "French Spaniel", 7, "definitive", "later"],
  ["braque-saint-germain", "브라크 생제르맹", "Braque Saint-Germain", 7, "definitive", "later"],
  ["blue-picardy-spaniel", "블루 피카디 스패니얼", "Blue Picardy Spaniel", 7, "definitive", "later"],
  ["field-spaniel", "필드 스패니얼", "Field Spaniel", 8, "definitive", "later"],
  ["sussex-spaniel", "서식스 스패니얼", "Sussex Spaniel", 8, "definitive", "later"],
  ["wetterhoun", "베터훈", "Wetterhoun", 8, "definitive", "later"],
  ["kooikerhondje", "쿠이커혼제", "Nederlandse Kooikerhondje", 8, "definitive", "later"],
  ["drentsche-patrijshond", "드렌츠허 파트레이스훈트", "Drentsche Patrijshond", 8, "definitive", "later"],
  ["griffon-bruxellois", "브뤼셀 그리폰", "Griffon Bruxellois", 9, "definitive", "later"],
  ["petit-brabancon", "프티 브라방송", "Petit Brabancon", 9, "definitive", "later"],
  ["russian-toy", "러시안 토이", "Russian Toy", 9, "definitive", "later"],
  ["lowchen", "뢰첸", "Lowchen", 9, "definitive", "later"],
  ["english-toy-spaniel", "잉글리시 토이 스패니얼", "English Toy Spaniel", 9, "definitive", "later"],
  ["scottish-deerhound", "스코티시 디어하운드", "Scottish Deerhound", 10, "definitive", "later"],
  ["hungarian-greyhound", "헝가리안 그레이하운드", "Hungarian Greyhound", 10, "definitive", "later"],
  ["catalan-sheepdog", "카탈란 셰퍼드", "Catalan Sheepdog", 1, "definitive", "later"],
  ["croatian-sheepdog", "크로아티안 셰퍼드", "Croatian Sheepdog", 1, "definitive", "later"],
  ["komondor", "코몬도르", "Komondor", 1, "definitive", "later"],
  ["kuvasz", "쿠바스", "Kuvasz", 1, "definitive", "later"],
  ["schapendoes", "샤펜도스", "Schapendoes", 1, "definitive", "later"],
  ["portuguese-sheepdog", "포르투기즈 셰퍼드", "Portuguese Sheepdog", 1, "definitive", "later"],
  ["maremma-sheepdog", "마렘마 앤 아브루초 셰퍼드", "Maremma and Abruzzo Shepherd Dog", 1, "definitive", "later"],
  ["polish-tatra-sheepdog", "폴리시 타트라 셰퍼드", "Tatra Shepherd Dog", 1, "definitive", "later"],
  ["romanian-mioritic-shepherd-dog", "루마니안 미오리틱 셰퍼드", "Romanian Mioritic Shepherd Dog", 1, "definitive", "later"],
  ["romanian-carpathian-shepherd-dog", "루마니안 카르파티안 셰퍼드", "Romanian Carpathian Shepherd Dog", 1, "definitive", "later"],
  ["broholmer", "브로홀머", "Broholmer", 2, "definitive", "later"],
  ["fila-brasileiro", "필라 브라질레이로", "Fila Brasileiro", 2, "definitive", "later"],
  ["hovawart", "호바바르트", "Hovawart", 2, "definitive", "later"],
  ["landseer", "랜드시어", "Landseer", 2, "definitive", "later"],
  ["pyrenean-mastiff", "피레니안 마스티프", "Pyrenean Mastiff", 2, "definitive", "later"],
  ["sarplaninac", "샤르플라니나츠", "Sarplaninac", 2, "definitive", "later"],
  ["tosa", "도사", "Tosa", 2, "definitive", "later"],
  ["tornjak", "토르냐크", "Tornjak", 2, "definitive", "later"],
  ["central-asian-shepherd-dog", "센트럴 아시안 셰퍼드", "Central Asian Shepherd Dog", 2, "definitive", "later"],
  ["spanish-mastiff", "스패니시 마스티프", "Spanish Mastiff", 2, "definitive", "later"],
  ["australian-terrier", "오스트레일리안 테리어", "Australian Terrier", 3, "definitive", "later"],
  ["irish-terrier", "아이리시 테리어", "Irish Terrier", 3, "definitive", "later"],
  ["lakeland-terrier", "레이클랜드 테리어", "Lakeland Terrier", 3, "definitive", "later"],
  ["skye-terrier", "스카이 테리어", "Skye Terrier", 3, "definitive", "later"],
  ["dandie-dinmont-terrier", "댄디 딘몬트 테리어", "Dandie Dinmont Terrier", 3, "definitive", "later"],
  ["glen-of-imaal-terrier", "글렌 오브 이말 테리어", "Glen of Imaal Terrier", 3, "definitive", "later"],
  ["japanese-terrier", "재패니즈 테리어", "Japanese Terrier", 3, "definitive", "later"],
  ["german-hunting-terrier", "저먼 헌팅 테리어", "German Hunting Terrier", 3, "definitive", "later"],
  ["norwegian-buhund", "노르웨이안 부훈트", "Norwegian Buhund", 5, "definitive", "later"],
  ["russian-european-laika", "러시안 유러피안 라이카", "Russian-European Laika", 5, "definitive", "later"],
  ["east-siberian-laika", "이스트 시베리안 라이카", "East Siberian Laika", 5, "definitive", "later"],
  ["west-siberian-laika", "웨스트 시베리안 라이카", "West Siberian Laika", 5, "definitive", "later"],
  ["norrbottenspets", "노르보텐스펫츠", "Norrbottenspets", 5, "definitive", "later"],
  ["jamthund", "얌트훈트", "Jämthund", 5, "definitive", "later"],
  ["ariegeois", "아리에주아", "Ariégeois", 6, "definitive", "later"],
  ["anglo-francais-de-petite-venerie", "앙글로 프랑세 드 프티트 베네리", "Anglo-Français de Petite Vénerie", 6, "definitive", "later"],
  ["billy", "빌리", "Billy", 6, "definitive", "later"],
  ["briquet-griffon-vendeen", "브리케 그리폰 방데앙", "Briquet Griffon Vendeen", 6, "definitive", "later"],
  ["dunker", "둥케르", "Dunker", 6, "definitive", "later"],
  ["halden-hound", "할덴 하운드", "Halden Hound", 6, "definitive", "later"],
  ["hygen-hound", "히겐 하운드", "Hygen Hound", 6, "definitive", "later"],
  ["transylvanian-hound", "트란실바니안 하운드", "Transylvanian Hound", 6, "definitive", "later"],
  ["tyrolean-hound", "티롤리안 하운드", "Tyrolean Hound", 6, "definitive", "later"],
  ["braque-francais-type-gascogne", "브라크 프랑세 타입 가스코뉴", "Braque Français, type Gascogne", 7, "definitive", "later"],
  ["braque-d-auvergne", "브라크 도베르뉴", "Braque d'Auvergne", 7, "definitive", "later"],
  ["german-stichelhaar", "저먼 스티헬하르", "German Stichelhaar", 7, "definitive", "later"],
  ["spinone-italiano", "스피노네 이탈리아노", "Spinone Italiano", 7, "definitive", "later"],
  ["large-munsterlander", "라지 뮌스터랜더", "Large Munsterlander", 7, "definitive", "later"],
  ["irish-red-and-white-setter", "아이리시 레드 앤 화이트 세터", "Irish Red and White Setter", 7, "definitive", "later"],
  ["hungarian-wirehaired-vizsla", "헝가리안 와이어헤어드 비즐라", "Hungarian Wirehaired Vizsla", 7, "definitive", "later"],
  ["berger-picard", "피카르디 셰퍼드", "Berger Picard", 1, "definitive", "later"],
  ["pumi", "푸미", "Pumi", 1, "definitive", "later"],
  ["pyrenean-sheepdog", "피레니안 셰퍼드", "Pyrenean Sheepdog", 1, "definitive", "later"],
  ["lancashire-heeler", "랭커셔 힐러", "Lancashire Heeler", 1, "definitive", "later"],
  ["saarloos-wolfdog", "사르로스 울프도그", "Saarloos Wolfdog", 1, "definitive", "later"],
  ["aidi", "아이디", "Aidi", 2, "definitive", "later"],
  ["caucasian-shepherd-dog", "코카시안 셰퍼드", "Caucasian Shepherd Dog", 2, "definitive", "later"],
  ["presa-canario", "프레사 카나리오", "Presa Canario", 2, "definitive", "later"],
  ["black-russian-terrier", "블랙 러시안 테리어", "Black Russian Terrier", 2, "definitive", "later"],
  ["austrian-pinscher", "오스트리안 핀셔", "Austrian Pinscher", 2, "definitive", "later"],
  ["danish-swedish-farmdog", "덴마크-스웨디시 팜도그", "Danish-Swedish Farmdog", 2, "definitive", "later"],
  ["estrela-mountain-dog", "에스트렐라 마운틴 도그", "Estrela Mountain Dog", 2, "definitive", "later"],
  ["welsh-terrier", "웰시 테리어", "Welsh Terrier", 3, "definitive", "later"],
  ["brazilian-terrier", "브라질리안 테리어", "Brazilian Terrier", 3, "definitive", "later"],
  ["english-toy-terrier", "잉글리시 토이 테리어", "English Toy Terrier", 3, "definitive", "later"],
  ["pharaoh-hound", "파라오 하운드", "Pharaoh Hound", 5, "definitive", "later"],
  ["ibizan-hound", "이비잔 하운드", "Ibizan Hound", 5, "definitive", "later"],
  ["lapponian-herder", "라포니안 허더", "Lapponian Herder", 5, "definitive", "later"],
  ["swedish-lapphund", "스웨디시 라프훈트", "Swedish Lapphund", 5, "definitive", "later"],
  ["podenco-canario", "포덴코 카나리오", "Canarian Warren Hound", 5, "definitive", "later"],
  ["austrian-black-and-tan-hound", "오스트리안 블랙 앤 탄 하운드", "Austrian Black and Tan Hound", 6, "definitive", "later"],
  ["styrian-coarse-haired-hound", "슈타이리셰 코어스헤어드 하운드", "Styrian Coarse-haired Hound", 6, "definitive", "later"],
  ["slovakian-hound", "슬로바키안 하운드", "Slovakian Hound", 6, "definitive", "later"],
  ["posavac-hound", "포사바츠 하운드", "Posavac Hound", 6, "definitive", "later"],
  ["bosnian-broken-haired-hound", "보스니안 브로큰헤어드 하운드", "Bosnian Broken-haired Hound", 6, "definitive", "later"],
  ["serbian-hound", "세르비안 하운드", "Serbian Hound", 6, "definitive", "later"],
  ["montenegrin-mountain-hound", "몬테네그린 마운틴 하운드", "Montenegrin Mountain Hound", 6, "definitive", "later"],
  ["greek-harehound", "그릭 헤어하운드", "Greek Harehound", 6, "definitive", "later"],
  ["italian-segugio", "이탈리안 세구지오", "Italian Hound", 6, "definitive", "later"],
  ["spanish-hound", "스패니시 하운드", "Spanish Hound", 6, "definitive", "later"],
  ["grand-bleu-de-gascogne", "그랑 블루 드 가스코뉴", "Grand Bleu de Gascogne", 6, "definitive", "later"],
  ["basset-bleu-de-gascogne", "바셋 블루 드 가스코뉴", "Basset Bleu de Gascogne", 6, "definitive", "later"],
  ["basset-fauve-de-bretagne", "바셋 포브 드 브르타뉴", "Basset Fauve de Bretagne", 6, "definitive", "later"],
  ["basset-artesien-normand", "바셋 아르테지앙 노르망", "Basset Artesien Normand", 6, "definitive", "later"],
  ["poitevin", "푸아트뱅", "Poitevin", 6, "definitive", "later"],
  ["hamiltonstovare", "해밀턴스퇴바레", "Hamiltonstövare", 6, "definitive", "later"],
  ["schillerstovare", "쉴러 스퇴바레", "Schillerstövare", 6, "definitive", "later"],
  ["smaland-hound", "스몰란드 하운드", "Smålandsstövare", 6, "definitive", "later"],
  ["drever", "드레버", "Drever", 6, "definitive", "later"],
  ["old-danish-pointer", "올드 대니시 포인터", "Old Danish Pointer", 7, "definitive", "later"],
  ["slovakian-wirehaired-pointer", "슬로바키안 와이어헤어드 포인터", "Slovakian Wirehaired Pointer", 7, "definitive", "later"],
  ["burgos-pointer", "부르고스 포인터", "Burgos Pointer", 7, "definitive", "later"],
  ["picardy-spaniel", "피카르디 스패니얼", "Picardy Spaniel", 7, "definitive", "later"],
  ["pont-audemer-spaniel", "퐁 오데메르 스패니얼", "Pont-Audemer Spaniel", 7, "definitive", "later"],
  ["stabyhoun", "스타비하운", "Stabyhoun", 7, "definitive", "later"],
  ["welsh-springer-spaniel", "웰시 스프링어 스패니얼", "Welsh Springer Spaniel", 8, "definitive", "later"],
  ["affenpinscher", "아펜핀셔", "Affenpinscher", 9, "definitive", "later"],
  ["kromfohrlander", "크롬포어랜더", "Kromfohrländer", 9, "definitive", "later"],
  ["biewer-terrier", "비버 테리어", "Biewer Terrier", 9, "definitive", "later"],
  ["polish-greyhound", "폴리시 그레이하운드", "Polish Greyhound", 10, "definitive", "later"],
  ["smooth-collie", "스무스 콜리", "Collie Smooth", 1, "definitive", "later"],
  ["bouvier-des-ardennes", "부비에 데 아르덴", "Bouvier des Ardennes", 1, "definitive", "later"],
  ["majorca-shepherd-dog", "마요르카 셰퍼드", "Majorca Shepherd Dog", 1, "definitive", "later"],
  ["south-russian-shepherd-dog", "사우스 러시안 셰퍼드", "South Russian Shepherd Dog", 1, "definitive", "later"],
  ["chodsky-pes", "초드스키 페스", "Chodsky Pes", 1, "provisional", "later", ["ko-name-review"]],
  ["dutch-smoushond", "더치 스무숀드", "Dutch Smoushond", 2, "definitive", "later"],
  ["saint-miguel-cattle-dog", "상 미겔 캐틀 도그", "Saint Miguel Cattle Dog", 2, "definitive", "later"],
  ["majorca-mastiff", "마요르카 마스티프", "Majorca Mastiff", 2, "definitive", "later"],
  ["cimarron-uruguayo", "시마론 우루과요", "Cimarron Uruguayo", 2, "definitive", "later"],
  ["castro-laboreiro-dog", "카스트루 라보레이루 독", "Castro Laboreiro Dog", 2, "definitive", "later"],
  ["rafeiro-do-alentejo", "라페이루 두 알렌테주", "Rafeiro do Alentejo", 2, "definitive", "later"],
  ["romanian-bucovina-shepherd-dog", "루마니안 부코비나 셰퍼드", "Romanian Bucovina Shepherd", 2, "definitive", "later"],
  ["karst-shepherd-dog", "카르스트 셰퍼드", "Karst Shepherd Dog", 2, "definitive", "later"],
  ["canadian-eskimo-dog", "캐나디안 에스키모 도그", "Canadian Eskimo Dog", 5, "definitive", "later"],
  ["norwegian-elkhound-black", "블랙 노르웨이언 엘크하운드", "Norwegian Elkhound Black", 5, "definitive", "later"],
  ["thai-bangkaew-dog", "타이 방깨우 독", "Thai Bangkaew Dog", 5, "definitive", "later"],
  ["taiwan-dog", "타이완 도그", "Taiwan Dog", 5, "definitive", "later"],
  ["brazilian-tracker", "브라질리안 트래커", "Brazilian Tracker", 6, "definitive", "later"],
  ["french-tricolour-hound", "프렌치 트라이컬러 하운드", "French Tricolour Hound", 6, "definitive", "later"],
  ["french-white-and-black-hound", "프렌치 화이트 앤 블랙 하운드", "French White and Black Hound", 6, "definitive", "later"],
  ["french-white-and-orange-hound", "프렌치 화이트 앤 오렌지 하운드", "French White and Orange Hound", 6, "definitive", "later"],
  ["great-anglo-french-tricolour-hound", "그레이트 앵글로 프렌치 트라이컬러", "Great Anglo-French Tricolour Hound", 6, "definitive", "later"],
  ["great-anglo-french-white-and-black-hound", "그레이트 앵글로 프렌치 화이트 앤 블랙", "Great Anglo-French White and Black Hound", 6, "definitive", "later"],
  ["great-anglo-french-white-and-orange-hound", "그레이트 앵글로 프렌치 화이트 앤 오렌지", "Great Anglo-French White and Orange Hound", 6, "definitive", "later"],
  ["polish-hound", "폴리시 하운드", "Polish Hound", 6, "definitive", "later"],
  ["american-foxhound", "아메리칸 폭스하운드", "American Foxhound", 6, "definitive", "later"],
  ["black-and-tan-coonhound", "블랙 앤 탄 쿤하운드", "Black and Tan Coonhound", 6, "definitive", "later"],
  ["beagle-harrier", "비글 해리어", "Beagle Harrier", 6, "definitive", "later"],
  ["griffon-blue-gascony", "그리폰 블루 드 가스코뉴", "Griffon Bleu de Gascogne", 6, "definitive", "later"],
  ["griffon-fauve-de-bretagne", "그리폰 포브 드 브르타뉴", "Griffon Fauve de Bretagne", 6, "definitive", "later"],
  ["griffon-nivernais", "그리폰 니베르네", "Griffon Nivernais", 6, "definitive", "later"],
  ["hellenic-hound", "헬레닉 하운드", "Hellenic Hound", 6, "definitive", "later"],
  ["serbian-tricolour-hound", "세르비안 트라이컬러 하운드", "Serbian Tricolour Hound", 6, "definitive", "later"],
  ["german-hound", "저먼 하운드", "German Hound", 6, "definitive", "later"],
  ["westphalian-dachsbracke", "베스트팔리안 닥스브라케", "Westphalian Dachsbracke", 6, "definitive", "later"],
  ["small-swiss-hound", "스몰 스위스 하운드", "Small Swiss Hound", 6, "definitive", "later"],
  ["hanoverian-scent-hound", "하노버리안 센트하운드", "Hanoverian Scent Hound", 6, "definitive", "later"],
  ["artois-hound", "아르투아 하운드", "Artois Hound", 6, "definitive", "later"],
  ["istrian-short-haired-hound", "이스트리안 쇼트헤어드 하운드", "Istrian Short-haired Hound", 6, "definitive", "later"],
  ["istrian-wire-haired-hound", "이스트리안 와이어헤어드 하운드", "Istrian Wire-haired Hound", 6, "definitive", "later"],
  ["braque-francais-type-pyrenees", "프렌치 포인터 피레네 타입", "Braque Français, type Pyrénées", 7, "definitive", "later"],
  ["braque-bourbonnais", "브라크 뒤 부르보네", "Braque du Bourbonnais", 7, "definitive", "later"],
  ["ariege-pointing-dog", "아리에주 포인팅 도그", "Braque de l'Ariege", 7, "definitive", "later"],
  ["portuguese-pointing-dog", "포르투기즈 포인팅 도그", "Portuguese Pointing Dog", 7, "definitive", "later"],
  ["pudelpointer", "푸델포인터", "Pudelpointer", 7, "definitive", "later"],
  ["bohemian-wire-haired-pointing-griffon", "보헤미안 와이어헤어드 포인팅 그리폰", "Bohemian Wire-haired Pointing Griffon", 7, "definitive", "later"],
  ["german-spaniel", "저먼 스패니얼", "German Spaniel", 8, "definitive", "later"],
  ["king-charles-spaniel", "킹 찰스 스패니얼", "King Charles Spaniel", 9, "definitive", "later"],
  ["griffon-belge", "벨지안 그리폰", "Griffon Belge", 9, "definitive", "later"],
  ["eesti-hound", "에스티 하운드", "Estonian Hound", 6, "provisional", "later"],
  ["kintamani-bali-dog", "킨타마니 발리 도그", "Kintamani-Bali Dog", 5, "provisional", "later"],
  ["kazakh-tazy", "카자흐 타지", "Kazakh Tazy", 10, "provisional", "later"],
  ["ratonero-bodeguero-andaluz", "라토네로 보데게로 안달루스", "Ratonero Bodeguero Andaluz", 3, "provisional", "later"],
  ["valencian-terrier", "발렌시안 테리어", "Valencian Terrier", 3, "provisional", "later"],
  ["romanian-raven-shepherd-dog", "루마니안 레이븐 셰퍼드", "Romanian Raven Shepherd Dog", 1, "provisional", "later"],
  ["tatra-hound", "타트라 하운드", "Tatra Hound", 6, "provisional", "later"],
  ["transmontano-mastiff", "트란스몬타노 마스티프", "Transmontano Mastiff", 2, "provisional", "later"],
  ["brazilian-campeiro-bulldog", "브라질리안 캄페이루 불도그", "Brazilian Campeiro Bulldog", 2, "provisional", "later"],
  ["segugio-dell-appennino", "세구지오 델 아펜니노", "Segugio dell'Appennino", 6, "provisional", "later"],
  ["sabueso-fino-colombiano", "사부에소 피노 콜롬비아노", "Sabueso Fino Colombiano", 6, "provisional", "later"],
  ["macedonian-shepherd-dog-karaman", "마케도니안 셰퍼드 도그 카라만", "Macedonian Shepherd Dog Karaman", 2, "provisional", "later"],
  ["sapsaree", "삽살개", "Sapsaree", null, "non-fci", "later", ["ko-name-review"]],
  ["pungsan-dog", "풍산개", "Pungsan Dog", null, "non-fci", "later", ["ko-name-review"]],
  ["donggyeongi", "동경이", "Donggyeongi", null, "non-fci", "later", ["ko-name-review"]],
  ["jeju-dog", "제주개", "Jeju Dog", null, "non-fci", "later", ["ko-name-review"]],
  ["mongolian-bankhar", "몽골 방카르", "Mongolian Bankhar", null, "non-fci", "later"],
] satisfies readonly MasterInventorySeed[];
